### ISSUE TITLE
$Service is now deprecated. Use $uibService instead.

### ISSUE THREAD

**Issue by declanelcocks** [angular-ui/bootstrap#4591] opened 2015-10-12 04:43 UTC
I've updated to `0.14.0` to make use of the fixed tooltips and a few other things and I now have the warning listed in the comment. Are there some ongoing issues regarding migrating to `0.14.0`? For example, I have no instances of `$tooltip` used within my app, but I still get the warning to use `$uibTooltip` and to use `uib-tooltip-html-popup`. Similarly, after replacing all `$modal` instances with `$uibModal`, I still receive the warnings. I did also try updating the directives on the page to `uib-tooltip-...` as well.

**Comment by maxklenk** [comment] 2015-10-12 08:47
Even if your are not using the `$tooltip` service, the message tells you to replace all tooltip classes and directives like:
```html
<a tooltip="Hey">  => <a uib-tooltip="Hey">
```

**Comment by Foxandxss** [comment] 2015-10-12 09:01
There could be some edge cases where you see a deprecation warning when you shouldn't.

I tracked lot of them and I wasn't able to get more.

Check the migration guide (link on readme) and see if you're missing something.

**Comment by declanelcocks** [comment] 2015-10-13 01:43
Yeah I've taken a look at the migration guide. I'm only using `tooltip` in one HTML file currently, so I know the warning can't be coming from anywhere else. I replaced all instances of `tooltip` with `uib-tooltip` (although I didn't see any information for `tooltip-class` in the guide/source code as `uib-tooltip-classes` threw some errors) and the warning still appears. To be more specific I'm using `tooltip-html`, `tooltip-class`, `tooltip-position` and `tooltip-html`.

**Comment by Foxandxss** [comment] 2015-10-13 09:48
@declanelcocks Can you create a plunker with the popover that is causing that issue for you?

**Comment by declanelcocks** [comment] 2015-10-15 01:39
@Foxandxss Sorry for slacking on the replies, I had to move on to working on something else first as this was a minor issue in my project. I will try to play around with this before the weekend and let you know how it goes. I believe after updating the demo page, it's a bit easier to understand the migration so it may just be a simple error on my end.

**Comment by Dilatorily** [comment] 2015-10-16 03:29
@Foxandxss I was able to reproduce a misleading deprecation warning with the popover class.

Here is a [plunkr](http://plnkr.co/edit/enbP5gCjDCzD81pyYouw?p=preview) of the issue.

**Comment by declanelcocks** [comment] 2015-10-16 06:39
@Dilatorily Correct, I receive warnings for this as well but the warning should be a bit more explicit as you find yourself looking through the source code for tooltip rather than popover

**Comment by Dilatorily** [comment] 2015-10-16 06:53
@declanelcocks I agree. Other libraries use the Bootstrap's `popover` class, and they will create a false deprecation warning.

If the warnings could be clearer by having the right source, and by having the right use case (element, attribute, or class), it would have saved me a lot of headaches.

**Comment by Foxandxss** [comment] 2015-10-16 08:12
@Dilatorily Angular will process all classes in the HTML and check if they are directives. Since `tooltip` is a directive, Angular will wake up the `tooltip` directive, also wake up all of his injections and bam, `$tooltip` will cry.

I spent at least 5 hours figuring it out and we had to do some workarounds to avoid that.

I think I can go one step further to make it better. Will investigate.

Also, I will investigate if I can make the warning a bit more useful.

**Comment by declanelcocks** [comment] 2015-10-16 09:35
@Foxandxss It's a very picky improvement so it's not much of a big deal 😊

**Comment by Foxandxss** [comment] 2015-10-16 09:38
It was a dead end at the end.

I am playing with logging the element and attributes for each deprecation. Way more verbose now, so I am not entirely sure if it is a good idea.

Will discuss it with the other guys.

**Comment by Foxandxss** [comment] 2015-10-16 23:22
Well, we thought that there is no best way to improve the error messages and since this issue is now resolved, I am closing this.

**Comment by Dilatorily** [comment] 2015-10-17 06:31
I also tinkered on my side to try to disable the deprecation warning when it gets called from `popover`.

In the end, I had the same conclusion as @Foxandxss and just disabled all `$tooltip` deprecation warnings.

Relevant snippet of code:
```javascript
$provide.decorator('$tooltipSuppressWarning', function () { return true; });
```

**Comment by Foxandxss** [comment] 2015-10-17 11:09
If you really need to add that tooltip class by hand (I Don't think there is a _real_ need) yes, better disable it.

Still, you don't need to decorate it, it is just a service. Inject it in a .config method and disable it.

**Comment by icfantv** [comment] 2015-10-17 14:01
So I'm confused here.  The deprecation warnings are totally superfluous.  Why are you wanting to disable them?  Why can't you change the directive names?

**Comment by pkozlowski-opensource** [comment] 2015-10-17 14:13
Guys, what do you think about cutting a new release with the old (unprefixed) things dropped? I understand that we want to be nice to users but it seems like there are corner cases / issues on ng side to do it properly. On top of this supporting 2 sets of directives adds bytes to the library, runtime overhead etc.

If users want / need to migrate this is a relatively simple process (search and replace). 

WDYT?

**Comment by Foxandxss** [comment] 2015-10-17 14:25
The main goals was to make the transition as painless as possible, that is why we did all this extra work to having both versions to coexist.

Our implementation is not flawless but I think we covered almost all use cases. The use case in here is a very concrete use case that can be silenced easily.

The goal is also to provide time to people to upgrade. There is some overhead, I agree, but is not that big.

The big concern right now is to have versioned docs (which I am fixing in this very moment). After that, we could consider that big BC.

**Comment by Vladimir-Purple** [comment] 2015-10-18 15:55
Hi.
I encountered same issue, I searched all over the project for missed piece of code to be renamed but ended with no result.
Then I remembered that we extended 'template/tooltip/tooltip-html-popup.html' template like so:
```
angular.module('template/tooltip/tooltip-html-popup.html', []).run(['$templateCache', function($templateCache) {
    $templateCache.put('template/tooltip/tooltip-html-popup.html',
        '<div class="tooltip"\n' +
        '  tooltip-animation-class=\"fade\"\n' +
        '  uib-tooltip-classes\n' +
        '  ng-class="{ in: isOpen() }">\n' +
        '  <div class=\"tooltip-arrow\"></div>\n' +
        '  <div class=\"tooltip-inner\" bind-html-compile=\"contentExp()\"></div>\n' +
        '</div>\n' +
        '');
}]);
```
we did it before upgrading to 0.14.x.
I found that class="tooltip" actually thats what was reason behind the warning, it was removed in 0.14.x.
http://plnkr.co/edit/VFnXUMuQRi6RS3biXKG9?p=preview

Hope it helps someone.

**Comment by wesleycho** [comment] 2015-10-18 17:57
@Vladimir-Purple this is the danger when using custom templates - one should scour the changelog for any major changes there that could impact templates

@pkozlowski-opensource I have been thinking about that - I think we should potentially explore moving to 1.0 in a few weeks (I'm hoping to have a 1.0 release in a month from now or so), we currently have been focused on monitoring any critical issues related to prefixing or tooltip/popover issues to ensure we can move fast to fix them & making new releases when the bugs were critical (i.e. garbage collection issues or breaking 1.3 compatibility).

**Comment by thorn0** [comment] 2015-10-20 18:10
Will the service names still be prefixed with `$`? What for? Isn't this prefix reserved for Angular's own services only?

**Comment by Foxandxss** [comment] 2015-10-20 18:11
I think the same, but we decided to leave it with $.

**Comment by thorn0** [comment] 2015-10-20 18:15
It's a bad example for other library authors. Why not drop it if you're renaming things anyway?

**Comment by Foxandxss** [comment] 2015-10-20 18:19
I talked about it at #4373

**Comment by wesleycho** [comment] 2015-10-27 13:56
Closing as I believe we have done all we can for helpful prefixing warning for 0.14.x - we have started 1.0 work and stripped out the deprecated directives/services in `master`.

**Closed by wesleycho** 2015-10-27 13:56 UTC
Labels: needs: investigation, needs: plunkr

**Comment by kimx** [comment] 2015-11-30 03:05
If I upgrade to 0.14.x.There has to be a way to ignored warning message with do not add any prefix?

**Comment by icfantv** [comment] 2015-11-30 15:53
@kimx, I've no idea what you're trying to ask so I'm just going to take stab in the dark here.  If you want to turn off the warning messages, yes, there is a way.  Each component has its own warning suppression flag.

E.g., taking a look at the alert component, specifically, [the diff](https://github.com/angular-ui/bootstrap/commit/21e852b8ecdefb5471eb02c85d42280b3fedf15f#diff-352f846e2dbf384db9f705c8ff55f5ac) where the deprecated code was removed, you can see that it checks the `$alertSuppressWarning` flag for when deprecated directives, i.e., those without prefixes are used.

If this is not what you meant, please clarify your question and let us know.  Cheers.

**Comment by kimx** [comment] 2015-11-30 22:49
@icfantv  The answer is what I want,thanks you.
I have another question is that turn off the warning messages can be used all of next release in the future or will until specific version then cannot use.

**Comment by Foxandxss** [comment] 2015-11-30 22:54
next version won't have warning messages nor old non prefixed directives. You're forced to put the prefix if you want to update to the next version.

**Comment by icfantv** [comment] 2015-11-30 22:55
@kimx, they've already been removed in `master` meaning the next release, 1.0.0, all the deprecated code will no longer be supported as it will be removed.

Disabling any deprecation warnings is usually a bad idea as the API is trying to tell you to do something via the new way and if you disable them, well....one day you're going to upgrade and stuff isn't going to work anymore.

**Comment by kimx** [comment] 2015-11-30 23:01
@Foxandxss  @icfantv  I got it,thank you all answer me.
