### ISSUE TITLE
Carousel stops working after few minutes in case of inactivity

### ISSUE THREAD

**Issue by ritesh14887** [angular-ui/bootstrap#5621] opened 2016-03-11 07:04 UTC
**Bug description:**
When you are adding carousel on a page it will work as expected, but if you will leave that page inactive for few mins it will stops sliding. Apart from this its navigational and slide indicator controls stops working. It is in kind of freeze mode.

**Steps to Replicate**
It can be replicated on Demo Page of Angular UI.
1. Open page and go to carousel demo
2. leave that page inactive for few minutes.
3. Come Back again...its stopped and freeze
http://angular-ui.github.io/bootstrap/#/carousel

**Version of Angular, UIBS, and Bootstrap**

**Angular: **
AngularJS v1.5.0
Angular Animate v1.5.0

**UIBS:**
0.14.0 - 2015-10-08

**Bootstrap:**

 Bootstrap v3.3.6

Screens:
[https://youtu.be/w2zRKuQQCJY](url)

**Comment by wesleycho** [comment] 2016-03-11 15:36
Closing as a duplicate of #5471 - this is actually more of an ngAnimate issue.

**Closed by wesleycho** 2016-03-11 15:36 UTC

**Comment by icfantv** [comment] 2016-03-11 16:41
@ritesh14887, please be respectful of our time by reading our project documentation and searching both open and closed issues before entering anything.  Thanks.

**Comment by ritesh14887** [comment] 2016-03-12 10:33
@icfantv Thnks for your response....... I have checked for closed issue only before logging this issue but #5471 is still in open state....Sorry for using your time on this....
