### ISSUE TITLE
Popover too small for its content with IE 11

### ISSUE THREAD

**Issue by jlebit** [angular-ui/bootstrap#4460] opened 2015-09-24 06:30 UTC
The popover is not correctly sized with Internet Explorer 11.
The following happens:

![popover-bug-ui-bootstrap](https://cloud.githubusercontent.com/assets/13313502/10066747/3e72bece-6296-11e5-804c-cffb16532ef1.png)

The issue happens with version 0.13.4 but  seems to work with previous version (0.13.3).

You can reproduce the issue here: http://jsfiddle.net/tjruzpmb/1/

**Comment by terryt2000** [comment] 2015-09-29 13:13
tooltips also have a problem on IE 11

**Comment by RobJacobs** [comment] 2015-09-29 14:26
Here is a [plunk](http://plnkr.co/edit/H5hxr3hHshqdMV7LzHz9?p=preview) with the latest from master.  Does not seem to be a problem anymore.

**Comment by cvanleeuwen** [comment] 2015-10-05 09:51
Using `angular-ui/bootstrap-bower#febda42` I was still able to repoduce the issue in my private project.

The overflow is caused by an explicit width/height which is set by tooltip provider. (ui-bootstrap.tpls.js line 3407 / 3408). 

Somehow the explicit width/height is applied to Internet Explorer, but firefox/chrome don't have those set (just top/left). Maybe the `positionTimeout` isn't triggered in those browsers?

Removing the explicit width/height seems solves the issue. But I don't know if this would cause another issue?

**Comment by RobJacobs** [comment] 2015-10-05 12:15
@cvanleeuwen Width and height are no longer being set: https://github.com/angular-ui/bootstrap/blob/master/src/tooltip/tooltip.js#L162

**Comment by cvanleeuwen** [comment] 2015-10-06 09:17
Ah my bad! I thought I was using the latest master, but `angular-ui/bootstrap-bower` is not same as `angular-ui/bootstrap` master.

Is there a way to replace/test `angular-ui/bootstrap-bower` with `angular-ui/bootstrap` via bower? Or should I run it as a custom build?

**Comment by RobJacobs** [comment] 2015-10-09 13:39
This is fixed in the 0.14.0 release.

**Closed by RobJacobs** 2015-10-09 13:39 UTC
Labels: browser: IE11, component: tooltip, needs: investigation
