### ISSUE TITLE
Collapse directive with angular 1.4.x is less smooth than with angular 1.3.x

### ISSUE THREAD

**Issue by Waterstraal** [angular-ui/bootstrap#4254] opened 2015-08-21 11:26 UTC
I've noticed that since I've upgrade to angularjs 1.4.3, the collapse animation looks not as smooth as it used to be. It's definitely slower, but it also looks less smooth and more "shocky"? It looks like the animation is linear in 1.4.4 and eased in 1.3.18.

I have created two plunkers demonstrating the issue:

**Collapse with AngularJS 1.3.18 & ui bootstrap 0.13.3**
http://plnkr.co/edit/wL8uXVbOmn10ISdwp1o9?p=preview

**Collapse with AngularJS 1.4.4 & ui bootstrap 0.13.3**
http://plnkr.co/edit/D9uCqCWpQuk4MEQ0iCrq?p=preview

**Comment by wesleycho** [comment] 2015-08-21 14:34
Thanks for the reproduction - perhaps this is due to $animate changes in 1.4.x, and $animateCss is needed to get the proper animation benefits here.

**Comment by wesleycho** [comment] 2015-08-22 21:43
I did an investigation, and this turns out to be a bug in ngAnimate in Angular - I filed an issue in https://github.com/angular/angular.js/issues/12656 .

This brings us to a conundrum - I can force the easing to be `ease`, but then this will potentially be too restrictive if someone wants to override this and the bug is fixed in ngAnimate proper. I will wait for a decision from Matias first before deciding to go down that rabbit hole.

**Comment by trajano** [comment] 2015-09-05 00:39
I have a Plunkr that still shows unsmooth animation in 1.3.x of Angular
http://plnkr.co/edit/fPlCSvVwGF94WuvEwu5I?p=preview

**Comment by wesleycho** [comment] 2015-09-05 00:41
@trajano: unless it's a clear Angular problem, I recommend reporting those types of issues to the UI Bootstrap repository and not here - this issue is specifically because the problem was isolated as a ngAnimate issue.

**Comment by trajano** [comment] 2015-09-05 00:46
I'm confused, isn't this the Angular UI bootstrap repository?  I mean it shows in https://github.com/angular-ui/bootstrap/

Also I just tested the two plunkrs from the OP they seem to both work correctly.  Not sure what issue it had.

**Comment by trajano** [comment] 2015-09-05 00:47
Also this Fiddle http://jsfiddle.net/whytheday/2Dj7Y/11/ shows it works correctly on bootstrap only.

**Comment by wesleycho** [comment] 2015-09-05 00:47
Whoops, I'm losing my mind from GitHub notifications :) .

**Comment by trajano** [comment] 2015-09-05 00:49
@wesleycho ya you got me confused too :) However the plunker's from @Waterstraal seem to work smoothly, what's the issue?

**Comment by wesleycho** [comment] 2015-09-05 04:52
I'm not quite sure - if I had to suspect, it might have to do with the fact that this is a table.

I don't think it is worthwhile to try to fix this for 1.3, given that the Angular team does not really maintain 1.3.x excepting for major enough updates (their focus is 1.2 for critical bug fixes and 1.4 for current active development).

**Comment by trajano** [comment] 2015-09-05 21:22
It also has issues with 1.4.3, http://plnkr.co/edit/bZIpFvIPjMxVaFh19Ln0?p=preview

I can "feel" it is animating because there's a slight delay.

**Comment by wesleycho** [comment] 2015-09-06 23:16
That is a separate issue and should be separated from this particular issue - this issue is specifically about the linear transition vs. ease.

**Comment by trajano** [comment] 2015-09-07 06:21
OK I'll create a new issue

**Comment by icfantv** [comment] 2015-10-28 16:29
Closing as this seems to be working quite nicely with 0.14.3 and 1.4.7.

**Closed by icfantv** 2015-10-28 16:29 UTC
Labels: component: collapse, type: ngAnimate
