### ISSUE TITLE
Tooltip placement error after update to 0.13.2

### ISSUE THREAD

**Issue by bartekupartek** [angular-ui/bootstrap#4103] opened 2015-08-04 07:00 UTC
I've updated to newest version from 0.13.0 and I've got an error:
```
angular.js:12330 TypeError: Cannot read property 'isOpen' of null
    at ui-bootstrap-tpls.js:3303
```
unless I delete tooltip-placement attribute:
```<a tooltip-placement="top" tooltip="{{'test'}}" tooltip-append-to-body="true">```

How can I rid of this issue?

Tested with angular 1.4.3, bootstrap 3.1.1

**Comment by RobJacobs** [comment] 2015-08-04 12:24
@bartekupartek  We need plunks demonstrating the issue, or we just spend time guessing what the problem might be.  I created a [plunk](http://plnkr.co/edit/CLnZoQarJgC9cHyc9VRe?p=preview) based on the code you provided and am not seeing the error you reported.

**Comment by wesleycho** [comment] 2015-08-13 06:40
Closing due to lack of actionable evidence (most notably reproduction).

**Closed by wesleycho** 2015-08-13 06:40 UTC
Labels: component: tooltip, needs: info, needs: plunkr
