### ISSUE TITLE
Popover content is not being adjusted to fit the viewport

### ISSUE THREAD

**Issue by oitozero** [angular-ui/bootstrap#4143] opened 2015-08-07 17:24 UTC
Popover content is not being adjusted to fit the viewport. When using the standard bootstrap library, content is adjusted to fit the viewport, which doesn't seem to been happening with angular bootstrap.

Example using Bootstrap:
http://plnkr.co/edit/CP6aKuN2UwXLCyXWER9j

Example using Angular Bootstrap:
http://plnkr.co/edit/V9bEMHSNos3eCH6CIzAU

Any solution for this?

**Comment by wesleycho** [comment] 2015-08-07 17:28
Closing as a duplicate of #4090

**Closed by wesleycho** 2015-08-07 17:28 UTC
Labels: component: popover, resolution: duplicate
