### ISSUE TITLE
Unknown provider: aProvider <- a

### ISSUE THREAD

**Issue by ankitoodles** [angular-ui/bootstrap#3173] opened 2015-01-09 12:09 UTC
I am getting this issue after js minification.

I tried to avoid minification of ui.bootstrap.tpls.js(but others are minified),still the same error.

**Comment by karianna** [comment] 2015-01-09 12:44
Needs more information, a plunkr + the versions of angluar-ui, bootstrap and angular

**Comment by antoinepairet** [comment] 2015-01-09 12:57
The probability that error comes from ui-bootstrap is very low.
Please ask for support on SO. I will close this for now.
regards,

**Closed by antoinepairet** 2015-01-09 12:57 UTC
Labels: needs: info, resolution: can't reproduce / no info

**Comment by rally25rs** [comment] 2016-10-26 14:05
These errors are usually due to copy/paste of code examples that aren't totally correct. For example, the example JS for the `modal` directive shows this JS:

```
    $uibModal.open({
      animation: $ctrl.animationsEnabled,
      ariaLabelledBy: 'modal-title-bottom',
      ariaDescribedBy: 'modal-body-bottom',
      templateUrl: 'stackedModal.html',
      size: 'sm',
      controller: function($scope) {
        $scope.name = 'bottom';  
      }
    });
```

which will cause the error mentioned.

The problem is that 

```
      controller: function($scope) {
        $scope.name = 'bottom';  
      }
```

will minify to

```
      controller: function(a) {
        a.name = 'bottom';  
      }
```

and then Angular will try to resolve 'a' as 'aProvider' (it appends "Provider" internally).
