### ISSUE TITLE
Datepicker Controller cannot be named "DatepickerController"

### ISSUE THREAD

**Issue by ozomer** [angular-ui/bootstrap#3062] opened 2014-12-07 19:42 UTC
http://plnkr.co/edit/Q7ryAsC5UxnS2FFq3tDy?p=preview
vs
http://plnkr.co/edit/niAUKww0cFH1VehZoP0L?p=preview

**Comment by dmitriz** [comment] 2015-04-17 00:47
Maybe close and link to:
https://github.com/angular-ui/bootstrap/issues/3396

**Comment by chrisirhc** [comment] 2015-04-17 05:58
Good point. Closing as duplicate of #3396 .

**Closed by chrisirhc** 2015-04-17 05:58 UTC
Labels: resolution: duplicate
