### ISSUE TITLE
Form Reset and Typeahead Bug

### ISSUE THREAD

**Issue by acgentry** [angular-ui/bootstrap#3049] opened 2014-12-04 16:48 UTC
If you set your typeahead to restrict to list (typeahead-editable="false) and the user types in garbage, resetting the form using a new model (model = {}) does not clear the typeahead control.  

[Here](http://embed.plnkr.co/4rzdI3KoCfIYOM5zROS5/preview) is a plnkr.

It does clear the control if the user selects a correct item in the array or the editability is turned on.

There seems to be other issues like this, but not exactly related since those seem to be angular 1.3 related and it looks like this is a problem in 1.2 as well.

**Comment by dmitriz** [comment] 2015-04-15 00:00
I wonder what kind of behaviour was actually intended with `typeahead-editable="false"`?

It indeed does not prevent user from typing garbage. 
However, not letting user type for no visible reason isn't user-friendly.

Even more problems restricting user edit would come from async loading...

**Comment by RobJacobs** [comment] 2015-04-15 00:15
Comments in the code: 

    should it restrict model values to the ones selected from the popup only?

**Comment by ankit5990** [comment] 2015-04-17 07:34
When typeahead is used with configuration <code>typeahead-editable="false"</code>, any garbage value entered by user sets the value of typeahead model to <code>undefined</code>. 

The approach used in the demo plunk tries to reset the values in the form by setting the corresponding value of the model to <code>undefined</code> again. As there is no actual change in the value of the model, the ngModel $formatters are not invoked which would have cleared the view, hence no change occurs in value being displayed.

The typeahead widget is not able to determine if any change has happened in the model, because for the widget, the value has not changed at all. It is still <code>undefined</code>.

In order to reset the model values, we can modify the resetting logic used in the plunk and explicitly set the value for the typeahead model to <code>null</code> as in this sample <a href="http://plnkr.co/edit/N6bES2vofDf1CvMHkBsh?p=preview">plunk</a>.

**Comment by ankit5990** [comment] 2015-04-17 07:37
There seem to be no straight forward way to fix this issue. 

The typeahead directive reads the input value and tries to assign a model value to it by using ngModel.$parsers. In case when model value can only be selected from the typeahead dropdown, the parser returns <code>undefined</code> to mark the input parsed value as invalid-parsed. 

As mentioned in <a href="https://docs.angularjs.org/api/ng/type/ngModel.NgModelController">angular docs</a>, in such a case, the model is assigned a value <code>undefined</code>.

Now if we use some logic to reset the value of the typeahaed by reassigning it <code>undefined</code>, it will not work as no watches, formatters, etc will be invoked (as no actual change in value has occured).

**Comment by chrisirhc** [comment] 2015-04-17 07:44
Agreed. This isn't restricted to just typeahead. Any form input that requires a parser would have this same issue. I believe this is by design (by AngularJS) though. As @ankit5990 mentioned, you need the explicit null.

**Closed by chrisirhc** 2015-04-17 07:44 UTC
Labels: AngularJS 1.2, AngularJS 1.3, component: typeahead, PRs plz!

**Comment by ankit5990** [comment] 2015-04-18 18:36
:)
my pleasure...
I am glad you found the analysis useful
