### ISSUE TITLE
Displaying the black square a few milliseconds in the "animation: false" in Modal

### ISSUE THREAD

**Issue by hopest** [angular-ui/bootstrap#5298] opened 2016-01-19 11:01 UTC
If you turn off the animation dialog box, at the moment, it appears completely black shade.

this problem can be clearly seen in the browser IE11, or on slower computers
![screenshot_7](https://cloud.githubusercontent.com/assets/5830839/12416804/359dd56e-beac-11e5-9c86-2b0b7264ee23.jpg)

**Comment by wesleycho** [comment] 2016-01-19 14:24
Is this with 1.1.0? Can you give more information about this scenario? I am having trouble reproducing this.

**Comment by hopest** [comment] 2016-01-19 21:08
Here https://www.youtube.com/watch?v=ZGVNKinES6А video that demonstrates this point.
The first part of the **animation: true**. The second part of the **animation: false**

When **animation: false** on older PCs, the black shading can be seen for a long time.

**Comment by wesleycho** [comment] 2016-01-19 22:26
I need more information still - what versions does this occur in, and how best can I reproduce it in order to craft a fix for this?

Without this information, this isn't likely to be fixed.

**Comment by hopest** [comment] 2016-01-20 08:13
This is version 1.1.0.
Sample code, taken out of the main examples of library http://angular-ui.github.io/bootstrap/#/modal http://plnkr.co/edit/FLrgGm?p=preview
1. Open example
2. Press the **Toggle Animation (false)**
3. Open Inspect Chrome


Put breakpoints
...angular-animate.js
Number line **2598**

```
 function markElementAnimationState (element, state, details) {
      details = details || {};
      details.state = state;
.....
}
```

Inspecting (F8)

**Comment by sime** [comment] 2016-01-20 14:35
Using the above technique, I too see for a moment the backdrop element only having the following classes for a number 'cycles': `modal-backdrop in-add`.

Eventually the backdrop element finishes on `modal-backdrop in`

**Comment by sime** [comment] 2016-02-12 16:04
I don't know if there is a possible solution, but a workaround is this overriding CSS

```css
.modal-backdrop {
  opacity: .5;
}
```

But it does leave backdrop inherently broken by default.

**Comment by wesleycho** [comment] 2016-03-05 05:40
We may try fixing this by switching from $animateCss to $animate - anyone may try their hand at experimenting with a switch and seeing if this fixes the issue, but if not, I will investigate this myself.

**Comment by wesleycho** [comment] 2016-03-05 13:34
I took a look, but it looks like switching to $animate does not fix this, as seen [here](http://plnkr.co/edit/akifkx?p=preview).

I suspect this is due to a change that fixed another bug that was worse, 1dbad8a05739964b06d4ecb40fea2ce5030107ed.

If this is the case, we may have to break up the compilation step depending on the state of animations.

**Closed** 2016-03-05 18:47 UTC
Labels: component: modal, severity: regression, type: bug, type: ngAnimate

**Comment by mb2140** [comment] 2016-03-22 05:07
Looks like I'm still running into this issue (slower computer).  Is there a way to manually remove the fade-in/fade-out, or just adjust the timing?

**Comment by sime** [comment] 2016-03-22 06:17
@mb2140 Have you tried my previously suggested CSS override?

**Comment by mb2140** [comment] 2016-03-22 13:37
I tried:

.modal-backdrop {
  opacity: .5 !important;
}

But it doesn't seem to do anything.  I'm wondering if maybe this is an inline style being set by js somewhere?
