### ISSUE TITLE
Content shifts to right

### ISSUE THREAD

**Issue by Mioleris** [angular-ui/bootstrap#6216] opened 2016-08-31 07:19 UTC
Noticed that when modal window is open my content with fixed menu shifts to right.
The problem is that code line:
```
if ($uibPosition.isScrollable(appendToElement)) { ...
```
returns false becouse body element default overflow is visible. But your regexp checks for auto|scroll.

And other code line:
```
if (scrollbarPadding.heightOverflow && scrollbarPadding.scrollbarWidth) {
```
scrollbarPadding.heightOverflow returns false although there is verticall scrollbar on my website.

This code line:
```
heightOverflow: scrollParent.scrollHeight > scrollParent.clientHeight,
```
scrollHeight and clientHeight returns same values although there is verticall scrollbar

Angular: 1.4.9

Bootstrap: 2.1.3

Windows 10, Chrome Version 52.0.2743.116 m (64-bit)

**Comment by pkozlowski-opensource** [comment] 2016-08-31 07:42
Duplicate of #6125

**Closed by pkozlowski-opensource** 2016-08-31 07:42 UTC
