### ISSUE TITLE
parseDateString function receive modelValue

### ISSUE THREAD

**Issue by nosix** [angular-ui/bootstrap#6345] opened 2016-12-04 12:58 UTC
### Bug description:

I have validation error in valid date. The date is formatted ISO 8601. For example, "2016-12-03T15:00:00.000Z".

The date is converted to Date object in directive, as below:

```
ctrl.$formatters.push(function(modelValue){
  return modelValue === null ? null : new Date(modelValue);
});
```

At the time, `parseDateString` function in datepickerPopup/popup.js is failed. `viewValue` parameter receive `modelValue`. 

```
function parseDateString(viewValue) {
    var date = dateParser.parse(viewValue, dateFormat, $scope.date);
    ...
}
```

```
function validator(modelValue, viewValue) {
    var value = modelValue || viewValue;

    ...

    if (angular.isString(value)) {
      return !isNaN(parseDateString(value));
    }

    return false;
}
```

For example, `modelValue = '2016-12-03T15:00:00.000Z'`, `viewValue = '2016-12-04'` and `uib-datepicker-popup="yyyy-MM-dd"`.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/sMNKxk

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.9

UIBS: 2.3.0

Bootstrap: 3.3.7

**Comment by wesleycho** [comment] 2016-12-27 10:35
I highly recommend converting the date string into a date object before binding, and not mess with the formatters/parsers. This won't be fixed in the library itself as it does not support string usage due to timezone issues, and this formatter looks like an attempt to work around it.

Going to close as expected behavior.

**Closed by wesleycho** 2016-12-27 10:35 UTC

**Comment by nosix** [comment] 2016-12-27 12:15
Thank you for your reply.

I thought viewValue parameter at parseDateString function in datepickerPopup/popup.js must have viewValue, but viewValue parameter has modelValue. As a reason for thinking like that, the parameter name is `viewValue`. If parameter name is `value`, I don't wonder. 

You wrote "it does not support string usage", but validator function checks `parseDateString(value)`. Why does check it? I wonder it. If value must not have string, then I think that the code should be as follows.

```
if (angular.isString(value)) {
    return false;
}
```

So, I thought value variable at validator function can have string.
