### ISSUE TITLE
Dropdown directive shouldn't fire $rootscope.$digest() on every dropdown close

### ISSUE THREAD

**Issue by YuraDubensky** [angular-ui/bootstrap#6403] opened 2017-01-11 12:28 UTC
### Bug description:
In "dropdown.js" line 112 there is call to openscope.$apply(), which triggers $rootscope.$digest(). This adds additional and not needed (I could be wrong here) full app digest cycle. That would be great if this call could be replaced with openscope.$digest(). 

Same applies to lines 324-326. Instead of wrapping "dropdownCtrl.toggle();" in scope.$apply, it can written as chaining:
dropdownCtrl.toggle();
scope.$digest();

### Version of Angular, UIBS, and Bootstrap

Angular:
1.5.9
UIBS:
1.3.3
Bootstrap:
?

**Comment by wesleycho** [comment] 2017-01-23 10:35
I do not think this can be done safely - toggling of the dropdown state with the open binding means that changes can flow up the $scope tree, resulting in potentially app-wide changes, and this behavior is almost assuredly relied upon in production applications.

Going to close this as something that will not be supported due to the regressions/bugs this request is likely to spawn.

**Closed by wesleycho** 2017-01-23 10:35 UTC
