### ISSUE TITLE
uib-collapse flicker issue.

### ISSUE THREAD

**Issue by mehmetenes** [angular-ui/bootstrap#5055] opened 2015-12-11 14:04 UTC
After updating the ui-family libraries, the navigation menu based on collapse directive started to flicker at every load. Since my menu data is updated based on an interval, this caused flickers on regular basis. the old collapse directive was working without flickers. the issue is caused by the difference in expand and collapse methods called by the uibCollapse watcher.

the comment in the collapse method says;
// IMPORTANT: The height must be set before adding "collapsing" class.
// Otherwise, the browser attempts to animate from height 0 (in
// collapsing class) to the given height here.

it was taken into account in the old directive (collapse) but not in the new one and for those whose "shouldCollapse" is always false because of the newly resolved menu items will have a flicker effect during expand method call.

**Comment by icfantv** [comment] 2015-12-11 15:40
If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

**Comment by wesleycho** [comment] 2015-12-17 10:33
Closing due to lack of reproduction.

However, due to the nature of the last sentence, I suspect we already addressed this issue in #5075.

**Closed by wesleycho** 2015-12-17 10:33 UTC
Labels: component: collapse, needs: plunkr
