### ISSUE TITLE
Issues with a text input and date

### ISSUE THREAD

**Issue by sampie** [angular-ui/bootstrap#5159] opened 2016-01-07 13:37 UTC
If the date format is specified as dd.mm.yy the datepicker does not recognize strings like "1.1.2016" (like it is typically typed), but user must type 01.01.2016. It also seems that if user types 1.1.2016 or something else that is considered invalid, the ng-model variable disappears from the containing object structure. Is it possible to configure datepicker in such a way that 1) input field ng-variable is maintained as a string 2) the variable is altered by the datepicker only when a date is selected from the popup?

**Comment by wesleycho** [comment] 2016-01-07 14:18
This is addressed in `master` via b1cfc5762dd80d8eecec95385a4dcf335cdb8ecd

**Closed by wesleycho** 2016-01-07 14:18 UTC

**Comment by sampie** [comment] 2016-01-09 07:53
I tested in plunker. I added {{dt}} to the code to see the ng-model content. Selected "dd.MM.yy" format from the selection box and wrote "12.1.2016" to the first popup. dt did not print at all. Only when I wrote "12.10.2016" the dt became available/visible. Did I use this in some wrong way?

**Comment by wesleycho** [comment] 2016-01-09 13:02
There are the M! and d! formats for optional leading 0s. The commit I referenced shows usage.

This is available in the newly released 1.0. If you aren't able to immediately upgrade, you can override the dateparser service with the one from `master`.

**Comment by sampie** [comment] 2016-01-09 13:20
I am unsure how to specify to the datepicker to use M! and d!. 
The datepicker plunker from https://angular-ui.github.io/bootstrap/ seems to be using 1.0.0 and the code has a line: "$scope.altInputFormats = ['M!/d!/yyyy'];" Still the plunker example do not accept "2016/01/9". If I put this 'M!/d!/yyyy' string to  $scope.format, it does not work either.

**Comment by wesleycho** [comment] 2016-01-09 13:30
Please post a reproduction - I am not able to reproduce your problem.

**Comment by sampie** [comment] 2016-01-09 21:20
Now I got it. So "altInputFormats" like "format" describe just one input format and in the example it is not possible to write the offered formats 'dd-MMMM-yyyy', 'yyyy/MM/dd', 'dd.MM.yyyy' with one digit. Only a totally different form 'M!/d!/yyyy' is allowed to be typed with one digit, so this needs to be rewritten as 'd!.M!.yyyy' to make my original date string to be accepted. So, 1.0.0 Seems to work with nicely when user writes accepted format. Now, if user clears the input field the value becomes null. However, if user writes by a mistake an invalid string and the json is sent to server, the key and value are missing from the json. I am not unsure how this case should be handled because server can't see the malformed datestring.
