### ISSUE TITLE
tooltip-append-to-body="true" should be simply:  tooltip-append-to-body

### ISSUE THREAD

**Issue by gaultier** [angular-ui/bootstrap#4495] opened 2015-09-30 12:24 UTC
Hello,
When we use the tooltip element and we would like to append it to the body, we expect to use the option this way:
```
<p tooltip="my tooltip" tooltip-append-to-body>Hello</p>
``` 
But in fact the only possible usage is this way:
```
<p tooltip="my tooltip" tooltip-append-to-body="true">Hello</p>
``` 

This is counter-intuitive, hard to detect, and every other component does it the simple way.
This option should probably be used with the shortest syntax.

Could we either way add an example in the doc?

The only hint to use it that way is here: https://github.com/angular-ui/bootstrap/blob/master/src/tooltip/test/tooltip.spec.js#L538

**Comment by icfantv** [comment] 2015-09-30 17:01
We don't have an `$observe` on the `*-append-to-body` attribute so we're not evaluating it for changes.  I think this is a reasonable request.  Please feel free to submit a PR w/ appropriate functional tests.

I ask that you please do the PR because there's nothing wrong with what we have now and it is working.  Thus, it's probably going to be a very low priority for us to change.

**Comment by wesleycho** [comment] 2015-10-26 21:31
This would actually require a breaking change, and a potentially onerous one - [these lines](https://github.com/angular-ui/bootstrap/blob/master/src/tooltip/tooltip.js#L488-L489) are the culprit. The change needed would be
```js
            var appendToBodyVal = (prefix + 'AppendToBody') in attrs;
            appendToBody = appendToBodyVal || appendToBody;
```

I am inclined to reject this request.

**Comment by chrismbarr** [comment] 2015-10-27 18:25
This isn't true in all cases.  I set up my app to set this option by default, like so:

```typescript
angular.module("myApp")
    .config(["$tooltipProvider", ($tooltipProvider: angular.ui.bootstrap.ITooltipProvider) => {
		$tooltipProvider.options({
			appendToBody: true
		});
	}])
```

and I use `tooltip-append-to-body="false"` on the occasion when I need it.

**Comment by RobJacobs** [comment] 2015-10-27 19:21
Valid point by @chrismbarr, my vote: :-1:

**Comment by wesleycho** [comment] 2015-10-27 19:55
Great point @chrismbarr - closing as invalid.

**Closed by wesleycho** 2015-10-27 19:55 UTC
Labels: component: popover, component: tooltip, resolution: invalid, type: enhancement

**Comment by gaultier** [comment] 2015-10-27 21:07
Either way I think a precision/example in the documentation would be nice because this option is present on none of the existing examples.

**Comment by deje1011** [comment] 2015-11-26 14:55
totally agree with @gaultier, it would be nice to mention this in the documentation as it is not the expected behavior (in my opinion). 
Currently it just says:
 "tooltip-append-to-body: Should the tooltip be appended to $body instead of the parent element?"

Why can't the attribute be checked to be neither undefined nor false though?

**Comment by icfantv** [comment] 2015-11-26 15:29
@deje101, maintaining this OSS library requires a fair amount of work by many people.  Please extend us the courtesy of searching both open and closed issues before commenting.  There is an open issue from a few days ago, #4945, that is tracking this.

**Comment by deje1011** [comment] 2015-11-26 16:00
Sorry @icfantv, I just randomly found this thread when I was searching for a solution on google. I will check for new issues before posting next time.

**Comment by icfantv** [comment] 2015-11-26 18:04
No worries and thanks.
