### ISSUE TITLE
is uib-tab-heading compiling? if so, it's doing it in isolation. Parent controllers not found.

### ISSUE THREAD

**Issue by miguel-leon** [angular-ui/bootstrap#6063] opened 2016-06-29 17:14 UTC
Adding a directive that requires a parent controller to the tab heading element (uib-tab-heading) gives a angularjs compilation error. Which doesn't happen if this directive is in a sibling element of the tab heading. It's like the tab heading is being transcluded in isolation and doesn't know about its parent elements.

Check out in http://plnkr.co/edit/ME3jKBy14fzyyORzZymm?p=preview
View the console error.

**Comment by wesleycho** [comment] 2016-06-29 18:06
It is not compiled. It is a custom element that is not an Angular directive. There is a potential controller issue due to the library not using multi-slot transclusion from Angular 1.5 yet.

Going to close this as a duplicate of #5709.

**Closed by wesleycho** 2016-06-29 18:06 UTC

**Comment by miguel-leon** [comment] 2016-06-29 22:26
It doesn't have to do with that. It also happens with Angular < 1.5.

The element is automatically compiled when passed to the transclusion function in line [5658](https://github.com/angular-ui/bootstrap/blob/master/src/tabs/tabs.js#L212).

I reverse engineered the stack calls and I see the problem is that the element is never added to the DOM inside that cloneLinkingFn, so it doesn't have parents to get the required controllers from.

It might not be an easy-to-solve bug or even a design problem, but it's there.
Sorry to bother, but it was worth reporting, at least for it to be considered a lack of capabilities in the tab set directive if not a bug.

Sadly, this is the [second time](https://github.com/angular-ui/bootstrap/issues/5089#issuecomment-165671084) it has happened to me that you disdain a post as if I was talking nonsense.

Regards.
