### ISSUE TITLE
Timezone setting is being ignored by date picker and date picker popup

### ISSUE THREAD

**Issue by weblets** [angular-ui/bootstrap#6140] opened 2016-08-04 06:24 UTC
### Bug description:

I tried to have the date picker popup display and handle a different timezone but it seems that this does not work.
The root problem is, ng-model-options="{timezone: 'any timezone setting'}" does not seem to have any effect on the resulting date. Also today and maxDate and minDate seem to adjust themselves still on the local browser timezone.

I have attached a plunker example which shows the problem.

I basically worked around all this with a set of decorators which fixes most core problems (aka the parser for instance does not take the timezone into account, comparisons only compare dates not time etc...)
But for one thing I had to fix the code itself, for the popup the ng-model-options timezone is reset to zero thus resulting in the display of selected date and today always for the local timezone not the one set in the model options.

https://gist.github.com/weblets/1eb834783f7e1d1138b83ec430a252aa

This links to a code snippet with the affecting line documented. I am not entirely sure what sideffects we get if we leave the timezone in instead of nulling it in a non decorated scenario. I have to perform further tests on this in a standard non decorated environment. But the timezone ignoring problem is deeper it also is in the parser etc... So fixing this line alone wont help.

### Link to minimally-working plunker that reproduces the issue:
Here is a plunker which demonstrates the general problem of the timezone being ignored.
You have to be out of GMT+2 to see the problem of both input fields (one with timezone setting and one without showing a local date and producing the same results)

http://plnkr.co/edit/bAz3swqtE9HRLMJFjKIo?p=preview

### Version of Angular, UIBS, and Bootstrap
Angular:  1.5.5
UIBS:  2.0.1
Bootstrap:  3.3.6

**Comment by icfantv** [comment] 2016-08-04 15:47
@weblets you could have updated the original issue and I would have reopened.  :-)

Thank you for resubmitting with the necessary, additional details.  We'll take a look.

**Comment by wesleycho** [comment] 2016-08-06 06:27
It should be noted that the ng-model-options config for the popup and the inline datepicker are separated now - that might be the cause of this. See [here](http://plnkr.co/edit/5Me6Ik5oXeWstiRYwOhW?p=preview).

**Comment by joseph-etorne** [comment] 2016-08-11 13:33
I am also having problems with **ng-model-options="{timezone: '+0000'}"**.  when selecting a new date, it should get the date and time in UTC, instead i get the local date and time.  This only happens in versions 2.0.0 and 2.0.1.  I tried version 1.3.3 and it's working fine

**Comment by wesleycho** [comment] 2016-08-20 13:32
This should be fixed now in the latest release.

**Closed by wesleycho** 2016-08-20 13:32 UTC
Labels: component: datepicker-popup, needs: investigation
