### ISSUE TITLE
Datepicker not working with i18n + longDate

### ISSUE THREAD

**Issue by javorosas** [angular-ui/bootstrap#4028] opened 2015-07-28 05:46 UTC
The date shows up well at the begining. Then, when selecting a date, the ng-model is set to undefined.

I'm having these issues with the datepicker under the following circumstances:

* Angular 1.4.3
* ui-bootstrap 0.13.1
* angular i18n es-mx
* When `datepicker-popup="longDate"`

I prepared this plunkr where it's reproduced
http://plnkr.co/edit/5M69XTp1dCuTS1MEH1r5?p=preview

Using ui-bootstrap 0.12.1 is working fine (except for the initialization format issue that was fixed on 0.13.0).

Thanks.

**Comment by wesleycho** [comment] 2015-07-28 14:22
Indeed, the datepicker does not currently support i18n - if you look in the dateparser component in the source code, you will see that there are manual regexs for parsing the date. `long` is not an option there.

I will gladly accept any PRs fixing this.

**Comment by javorosas** [comment] 2015-07-28 18:51
short and medium are neither an option and they both work

**Comment by wesleycho** [comment] 2015-07-28 23:16
Not all of the flags in `long` option work (as per Angular documentation) is the problem IIRC.

**Comment by wesleycho** [comment] 2015-10-15 05:54
Closing as a duplicate of #3418

**Closed by wesleycho** 2015-10-15 05:54 UTC
Labels: component: datepicker, PRs plz!, type: enhancement
