### ISSUE TITLE
Datepicker - ignores format on initial data bind with angular 1.3.15 stable

### ISSUE THREAD

**Issue by johnsonlin** [angular-ui/bootstrap#3595] opened 2015-04-29 01:11 UTC
I replaced angular lib from 1.2.6 to 1.3.5 of http://angular-ui.github.io/bootstrap/#/datepicker on my local machine and found the datepicker ignores the `format` (which is `'dd-MMMM-yyyy'`) on initial data bind.
Here's a comparison
### My demo with 1.3.15 stable
http://plnkr.co/edit/t5PnLtq9Ygh5iosJXaT8?p=preview

### Official site demo with 1.2.6
http://plnkr.co/edit/5E0Hnx?p=preview

**Comment by johnsonlin** [comment] 2015-04-29 01:13
I even tried the latest stable version which is 1.3.15
it does the same thing as 1.4.0

**Comment by rvanbaalen** [comment] 2015-04-29 01:30
Please fork the demo plunkr to show your issue. We dont support Angular 1.4 yet since there is no stable (non-beta) release so far. If this is also an issue in 1.3 we'll have to take a look at it for the 0.13 or 0.13.x release.

**Comment by johnsonlin** [comment] 2015-04-29 01:56
@rvanbaalen 
not sure if I did what you want me to do.
But I think it's easy enough for you to review
thanks

**Comment by rvanbaalen** [comment] 2015-04-29 20:13
This seems a duplicate of #3104

**Comment by chrisirhc** [comment] 2015-05-03 06:50
I believe this is now working on 0.13.0. See http://plnkr.co/edit/dXJlJEbMHoNX8tE740MI?p=preview

**Closed by chrisirhc** 2015-05-03 06:50 UTC
Labels: AngularJS 1.3, component: datepicker, needs: investigation
