### ISSUE TITLE
datepicker custom-class not rendering with function that uses $resource data

### ISSUE THREAD

**Issue by extropianer** [angular-ui/bootstrap#4189] opened 2015-08-11 22:18 UTC
The datepicker module seems to not 'render' correctly if supplying a `customClass` that takes data from an async `$resource`. Going through the sourcecode i realized that selecting a new date forces the directive to `renderView()` which in turn triggers the `customClass`. However even though the function gets called and assings the correct custom class it is still not visible on the HTML. I am not sure whether this is an issue with the a-ui or DOM itself since the `customClass` gets called and attaches the style to the DOM element - at least that's what chrome debug tells me. 
To correctly display the custom class on the date i have to switch to another month and then go back to the previous. 

I modified the tutorial plunker to reflect this problem by adding one of the two custom classes after a 10ms timeout (line 50-ish). In addition I added a small counter that increases every time the customClass function (`getDayClass`) gets called due to `renderView()` calls in the bootstrap.datepicker directive. This shows that the `renderView` gets called, the classes even get attached to the DOM but they are not rendered.
http://plnkr.co/edit/h8PxWfxSEtZuVCct00mD?p=preview

Reproduce:
* load the plunker > you should see one green day (tomorrow)
* click on a random day > the counter on the bottom should increase, indicating that the customClass was called (click on a day triggers `renderView()`)
* still only one day with a special class
* switch to next month and back
* see day after tomorrow also highlighted with special class

I tried investigating the issue in the sourcecode but i couldn't find any trails to pursue..so it would be great if you can point me in the right direction! 

bower.json / versions used
```
  "dependencies": {
    "angular": "~1.3.0", =>  @license AngularJS v1.3.17
    "angular-bootstrap": "0.13.x", => * Version: 0.13.2 - 2015-08-02
    "angular-route": "latest",
    "angular-resource": "latest",
    "bootstrap": "3.3.x",
    "requirejs-text": "2.0.x",
    "requirejs": "2.1.x"
  },
  "devDependencies": {
    "angular-mocks": "~1.3.0"
  }
}
```

**Comment by wesleycho** [comment] 2015-10-20 11:14
Closing as this is essentially a duplicate of #4626

**Closed by wesleycho** 2015-10-20 11:14 UTC
Labels: component: datepicker, needs: investigation, type: bug

**Comment by rknell** [comment] 2016-04-14 11:46
I note this is closed but if you then click on another date the one previously selected will likely show up (at least it does in my rig)

Since I'm using a custom build anyway, I am going to find a way to expose the function and call in manually when you change the input data

**Comment by rknell** [comment] 2016-04-14 12:02
super hacky but this seems to work for me. Replace the function in datepicker. I tried using $timeout but it didn't like it. 

Step 1. Change the signature to include a `retry` variable. Its just a placeholder to kill the infinite loop.
```
this.refreshView = function(retry) {
```

Step 2. Add this to the end of the function
```
if(!retry){
      setTimeout(function () {
        console.log("Refreshing view timeout");
        _this.refreshView(true);
        $scope.$apply();
      }, 1);
    }
```


Full Code:
```
this.refreshView = function(retry) {
    console.log("Refresh view");
    if (this.element) {
      $scope.selectedDt = null;
      this._refreshView();
      if ($scope.activeDt) {
        $scope.activeDateId = $scope.activeDt.uid;
      }

      var date = ngModelCtrl.$viewValue ? new Date(ngModelCtrl.$viewValue) : null;
      date = dateParser.fromTimezone(date, ngModelOptions.timezone);
      ngModelCtrl.$setValidity('dateDisabled', !date ||
        this.element && !this.isDisabled(date));
    }
    var _this = this;

    if(!retry){
      setTimeout(function () {
        console.log("Refreshing view timeout");
        _this.refreshView(true);
        $scope.$apply();
      }, 1);
    }

  };
```
