### ISSUE TITLE
Tooltip fails when closing on an element that's removed

### ISSUE THREAD

**Issue by WilcoFiers** [angular-ui/bootstrap#3347] opened 2015-02-27 14:46 UTC
I'm using the tooltip on a delete button, which delete a row in a table. The button has a mouse enter/leave effect. When I click the button, which is then deleted with an animation, the following error is logged:
Uncaught TypeError: Cannot read property 'isOpen' of null

The following seems to fix the problem:
            function toggleTooltipBind () {
              if (!ttScope) return; // Check that the element still exists. 
              if ( ! ttScope.isOpen ) {
                showTooltipBind();
              } else {
                hideTooltipBind();
              }
            }

**Comment by karianna** [comment] 2015-02-27 14:51
plunkr please

**Comment by wesleycho** [comment] 2015-08-06 07:14
Closing this issue as potentially old, and due to lack of reproduction.

Feel free to open a new issue if you are able to reproduce this on Plunker.

**Comment by btrauma8** [comment] 2015-09-04 19:42
I can reproduce this with a plunkr!  

http://plnkr.co/edit/gXcpxofs6PMJ1M7LaCfy?p=preview

my fix is just "if (!ttScope) return;" as first line of hide() function

**Comment by wesleycho** [comment] 2015-09-04 20:12
That's a reasonable & simple fix - would you like to file a PR with it? If not, I can do so, but you should get the credit :) .

**Comment by SyntaxUnknown** [comment] 2015-09-09 15:24
We're actually hitting this error in several other locations in our application:

            attrs.$observe( prefix+'Title', function ( val ) {
              Here --> ttScope.title = val;
              positionTooltipAsync();
            });

            attrs.$observe( prefix + 'Placement', function () {
             Here -->  if (ttScope.isOpen) {
                $timeout(function () {
                  prepPlacement();
                  show()();
                }, 0, false);
              }
            });


It seems for our issue, problem that ttScope is set to null here:

            // Make sure tooltip is destroyed and removed.
            scope.$on('$destroy', function onDestroyTooltip() {
              $timeout.cancel( transitionTimeout );
              $timeout.cancel( popupTimeout );
              unregisterTriggers();
              removeTooltip();
              ttScope = null;
            });

but the attrs.$observe() calls are not released. It seems those are still firing after $destroy happens in my tests.

For each attrs.$observe(), it should hold on to the return value and then call it during release, correct?

**Comment by wesleycho** [comment] 2015-09-09 15:27
Good call - we need to investigate this further.

**Closed** 2015-09-24 16:14 UTC
Labels: component: tooltip, type: bug
