### ISSUE TITLE
Datepicker popup does not work with literals

### ISSUE THREAD

**Issue by douglascvas** [angular-ui/bootstrap#5665] opened 2016-03-21 15:31 UTC
### Bug description:
Datepicker popup does not work with literals (as the one example shown in the documentation). 
Example: 
```
uib-datepicker-popup="d 'de' MMMM y"
```
or even
```
uib-datepicker-popup="yyyy-MM-dd h 'o\'clock'"
```
### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/h4bZ5VnkCDAnyugFphLk

### Version of Angular, UIBS, and Bootstrap

Angular: `1.5`
UIBS:  `1.2.5`
Bootstrap:  `3.3.6`

**Comment by wesleycho** [comment] 2016-03-21 16:01
Closing as duplicate of #5620

**Closed by wesleycho** 2016-03-21 16:01 UTC
