### ISSUE TITLE
date picker regression: min-,init-,max- date only work with strings while ng-model only works with object

### ISSUE THREAD

**Issue by arisbartee** [angular-ui/bootstrap#5335] opened 2016-01-24 05:03 UTC
I've have just updated to 1.1.0 from 0.13.4. 
I've come across a regression with the following options: min-,init-,max-date only work with strings while ng-model only works with a date object

 In version 0.13.4 I use a string as my input value  with the  format: "yyyy-MM-dd".
I use 2 date pickers(dp1 and p2). I also use 3 date values(d1, d2, today).  The problem can be describe this way

dp1 ->  min-date="" max-date="d2" init-date="" ng-model="d1"
dp2 -> min-date="d1" max-date="" init-date="d1" ng-model="d2"

The expected results are: 
 when d2 changes the max-date for dp1 should change. 
when d1 changes the min-date for dp2 should change.
currently this does not happen because the ng-model value can not be re-used.

**Comment by wesleycho** [comment] 2016-01-24 09:14
Can you post a reproduction in Plunker?

**Comment by tribicito** [comment] 2016-01-29 00:11
I'm having the same issue with the calendar. If the dates are on a string format, the calendar does not open. I have attached a plunkr for you to review.

https://plnkr.co/edit/pqBK0omSm2Mdt86ov4WS?p=preview

**Comment by wesleycho** [comment] 2016-01-31 22:07
Closing due to lack of reproduction.

**Closed by wesleycho** 2016-01-31 22:07 UTC
Labels: component: datepicker, needs: plunkr
