### ISSUE TITLE
1.0.3: ng-class broken on uib-accordion-group 

### ISSUE THREAD

**Issue by hoxu** [angular-ui/bootstrap#5227] opened 2016-01-13 09:28 UTC
Consider this plunkr:

http://plnkr.co/edit/oPXpvtLfP3xZtSH1YqkQ?p=preview

This:

```
    <uib-accordion-group heading="Static Header, initially expanded" is-open="status.isFirstOpen" is-disabled="status.isFirstDisabled" ng-class="{'bg-info': true}">
```

Results in div.panel having ng-class attribute:

```
ng-class="{'bg-info': true} panelClass || 'panel-default'"
```

Which looks like invalid syntax to me!

**Comment by wesleycho** [comment] 2016-01-13 13:59
Duplicate of #4172.

In short, it is recommended to use `class="{{myCustomClass}}" in this situation since `uib-accordion-group` uses `replace: true` under the hood, which is the situation that Angular itself does not support ng-class usage with.

**Closed by wesleycho** 2016-01-13 13:59 UTC

**Comment by remydavid** [comment] 2016-01-22 11:48
How do you access accordion status then ?
I need to have a class set when accordion is open, I have : 
    <uib-accordion-group
          class="{{vm.getAccordionClass(status.open)}}"

But status.open is undefined.
