### ISSUE TITLE
pagination control accessibility, skip disabled buttons

### ISSUE THREAD

**Issue by hbostic** [angular-ui/bootstrap#5448] opened 2016-02-09 03:08 UTC
When tabbing through the pagination controls, first page for instance, the previous and go to first buttons are correctly disabled, however, their tabindex is not set and thus allowing them to be tabbed in their disabled state.  Is this by design?

**Comment by icfantv** [comment] 2016-02-09 04:12
Closing as duplicate of #5151.

**Closed by icfantv** 2016-02-09 04:12 UTC

**Comment by chvenkat668** [comment] 2017-03-13 06:36
Hi. I am also facing same kind of issue, can you help me, how you resolved this accessibility issue in ui-bootstrap1.1.1
