### ISSUE TITLE
UI Boostrap for Bootstrap 4

### ISSUE THREAD

**Issue by matheusggds** [angular-ui/bootstrap#6535] opened 2017-05-02 13:59 UTC
Is there a support for Bootstrap 4 using Angular 1.x ?

**Comment by pkozlowski-opensource** [comment] 2017-05-02 14:17
No, but there is Bootstrap 4 version for Angular 2+: https://ng-bootstrap.github.io/#/home

**Comment by kukac7** [comment] 2017-05-02 15:47
@matheusggds topic: https://github.com/angular-ui/bootstrap/issues/4234

**Comment by pkozlowski-opensource** [comment] 2017-05-02 15:49
Yeh, this is direct duplicate of #4234

**Closed by pkozlowski-opensource** 2017-05-02 15:49 UTC
