### ISSUE TITLE
tabset and Angucomplete conflict

### ISSUE THREAD

**Issue by kuroware** [angular-ui/bootstrap#3898] opened 2015-07-06 04:49 UTC
Using angucomplete from:
<a href="https://github.com/darylrowland/angucomplete
">https://github.com/darylrowland/angucomplete</a>
Or angucomplete-alt from:
<a href="https://github.com/ghiden/angucomplete-alt">https://github.com/ghiden/angucomplete-alt

Both seemingly result in a "conflict" as selectedobject/selected-object remains undefined even after being selected. Upon removing the angucomplete directive from the tabset interior, selected-object became defined. 

Edit:
Also noticed that trying to use something like
<pre>
 input type="text" ng-model="blah" 
</pre>
Also remains undefined for blah. Set a $scope.$watch on blah as well to no avail.

**Comment by wesleycho** [comment] 2015-07-06 20:14
Can you show a reproduction via [Plunker](http://plnkr.co/)? Taking a quick look at the angucomplete code, I notice no usage of ng-model though, which looks suspicious on first glance.

Also, is there any reason why [typeahead](http://angular-ui.github.io/bootstrap/#/typeahead) wouldn't satisfy your needs?

**Comment by wesleycho** [comment] 2015-09-01 20:18
Closing due to insufficient information - feel free to provide more information if this is a UI Bootstrap issue in particular.

**Closed by wesleycho** 2015-09-01 20:18 UTC
Labels: component: tab, needs: info, needs: plunkr
