### ISSUE TITLE
selecting the current day from datepicker does not sync the value with model

### ISSUE THREAD

**Issue by izzeddeen** [angular-ui/bootstrap#4133] opened 2015-08-07 06:40 UTC
When you bind datepicker to a model that's initially empty, then select today's date from the calendar, that day will get rendered in the input field but does not sync with the model.

**Comment by Foxandxss** [comment] 2015-08-07 09:21
Could you please create a plunker to reproduce the error? It is working for me.

**Comment by nipec** [comment] 2015-08-10 14:37
I have a similar strange error. When setting my date initially, everything works fine. See Plunker: http://plnkr.co/edit/RkByqVhCrcSCXWGXGkWo

The date of today is shown correctly in the view and in the model.

Now test this: Open the popup datepicker and click on "Clear". Then click on "Today". View is fine, the model is wrong. It shows yesterday, I assume because my timezone offset was substracted. It shows 
2015-08-09T22:00:00.000Z

**Comment by wesleycho** [comment] 2015-08-16 09:43
Closing due to no reproduction.

@nipec there are numerous open issues about that particular bug you mention, so we will be using those tickets to track progress on that issue.

**Closed by wesleycho** 2015-08-16 09:43 UTC
Labels: component: datepicker, needs: plunkr
