### ISSUE TITLE
Swiping modal window on iOS

### ISSUE THREAD

**Issue by gh-naylor** [angular-ui/bootstrap#1720] opened 2014-02-01 01:33 UTC
Swiping a modal window on iOS that has an overflow scrolls the background page instead of the contents of the modal.

I looked into binding touchstart to the .modal-dialog element using ng-touch, but I'm not having much luck.

Has anyone been down this road before?

**Comment by wesleycho** [comment] 2015-08-03 06:07
There is a suggested workaround in #3891.

Closing this as a duplicate of that issue, as there is more information on research into the problem in that issue.

**Closed by wesleycho** 2015-08-03 06:07 UTC
Labels: component: modal, resolution: support, type: bug
