### ISSUE TITLE
Collapse inside collapse not working as expected with example

### ISSUE THREAD

**Issue by W1zzard** [angular-ui/bootstrap#2821] opened 2014-10-13 07:42 UTC
If i use collapse inside other collapse inner collapse not working as expected:
http://plnkr.co/edit/DTY72Zf7dX3QqN6jwtcj?p=preview
toggle collapse, then toggle inner collapse, then close outer and close inner, open outer, inner still open but should be closed.

**Comment by chrisirhc** [comment] 2015-03-23 03:05
Should be fixed via #1444

**Comment by chrisirhc** [comment] 2015-03-23 03:09
Possibly duplicate of #1774

**Closed** 2015-03-23 10:02 UTC
Labels: component: collapse, type: bug
