### ISSUE TITLE
Carousel interferes with original bootstrap carousel

### ISSUE THREAD

**Issue by DetlefPeters** [angular-ui/bootstrap#4932] opened 2015-11-20 10:38 UTC
In an existing web application, I have a bootstrap carousel similar to that on the [Bootstrap homepage](http://getbootstrap.com/javascript/#carousel):
```html
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="..." alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <img src="..." alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    ...
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
```
For some reasons, extensions to this application are supposed to be made with Angular and Angular Bootstrap directives. So I added the "angular.js" and "ui-bootstrap-tpls.js" to the pages' scripts.
But, after doing this, the existing code above is altered at runtime in an unexpected way:
```html
(...Indicators and Wrapper above this line are ok...)
<!-- Controls -->       
<div ng-class="{
    'active': active
  }" class="{
    'active': active
  }" ng-transclude="" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left ng-scope"></span>
    <span class="sr-only ng-scope">Previous</span>
</div>
<div ng-class="{
    'active': active
  }" class="{
    'active': active
  }" ng-transclude="" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right ng-scope"></span>
    <span class="sr-only ng-scope">Next</span>
</div>
```
Also, the browser console shows an runtime error like this:
```
http://xhr.spec.whatwg.org/.
Error: [$compile:ctreq] http://errors.angularjs.org/1.4.7/$compile/ctreq?p0=carousel&p1=slide
    at Error (native)
```
Is this a bug in angular-ui-bootstrap?

Best regards,
  D. Peters

**Comment by icfantv** [comment] 2015-11-20 18:02
Without seeing a minimally working plunker that shows the problem it's nearly impossible to see what you're doing and what you're doing incorrectly.  Also, I'm not seeing any Angular UI Bootstrap directives above.

I should point out that you shouldn't be using Bootstrap's Javascript AND Angular UI Bootstrap.  Pick one or the other.  There were namespace collisions (which is why we introduced the `uib-` prefix for our directives, but I don't recall hearing or seeing any involving the carousel.

**Comment by icfantv** [comment] 2015-11-20 23:08
@DetlefPeters, after discussing with the team we're closing this as not an issue.  In the future, If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).  Thanks.

**Closed by icfantv** 2015-11-20 23:08 UTC
Labels: component: carousel, needs: plunkr

**Comment by DetlefPeters** [comment] 2015-11-23 09:29
Are you serious? Waiting with a reaction until weekend has started here in Europe, and then closing the issue before I can get back into my office on Monday? Not so fast, ladies and gentlemen!

In your first comment, you've seen it clearly: there is no Angular Bootstrap directive in the example, just  plain vanilla Bootstrap HTML. And that is exactly what bothers me - the JS for Angular Bootstrap manipulates existing, vanilla Bootstrap in a way that leads to runtime errors!

Since we have to depend on "npm" or "bower" for our deployment, any of the next two options would IMHO solve the problem:
a) providing "npm install" options for a custom build of Angular Bootstrap where I can leave out the "carousel" directives
b) dropping the "deprecated" code from the Angular Bootstrap JS, at least for the carousel - this deprecated piece of code causes the error mentioned above.

Regards,
  Detlef Peters.

**Comment by RobJacobs** [comment] 2015-11-23 13:20
@DetlefPeters The angular-ui-bootstrap library is meant to replace the TWBS bootstrap.js allowing you to use the javascript powered TWBS components in an angular way rather than rely on jQuery like the TWBS bootstrap.js does.  Why would you want both types of implementations in your project and not use the angular-ui-bootstrap library exclusively the with TWBS css file?

**Comment by DetlefPeters** [comment] 2015-11-23 14:05
@RobJacobs I don't think the TWBS bootstrap.js is the problem. Even when I run my app without it, I get the Angular error, and as far as I can see it, ui-bootstrap.js unnecessarily tries to compile my HTML even when there is no Angular directive at all. 
My conclusion so far is that angular-ui-bootstrap is not compatible with the carousel HTML from TWBS (please see my initial post). Most likely, either the CSS classes ("carousel", "slide") or one of the attributes ("data-slide", "data-ride") cause this strange behavior.

**Comment by RobJacobs** [comment] 2015-11-23 20:15
Carousel has a compliment [slide](https://github.com/angular-ui/bootstrap/blob/master/src/carousel/carousel.js#L216) directive that has been re-named to uib-slide to avoid these types of conflicts.  The TWBS carousel requires javascript, whether it be the bootstrap.js or the angular-ui-bootstrap library.  I was questioning how you intend to use the carousel, with the angular-ui-bootstrap library, or the TWBS bootstrap.js?  If you were to use the angular-ui-bootstrap library and follow the suggested markup from the angular-ui-bootstrap library, I'm confident you would not be having this issue.  Regardless, there's not much we can do to help you without a plunk demonstrating the problem.

**Comment by DetlefPeters** [comment] 2015-11-24 11:42
@RobJacobs I spent some time trying to set up a plunk for this issue. Unfortunately (for me, not for you), I cannot reproduce the error on plunkr, and I need more time to narrow things down in our rather large javascript framework. Until then, this issue may remain closed.

Thanks for helping,
  Detlef

**Comment by Foxandxss** [comment] 2015-11-24 12:01
You're seeing this from the wrong perspective. It is not like we don't want to help you and we want to to hide this issue.

This library is a replacement for `bootstrap.js` so that means that you don't need to use `bootstrap.js` and also change all the markup to use this library instead of `bootstrap.js` (use directives with their attributes, etc etc).

Before our version 0.14.0 we didn't have this directives prefixed, so you could run in problems where having both our library and `bootstrap.js` it would case some overlap.

If you don't load `bootstrap.js` and you modify the markup to use our prefixed directives (`uib-carousel`, `uib-slide`) it won't give you any issue.

We closed this issue because we can't do anything outside the scope of this library. And please don't say that it is **not** unfortunate for us that you cannot reproduce the issue. If there is an issue in our side, we want to fix it.

Again, I believe that this issue is just a misunderstanding from your side in how this library work.

**Comment by DetlefPeters** [comment] 2015-11-24 13:28
Please don't feel offended. From the observation that my code is working again after commenting out Angular Bootstrap UI, I concluded in the first place that there might be a bug in this library. But now I've learned that the combination of your lib and one of our libs is incompatible. It is, in fact, not `bootstrap.js`, but some other lib which I still have to identify.
I'm sorry to say that your idea of replacing the vanilla TWBS code with a `uib-carousel` directive is out-of-scope at the moment, for the carousel is dynamic server-side content, created by scala HTML templates.

**Comment by DetlefPeters** [comment] 2015-11-24 16:03
Ok, I found a solution after all!
I cannot replace the entire existing TWBS carousel, but I can at least replace the two `data-slide` attributes - because these two are unwillingly treated as Angular `slide`directives. So, I eliminated these attributes from the two 'prev/next' controls and wrote some additional JS to handle the click events manually.
Looks like this:
```coffeescript
  $('.left.carousel-control').on('click', (e) ->
    carousel = $(e.currentTarget).data('target')
    $(carousel).carousel('prev')
  )
```
Thanks again for your help. Best regards,
   Detlef
