### ISSUE TITLE
Datepicker should not focus when clicking on close button

### ISSUE THREAD

**Issue by artdias90** [angular-ui/bootstrap#4290] opened 2015-08-27 15:58 UTC
Whenever I select a date, the datepicker is focusing on the input, which causes the datepicker to open again on IE. Any way to tell it to not focus when selecting a date?

**Comment by wesleycho** [comment] 2015-08-28 16:33
Do you know what versions of IE this occurs on?

**Comment by artdias90** [comment] 2015-08-30 06:57
I experienced it in IE 11, 10, 9. I will provide a plunker

**Comment by artdias90** [comment] 2015-09-02 07:19
All versions... you can check at http://angular-ui.github.io/bootstrap/

This is a big issue when using the ng-focus feature. After selecting a date on IE, the cursor focus on the input, causing the datepicker to open again, because IE focus the cursor back to the input. There should be an option to not focus after selecting date.

**Comment by wesleycho** [comment] 2015-09-02 22:18
I am not able to reproduce this on IE11 on Windows 8.1.

**Comment by wesleycho** [comment] 2015-10-31 04:40
I am still not able to reproduce this, and there has not been any response or more information for solving this issue - closing due to lack of actionable information.

**Closed by wesleycho** 2015-10-31 04:40 UTC
Labels: component: datepicker, needs: info, needs: investigation, type: bug
