### ISSUE TITLE
Modal's 'resolve' functionality should determine dependency order automatically (like UI.Router)

### ISSUE THREAD

**Issue by DerekSeverson** [angular-ui/bootstrap#5030] opened 2015-12-07 17:05 UTC
**Brief:**  UI.Bootstrap's $uibModal resolve should work more like UI.Router by being able to determine the order that the resolves need to be executed in, based on the dependencies of each resolve. 

**Plunkr:**  http://plnkr.co/edit/pUgM6m?p=preview

**Details:** 
When using $uibModal's 'resolve' functionality, UI.Bootstrap should determine the order the resolves need to be resolved in based on the dependencies of each resolve.  For example (straight from the plunkr), if resolve 'message' is dependent on the 'user' resolve, the 'user' resolve should be resolved first and once its resolved, only then can 'message' resolve start executing.    
Whether this is a bug or a feature request, this request seems reasonably easy to implement seeing that [UI.Router resolve](https://github.com/angular-ui/ui-router/wiki#resolve) already implements it this way.  [UI Router](https://github.com/angular-ui/ui-router) is open source, so just look at how it does its resolves and do the same.  I am not saying to make UI.Router a dependency of UI.Bootstrap; but rather, to implement the modal's resolves in a similar manner that UI.Router does - in order to 'resolve' dependencies in the correct order.

**Version/Library Details:**
AngularJS: 1.4.*
UI.Router: 0.2.*
UI.Bootstrap: 0.14.*

**NOTE:**
I actually saw that there was an issue already, but was closed due to no response (and there was no plunkr) - [Issue #1959](https://github.com/angular-ui/bootstrap/issues/1959).  So unfortunately, the feature was not implemented.  

Let me know if you have questions, this feature would be much appreciated.

**Comment by wesleycho** [comment] 2015-12-07 17:13
Closing as a duplicate of #3405 :)

**Closed by wesleycho** 2015-12-07 17:13 UTC

**Comment by pkozlowski-opensource** [comment] 2015-12-07 17:18
Is it worth it on this library side? If I understand correctly it is _very_ easy to do it on the user side by just having one function in resolve. 

I'm not convinced that additional complexity, code size and (small) runtime penalty is worth it. -1 from me, but happy to be convinced otherwise if the code turns out small (<10 LOC) and straightforward.

**Comment by wesleycho** [comment] 2015-12-07 17:19
It's definitely not simple - [here](https://github.com/angular-ui/ui-router/blob/master/src/resolve.js) is UI Router's implementation

**Comment by DerekSeverson** [comment] 2015-12-07 17:28
I apologize for the duplicate Issue.  Thank you for the quick response.  I was just about to link the UI Router's implementation of their $resolve service.

Well, I guess I'll just use the $resolve service in UI.Router directly to get around $modal's resolve. If you'd like, I could post my workaround for others who have the same issue.

**Comment by wesleycho** [comment] 2015-12-07 17:36
One thing we could perhaps allow is for users to configure their own resolve handler for the modal.

**Comment by DerekSeverson** [comment] 2015-12-07 18:11
+1  That would solve the concerns of duplication of functionality and complexity of implementation.

**Comment by neerajjain92** [comment] 2017-10-11 09:49
@DerekSeverson  Please post your workaround.
