### ISSUE TITLE
translateY transition not working on modal-sm and modal-lg

### ISSUE THREAD

**Issue by bboyle** [angular-ui/bootstrap#5022] opened 2015-12-07 03:30 UTC
You can view this issue directly on the examples page: https://angular-ui.github.io/bootstrap/#/modal

Clicking 'Open me!': a modal appears with a translateY and opacity transition.

Clicking 'Large modal' or 'Small modal': a modal appears with opacity transition, but the translateY transition does not work (it does work when the modal is closed).

We've only encountered this issue since upgrading (were on a pretty old version previously).

Anyone know a fix?

**Comment by wesleycho** [comment] 2015-12-07 07:40
Closing as duplicate of #4263

**Closed by wesleycho** 2015-12-07 07:40 UTC
