### ISSUE TITLE
[DatePicker] Remove one time binding for customClass in day/month/year templates

### ISSUE THREAD

**Issue by bogdanalexe90** [angular-ui/bootstrap#4227] opened 2015-08-18 17:02 UTC
In commit cbea5f928ef2665d74dde4dc66896321d95d1d58 was introduced a performance refactor by enableing one-time bindings for some expressions.  This broke the functionality of `customClass` as now you can specify a custom class only for the first render. When you modify the current date the class attribute is not updated anymore.

This can be solved by removing one-time binding like in the following example: 
```html
<td ng-repeat="dt in row track by dt.date" class="text-center" role="gridcell" id="{{::dt.uid}}" ng-class="dt.customClass">
```

**Comment by wesleycho** [comment] 2015-08-18 17:45
So in an unscientific test, I ran the tests with the binding as is, and without the one-time binding - the result was a significant hit to performance from 0.271s on the worst test with the binding and 0.405s on the worst test without the one-time binding, for a performance degradation of 67% in that situation.

I am not sure we want to support removing the binding given the drastic performance difference.

**Comment by RobJacobs** [comment] 2015-08-18 20:21
The templates have been wrapped in an ng-if, so each time they become visible, the customClass is re-evaluated and applied.  The only time this issue would come into play is if you are attempting to change the customClass after the week/month/day elements have been rendered.

**Comment by bogdanalexe90** [comment] 2015-08-18 20:31
Yes. But the customClass expression is evaluated on each model change. So it will be nice that the class  attribute to be updated too.

I have the following use case:
I'm trying to implement something like a range picker (2 date pickers tight together) and i want to highlight the selected interval on each start/end date change.

**Comment by wesleycho** [comment] 2015-08-23 13:56
I think this is a reasonable request, but we may need to come up with a mechanism that avoids large $digest cycle issues.

**Comment by ktsashes** [comment] 2015-09-14 23:48
#4189 Is probably the same issue, and a much more common use case (though I have officially hit both the use case described here and the one in the other bug in different areas of my app).

Is there any workaround way to force rerendering after a model change? I'll pour through the code, but I figured someone here might already know.

**Comment by Nekle** [comment] 2015-09-15 09:32
hm, remove it first, make it work, then try to fix $digest cycle issues.

**Comment by wesleycho** [comment] 2015-09-15 13:23
As already stated, the performance degradation is already too large for this to be simply reverted - a 67% regression in performance is too much for the majority of the users.

Any solution must not significantly sacrifice performance.

**Comment by ktsashes** [comment] 2015-09-15 15:33
@wesleycho What task or circumstances causes such a high performance degradation? Is it at all times? Only when the attribute/feature is added to the datepicker? Is it only on model changes? Is it only when the picker is interacted with? Which test is taking that hit? What is that test you are running it on doing? Is it using that feature heavily or in a way that is expected to degrade performance? Was this average performance over multiple runs or a single run instance that say this hit?

Right now, this feature is 100% useless to me. I have been unable to come up with any circumstance that I would use this feature without loading items from the server via a `$resource` or using the dynamic classes with some selection feature. And after looking over the code, the only way it looks like for me to successfully use this feature is to completely destroy and re-add the component every time the user makes a change.

I understand not wanting to impact users with a 67% performance degradation. But right now you've got a broken feature. It does not work as expected (or as documented), and most of the major use cases for it that I can think of are not possible. Saying you can't do it simply because 1 test got 67% slower doesn't seem to me to be a very good reason unless that 67% slower is going to really impact all users.

*You've over optimized at the cost of a feature*. At this point you've got to pull the optimization, document the change, or pull the feature entirely (not that I'm recommending that, that would be an overreaction). Because at the moment no one seems to have a better optimization and it does not work as stated (and as I said earlier, it doesn't work for my cases at all).

**Comment by wesleycho** [comment] 2015-09-15 15:52
Many tests are affected by this in the performance metrics - the degradation is all around to what some might consider unacceptable levels of performance. This is not surprising since ng-class adds about 30 watchers involving direct DOM manipulation. This level of performance change is not acceptable, adding 100+ ms speed degradation will simply not be supported (and this is on an iMac 5K - the difference is far less kind to removal on older machines).

As I said and repeat, any solution must solve this in a performant way - simply removing the one time binding is not an option given that this has a major quantifiable performance impact that is impossible to opt-out of. Simply complaining & ignoring the performance issue is poor engineering, especially in a library that is core to many applications.

**Comment by ktsashes** [comment] 2015-09-15 16:26
I'm not trying to ignore the performance implications. One of the reasons I asked the questions I did was because your early comment only really mentioned a single testing have such a wide performance discrepancy. Which, as I said, would be expected in some cases.

I would say this needs to be added to the documentation then. Because as it stands you already have 2 bugs on the matter, it would seem.

In terms of solutions, I can't see a great way to solve this without the `$digest` impact on at least some level. So long as it remains a function, it would need to be evaluated at each cycle for each visible item in the calendar to check for changes, which is likely on par with the impact of `ngClass` doing the evaluation. If it truly is just `ngClass` is inefficient with number of binds, it should be possible to use a timer or something to do the evaluation outside, watch for changes, and update it that way.

Some alternative solutions that aren't code only changes (i.e. require additional components or different configuration for a strict update)
 * Opt-in bind once/vs watch. Set another attribute that causes it to do the `$digest` with the `ngClass` call
 * Use an object instead of a function, and watch the object for changes. Something like `{ "2012": "my-custom-class", "2014-04-01": "april-fools-class" }` and the user can be responsible for updating that outside, and those are mapped through code. (Looking through the code for this, it looks like it *might* be a fairly big change, though).
 * Triggerable rebinds for the classes through an exposed function or event or something

**Comment by Nekle** [comment] 2015-09-17 02:22
it will be better to give a method to refresh the ui

**Comment by fushnisoft** [comment] 2015-09-30 13:41
On a performance related note, in a particular implementation I have found that changing the `track by` in the day template from `track by dt.date` to `track by $index` has a massive improvement. However, I am not sure if this is connected to other customizations in my particular implementation.

Here is a plunk containing the modified template - http://plnkr.co/edit/R1FmCbLpaBtozIouEaes?p=preview

Note: You also have to remove some of the one-time bindings but if I understand correctly that is ok because the ng-repeat is more efficient now giving a greater overall improvement to performance. @wesleycho I would be interested to see if it changes your perf test results.

**Comment by wesleycho** [comment] 2015-10-15 05:53
@fushnisoft the datepicker needs massive improvements to performance - from my investigations, removing the one time binding is out of the question, period. Any solution to this problem needs to solve the multiple watcher problem in a performant way - the datepicker's performance is unsatisfactory as anyone running the tests on machines of varying ages can see (a two year old Macbook Air of mine screeches to a halt on the datepicker tests as is, and that is with one-time binding).

Closing this issue in favor of #4626

**Closed by wesleycho** 2015-10-15 05:53 UTC
Labels: component: datepicker, type: enhancement
