### ISSUE TITLE
An issue with HTML5 Form validation inside tabs

### ISSUE THREAD

**Issue by huyph** [angular-ui/bootstrap#6048] opened 2016-06-24 02:20 UTC
### Bug description:
Insides a tab, there are invalid input fields. On form submission, the invalid tab is not automatically activated. 

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/yzNHMireMl2I7ULPyBRW?p=preview
Steps to reproduce:
1) Observe that "age" tab is invalid, because there is one empty input field with `required`
2) Stay on "Name" tab, and  then hit "submit form"

The default browser tooltip for `required` error is not showing because "age" tab is not active.

### Version of Angular, UIBS, and Bootstrap
Angular: 1.5.3
UIBS: 1.3.3
Bootstrap: 3.3.6

**Comment by icfantv** [comment] 2016-06-24 04:48
@huyph there is, quite literally, no way for us to know what someone will place inside a tab.  If you want to make a tab active because a form field is invalid, then the onus is on you to make that tab active.  This can be done quite easily via the `active` property on the `tabset` element.

I will say, relying on HTML5 form validation is probably not a good way to go for several reasons:  1) HTML5 form validation support is not universal across all browsers, and 2) angular already provides a validation mechanism for form fields (as well as letting you define your own validators) and it is browser agnostic.

I'm going to close this as not a bug

**Closed by icfantv** 2016-06-24 04:48 UTC
