### ISSUE TITLE
IE11 - on click the datepicker shows duplicated

### ISSUE THREAD

**Issue by Jefiozie** [angular-ui/bootstrap#5946] opened 2016-05-31 15:04 UTC
### Bug description:

When upgrading the bootstrap we found a issue with the datepicker. 
On click it shows duplicated in IE 11 and in Edge.

**Screenshot when pressing a random date:**

![ie11-bug](https://cloud.githubusercontent.com/assets/17835373/15679216/55133822-2751-11e6-9b8f-a9ac9b8687ef.png)

**Red circles the value i have selected and the duplicated calendar:**

![ie11-bug-selectedinred](https://cloud.githubusercontent.com/assets/17835373/15679215/55131054-2751-11e6-895e-f31bb3481794.png)

### Link to minimally-working plunker that reproduces the issue:
[Link to demo ui-bootstrap](https://angular-ui.github.io/bootstrap/)

### Version of Angular, UIBS, and Bootstrap

Bootstrap: latest
IE : 11.0.9600 
IE Updateversion: 11.0.31
Edge: 25 
Edgehtml: 13.10586

**Comment by icfantv** [comment] 2016-05-31 15:05
I asked @Jefiozie to enter this.  @RobJacobs do you have time to look at this?  I think you have access to IE11.  Thanks.

**Comment by RobJacobs** [comment] 2016-05-31 15:15
Duplicate of #5446

**Comment by icfantv** [comment] 2016-05-31 15:21
@RobJacobs Ah, ok.  thanks.

**Closed by icfantv** 2016-05-31 15:21 UTC
Labels: browser: IE11, component: datepicker, needs: investigation

**Comment by Jefiozie** [comment] 2016-05-31 18:27
This comment [#5446](https://github.com/angular-ui/bootstrap/issues/5446#issuecomment-207170066) helped me for now.
