### ISSUE TITLE
Open modal is shifting body content to the right

### ISSUE THREAD

**Issue by alexndlm** [angular-ui/bootstrap#3714] opened 2015-05-26 10:15 UTC
When the page has a vertical scroll and opens a modal window, the vertical scroll on the page hiding. Because of this, the content moves to the right. In the Bootstrap this problem is solved by adding right padding to the body when scroll hiding.

http://plnkr.co/edit/ynWJUbnryVkSHdEjFRMw?p=preview

**Comment by rvanbaalen** [comment] 2015-05-27 12:53
Not sure if this is something UI Bootstrap should do since it's part of the styling.
You can however easily implement this behaviour in CSS by styling the `body.modal-open` selector

**Comment by alexndlm** [comment] 2015-05-27 12:58
More info for Bootstrap https://github.com/twbs/bootstrap/issues/9855

**Comment by rvanbaalen** [comment] 2015-05-27 13:01
This is my first thought as well:

https://github.com/twbs/bootstrap/issues/9855#issuecomment-22911988

**Comment by rvanbaalen** [comment] 2015-05-27 13:04
Referencing this here, could be a solid fix:

https://github.com/twbs/bootstrap/commit/0907244256d923807c3a4e55f4ea606b9558d0ca

**Comment by kunal999** [comment] 2015-07-14 19:23
+1

**Comment by munkeyxis** [comment] 2015-09-16 13:49
Adding my +1 to this as well. Would really like to see this fixed.

**Comment by icfantv** [comment] 2015-09-16 15:26
Please do not just "+1" issues.  If you would like to show your support for a fix, PRs are welcome.  Simply adding the text "+1" adds no inherent value and clutters up the thread.  Thanks.

**Comment by wesleycho** [comment] 2015-12-01 18:16
Closing as a duplicate of #2631

**Closed by wesleycho** 2015-12-01 18:16 UTC
Labels: component: modal, needs: investigation, type: enhancement
