### ISSUE TITLE
[performance] Dropdown - remove from DOM

### ISSUE THREAD

**Issue by piernik** [angular-ui/bootstrap#3709] opened 2015-05-25 18:21 UTC
I see that all dropdown divs are always in DOM - they are only `display:none`
Why not remove them from DOM when they are hidden?
It could be good performance boost.

**Comment by rvanbaalen** [comment] 2015-05-25 18:41
Can you provide some details/examples that confirm your assumptions?

**Comment by piernik** [comment] 2015-05-26 06:08
It's exmaple from official site: http://plnkr.co/edit/?p=preview
dropdown menu is always in DOM - even when it's not visible.
With static menu it's not a problem but somtime that menu is created via ng-repeat with bindings, so removing dropdown after hiding could be usefull.

**Comment by rvanbaalen** [comment] 2015-05-27 12:39
I meant perhaps you can demonstrate in a jsperf.com snippet that your suggestion is actually a significant performance boost.

**Comment by RobJacobs** [comment] 2015-05-27 13:07
The dropdown directive has no associated template, it simply handles positioning and toggling the css display value. A transclude template with ng-if bound to the isOpen property could work.

**Comment by wesleycho** [comment] 2015-07-31 07:03
This has a performance tradeoff of increasing the overhead at runtime on show/hide for reducing the number of watchers in the dropdown template.

The question then is, which approach is preferred? After thinking about it, an ng-if would probably be preferred most of the time, but might require a breaking change. Maybe creating another directive set specifically for using ng-if is preferred for support of the option?

**Comment by piernik** [comment] 2015-08-19 10:43
Any news on this one?

**Comment by icfantv** [comment] 2015-08-19 13:36
@piernik, you were asked for some performance data to back up your claims.  Do you have these results available?  Can you link them here?

This is not a bug yet and thus is fairly low on the priority list.

**Comment by piernik** [comment] 2015-08-19 18:07
If something is in DOM and has watchers then it is 100% slower than if something is not in DOM and does not have watchers.
Why You need tests for?

**Comment by icfantv** [comment] 2015-08-19 19:19
@piernik except that you will still have a watcher on the `ng-if` and you can perform one-time bindings on the nested items (`ng-repeat` or otherwise) so that they don't have watchers if they don't need them.

You are asking for a low priority feature without a strong justification.  If you can provide some performance metrics that can show this provides a major boost we would be happy to consider it.  Alternatively, as this is an OSS project, feel free to open a PR with this feature implemented.

Otherwise, ignoring a request for more information, and then following up with a request for more information is not very helpful or productive.

**Comment by piernik** [comment] 2015-08-21 05:51
Ok my quick test.

This code
```
<!-- Single button -->
<div class="btn-group" dropdown is-open="status.isopen">
    <button id="single-button" type="button" class="btn btn-primary" dropdown-toggle ng-disabled="disabled">
        Button dropdown <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu" aria-labelledby="single-button">
        <li role="menuitem"><a href="#">Action</a></li>
        <li role="menuitem"><a href="#">Another action</a></li>
        <li role="menuitem"><a href="#">Something else here</a></li>
        <li class="divider"></li>
        <li role="menuitem"><a href="#">Separated link</a></li>
    </ul>
</div>
```
generates 4 extra watchers (options are static)

This one - 4 dyniamic options generates 9 extra watchers
```
<!-- Single button -->
<div class="btn-group" dropdown is-open="status.isopen">
    <button id="single-button" type="button" class="btn btn-primary" dropdown-toggle ng-disabled="disabled">
        Button dropdown <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu" aria-labelledby="single-button">
        <li ng-repeat="item in vm.opcje" role="menuitem"><a href="#">{{item}}</a></li>
    </ul>
</div>
```

And here You have only 4 options - simple bindings - not like `<li ng-repeat="item in vm.opcje" role="menuitem"><a ui-sref="app.page({id:item.id})">{{item.name}} <i class="fa" ng-class="{{item.icon}}"</a></li>` where You have two extra watchers on one item.
Sometimes You have 5-20 options? And even 10 dropdowns on webpage. And never those 10 dropdowns are opened in the same time!
If doprdown list would be designed with `ng-if`  - striped from DOM if not opened all theese watchers would be absent.
It is big performance boost.

**Comment by icfantv** [comment] 2015-08-21 16:27
Any reason you didn't use one-time bindings as previously suggested?  I'm not trying to pick a fight here or say this won't ever get addressed.  I'm trying to get you to think about the issue and the solution you propose.

**Comment by piernik** [comment] 2015-08-23 18:40
Because my options can change.

**Comment by wesleycho** [comment] 2015-09-09 07:58
This is a valid concern - there is no need for a reproduction here. I think I agree with @piernik, and that the tradeoff is worthwhile enough to use ng-if instead. The only potential tricky part would be to implement this behavior for the `append-to-body` option.

**Comment by mikesir87** [comment] 2015-11-17 15:49
I too would be interested in this capability.  We have many (up to a hundred) rows that each have a dropdown in which the menu's items change depending on the current state of the item in the row (think Approve/Reject, etc.).

I'd be happy to spend some time making up a PR, if given some direction on where to go.  Any thoughts?

**Comment by RobJacobs** [comment] 2015-11-17 18:50
The dropdown has an is-open attribute that can be leveraged by ng-if on the dropdown menu element, example [plunk](http://plnkr.co/edit/3REZ4HWaBu3ACtIl6yE5?p=preview)  Handling this within the directive would require quite a bit of work as the dropdown menu is not part of the directive template.

**Comment by piernik** [comment] 2016-01-22 13:05
I found another good reason for removing dropdown from DOM - can use ngAnimate :)

**Comment by wesleycho** [comment] 2016-04-06 21:15
I took a look at implementing this - @RobJacobs is correct, this would take quite a lot of work. Given how easy it is to do on the user's side, I'm not sure how good it would be for this to be handled by this library.

Closing this as something that doesn't make sense given that the dropdown does not have a template, and thus would be a breaking modification.

**Closed by wesleycho** 2016-04-06 21:15 UTC
Labels: component: dropdown, type: performance
