### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by latch** [angular-ui/bootstrap#3732] opened 2015-05-29 06:30 UTC
If datepicker field set emty (for exemple, click "Clear" button in datepicker widget) in console write error: "Datepicker directive: "ng-model" value must be a Date object, a number of milliseconds since 01.01.1970 or a string representing an RFC2822 or ISO 8601 date." and  form (with datepicker)  be is not valid ($scope.form.$valid is false). I think, that empty (null) value for date field is not error! It's wrong.

**Comment by rvanbaalen** [comment] 2015-05-30 22:01
Sorry, your reported issue is very hard to understand if you don't use some interpunction here and there.

What is exactly your problem? And can you please reproduce this in a plunkr? Without a plunkr, we won't start investigating the issue.

**Comment by latch** [comment] 2015-06-01 05:34
I'm sorry for the bad explanation. Again briefly.

First I open my form with the datepicker. The Datepicker is empty, all ok. Then I choose some date, all is well. Then I decide to leave this field blank, press 'Clear' button... and that's a problem. In the console I see the error "Datepicker directive: "ng-model" value must be a Date object, a number of milliseconds since 01.01.1970 or a string representing an RFC2822 or ISO 8601 date." and my form with the date becomes invalid. It turns out that an empty value for a date field, this is a mistake. I think this is not right.

Plunker:
http://plnkr.co/edit/4SPYlJmb0LoNLoCMTCb8?p=preview

**Comment by rvanbaalen** [comment] 2015-06-01 05:36
Now I get it! Thanks for the explanation.

This issue is a duplicate of #3701

**Closed by rvanbaalen** 2015-06-01 05:36 UTC
Labels: component: datepicker, needs: plunkr
