### ISSUE TITLE
Cannot focus on input element of modal form after using uib-dropdown

### ISSUE THREAD

**Issue by ndrsv** [angular-ui/bootstrap#6364] opened 2016-12-13 10:50 UTC
### Bug description:

In brief, triggering a modal form after using a uib-dropdown on the page makes it impossible to focus on the form input.

Try the following in the provided plunker:

1. Click button (A) to activate modal form.  
2. Click on the input & it focuses

3. Click the uib-dropdown button 'Select' (no need to select menu button (B))
4. Click button (A) again. It is not possible to focus on the input 

### Link to minimally-working plunker that reproduces the issue:

https://plnkr.co/edit/Aa8zqYgrqd5o0a1yy4EU?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.8

UIBS: 2.3.1

Bootstrap: 3.3.7

### Other comments

It used to work in UIBS 2.2.0.

**Comment by brik** [comment] 2016-12-13 13:56
Also experiencing the same problem in UIBS 2.3.1, works in 2.2.0.

**Comment by jacobharasimo** [comment] 2016-12-13 14:29
same exerience. v2.3.0 works and 2.3.1 breaks.

assume this is related https://github.com/angular-ui/bootstrap/pull/6295 by @ajpz https://github.com/angular-ui/bootstrap/commit/8a4f625

**Comment by nimamarashi** [comment] 2016-12-13 20:49
Same here. After opening the uib-dropdown, inputs lose their focus on mouseup. Input does not to be necessarily on a modal. Any input on same page or even after routing to another page does not accept focus after opening the uib-dropdown. 
Angular: 1.5.9
angular-bootstrap: 2.3.1

**Comment by 580** [comment] 2016-12-14 08:22
Same problem. Also happens on Getting Started Page: 
https://angular-ui.github.io/bootstrap/#/dropdown

Drop down element always get focused.

**Comment by jacobharasimo** [comment] 2016-12-14 13:31
Bug for me happened even when focus on a input inside modal so I think you
issue is separate

**Comment by adybionka** [comment] 2016-12-14 14:17
It is the same reason: `focusToggleElement`.  Just `focusToggleElement` is invoked in some circumstances  but should't. I didn't analyze dropdown menu code deeply, but I found case when `focusToggleElement` is not invoked when as element with  uib-dropdown-menu you use `<a>` tag without `href `attribute (what of course is invalid html). To test it  replace this piece of code: 

      <button type="button" class="btn btn-primary dropdown-toggle" uib-dropdown-toggle>
        <span translate>Select</span>
        <span class="caret"></span>
      </button>

by this

      <a class="btn btn-primary dropdown-toggle" uib-dropdown-toggle>
        <span translate>Select</span>
        <span class="caret"></span>
      </a>

here https://plnkr.co/edit/Aa8zqYgrqd5o0a1yy4EU?p=preview

Of course this is only workaround and bug should be fixed by authors of ui-bootstrap.

**Comment by StefanAndjelic** [comment] 2016-12-14 14:21
@adybionka spot on! Looks like the culprit is in [dropdown.js](https://github.com/angular-ui/bootstrap/blob/master/src/dropdown/dropdown.js#L108) on line 108. The closeDropdown is being invoked on document.click so it focuses the toggleElement (if focusable) every time someone clicks.

**Comment by alejandroiglesias** [comment] 2016-12-14 14:24
I confirm this issue happening on `2.3.1` and not on `2.3.0`. Also as @adybionka mentioned, removing the `href` attribute from the `a` tags stops the issue from happening on `2.3.1`.

**Comment by StefanAndjelic** [comment] 2016-12-14 14:26
Removing the `href` tag only works because then the element cannot be focused. The issue still persists with buttons.

**Comment by romanzoller** [comment] 2016-12-14 15:07
This seems to be a duplicate of #6357

**Comment by adybionka** [comment] 2016-12-14 15:26
Another workaround of this problem is just not use `uib-dropdown-toggle` to open dropdown menu. `focusToggleElement` method is only invoked when is a element with `uib-dropdown-toggle` directive, which is optional. Instead of this, to open dropdown menu just use `is-open` attribute:

        <div uib-dropdown is-open="isOpenedDropdownMenu">
            <button ng-click="toggleDropdown($event)">Open dropdown</button>
                
            <ul uib-dropdown-menu>
                <li>...</li>
            </ul>
        </div>

And in controller:

       $scope.toggleDropdown = function($event) {
            $event.preventDefault();
            $event.stopPropagation();
            $scope.isOpenedDropdownMenu = !$scope.isOpenedDropdownMenu;
        };

**Comment by adgoncal** [comment] 2016-12-14 20:48
It looks like the root of the problem was identified by @vukers:
 https://github.com/angular-ui/bootstrap/commit/c824731ae8fed3d56bedaaf88fc8e86a4224e96d#commitcomment-20174042

**Comment by vukers** [comment] 2016-12-14 20:58
@mattlewis92 has a pull request with the fix: #6363

**Comment by GAndriyS** [comment] 2016-12-16 08:54
seems like #6321 related too (text input focus bug)

**Comment by codymullins** [comment] 2016-12-20 14:26
Yeah, we are experiencing the same issue. We were developing on 2.3.0 and our deployment today went out with 2.3.1 causing widespread breakages for our drop downs.

**Comment by dougludlow** [comment] 2016-12-20 23:16
e07f9fd appeared to resolve the issue for me.

Looking through the list of issues, these all seem like duplicates:
#6321
#6357
#6372

**Comment by sashberd** [comment] 2016-12-22 07:50
Same issue with 2.3.1 and angular 1.5.9. Reversing to 2.3.0 solve issue. Waiting for fix

**Closed** 2016-12-27 09:51 UTC

**Comment by mold** [comment] 2017-01-11 16:19
I still have to click input fields twice in order to get the focus to move there, once to close the dropdown and again to shift focus (regardless of whether the input is in a modal or not).

(Angular 1.5.9, UIBS 2.4.0)

**Comment by andriy-ml** [comment] 2017-01-11 19:46
The same behavior as @mold described for Angular 1.5.7 and UIBS 2.3.0

This piece of code always grabs focus for dropdown when toggle happens.
`scope.focusToggleElement = function() {
    if (self.toggleElement) {
      self.toggleElement[0].focus();
    }
  `};`

**Comment by mcm-ham** [comment] 2017-01-17 06:53
I experiencing the problem reported by @mold as well. Created bug #6410 to track this.

**Comment by axtscz** [comment] 2017-01-18 03:07
Also experiencing this bug. Going back to 2.3.0 did not seem to help
