### ISSUE TITLE
Datepicker popup not rendering date on ng-model-options={ updateOn : 'blur' }

### ISSUE THREAD

**Issue by marsc** [angular-ui/bootstrap#5311] opened 2016-01-20 07:11 UTC
Hey,

if you have a datepicker popup on an input with ng-model-options={ updateOn : 'blur' } it is possible to enter a date manually but selecting it via datepicker doesn't work. The selected date isn't applied and the datepicker popup stays open. But this option should only affect the input itself and not the datepicker popup.

See this plunkr: http://plnkr.co/edit/Rgr9AZNW0bC01wDdww8R?p=preview

**Comment by wesleycho** [comment] 2016-01-20 08:25
Closing as duplicate of #4837

**Closed by wesleycho** 2016-01-20 08:25 UTC
