### ISSUE TITLE
New Datepicker throwing dateparser error (Cannot read property in ui-bootstrap-tpls)

### ISSUE THREAD

**Issue by stephengardner** [angular-ui/bootstrap#5228] opened 2016-01-13 09:33 UTC
I upgraded to latest version and am receiving this console error when instantiating the datepicker:
```javascript
TypeError: Cannot read property 'join' of undefined
    at init (ui-bootstrap-tpls.js:832)
    at new <anonymous> (ui-bootstrap-tpls.js:849)
    at invoke (angular.js:4185)
    at Object.instantiate (angular.js:4193)
    at Object.<anonymous> (angular.js:4054)
    at Object.invoke (angular.js:4185)
    at Object.enforcedReturnValue [as $get] (angular.js:4038)
    at Object.invoke (angular.js:4185)
    at angular.js:4003
    at getService (angular.js:4144)
```

That line is specifically here: 
```javascript
      {
        key: 'GGGG',
        regex: $locale.DATETIME_FORMATS.ERANAMES.join('|').replace(/\s/g, '\\s')
      },
```

my bower.json:
```javascript
{
  "name": "test",
  "version": "0.0.0",
  "dependencies": {
    "angular": ">=1.4.*",
    "json3": "~3.3.1",
    "es5-shim": "~3.0.1",
    "jquery": "~1.11.0",
    "bootstrap-sass-official": "~3.1.1",
    "bootstrap": "~3.1.1",
    "angular-resource": ">=1.2.*",
    "angular-cookies": ">=1.2.*",
    "angular-sanitize": ">=1.2.*",
    "angular-bootstrap": "~1.0.3",
    "font-awesome": "~4.3.0",
    "lodash": "~2.4.1",
    "angular-socket-io": "~0.6.0",
    "angular-ui-router": "~0.2.10",
    "angular-modal-service": "~0.6.0",
    "fastclick": "~1.0.6",
    "angular-input-masks-usa": "~1.3.2",
    "angular-lazytube": "~0.2.0",
    "angularjs-dropdown-multiselect": "~1.5.2",
    "angular-utils-pagination": "~0.6.0",
    "angular-google-maps": "~2.0.17",
    "geocomplete": "~1.6.5",
    "angular-touch": "~1.3.15",
    "ngInfiniteScroll": "1.0.0",
    "angular-animate": "~1.3.15",
    "angular-moment": "~0.10.1",
    "ng-lodash": "~0.2.3",
    "ngSmoothScroll": "~1.7.1",
    "ngDialog": "~0.4.0",
    "angular-bootstrap-checkbox": "~0.3.1"
  },
  "devDependencies": {
    "angular-mocks": ">=1.2.*",
    "angular-scenario": ">=1.2.*"
  },
  "resolutions": {
    "angular": "~1.3.x"
  }
}
```

**Comment by wesleycho** [comment] 2016-01-13 14:02
Can you give a stripped down reproduction in [Plunker](http://plnkr.co/edit/Fgava5VLkUHIp15uY01n?p=preview)?

**Comment by wesleycho** [comment] 2016-01-13 14:04
One thing I see that is problematic in your bower.json - you should not have a resolution of `"angular": "~1.3.x". UI Bootstrap 1.0.3 only supports 1.4 and higher (ideally you should be on 1.4.5 or higher, preferably 1.4.8).

**Comment by wesleycho** [comment] 2016-01-13 14:07
Did some searching here - the only way this can happen is if your angular version is on 1.2 or below, as seen [here](https://github.com/angular/angular.js/blob/g3_v1_2/src/ngLocale/angular-locale_en-us.js). [1.3](https://github.com/angular/angular.js/blob/g3_v1_3/src/ngLocale/angular-locale_en-us.js) is where ERANAMES are introduced, which points the problem as your version of angular.

Closing as a usage issue.

**Closed by wesleycho** 2016-01-13 14:07 UTC

**Comment by xuhong** [comment] 2016-02-29 08:50
I got the same error today and finally found the reason is that `angular-i18n` hasn't been updated to the same version.

**Comment by terencemutizwa** [comment] 2016-02-29 12:44
yeah im getting this same error on 1.4.9, im guessing @xuhong  is right

**Comment by Sanmoo** [comment] 2016-03-12 14:24
I had the same issue here and updating angular-i18n to 1.4.8 has solved it.

**Comment by eduardolagares** [comment] 2016-04-21 21:21
Im getting this same error on angular 1.5.5, angular-18n 1.5.5 and angular-bootstrap 1.3.2.

**Comment by Neustren** [comment] 2016-07-28 01:40
In my case, i was using angular-locale en-us, same name module , I uninstalled it and downloaded the angular-i18n and everything worked

**Comment by VuHoi** [comment] 2018-10-11 08:35
The same error  when I use angular 1.7.5 and UI-Bootstrap 3.0.5.
