### ISSUE TITLE
Datepicker popup's initial format is broken in angular 1.3.X

### ISSUE THREAD

**Issue by rustygreen** [angular-ui/bootstrap#3025] opened 2014-11-26 20:07 UTC
The datepicker popup's initial display value does not use the passed in format. After you select a value for the first time, it will display it property (using the passed in format).

Here is the angular-ui websites "datepicker" Plunkr with only the version of angular changed to 1.3. All 1.2 versions work great, it's only when using Angular 1.3:
[Plunkr](http://plnkr.co/edit/j0uVkyCTYDFQnNqEHtiJ?p=preview)

**Comment by uberspeck** [comment] 2015-01-08 16:51
+1

**Comment by antoinepairet** [comment] 2015-01-08 19:07
Closing as it is a duplicate of #2659 
We will deal with it ASAP

**Closed by antoinepairet** 2015-01-08 19:07 UTC

**Comment by luongvanphuc** [comment] 2015-12-15 11:39
Hi, it seems that the issue is back again in angular 1.5.0 (beta):
http://plnkr.co/edit/cg1Uj5kF8fNAaNuTvxVY?p=preview

**Comment by icfantv** [comment] 2015-12-15 17:52
@luongvanphuc, would you mind please filing a new issue and referencing this one rather than piggy-backing?  It helps us track it better.  Thanks.

**Comment by luongvanphuc** [comment] 2015-12-16 01:46
@icfantv, sorry for that :-)
