### ISSUE TITLE
datepicker-popup: Cannot change minDate option on the fly

### ISSUE THREAD

**Issue by mike-bresnahan** [angular-ui/bootstrap#3188] opened 2015-01-14 17:35 UTC
I have 2 datepicker-popup's that define a date range. There is a constraint that the second date must be greater than or equal to the first date. When the user changes the first one, I would like to set the minDate option of the second one. I have attempted to do this like this:

	$scope.endDateOptions = {
		minDate: 'BeginDate'
	};

However, the expression 'BeginDate" does not resolve to anything because the context of the $watch in DatepickerController is an isolated scope. Here is the relevant source code from ui-bootstrap.tpls.js:

	// Watchable date attributes
	angular.forEach(['minDate', 'maxDate'], function( key ) {
	    if ( $attrs[key] ) {
		$scope.$parent.$watch($parse($attrs[key]), function(value) {
		    self[key] = value ? new Date(value) : null;
		    self.refreshView();
		});
	    } else {
		self[key] = datepickerConfig[key] ? new Date(datepickerConfig[key]) : null;
	    }
	});

I don't understand what the above $watch is supposed to accomplish. In what use case would I want to watch for a change in the isolated scope of datepicker-popup? Shouldn't the $watch context be the parent of the datepicker-popup so that it can see changes in 'BeginDate'?

**Comment by antoinepairet** [comment] 2015-01-15 22:22
@mike-bresnahan  It actually is on the parent scope: `$scope.$parent.$watch(...`
Without a clear reproduction scenario, we will not be able to help you. Please provide a plunkr.

In your example, you assign `minDate` to a string: `minDate: 'BeginDate'`. `minDate` should be a variable, not an expression to be evaluated against a scope.

Based on my understanding of your usecase, I think the solution would be set up a watch in your controller code, look for change to `beginDate` and update `endDateOptions.minDate` accordingly.

Closing for now as I do not see any issue with ui-boostrap code.

rgds

**Comment by mike-bresnahan** [comment] 2015-01-15 22:46
I'll find some time to create a small test case.

$scope.$parent is still an isolated scope within the directive. Changing the code to $scope.$parent.$parent.$parent allows it to work as expected, however it feels fragile to depend on the scope tree structure. I'm thinking there is a better solution. Allowing minDate to set via a directive as it is for datepicker sounds like a good possibility.

Correct me if I am wrong, but the value of endDateOptions.minDate is passed to $parse() therefore it needs to be an angular expression. If I set endDateOptions.minDate to an variable containing an number or an number literal and then change it, it will not trigger the $watch. (Note also that setting endDateOptions.minDate to a Date object unexpectedly results in an exception.)

**Comment by mike-bresnahan** [comment] 2015-01-15 23:54
Here is a complete example.


```
<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en" ng-app="myApp" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en" ng-app="myApp" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en" ng-app="myApp" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en" ng-app="myApp" class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>My AngularJS App</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link type="text/css" rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />
  <script src="bower_components/angular/angular.js"></script>
  <script src="bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>
  <script src="app.js"></script>
</head>
  <body>
    <div ng-controller="MyController">
      <input type="text" datepicker-popup="MM-dd-yyyy" is-open="beginDatePickerOpen" ng-model="beginDate"/>
      <button type="button" ng-click="openBeginDatePicker($event)" ><i class="glyphicon glyphicon-calendar"></i></button>
      <input type="text" datepicker-popup="MM-dd-yyyy" is-open="endDatePickerOpen" datepicker-options="endDatePickerOptions" ng-model="endDate"/>
      <button type="button" ng-click="openEndDatePicker($event)" ><i class="glyphicon glyphicon-calendar"></i></button>
    </div>
</body>
</html>
```
```javascript
angular.module('myApp', ['ui.bootstrap']).controller('MyController', function($scope) {
    'use strict';
    $scope.beginDate = new Date();
    $scope.beginDatePickerOpen = false;
    $scope.endDate = new Date();
    $scope.endDatePickerOpen = false;
    
    $scope.openBeginDatePicker = function ($event) {
	$event.preventDefault();
	$event.stopPropagation();
	$scope.beginDatePickerOpen = !$scope.beginDatePickerOpen;
    };
    
    $scope.openEndDatePicker = function ($event) {
	$event.preventDefault();
	$event.stopPropagation();
	$scope.endDatePickerOpen = !$scope.endDatePickerOpen;
    };
    
    $scope.endDatePickerOptions = {
	// This results in an exception
	// minDate: $scope.beginDate

	// This correctly sets minDate initially, but there is no way to change it afterwards.
	// minDate: $scope.beginDate.getTime()

	// This has no effect. It is evaluated as an angular expression in the isolated scope of DatepickerController.
	minDate: 'beginDate'
    };
});    

```

**Comment by antoinepairet** [comment] 2015-01-16 07:04
@mike-bresnahan Here is a working plunkr: http://plnkr.co/edit/Ssa7ofSoCiolMqUnVWlq?p=preview

The `min-date` attribute is working as expected, as explained in my first post. However, there is probably a bug with datepickerOptions and its parsing. I will have a look a it later.

```` html
    <div ng-controller="MyController">
      <input type="text" datepicker-popup="MM-dd-yyyy" is-open="beginDatePickerOpen" ng-model="beginDate"/>
      <button type="button" ng-click="openBeginDatePicker($event)" ><i class="glyphicon glyphicon-calendar"></i></button>
      <input type="text" min-date="beginDate" datepicker-popup="MM-dd-yyyy" is-open="endDatePickerOpen" ng-model="endDate"/>
      <button type="button" ng-click="openEndDatePicker($event)" ><i class="glyphicon glyphicon-calendar"></i></button>
    </div>
````

![screen shot 2015-01-16 at 07 37 48](https://cloud.githubusercontent.com/assets/5238592/5772416/adfc3180-9d52-11e4-8e73-effcd3b0d176.png)

**Comment by mike-bresnahan** [comment] 2015-01-16 16:10
Ah ha! So you can use the minDate attribute/directive on the datepicker-popup element. That's not obvious from reading the documentation. Regardless, I probably should have tried it. I had tunnel vision. Thanks!

**Comment by jrsadik7** [comment] 2015-03-04 19:00
hi all......
currently i am using one datepicker from plunker, actually datetimepicker is nice but the problem is i cant able to set the minDate and maxDate
here is the plunker http://plnkr.co/edit/DKQRvz2WJ7Awl6pLEURV?p=preview

**Comment by jrsadik7** [comment] 2015-03-04 19:02
i am not able to give minDate and maxDate please help me 
here is my plunker

http://plnkr.co/edit/DKQRvz2WJ7Awl6pLEURV?p=preview

**Comment by wesleycho** [comment] 2015-03-17 04:28
@antoinepairet any update on this?

**Comment by ashanvabs** [comment] 2015-05-14 04:49
+1

**Comment by wesleycho** [comment] 2015-11-07 15:30
Closing, as this looks like it was a usage issue.

The docs will be updated before the 1.0 release with more thorough usage examples for each option.

**Closed by wesleycho** 2015-11-07 15:30 UTC
Labels: component: datepicker, needs: investigation, type: bug

**Comment by ricksmt** [comment] 2016-03-08 16:47
The documentation still doesn't cover this use case.

**Comment by SudarshanSMD** [comment] 2016-05-31 08:29
For anyone wondering how this could work with new version of angular-ui bootstrap. We have to just pass the model of first datepicker to datepicker that should depend on the first datepicker.

eg:
```
<input type="text" uib-datepicker-popup ng-model="startDate" is-open="startDate.opened" />

<input type="text" uib-datepicker-popup ng-model="endDate" is-open="endDate.opened"                                          datepicker-options="{minDate: startDate}"/>

```
