### ISSUE TITLE
uib-alert not animated for first item

### ISSUE THREAD

**Issue by Lorthirk** [angular-ui/bootstrap#5924] opened 2016-05-24 16:36 UTC
Hello. When using uib-alert directive with ng-repeat, it seems that the first item put in the alerts array is not animated when it's added to the collection if the collection itself is empty. You can verify this behavior in [this plunkr](http://plnkr.co/edit/iGA8hGhD5jHv1BzV9lJ4?p=preview), which is a fork of the docs' demo, where I just use an empty array instead of a prepopulated one. 

AngularJS 1.5.5, angular-ui-bootstrap 1.3.3, Bootstrap 3.3.6

**Comment by icfantv** [comment] 2016-05-24 18:20
I don't know that this is a bug in our library.  The alert code is VERY simple.  If you would like us to look into this, we are going to need you to prove this is our code and not angular.  My initial thought is this has something to do with ngAnimate and the item being added to the DOM.

**Comment by Lorthirk** [comment] 2016-05-24 18:52
Ok. Could you give me some inputs on how to test it properly? Perhaps I could just update the plunkr with divs instead of uib-alerts?

**Comment by ipengyo** [comment] 2016-06-05 15:18
I also have the same problem

At that time the first alert did not add the class state of angular-animated

**Comment by wesleycho** [comment] 2016-06-13 21:02
I did an investigation, and it appears that the problem is using ng-repeat on an element with a template. See [here](http://plnkr.co/edit/FJyCvmTv3TQO7DaMDS87?p=preview) for working version based on current `master`.

There is a chance that the refactor we did assists in addressing this issue. Closing this as fixed/not a bug

**Closed by wesleycho** 2016-06-13 21:02 UTC
Labels: component: alert, type: ngAnimate
