### ISSUE TITLE
Tooltip/popover as menu (different opening and closing events)

### ISSUE THREAD

**Issue by davidpelayo** [angular-ui/bootstrap#2863] opened 2014-10-21 08:41 UTC
From what I need, I've realised we can refactor a bit the code to support the popover concept be used like a menu component.

In my case, I need a scenario where given a certain div, by declaring it as popover, it would be nice to set an option to make the popover behaves like a menu component. Meaning it needs to be opened with different events simultaneously (like mouseenter as well as click/focus), while closing should be defined when clicking or, complementary, when mouseleaving the div area or the menu (children div) area.

Do you think it would be possible to manage to have anything similar to this? Thanks.

**Comment by icfantv** [comment] 2015-08-06 15:35
Closing as duplicate of #590.

**Closed by icfantv** 2015-08-06 15:35 UTC
Labels: component: popover, component: tooltip, type: enhancement
