### ISSUE TITLE
Cannot read property 'noTransition' of undefined after upgrade to 0.13.0

### ISSUE THREAD

**Issue by balaramm** [angular-ui/bootstrap#3803] opened 2015-06-11 15:45 UTC
Cannot read property 'noTransition' of undefined after upgrade to 0.13.0
function config($compileProvider) {
              /*
              When it is true then it run correctly.
              When it is false then error 
              TypeError: Cannot read property 'noTransition' of undefined
              */
                $compileProvider.debugInfoEnabled(false); 

            }

Please visit: 
http://plnkr.co/edit/xXSeaKXCxZvTl1bA6u2D?p=preview
Please correct this issue.

**Comment by wesleycho** [comment] 2015-06-11 17:14
Closing as a duplicate of #3794.

**Closed by wesleycho** 2015-06-11 17:14 UTC
