### ISSUE TITLE
Date picoler US format issue

### ISSUE THREAD

**Issue by natcohen** [angular-ui/bootstrap#3140] opened 2014-12-25 04:49 UTC
Hello,

There is an unresolved issue (like many others) and I'm trying to find a solution...

Can anyone tell me how I can help to resolve it? https://github.com/angular-ui/bootstrap/issues/2369

Thanks

**Comment by RobJacobs** [comment] 2015-01-07 20:06
@natcohen This seems to be a duplicate of #2369 , closing for now.

**Closed by RobJacobs** 2015-01-07 20:06 UTC
