### ISSUE TITLE
Tooltip position doesn't work correctly near page edges

### ISSUE THREAD

**Issue by guspersson** [angular-ui/bootstrap#3286] opened 2015-02-11 09:30 UTC
The tooltips doesn't get positioned correctly when attached to elements near the page edges.
I've created a plunker to illustrate the problem:
http://plnkr.co/edit/tEvNeom8EICLH2yONjUl?p=preview

The same example without AngularJS, using just Bootstrap and jQuery. The tooltips are positioned correctly:
http://plnkr.co/edit/R3Aupt4ZMQz0i4SwuGax?p=preview

AngularJS: 1.2.27
Angular UI: 0.12.0
Bootstrap: 3.1.1

**Comment by Dev63** [comment] 2015-02-11 18:41
I don't think this is related to page edges: I think it's related to positioning.  See this (unanswered) [Stackoverflow question about tooltip/popover positioning in floats](http://stackoverflow.com/questions/28228952/how-to-get-ui-bootstrap-popover-to-behave-in-float).  This used to work correctly, but it may be Bootstrap updates that have broken it.

**Comment by arjunasuresh3** [comment] 2015-04-13 06:42
+1

**Comment by piotr-gawlowski** [comment] 2015-04-25 11:08
+1

**Comment by icfantv** [comment] 2015-08-06 06:13
Closing as duplicate of #375.

**Closed by icfantv** 2015-08-06 06:13 UTC
Labels: component: $position, component: tooltip, PRs plz!
