### ISSUE TITLE
Carousel no-wrap doesn't do anything

### ISSUE THREAD

**Issue by davidrhoderick** [angular-ui/bootstrap#4439] opened 2015-09-18 22:42 UTC
I have used angular-ui on three projects so far and have yet to get the no-wrap to do anything.  I assume I am doing something wrong but I've tried a bunch of things and it should really be in the documentation.  How do I stop carousel from wrapping?  I have used `<carousel no-wrap="true">`, `<carousel no-wrap="false">`, and `<carousel no-wrap="noWrap">` and none work.

**Comment by Foxandxss** [comment] 2015-09-19 09:23
It should work if that `noWrap` variable is a bool (check the demo).

Still, I am checking the implementation and I am going to change it internally.

**Comment by wesleycho** [comment] 2015-10-14 04:47
Closing due to lack of actionable information.

It should be noted that we have [unit tests that cover this](https://github.com/angular-ui/bootstrap/blob/master/src/carousel/test/carousel.spec.js#L100-L143), so I highly suspect this is not a bug in the library.

**Closed by wesleycho** 2015-10-14 04:47 UTC
Labels: component: carousel
