### ISSUE TITLE
popover generates : Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by wallet77** [angular-ui/bootstrap#2927] opened 2014-11-04 21:08 UTC
Hi,

I have recently updated my frameworks and libs version. I want to use popover directive but it generates and error in jquery (Cannot read property 'split' of undefined).

After debugging I found that problem comes from this line in angular-ui :

```javascript
var positionStrParts = positionStr.split('-'); (line 910)
```

This line is call here :

```javascript
var ttPosition = $position.positionElements(element, tooltip, scope.tt_placement, appendToBody); (line 2533)
```

So I searched for **scope.tt_placement** which seems to be the root problem.
I found that this variable is only set here :

```javascript
attrs.$observe( prefix+'Placement', function ( val ) {
              scope.tt_placement = angular.isDefined( val ) ? val : options.placement;
});
```

So we observe **placement** attritube to set **scope.tt_placement**.

To fix the error I was obliged to set **popover-placement** and it works fine.
Is it a normal behavior ? In examples I saw some popover without this attribute.
Is it a bug or a documentation/code alignment problem?

In any cases, thanks for your work ;)

**Version** :
- angular : 1.3
- ui-bootstrap: 0.11.2
- jquery 2.1

**Comment by tholford** [comment] 2015-01-21 03:02
+1, experiencing this issue for both tooltips and popovers (dependency on tooltips) with Angular 1.3

**Comment by aeisenberg** [comment] 2015-01-23 20:52
+1

Seeing this too in popovers. I can confirm that the work around is to explicitly specify the popover-placement attribute in the html and the error goes away.

**Comment by cnaccio** [comment] 2015-02-18 18:33
There seems to be a problem with placement/position of  tooltips, and popovers. It has something to do with the changes to angular.isDefined which works differently in AngularJS 1.2 & 1.3 

Here are a few directives to patch the issues by setting defaults

            // Bootstrap UI fixes after upgrading to Angular 1.3
            .directive('tooltip', function() {
                return {
                    restrict: 'EA',
                    link: function(scope, element, attrs) {
                        attrs.tooltipPlacement = attrs.tooltipPlacement || 'top';
                        attrs.tooltipAnimation = attrs.tooltipAnimation || true;
                        attrs.tooltipPopupDelay = attrs.tooltipPopupDelay || 0;
                        attrs.tooltipTrigger = attrs.tooltipTrigger || 'mouseenter';
                        attrs.tooltipAppendToBody = attrs.tooltipAppendToBody || false;
                    }
                }
            })

            .directive('popover', function() {
                return {
                    restrict: 'EA',
                    link: function(scope, element, attrs) {
                        attrs.popoverPlacement = attrs.popoverPlacement || 'top';
                        attrs.popoverAnimation = attrs.popoverAnimation || true;
                        attrs.popoverPopupDelay = attrs.popoverPopupDelay || 0;
                        attrs.popoverTrigger = attrs.popoverTrigger || 'mouseenter';
                        attrs.popoverAppendToBody = attrs.popoverAppendToBody || false;
                    }
                }
            })

**Comment by RobJacobs** [comment] 2015-03-23 13:10
I'm not seeing this issue anymore when running against the latest master.  Seems somewhere along the way the observe for the placement attribute was removed and the prepPlacement function is called whenever the tooltip is opened (showTooltipBind() -> prepareTooltip() -> prepPlacement()) which sets the scope.placement property correctly.

**Comment by karianna** [comment] 2015-03-23 17:33
Closing as already fixed.

**Closed by karianna** 2015-03-23 17:33 UTC
Labels: AngularJS 1.3, component: popover, component: tooltip
