### ISSUE TITLE
ui.bootstrap.modal conflict

### ISSUE THREAD

**Issue by AbelZheng** [angular-ui/bootstrap#4214] opened 2015-08-17 11:02 UTC
use mobile browser.
input in modal conflict with ngTouch.
input unable to enter.

**Comment by pkozlowski-opensource** [comment] 2015-08-17 11:22
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

**Comment by wmaurer** [comment] 2015-08-26 15:30
I've no relation to the original poster, but I believe that I'm also experiencing the same problem.

When I have an input box in a modal dialog box, and tap in the input box, the virtual keyboard briefly opens, then immediately closes, and so I can't enter anything.

I've only been able to test it with Windows Phone 8.1 and Android Chrome.

I can also confirm that this only occurs when the ngTouch module is being used. Removing ngTouch stops the behaviour, so I believe there is a conflict.

Here's a plnkr: http://plnkr.co/edit/r0OqBlWV9PVY48kXiGhg?p=info
And the link for testing on a mobile device: http://embed.plnkr.co/r0OqBlWV9PVY48kXiGhg/preview

**Comment by Anisotropic** [comment] 2015-10-06 10:51
Can confirm this [bug/regression/conflict]. In our case on mobile devices in modal dialog select and input are not working together with ng-touch.

**Comment by Gamemaniak** [comment] 2015-10-06 11:03
This seems to be a duplicate of https://github.com/angular-ui/bootstrap/issues/2017.

**Comment by wesleycho** [comment] 2015-10-29 06:26
Was seeing this before, but I am not seeing this in the updated versions of the library and Angular [here](http://embed.plnkr.co/xjSc9FwV52DUun3dUDIp/preview).

Closing as resolved.

**Closed by wesleycho** 2015-10-29 06:26 UTC
Labels: component: modal, needs: plunkr
