### ISSUE TITLE
Popover closes unexpectedly

### ISSUE THREAD

**Issue by BartoGabriel** [angular-ui/bootstrap#5347] opened 2016-01-26 13:57 UTC
Example:
http://plnkr.co/edit/dMWd7KRHjaoOZWXyYvE5?p=preview

1. When I click on "today" the popover closes unexpectedly.
2. When I select a date the calendar closes, again I select a new date in the same calendar and closes unexpectedly the popover. This happens when I select twice dates in the same calendar.

Reference: https://github.com/angular-ui/bootstrap/issues/5305#issuecomment-173965779

**Comment by icfantv** [comment] 2016-01-26 15:48
@BartoGabriel, please do not use the issues forum for support-related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help) as support-related questions are best served by and for the community.  The issues forum is reserved for bugs.  Thanks.

The problem is you are using a datepicker inside a popover and you've specified `outsideTrigger` as the close trigger, which is happening when you click on the datepicker since it's outside the popover.  Your best bet is to use `none` and then use the `popover-is-open` property to manually close it based on the datepicker popup's `is-open` property.

**Comment by BartoGabriel** [comment] 2016-01-26 16:00
@icfantv It is not normal behavior. For example if you select the date from 01/03/2016 three times, the component is closed.
Why it is closed at the third time and not in the first?

**Comment by icfantv** [comment] 2016-01-26 16:07
While I agree that this is not normal behavior, it does not change the fact that you're not using the combination of the two correctly.  Because of this latter statement, I'm not sure it makes any sense for the developers to spend time investigating why this is occurring.  Investigation into issues can be quite time consuming and we would like to reserve it for issues that are more clearly library bugs.

I'm happy to reopen this but it's probably going to be a very low priority.  What are your thoughts?

**Comment by icfantv** [comment] 2016-01-26 16:21
I spoke with the dev team and we think we believe we have a relatively easy fix which would involve stopping event propagation on the buttons in the datepicker so that events don't leak out from the component (making it isolated).

That said, you still want to change your trigger on the popover because even if we do that, you're still going to run into issues with the buttons that lie outside the popover boundaries.

**Comment by icfantv** [comment] 2016-01-26 16:34
This is looking like a pretty big change since nearly all the templates will need to change as well as the datepicker code as well.  This is not trivial.

**Comment by BartoGabriel** [comment] 2016-01-26 16:41
I agree that the priority should be low, and the error is not urgent. I do not think it worthwhile to make many changes just for this error.

On the other hand, it does not take into account the limits of the popover as you say. For example, if you click on the June 2, it has the same behavior as clicking on a date which is within the borders of popover.

**Comment by wesleycho** [comment] 2016-01-26 16:50
I'm going to schedule this for 1.2 - I think this is pretty important to fix, but one can temporarily fix this by wrapping the datepicker usage like this
```html
<div ng-click="$event.stopPropagation()">
  <input uib-datepicker-popup ng-model="foo">
</div>
```

**Comment by BartoGabriel** [comment] 2016-01-26 17:21
@wesleycho thank you very much.

Following the example in case anyone ever need with the current version.
http://plnkr.co/edit/V5lzRCMUJCBerTzQ18pU?p=preview

**Closed** 2016-02-03 17:08 UTC
Labels: component: datepicker, needs: breaking change, type: bug
