### ISSUE TITLE
Namespace directives

### ISSUE THREAD

**Issue by toymachiner62** [angular-ui/bootstrap#3859] opened 2015-06-25 19:04 UTC
Your directives should contain names spaces. I just spent a week troubleshooting an issue where I had a directive with an attribute called "collapse" and when I ran it through my grunt build process it was not working. Eventually i figured out that if i removed angular-ui from my project it worked again so I believe there is a conflict between angular-ui's directive "collapse" and an attribute of my directive called "collapse".

If angular-ui had namespaces for it's directives like "ui-collapse", it is much less likely to have conflicts.

**Comment by RobJacobs** [comment] 2015-06-25 19:33
Duplicate of #3396

**Closed by RobJacobs** 2015-06-25 19:33 UTC
