### ISSUE TITLE
typeahead: selecting an item doesn't trigger ng-change

### ISSUE THREAD

**Issue by yktoo** [angular-ui/bootstrap#5818] opened 2016-04-19 07:25 UTC
### Bug description:
When there's the `ng-change` attribute set, it gets triggered on user input directly in the control, but it's never fired when the user selects an item from the typeahead list. Which is inconsistent, as, according to Angular docs:

> The ngChange expression is only evaluated when a change in the input value causes a new value to be committed to the model.

> It will not be evaluated:

> if the value returned from the $parsers transformation pipeline has not changed
> if the input has continued to be invalid since the model will stay null
> if the model is changed programmatically and not by a change to the input value

However selecting an item **is** an interaction by user -> `ng-change` must be fired.

### Link to minimally-working plunker that reproduces the issue:
https://plnkr.co/edit/xwA7HWt5dDZwcRffVgB5?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.3
UIBS: 1.1.2
Bootstrap: 3.3.6

**Comment by icfantv** [comment] 2016-04-19 14:28
At first glance, I don't see anything wrong with this - but it may result in unexpected behavior for users who are currently relying on `ng-change` to only be fired when the input value changes and not the underlying model.

I'm going to flag this for team discussion.

**Comment by wesleycho** [comment] 2016-04-21 06:34
ng-change is executed when the view value changes - when something is selected, that is when the model changes, so the flow is to do model -> view value update.

ng-change is for the opposite direction, when view value update -> model update. I'm fairly strongly against this suggestion, as it breaks the contract in Angular with how ng-change works in Angular's form components.

**Comment by yktoo** [comment] 2016-04-21 06:48
@wesleycho Not sure I understand what you mean by that. 

`ng-change`'s purpose is to notify the controller whenever the user's input has updated the value of the related model, as opposed to a programmatic change. It's working this way *on the control itself* either with or without a typeahead attached.

Now, if a user selects a value from the typeahead list (a user-initiated action), the result is a changed value in the model, however there's no `ng-change` fired.

That means that one always needs to subscribe to model changes via `$scope.$watch()` if the model's value is not only used in a view, but anywhere in the code. This is bad for two reasons:

1. It introduces inconsistency in reacting to a user-initiated action (`ng-change` for direct input, but if you have a typeahead attached, use `$watch()` instead). (The fact that typeahead itself updates the model programmatically is irrelevant for the developer making use of it.)
2. It burdens the digest cycle with an extra check, which can be avoided since the typeahead knows exactly when the model in scope has been updated by the selection.

**Comment by wesleycho** [comment] 2016-04-21 07:06
That is a naive understanding of the situation with how the typeahead works.

The data view value type of an input with the typeahead is a string that is a named representation of the model object. The model is the selected object, which can have as complex of a structure as a user likes. To set the $viewValue, one would need to do `ngModel.$setViewValue(nameRepresentationOfModel)`. However, there is no good way to go from that string to the model object.

This is an impossible implementation, and breaks the whole mechanism with when searching occurs, as well as break any potential usage of ng-model-options.

The best we can do with the way the typeahead is implemented is to correctly update the input view value when the model updates and to execute a search on input view value change (which is correct with Angular since arbitrarily modifying the $viewValue of an input to unexpected data types breaks expectations of how Angular should behave with input values & the parsers) without making an extremely major breaking change of how the HTML structure & API of the typeahead goes, which is pretty much out of scope due to lack of time & needing to work on the Angular 2 version of the library.

I'm not seeing a strong argument from the implementation side as to why we should accommodate this, especially when considering the massive work needed to accomplish this, as well as the user facing pain of having to migrate to something that would work with this expectation.

**Comment by wesleycho** [comment] 2016-04-28 16:29
Closing this as won't support

**Closed by wesleycho** 2016-04-28 16:29 UTC
Labels: component: typeahead, needs: breaking change, needs: investigation, type: enhancement
