### ISSUE TITLE
Carousel not working

### ISSUE THREAD

**Issue by dxwts** [angular-ui/bootstrap#4011] opened 2015-07-24 08:24 UTC
I used generator-angular  to create a angular project  and use carousel sample code, it not working.

bower.json
{
  "name": "test1",
  "version": "0.0.0",
  "dependencies": {
    "angular": "^1.3.0",
    "bootstrap-sass-official": "^3.2.0",
    "angular-animate": "^1.3.0",
    "angular-cookies": "^1.3.0",
    "angular-resource": "^1.3.0",
    "angular-route": "^1.3.0",
    "angular-sanitize": "^1.3.0",
    "angular-touch": "^1.3.0",
    "angular-bootstrap": "~0.13.1"
  },
  "devDependencies": {
    "angular-mocks": "^1.3.0"
  },
  "appPath": "app",
  "moduleName": "test1App",
  "overrides": {
    "bootstrap": {
      "main": [
        "less/bootstrap.less",
        "dist/css/bootstrap.css",
        "dist/js/bootstrap.js"
      ]
    }
  }
}

**Comment by lgaudez** [comment] 2015-07-24 10:03
Carousel directive is broken with angular 1.4.X. see https://github.com/angular-ui/bootstrap/issues/3811.

I tested with 1.3.17 and 0.13.1 and it seems to work well. 

Make a plunker if problem persist with 1.3.X version of angular.

**Comment by dxwts** [comment] 2015-07-24 10:38
@lgaudez Ah, ok, :+1: Thanks

**Comment by pkozlowski-opensource** [comment] 2015-07-24 10:58
Closing as duplicate of #3811

**Closed by pkozlowski-opensource** 2015-07-24 10:58 UTC
