### ISSUE TITLE
V0.13 - Cannot type only day with popup datepicker

### ISSUE THREAD

**Issue by tdeverdiere** [angular-ui/bootstrap#3869] opened 2015-06-29 07:58 UTC
We use the datepicker with the french format : dd/MM/yyyy and with the popup directive.
You use sometimes keyboard to type the date. When you only type the day, the model is not changed.
Ex : current date is 29/06/2015. You change 29 to 01, the date doesn't change. Here is the plunker : 

http://plnkr.co/edit/0lgEAmwhSxiimfKxmS24?p=preview

I don't think this is du to format because with yyyy/MM/dd i also reproduce the problem.

**Comment by ovarunendra** [comment] 2015-07-09 12:43
+1

**Comment by wesleycho** [comment] 2015-07-28 14:19
This appears to be a duplicate of #3713

**Closed** 2015-07-28 14:19 UTC
Labels: component: datepicker, resolution: duplicate

**Comment by tdeverdiere** [comment] 2015-07-28 14:35
In my Plunker you will not see the error **TypeError: baseDate.getFullYear is not a function** as in the #3713 
The stack of the error is :
> Datepicker directive: "ng-model" value must be a Date object, a number of milliseconds since 01.01.1970 or a string representing an RFC2822 or ISO 8601 date.
> (anonymous function) @ angular.js:11607
> render @ ui-bootstrap-tpls-0.13.0.js:1071
> ngModelCtrl.$render @ ui-bootstrap-tpls-0.13.0.js:1059
> ngModelWatch @ angular.js:23293
> Scope.$digest @ angular.js:14235
> Scope.$apply @ angular.js:14506
> $$debounceViewValueCommit @ angular.js:23262
> $setViewValue @ angular.js:23234
> listener @ angular.js:19653
> eventHandler @ angular.js:3014

**Comment by wesleycho** [comment] 2015-07-28 14:47
Right, but it turns out to be tightly related - #3759 should fix this.
