### ISSUE TITLE
Popover giving a "Syntax error, unrecognized expression" whenever I use 'popover-template'

### ISSUE THREAD

**Issue by ddoriazyp** [angular-ui/bootstrap#5384] opened 2016-02-02 00:34 UTC
I have a button with the following code:

```
<button type="button" class="btn btn-primary btn-lg btn-inverse round" popover-template="'deletePopover.html'">
   <i class="fa fa-trash-o"></i>&nbsp;&nbsp;Delete
</button>
```

and with the corresponding template:

```
<script type="text/ng-template" id="deletePopover.html">
  <div>
    <div>Deleting this creative will permanently remove it from any campaigns this is assigned to.</div>
    <div class="form-group">
      <button type="button" class="btn btn-primary btn-lg btn-inverse round">
        &nbsp;&nbsp;Confirm Delete
      </button>
    </div>
  </div>
</script>
```

Whenever I click on the button, I get the following message: "Syntax error, unrecognized expression: " followed by the template code above. Any ideas on why I'm getting this error? I'm on version 0.13.4 but I tried with version 1.1.1 and still got the same error.

**Comment by icfantv** [comment] 2016-02-02 00:39
@ddoriazyp, please do not use the issues forum for support-related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help) as support-related questions are best served by and for the community.  The issues forum is reserved for bugs.  Thanks.

If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

**Comment by icfantv** [comment] 2016-02-02 00:40
Closing until proper procedures are followed.

**Closed by icfantv** 2016-02-02 00:40 UTC

**Comment by icfantv** [comment] 2016-02-02 00:42
I should also note that having a popover with a click trigger on a button may not work as intended given that event propagation may not be what the developer requires.

**Comment by ddoriazyp** [comment] 2016-02-02 06:14
I'll keep that in mind for next time. Btw, your first intuition gave me some hope but it wasn't it as some of the examples are on buttons. The issue was that [strings starting with a newline (or anything other than "<") is not considered HTML string in jQuery 1.9](http://stage.jquery.com/upgrade-guide/1.9/#jquery-htmlstring-versus-jquery-selectorstring). Tx!
