### ISSUE TITLE
Typeahead demo async not working IE9

### ISSUE THREAD

**Issue by xtreemrage** [angular-ui/bootstrap#3773] opened 2015-06-08 11:51 UTC
The Typeahead demo, with async, does not work in IE9 (latest Chrome works).
Getting an error: Error: access denied. I assume that this is an CORS error.

angular-ui bootstrap: v0.13.0

**Comment by rvanbaalen** [comment] 2015-06-09 14:37
Please provide a plunkr.

**Comment by rvanbaalen** [comment] 2015-06-09 14:38
It sure smells like a cors error. That's something you should fix on your side and is not a bug in UI Bootstrap

**Comment by xtreemrage** [comment] 2015-06-09 14:45
I see this error on the angular-ui bootstrap site in IE9: http://angular-ui.github.io/bootstrap/#/typeahead

**Comment by pkozlowski-opensource** [comment] 2015-06-09 15:45
IE9 doesn't play well with CORS and this is why Angular's `$http` service doesn't support (read: doesn't do crazy hacks to pretend to support something that is not available in a browser) CORS request. AngularJS is not the only one here, see http://stackoverflow.com/questions/10232017/ie9-jquery-ajax-with-cors-returns-access-is-denied

In short: IE9 doesn't support CORS without ugly hacks. AngularJS didn't decide to add those hacks and we are certainly not going to do so in this library, sorry....

Closing as "won't fix"

**Closed by pkozlowski-opensource** 2015-06-09 15:45 UTC
Labels: component: typeahead, needs: plunkr, resolution: support
