### ISSUE TITLE
Pagination Flashes Content

### ISSUE THREAD

**Issue by mduey** [angular-ui/bootstrap#1689] opened 2014-01-28 18:42 UTC
When using Angular 1.2.10, Bootstrap 3 and ui-bootstrap-tpls-0.10.0.min.js, the pagination component will display a brief flash of itself (a second copy of itself) as well as content from hidden divs on the page (divs are using ng-hide and are in a ng-repeat).  This happens when a number is clicked on the pagination bar.

A workaround found in Issue #1350 Carousel solves the problem.  I was loading ngAnimate, but leaving it out fixed the problem.

**Comment by wesleycho** [comment] 2015-08-06 21:10
Can you check if this is still a problem with Angular 1.4 & current UI Bootstrap?

**Comment by wesleycho** [comment] 2015-09-18 05:13
Closing due to likely outdated issue - feel free to open an issue with reproduction if it is still a problem.

**Closed by wesleycho** 2015-09-18 05:13 UTC
Labels: component: pagination, needs: info, needs: plunkr
