### ISSUE TITLE
Dropdowns Never Lose Focus

### ISSUE THREAD

**Issue by RPGillespie6** [angular-ui/bootstrap#6372] opened 2016-12-14 22:25 UTC
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

Even after the dropdown closes, it does not lose focus. Clicking the mouse anywhere (including buttons) causes the focus to temporarily shift, but releasing the mouse instantly restores focus to the dropdown. Thus, pressing Enter will re-open the dropdown. This does not affect, for example, v0.12.0.

### Link to minimally-working plunker that reproduces the issue:

https://plnkr.co/edit/7atEkT1pCwF9X6F9KKAe?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.6

UIBS: 2.3.1

Bootstrap: 3

**Comment by SynRJ** [comment] 2016-12-15 08:48
We also have this issue. It appeared with the 2.3.1 release. Everytime you open a dropdown, all other inputs become unusable.

**Comment by RPGillespie6** [comment] 2016-12-15 14:54
Rolling back to 2.3.0 for now, then (package.json):

`"angular-ui-bootstrap": "2.3.0",`

**Comment by adgoncal** [comment] 2016-12-15 16:11
This is a duplicate of #6364

**Comment by alanziberi** [comment] 2016-12-15 19:23
https://github.com/angular-ui/bootstrap/issues/6357

**Comment by codymullins** [comment] 2016-12-20 14:26
Yeah, we are experiencing the same issue. We were developing on 2.3.0 and our deployment today went out with 2.3.1 causing widespread breakages for our drop downs.

**Comment by wesleycho** [comment] 2016-12-27 10:00
Missed this when merging - this is fixed by 955848c3b125ff24ce749a42283763dc16668ef0, and released in 2.3.2 just now.

**Closed by wesleycho** 2016-12-27 10:00 UTC
