### ISSUE TITLE
Open modal is shifting body content to the left

### ISSUE THREAD

**Issue by rc125** [angular-ui/bootstrap#3934] opened 2015-07-10 20:03 UTC
When launching the modal component the page to jump 15px to the left when a modal is opened.

Bootstrap v3.3 introduced additional JavaScript to overcome the flicker effect that occurs when a modal is rendered over a long page with a vertical scrollbar (see: twbs/bootstrap#9855). Bootstrap solves this problem by adding extra padding (equal to the width of the vertical scrollbar) to the body element when the modal opens. 

AngularUI Modal's JavaScript doesn't yet appear to mimic this behavior.

**Comment by andrepitombeira** [comment] 2015-07-17 09:13
This is duplicated. See https://github.com/angular-ui/bootstrap/issues/2631

**Comment by wesleycho** [comment] 2015-11-04 05:31
Closing this as a duplicate of #3714

**Closed by wesleycho** 2015-11-04 05:31 UTC
Labels: component: modal, resolution: duplicate, type: bug
