### ISSUE TITLE
Accordin Glyphicon Rendering Issue with IE11

### ISSUE THREAD

**Issue by VinothRajasekar** [angular-ui/bootstrap#3317] opened 2015-02-19 20:04 UTC
Hi,

I'm using angular accordin directive with IE11. I'm running into rendering issues, when I use Glyphicon. however, I have no renedering issues if I use the same with chrome. 

![image](https://cloud.githubusercontent.com/assets/3857385/6274674/1e21b9e4-b847-11e4-82e5-b7f971969626.png)

![image](https://cloud.githubusercontent.com/assets/3857385/6274701/5e52992a-b847-11e4-8e81-98f59b3e4ca5.png)

Thanks,
Vinoth

**Comment by wesleycho** [comment] 2015-08-06 16:00
I am not seeing this based on a current version of the accordion [here](http://plnkr.co/edit/0XBa4mzsRUW0nCdNbHEG?p=preview). Is there any particular reproduction steps required here?

**Comment by wesleycho** [comment] 2015-09-01 13:39
Closing due to lack of reproduction - feel free to get back with more information if this is still a problem.

**Closed by wesleycho** 2015-09-01 13:39 UTC
Labels: browser: IE11, component: accordion, needs: info, needs: plunkr
