### ISSUE TITLE
datepicker-popup='dd/MM/yyyy' is showing the given date as "MM/dd/yyyy"

### ISSUE THREAD

**Issue by RoelofDelft** [angular-ui/bootstrap#4215] opened 2015-08-17 12:14 UTC
The datepicker-popup='dd/MM/yyyy' is showing the given date as "MM/dd/yyyy" in the calendar component. 

In modal I place in my input:

datepicker-popup='dd/MM/yyyy'

But shows up as:

![datepickerpopover](https://cloud.githubusercontent.com/assets/13829194/9304554/a99ff4de-44e9-11e5-9bbd-e4827da526a0.JPG)

Software:
-- AngularJS 1.4.3 and higher tried
-- Ui-Bootstrap 0.13.3

**Comment by RobJacobs** [comment] 2015-08-17 13:43
Tested against this [plunk](http://plnkr.co/edit/1SwhBBh3saKPieDxciEE?p=preview) and everything seems to work.  Closing until a reproducible plunk is provided, please see: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

**Closed by RobJacobs** 2015-08-17 13:43 UTC

**Comment by RoelofDelft** [comment] 2015-08-17 13:54
Are you testing against these two minified versions?

Tnx in advance

**Comment by RoelofDelft** [comment] 2015-08-17 13:56
I mean this version:

/*
 * angular-ui-bootstrap
 * http://angular-ui.github.io/bootstrap/

 * Version: 0.13.3 - 2015-08-09

**Comment by mathpere** [comment] 2015-09-01 10:07
Hi,

I've just met the same issue since version 0.13.3

![Bug datepicker](https://docs.google.com/uc?id=0B_ksY-Q-HtWOaU5FT0JXX01ZNEU)

I explore for more details.

**Comment by RoelofDelft** [comment] 2015-09-01 12:47
Hi Mathpere,

Great to know that it wasn't me on my own struggling with this.

As RobJacobs was not willingly to help, I went on my own mission to solve the problem.

Used in the readonly input:
-- ng-model='StudyDate'
-- datepicker-popup='dd/MM/yyyy' and its other stuff
-- ng-change='moveDate( StudyDate.getDate() + \" / \" + (StudyDate.getMonth()+1) + \" / \" + StudyDate.getFullYear())'

Where StudyDate is a "new Date()" and changed in moveDate as follow:

    $scope.moveDate = function(foundDate) {

        var originalDateObject = new Date();
        var foundDateSplit = foundDate !== undefined && foundDate.length > 1 ? foundDate.split("/") : [];

        if (foundDateSplit.length > 2) {
            originalDateObject.setFullYear(foundDateSplit[2], foundDateSplit[1], foundDateSplit[0]);
            // Correct Month numbering
            originalDateObject.setMonth(originalDateObject.getMonth() - 1);

            // Copy date to calendar input
            $scope.StudyDate = originalDateObject;
        }
    }

Hope this helps?

If it does not help, just let me know.

**Comment by mathpere** [comment] 2015-09-01 21:29
Thanks RoelofDelft for your help, I really appreciate.

Unfortunately, I'm using datepicker directive within other complexe directive where I can not easily test your code.

After further investigations, it appears that originally, there was a bug: I was forced to initiate ng-model with a string rather than a Date object. I had found a workaround to handle this case.

But with this new release, this is no more required and this workaround implies this bug.

From now, ng-model must be a Date object and all is working fine.
