### ISSUE TITLE
ui.bootstrap.modal opens twice

### ISSUE THREAD

**Issue by bhushanvaidya3** [angular-ui/bootstrap#3356] opened 2015-03-03 18:14 UTC
ui.bootstrap.modal opens twice for some reason. Any clue will be much helpful. I'm instantiating the modal as shown in the code below:

````
 $scope.openAuditLogModal = function (size) {
      $log.info('Modal created at: ' + new Date());
        var modalInstance = $modal.open({
          templateUrl: '/Main/RFQ/views/tempPartial.html',
          controller: 'tempPartialController',
          windowClass: 'app-modal-window',
          size: size,
          resolve: {
            items: function () {
              return $scope.items;
            }
          }
        });

        modalInstance.result.then(function (selectedItem) {
          $scope.selected = selectedItem;
        }, function () {
          $log.info('Modal dismissed at: ' + new Date());
        });
      };
````

**Comment by ShashankaNataraj** [comment] 2015-03-09 09:19
I had a similar problem when working with pure bootstrap, have you included bootstrap.min.js twice by any chance?

**Comment by bhushanvaidya3** [comment] 2015-03-09 11:07
I've checked and I'm using bootstrap once. I'm managing my scripts via bower.

**Comment by karianna** [comment] 2015-03-09 11:58
plunkr please

**Comment by lewyue** [comment] 2015-04-03 09:44
I've the same problem 
and any ideas?

**Comment by pkozlowski-opensource** [comment] 2015-04-16 15:39
Closing due to the lack of reproduce scenario. @lewyue if you've got the same issues provide a reproduce scenario.

**Closed by pkozlowski-opensource** 2015-04-16 15:39 UTC
Labels: component: modal, needs: info
