### ISSUE TITLE
Timepicker Bug:minute accepts alphabetic character and doesnt show validation error  

### ISSUE THREAD

**Issue by harshpuidev** [angular-ui/bootstrap#5085] opened 2015-12-17 01:10 UTC
There is bug with when u enter 10:3a it accepts the input. It should have thrown an error. The following example is from the website demo.

![error](https://cloud.githubusercontent.com/assets/16329252/11858559/9330b8a4-a417-11e5-879f-8a215c6bc264.JPG)

 Now I need to Validate that how can i do that??

i want the 10:3a to throw an error. and not accept it has 10:03 PM

**Comment by wesleycho** [comment] 2015-12-17 03:11
I think this is a duplicate of #5059 - going to close that one since this appears to be more clearer.

**Closed** 2016-01-11 06:05 UTC
Labels: component: timepicker, PRs plz!, type: bug

**Comment by harshpuidev** [comment] 2016-01-25 19:18
Hi there can anyone update me which version would have these fix and when it will be released because we are currently using the timepicker and waiting for the fix.

**Comment by icfantv** [comment] 2016-01-26 00:11
@harshpuidev, please respect our time by looking at the contents of this issue before commenting with such a question.  A commit was made 15 days ago with this fix and was a part of the 1.0.0 release.  Please note that 1.1.0 was released this morning.
