### ISSUE TITLE
datepickerPopup wrong deprecation warning for unspecified minDate/maxDate

### ISSUE THREAD

**Issue by ndrsv** [angular-ui/bootstrap#5743] opened 2016-04-05 09:11 UTC
When using `datepickerPopup` 

- without `datepickerOptions`; or 
- with `datepickerOptions` and `minDate` or `maxDate` undefined

wrong deprecation warnings are printed to the console on popup activation:

> Literal date support has been deprecated, please switch to date object usage

http://plnkr.co/edit/ShuLcciyecNDfxlhOHHV?p=preview

Angular: 1.5.3
UIBS: 1.3.0
Bootstrap: 3.3.6

**Comment by evilaliv3** [comment] 2016-04-05 12:51
I think this ticket could be closed as documented with the following pull request: https://github.com/angular-ui/bootstrap/pull/5732

**Comment by TueCN** [comment] 2016-04-05 13:56
Either the updated docuemntation is wrong or there is a bug:

The documentation states that `minDate` and `maxDate` defaults to `null`.
However, I get the deprecation warnings when I do not specify a `datepicker-options` object or if I specify a options object without a `minDate` and `maxDate` property. 

Where are the default values?

It is really annoying that I _have_ to specify a `datepicker-options` attribute in my HTML and define a useless options object `vm.datepickerOptions = {minDate: null, maxDate: null};` in my controller to avoid getting the deprecation warnings.
I would like to instead have the default `null` values apply, as I have no needed configuration that requires a `datepicker-options`

Can we pretty please have the defaults back? :)

**Comment by wesleycho** [comment] 2016-04-05 14:40
It shouldn't be on the non-values - that is a bug and unintended behavior with the deprecation message.

We'll address this with 1.3.2.

**Comment by deeg** [comment] 2016-04-05 15:15
I didn't see this issue, but I believe my PR addresses this: #5747

**Closed** 2016-04-05 16:46 UTC
Labels: component: datepicker-popup, severity: confusing, type: bug
