### ISSUE TITLE
Collapse usage inside modal: section "pops" when not collapsed

### ISSUE THREAD

**Issue by levin81** [angular-ui/bootstrap#4414] opened 2015-09-14 13:20 UTC
http://plnkr.co/edit/x7FIiKirhANONuAwgKvH?p=preview

Just added to the unordered-list element a 'collapse="false"' (so everything should be business as usual), but when the modal is loaded it first displays the rest of the elements and then the element with the collapse directive pops into view.

**Comment by wesleycho** [comment] 2015-09-14 15:42
I think this might be a duplicate of an existing issue - not quite sure what is causing this bug, it needs some investigation.

**Comment by wesleycho** [comment] 2015-10-28 21:04
Just noting, I suspect this could be a ngAnimate regression in Angular.

**Comment by icfantv** [comment] 2015-10-28 21:43
Given the age of this in OSS days we should see if it's reproducible with the latest code versions.  When I was going through the backlog this morning I was able to close several animation issues just by doing this.

**Comment by wesleycho** [comment] 2015-12-16 01:16
This is still an issue in `master`, as can be seen [here](http://plnkr.co/edit/9rv2nNLxqq4Ppkgx1abc?p=preview).

**Comment by icfantv** [comment] 2016-01-11 16:37
Closing in favor of #5192.  Also see PR #5199.

**Closed** 2016-01-11 16:37 UTC
Labels: component: modal, type: ngAnimate
