### ISSUE TITLE
Popover needs to change position based on element position.

### ISSUE THREAD

**Issue by Praveen-V-S** [angular-ui/bootstrap#5203] opened 2016-01-11 07:16 UTC
Drop downs and popovers needs to open based on current position. For eg: if the popover toggle is positioned at the top of the page open the popover with position: bottom and vice versa, so that popovers and drop downs will be always visible.

**Comment by icfantv** [comment] 2016-01-11 15:48
Closing as duplicate of #4762.

@Praveen-V-S, please extend us the courtesy of searching both open and closed issues prior to entering anything in the issues forum.  Thanks.

**Closed by icfantv** 2016-01-11 15:48 UTC
