### ISSUE TITLE
tab index error

### ISSUE THREAD

**Issue by imshenshen** [angular-ui/bootstrap#6199] opened 2016-08-24 03:37 UTC
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
In file `src/tabs/tabs.js`, there has a function `sort`.

if my tab `index` is a string or i have  draggable tabs, the order of my own controller's tab will be different from the order in tab directive. And when i delete a tab,  the `newActiveTabIndex` is unexpect

**Comment by wesleycho** [comment] 2016-08-24 14:09
Closing due to insufficient minimal reproduction/information

**Closed by wesleycho** 2016-08-24 14:09 UTC

**Comment by imshenshen** [comment] 2016-08-28 13:30
@wesleycho ？？？

**Comment by pziegler** [comment] 2016-08-28 16:50
you should provide a basic plunker that shows the error at least

**Comment by imshenshen** [comment] 2016-08-29 01:22
https://plnkr.co/edit/OXakHwhjqvYjPUBAYdg2?p=preview

i think [this](https://github.com/angular-ui/bootstrap/blob/master/src/tabs/tabs.js#L71) want to select the second tab in the example. 
but [sort function](https://github.com/angular-ui/bootstrap/blob/master/src/tabs/tabs.js#L43) make it wrong.
My English is horrible 😭

**Comment by imshenshen** [comment] 2016-08-31 06:02
@ajoslin nobody care?
