### ISSUE TITLE
Carousel Slide.

### ISSUE THREAD

**Issue by Punith-Mithra** [angular-ui/bootstrap#5498] opened 2016-02-17 09:09 UTC
Please review, for uib-carousel in 1.1.1 

The carousel animation does not work when I switch to another tab for 10 to 15 seconds and again came back to the same tab.

This happens because even after moving to next tab (@line 207) $currentTransition is set to true
and $currentTransition is never set to false (@line 210) because animation is never going to happen when the tab is not active.

I hope this will help to resolve the problem.

Please try to resolve this issue in next release.

**Comment by icfantv** [comment] 2016-02-17 14:19
Closing as duplicate of #5471.

Thank you for the investigation.

Please be respectful of our time by searching existing issues prior to entering a new one.

**Closed by icfantv** 2016-02-17 14:19 UTC

**Comment by BenevidesLecontes** [comment] 2016-02-18 16:46
Punith-Mithra did u fixed this issue? If yes, how?. I didn't understand very well what u said above.

**Comment by icfantv** [comment] 2016-02-18 17:19
@BenevidesLecontes, no.  @Punith-Mithra did not fix the issue.  He/she merely pointed out where he/she thinks the issue is located.  This is clearly an important issue for you based on the amount of posting you're doing, so might I recommend you taking his/her hint and running the code yourself in a plunker?  You can perform a custom build by pulling our master branch and running `grunt` from the command line.  The generated files will be placed in the `dist` folder.  You can then copy and paste the contents of the unminified TPLS version of the file into your plunker.
