### ISSUE TITLE
crashed when used with <base href="/any-base/">

### ISSUE THREAD

**Issue by prasgema** [angular-ui/bootstrap#6234] opened 2016-09-12 13:15 UTC
Wasn't sure if I have to post this in `ui.bootstrap` or `ui.router`
But it happens when you are using `<base href="/any-base/">` altogether with `ui.router` and `ui.bootstrap` I can't seem to get out of the problem. At first, I thought this is a problem with `ui.router`; turns out when you comment the ui.bootstrap in angular dependencies, the problem stops.

The problem it caused is a continuous loop to load the required js files
![continuous](https://cloud.githubusercontent.com/assets/11336579/18436202/452fdd8a-7921-11e6-9f29-6778329b3487.png)

The problem does not happen when you are using `<base href="/">` or `<base href="/any-base">` but this doesn't produce wanted result. the use case is that: like to make a multiple-angular-UI application (suppose `https://host` is where I store the primary application), I need to make a separate angular application by heading to `https://hosts/admin`, using the same API as frontend. Using a <base href="/any-base"> will result all `ui-sref="..."` routes the link to `https://hosts/admi/path/to/route` instead of `https://hosts/admin/path/to/route`

Here's the example of code where it loads js infinitely
https://embed.plnkr.co/Nw4fPlELncOPoWdB2ehe/
although it won't work if not hosted on a single host

Angular: 1.5.8
UIBS: 2.1.3
UIR: 0.3.1
Bootstrap: 3.3.7

**Comment by wesleycho** [comment] 2016-09-14 13:51
I don't think this is a UI Bootstrap issue. UI Bootstrap does not touch the browser `location` at all.

Plunker seems to be broken, so I cannot look further, but I'm quite skeptical that UI Bootstrap is the cause.

**Comment by wesleycho** [comment] 2016-09-14 13:53
Actually, the reason Plunker seems to be broken is that the base href destroys the routing - without a deeper **minimal** reproduction, this cannot be acted on.

Closing as likely an invalid issue.

**Closed by wesleycho** 2016-09-14 13:53 UTC
