### ISSUE TITLE
tooltip-is-open is not working if it's parent has ng-if directive

### ISSUE THREAD

**Issue by feng-xiao** [angular-ui/bootstrap#5484] opened 2016-02-16 14:08 UTC
tooltip-is-open is not working if it's parent has ng-if directive

**Comment by wesleycho** [comment] 2016-02-16 14:21
This needs a reproduction on Plunker.

**Comment by wesleycho** [comment] 2016-02-16 15:32
I suspect this issue is due to not binding the value to a reference on $scope - see [Understanding Scopes](https://github.com/angular/angular.js/wiki/Understanding-Scopes) on the AngularJS wiki

**Comment by feng-xiao** [comment] 2016-02-18 14:57
it works if I change to use ng-show/ng-hide. would that be timing issues?

**Comment by RobJacobs** [comment] 2016-02-18 16:18
@feng-xiao Here is a [plunk](http://plnkr.co/edit/fmkIDm7n0dCb2nXmdFGG?p=preview) generated from the demo page that proves the tooltip-is-open is working as expected with ngIf.  I'm going to close this issue for now, if you can reproduce the problem, I will re-open it.

**Closed by RobJacobs** 2016-02-18 16:18 UTC
Labels: component: tooltip, needs: info, needs: plunkr

**Comment by chandlerkent** [comment] 2016-05-11 19:11
@RobJacobs here is a [plunk](http://plnkr.co/edit/ATixYRIv9A3PC76wc57x) based on your working plunk that demonstrates the issue.

There are two directives created with exactly the same logic. The only difference is one has an ng-if and one does not.

**Comment by Vaaceph** [comment] 2017-12-15 11:06
I agree with one who asked this question. If you use ng-if , tooltip-is-open does not work, but it works fine when you use ng-show.

**Comment by keithics** [comment] 2018-01-11 20:42
same problem here..
