### ISSUE TITLE
Close the popover with a close(x) button in title bar

### ISSUE THREAD

**Issue by ramprakash-ravi** [angular-ui/bootstrap#4470] opened 2015-09-25 05:40 UTC
Currently the popover is able to close only if i click again on the element where it is used to open.

Is there a option of **enabling/adding a close (x) button** in the title bar of popover to close the popover when it is open.

**Comment by icfantv** [comment] 2015-09-25 14:32
Please do not use the issues forum for support related requests.  Please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help) for how to receive support.

Closing as a duplicate of #3906 - see this issue for more information.

**Closed by icfantv** 2015-09-25 14:32 UTC
