### ISSUE TITLE
Popover directive doesn't fire ng-clicks from template in Safari

### ISSUE THREAD

**Issue by sethflowers** [angular-ui/bootstrap#4438] opened 2015-09-18 15:16 UTC
I have a popover using a template. Inside the template is a single element containing an ng-click that executes a function on the scope doing nothing but firing an alert. In other browsers, this works fine. In Safari 8.1 on El Capitan, nothing happens. 

    <button type="button" class="btn btn-default"
      popover-placement="bottom"
      popover-template="'template.html'">Click for Popover</button>

    <script type="text/ng-template" id="template.html">
      <a href="" ng-click="fireAlert()">Click for alert</a>
    </script>

I'm using angular 1.4.5, and angular-ui-bootstrap 0.13.4.

The following plunk can be used to test: http://plnkr.co/edit/ZDdiKt1VvQVAwxwblwvW?p=preview

**Comment by icfantv** [comment] 2015-09-18 15:32
Closing as duplicate of #3687.  @sethflowers, don't use a `<button>` is a temporary workaround.  You can see the comment thread in the linked issue.

**Comment by icfantv** [comment] 2015-09-18 15:33
Sorry.  I missed that you posted comments in #3687.  Any reason you opened a new issue?  What did I miss here?

**Comment by sethflowers** [comment] 2015-09-18 16:06
@icfantv This isn't the same issue as https://github.com/angular-ui/bootstrap/issues/3687. 

In the plunk, clicking on the button correctly opens the popover, but inside the popover, there is a link with an ng-click, which does nothing. This works in other browsers, but not safari.

**Comment by icfantv** [comment] 2015-09-18 16:15
Ok.  Please try with just `href` and not `href=""`.

**Comment by sethflowers** [comment] 2015-09-18 16:18
I don't think that matters, I originally was trying it with a div with ng-click which didn't work either. I think the plunk just ended up with an anchor.

**Comment by icfantv** [comment] 2015-09-18 16:18
That Plunker (without my previous comment) is working for me on Safari 8.0.7.

**Comment by sethflowers** [comment] 2015-09-18 16:29
@icfantv - Hmmm... this might be a false alarm. I'm testing in saucelabs because I don't have access to the hardware either, and it seems its just not opening the alert in Safari. I changed the method on the scope to just increment a count and it looks like that is happening. Sorry for the false alarm :/

**Closed** 2015-09-18 16:31 UTC
Labels: component: popover, component: tooltip

**Comment by icfantv** [comment] 2015-09-18 16:36
No worries, thanks for taking the time to assist debugging.
