### ISSUE TITLE
Error in DatePicker

### ISSUE THREAD

**Issue by YamilBracho** [angular-ui/bootstrap#6071] opened 2016-07-03 18:15 UTC
Hi, I have a datePicker in my form. Its definition:
`                    <div class="row">
                        <div class="col-xs-3">
                            <label class="control-label">Desde</label>
                            <p class="input-group">
                                <input type="text" 
                                       class="form-control" 
                                       uib-datepicker-popup="dd/MM/yyyy" 
                                       ng-model="dpDesde" 
                                       is-open="popup1.opened" 
                                       ng-required="true" 
                                       close-text='Cerrar'
                                       clear-text='Limpiar'
                                       current-text='Hoy'
                                       datepicker-options="dateOptions"
                                       alt-input-formats="altInputFormats" />
                                <span class="input-group-btn">
                                    <button type="button" 
                                            class="btn btn-default" 
                                            ng-click="openDatePop(1)">
                                        <i class="glyphicon glyphicon-calendar"></i></button>
                                </span>
                            </p>
                        </div>                        
`

I set 'required' for this field and its initial value is today. When I leave blank I got this error 👍 
`Error: I is undefined
q@http://localhost/SafeTravelClient/js/ui-bootstrap-tpls-1.3.3.min.js:8:6100
this.init/<@http://localhost/SafeTravelClient/js/ui-bootstrap-tpls-1.3.3.min.js:8:9508`

I guess it would try to apply some formatting or something and find a null value...

Any hint...

TIA,
Yamil

**Comment by icfantv** [comment] 2016-07-03 21:05
@YamilBracho, please be respectful of our time and processes by adhering to the issue template.  As we are all volunteers, we simply do not have the time to chase every incomplete issue entered by users.  As such, I apologize, but I am going to close this until you comply.  Thanks.

**Closed by icfantv** 2016-07-03 21:05 UTC

**Comment by YamilBracho** [comment] 2016-07-03 22:21
Sorry, but it was not my intention be respectful and make you lost time, my mistake...

**Comment by icfantv** [comment] 2016-07-04 05:03
@YamilBracho don't sweat it.  If you think this is a bug, please fill out our issue template and include a minimally working plunker and if you can reproduce the error there, we will take a look at it.  We ask you to do this because 1) as mentioned, we simply don't have the time, and 2) many times, users are unable to reproduce the issue which indicates that there is an issue that users' code.
