### ISSUE TITLE
Dateformat issue

### ISSUE THREAD

**Issue by Xainu31** [angular-ui/bootstrap#4437] opened 2015-09-18 14:50 UTC
I was using Ui bootstrap version 0.13.1 i upgraded it to 0.13.3
every thing was working fine bt by upgrading i am having following problem
I have a form in which i have a Datepicker. Date is provided from controller but when i give date to datepicker it starts throwing "Date" error when i select the same date from the datepicker i get no error but when i do it from controller it gives me error. in 0.13.1 it was fine bt now its not working properly.
I have created a Plunk which you can view for reference

http://plnkr.co/edit/Z3DaHXN7dH96JAVxXKiv?p=preview

**Comment by honeychen502** [comment] 2015-09-23 02:46
when i give date 10/09/2015, it works fine.But, when i turn to give 10/9/2015, its not working properly.
Maybe the format is dd/MM/yyyy.

**Comment by wesleycho** [comment] 2015-10-15 05:45
I am confused by this issue - I am not seeing any error here, can you explain clearly what you are referring to here with proper reproduction steps @Xainu31 ?

**Comment by wesleycho** [comment] 2015-10-28 21:04
Closing due to lack of reproducible information.

One should keep in mind that issues should only be reserved for legitimate bugs in the library, or feature requests - see https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem

**Closed by wesleycho** 2015-10-28 21:04 UTC
Labels: component: dateparser, component: datepicker, needs: info, needs: work
