### ISSUE TITLE
Tabs: Change hiding tab-content to ng-if instead ng-show/hide

### ISSUE THREAD

**Issue by konstantinkrassmann** [angular-ui/bootstrap#2637] opened 2014-08-27 06:48 UTC
Hello team,
Currently i'm developing a large web app with angular+your awesome bootstrap ui. 

When it goes to performance, angular offers many pitfalls.
I recently changed all my `ng-show/hides` to `ng-if` resulting in 20% performance boost (measured with AngularJS Batarang chrome extension and chrome web dev profiler)

The reason is the `ng-show` does hide the DOM elements via css. This means all watchers will continue working on the hidden elements. 
That's an __unnecessary__ enlargement of the scope digest and costs like >100ms of every scope digest (depending on hidden content and watchers there). All directives, filters, ... will still just refresh for noone.

`ng-if` on the other hand, __removes__ the __dom elements completely__ and __stops__ the corresponding __watchers__ from __working__ until the dom is visible.
When the DOM element get visible again, angular does recompile the element and element'
s children so you won't even see an difference between `ng-show` or `ng-if`.

Looking forward hearing from you soon.

**Comment by Hotell** [comment] 2015-06-05 14:24
duplicate of #3306

**Comment by wesleycho** [comment] 2015-09-17 13:37
I agree with the workaround mentioned https://github.com/angular-ui/bootstrap/issues/2637#issuecomment-59009523 - I believe to bake this into the library itself would be more difficult since transclusion is involved.

Closing as won't support.

**Closed by wesleycho** 2015-09-17 13:37 UTC
Labels: component: tab, type: enhancement

**Comment by ajwhite** [comment] 2015-09-17 13:39
Sounds good to me (coming here via #3306). This is what we ended up doing as well.
