### ISSUE TITLE
support <uib-tabset model="mySelectedTabName"> so that you can expose or set the selected tab name

### ISSUE THREAD

**Issue by jstrachan** [angular-ui/bootstrap#5152] opened 2016-01-06 12:55 UTC
Rather like using ng-model with things like <select>

it would be really handy to be able to know the currently selected tab or to set the selected tab (e.g. to bookmark the selected tab via a `$location.search()` parameter etc.

So rather than having to add a `select()` to each `<tab>` just add a select function on `<tabset>` or just bind the selected tab's heading (or tab object) to some model so that the outer controller can read the selection and ideally so that the outer controller can change the selected tab

**Comment by wesleycho** [comment] 2016-01-06 14:58
The main issue with this request I have is that this seems like this would add a bunch of complexity in order to support this feature, which would result in a lot of code & overhead that many do not need.

We favor extensibility over configuration due to the complexity and bloat that configuration ends up adding. What are your thoughts given this?

**Comment by jstrachan** [comment] 2016-01-06 15:03
maybe we need a separate selectable-tabset directive?

**Comment by icfantv** [comment] 2016-01-06 16:56
@jstrachan, that's going to result in a fair amount of duplicate code.

@wesleycho, what do you think about adding a method to `UibTabsetController` to return the active tab?  That would be a really straight-forward mod.  @jstrachan, would that suffice for your needs?

**Comment by wesleycho** [comment] 2016-01-06 17:08
@icfantv we have #4836 for making a breaking change in the tab API - we got it wrong, comparing it to the accordion API makes it clear.

**Comment by icfantv** [comment] 2016-01-06 17:43
Ah, ok.  I didn't see that.  Thanks.

**Comment by wesleycho** [comment] 2016-02-01 02:49
Going to close this as a duplicate of #4836 - any api signature discussion should be in there when we do make this change to how the tabs are used.

**Closed by wesleycho** 2016-02-01 02:49 UTC
Labels: component: tab
