### ISSUE TITLE
"ng-date-valid" doesn't get added to a text input when the date is set programmatically

### ISSUE THREAD

**Issue by distinctdan** [angular-ui/bootstrap#4704] opened 2015-10-23 19:37 UTC
On the demo page, if you select a date using the left datepicker (which is a text input), the right input never gets the "ng-date-valid" class added to it. However, if you select the date using the *right* input (which is a date input), the class gets successfully added to both inputs.

**Comment by distinctdan** [comment] 2015-10-23 20:17
The reason I'm using the ng-date-valid class is I need to validate the date if the user has entered something. However, the field is optional, so I can't use ng-required.

**Comment by icfantv** [comment] 2015-10-23 20:24
@distinctdan, there is not yet widespread browser support for `<input type="date"/>` (and there are still issues with those that allegedly do support it).  Please use `<input type="text"/>` and I believe this should solve your issue.

**Comment by distinctdan** [comment] 2015-10-23 20:32
@icfantv Sorry for the misunderstanding, I am using `<input type="text">` for everything. The text inputs are the ones that are broken. However, I happened to notice that the date input worked, so I brought it up to help with debugging.

**Comment by icfantv** [comment] 2015-10-23 20:41
I'm still not convinced this is an Angular UI Bootstrap issue, but I will reopen for investigation.  In the interim, can you please create a minimally working plunker that demonstrates the issue?  Thanks.

You can even use ours as a starting point, but strip out anything that's not relevant.

**Comment by distinctdan** [comment] 2015-10-23 21:59
Thanks, I'll give it a shot. I've got some work stuff to do at the moment, but I'll look into it soon.

**Comment by icfantv** [comment] 2015-10-23 22:04
No worries.

**Comment by schmitch** [comment] 2015-10-28 10:22
Currently I don't know if this is the same case however I needed a datepicker with format dd.MM.yyyy.
My API gets a date with the format of 'dd.MM.yyyy' currently I need to format all DATES to feed them to the datepicker, is there any alternative in doing so?
> Datepicker directive: "ng-model" value must be a Date object, a number of milliseconds since 01.01.1970 or a string representing an RFC2822 or ISO 8601 date.

Is there a way to change that??

**Comment by icfantv** [comment] 2015-10-28 15:09
@schmitch, based on my current understanding of what you've typed, yours is a completely different issue - one that is best suited for StackOverflow as our issues forum is reserved for bugs.

The format of the date is totally independent of the `Date` object in the `ng-model` - you can format it however you wish.  This is the entire point of separating views from models in that the view can display the model however it wishes.

**Comment by wesleycho** [comment] 2015-11-04 05:56
Closing as a duplicate of #4664.

Looking into what we can do about this.

**Closed by wesleycho** 2015-11-04 05:56 UTC
Labels: component: datepicker, needs: investigation, needs: plunkr

**Comment by distinctdan** [comment] 2015-11-04 14:53
Thanks for looking into it.
