### ISSUE TITLE
Datepicker doesn't work with ng-required and custom format

### ISSUE THREAD

**Issue by skalamichal** [angular-ui/bootstrap#4688] opened 2015-10-22 10:05 UTC
After upgrading to ui-bootstrap 0.14.2 I noticed that uib-datepicker-popup doesn't work correctly, when using ng-required with custom date format in uib-datepicker-popup="MM/dd/yyyy" (for example). The date value is set in the controller, when app is run.

Please see following plunks, with correct behavior (ui-bootstrap version 0.13.4):
http://embed.plnkr.co/QpdKLwXfcBBcpRW414BY/preview
And incorrect (ui-bootstrap version 0.14.2):
http://embed.plnkr.co/l7DtCL1dw3YhofCPtO38/preview

- angular: 1.3.20
- ui-bootstrap: 0.13.4 and 0.14.2
- bootstrap: 3.3.5

Michal

**Comment by RobJacobs** [comment] 2015-10-22 11:55
This is a duplicate of issues #4678, #4616, #4607, etc... and is fixed under PR #4635.  Please search closed issues before opening a new one.

**Closed by RobJacobs** 2015-10-22 11:55 UTC
