### ISSUE TITLE
uib-datepicker-popup with format d!.M!.yyyy

### ISSUE THREAD

**Issue by brunnurs** [angular-ui/bootstrap#5241] opened 2016-01-14 08:29 UTC
In #4496 the feature of optional leading zero's in date-input was discussed. Example: The user can enter either *1.4.2016* or *01.04.2016*. The issue has been fixed with commit b1cfc5762dd80d8eecec95385a4dcf335cdb8ecd, which introduced *d!* and *M!* to allow optional leading zero's on user-input. 

Unfortunately, it doesn't seem to work for the uib-datepicker-popup. I extended your [uib-datepicker-popup-example](http://plnkr.co/edit/DeZZmS3PVAN3CQp4KdGo?p=preview) by the format *d!.M!.yyyy*. When I pick a date, it's displayed in format *dd.MM.yyyy* and I can also enter a date in format *dd.MM.yyyy*. But when I enter e.g. *1.4.2016*, parsing does not work (it should because of optional-leading-zero-format).

**Comment by wesleycho** [comment] 2016-01-14 13:52
Closing as a duplicate of #5225.

One can work around that currently by using `ng-model-options="{allowInvalid: true}` as seen [here](http://plnkr.co/edit/pjlICm3iwLYNwMUYMD6I?p=preview), but this definitely needs to be fixed.

**Closed by wesleycho** 2016-01-14 13:52 UTC
