### ISSUE TITLE
With $modal, Bootstrap 3.3.0 works, Bootstrap 3.3.1 does not

### ISSUE THREAD

**Issue by linagee** [angular-ui/bootstrap#3184] opened 2015-01-13 22:24 UTC
When I pop up a $modal, it has a clear background on Bootstrap 3.3.1. I'm using the demo plunkr here to show the error: http://plnkr.co/edit/Z9C41lgsTge115c4BFSf?p=preview

(Change 3.3.1 to 3.3.0 and it works.)

**Comment by alexander-konovalov** [comment] 2015-01-28 20:21
May be bug in BS 3.3.1
Background is visible with this tablet:
.modal-backdrop {
  bottom: 0;
}

**Comment by ddhp** [comment] 2015-02-04 07:57
I found the same problem today, fixed with alexander's solution as well

**Comment by kevinoid** [comment] 2015-02-16 17:07
For reference, the cause was the merging of twbs/bootstrap#14927 in 3.3.1 which changes the positioning of `.modal-backdrop` to `absolute` and sets the height dynamically rather than from the positioning.

For compatibility with the current twbs/bootstrap CSS, `$modal` will need to dynamically set the backdrop height and provide an equivalent to `.handleUpdate()` for dynamically updating the height.  However, there appears to have been quite a bit of fallout from this change, including twbs/bootstrap#15314, twbs/bootstrap#15136, twbs/bootstrap#15345, and the new requirement of calling `.handleUpdate()` when modal content changes described in twbs/bootstrap#15106.  So it may make sense to see how these are fixed and before diving in (in particular whether [fixed positioning returns with scrollbar-sized padding](https://github.com/twbs/bootstrap/issues/15136#issuecomment-63130202)).

The fix suggested by @alexander-konovalov works as long as the modal content height is not longer than the viewport height (if it is, the backdrop ends at the initial viewport bottom edge).  Setting `position: fixed` would avoid this (and mostly reverts the problematic commit) but would cause the behavior in twbs/bootstrap#14916.  To avoid this, I've been limiting the height of the .modal-content element of my modals and setting `overflow-y: auto` to move the scrollbar onto .modal-content.  Although it's not ideal for a number of reasons, it works for now.

**Comment by kevinoid** [comment] 2015-02-16 17:27
One additional update:  I just realized UI Bootstrap places .modal-backdrop outside of .modal (as Twitter Bootstrap did before twbs/bootstrap#14724).  So adding `bottom: 0` and `position: fixed` to `.modal-backdrop` should completely solve the issue (I think `position: fixed` is required if the modal extends below the end of the body content, but I haven't tested to be sure).  So a potential fix for UI Bootstrap would be to add these styles inline.

**Comment by Rutix** [comment] 2015-03-03 07:03
@kevinoid That sounds more like a workaround then a real fix though. A real fix, in my opinion, would be one where we don't deviate from the workings which Bootstrap uses. So making sure .modal-backdrop gets rendered inside of .modal.

**Comment by kevinoid** [comment] 2015-03-03 13:09
Actually, now that twbs/bootstrap#15881 has landed, Twitter Bootstrap has gone back to placing  .modal-backdrop outside of .modal and has re-added `bottom: 0` and `position: fixed`.  So this issue will be fixed with the next release of Twitter Bootstrap.  No changes to UI Bootstrap are required (unless I've overlooked something).

**Comment by bsweeney** [comment] 2015-03-11 23:03
Just passing through on my way to issue #2970.

**Comment by wesleycho** [comment] 2015-03-15 22:09
This looks like it's a Bootstrap issue with a simple temporary workaround - feel free to reopen this issue if there is more evidence that it should be fixed in UI Bootstrap.

**Closed by wesleycho** 2015-03-15 22:09 UTC
Labels: Bootstrap 3.3.1, component: modal, needs: investigation, type: bug

**Comment by evilaliv3** [comment] 2015-03-17 15:27
i confirm and the issue is solved in bootstrap 3.3.4
