### ISSUE TITLE
$uibModalStack.dismissAll() not closing modal

### ISSUE THREAD

**Issue by anshad** [angular-ui/bootstrap#5458] opened 2016-02-10 10:00 UTC
I have a snippet where I am using `$uibModalStack.dismissAll('closing');` for closing progress dialog modal. It worked in previous version with the code `$modalStack.dismissAll('closing');` and it's not working in new version. My bower dependency is `"angular-bootstrap": "^0.14.0"`

Entire snippet:
```
(function () {
    'use strict';

    angular
        .module('app')
            .factory('CommonFactory', ['$uibModal', '$uibModalStack', CommonFactory]);

    function CommonFactory($uibModal, $uibModalStack) {
        return {
            showSpinner: function (promise, message) {

                if (!_.isUndefined(promise.then)) {

                    var modalInstance = $uibModal.open({
                        animation: true,
                        templateUrl: "/dist/app/features/modals/progressModal.html",
                        controller: ["$scope", "$uibModalInstance", function ($scope, $uibModalInstance) {
                            $scope.message = message;
                        }],
                        windowClass: 'progressModal',
                        keyboard: false,
                        backdrop: 'static'
                    });

                    return promise
                        .then(function (success) {
                            $uibModalStack.dismissAll('closing');
                            return success;
                        }, function (error) {
                            $uibModalStack.dismissAll('closing');
                            return error;
                        });
                }
            }
        };
    }

})();
```

**Comment by icfantv** [comment] 2016-02-10 14:03
Hi, can you please reproduce this in a plunker?  This will easily allow us to see if it's still an issue in th latest build, 1.1.2

**Comment by wesleycho** [comment] 2016-02-11 15:01
This is probably a user error, as we have a unit test specifically for this situation.

**Comment by icfantv** [comment] 2016-02-11 16:25
Agreed.

**Comment by anshad** [comment] 2016-02-11 18:01
I will try to create a plunkr for the same. But did you see any issues with the above code?

**Comment by wesleycho** [comment] 2016-02-11 18:04
This is too time-consuming for us to try to predict what is wrong based on your code - it tells us nothing, and this issue tracker is not a technical support channel. Without the minimum required information as listed in https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md , this issue will be closed.

**Comment by wesleycho** [comment] 2016-02-15 08:19
Closing due to lack of actionable information, and likely a use issue.

**Closed by wesleycho** 2016-02-15 08:19 UTC
Labels: component: modal, needs: plunkr

**Comment by bhavikgarg** [comment] 2016-09-22 10:45
fvvfvfvfvf

**Comment by victorbadila** [comment] 2017-02-03 12:43
I have the same problem it seems.

I will create a plunkr later this weekend, but until now I have the following:
In one module I have

```
angular.module(...).run(() => {
  $transitions.onSuccess({}, (t) => {
    debugger
    $uibModalStack.dismissAll(); // automatically dismiss modals on state change
  });
})
```

and in another module that takes the former module as a dependency I open a uibModal and then navigate from it with `$state.go(someOtherState);`

The debugger in the code above gets hit, but the next line does nothing and there are no console errors. The modal stays on screen.

**Comment by Tharushashehan** [comment] 2017-03-07 13:21
Recently I came across with a similar issue. My case was a CSS attribute **Display:block.** when I turned that in to null. It worked perfectly. does a shadow of your modal stays in the page. that was my issue. Hope this info will help.

**Comment by sg28** [comment] 2018-05-30 19:12
use $uibModalInstance.close();
make sure to inject $uibModalInstance as dependency
