### ISSUE TITLE
RTL support in $position service

### ISSUE THREAD

**Issue by mevjak** [angular-ui/bootstrap#2811] opened 2014-10-09 14:08 UTC
I have an issue with Popover directive on page with RTL languages. Popover horizontal position is calculated incorrectly: 

![popover-ltr-rtl](https://cloud.githubusercontent.com/assets/3751330/4577503/0b506948-4fbd-11e4-8f88-abe28ac72032.png)

```
<a class="popover-info" popover-append-to-body="true" popover-trigger="click" popover-placement="left" popover="{{'settingsLoseProtection' | translate}}">Info</a>
```
Is RTL support missing in $position service?  Or is it needed to make some Popover template tweaks?

Thanks for any advice.

**Comment by blowsie** [comment] 2015-07-14 13:46
I noticed a similar issue in the datepicker
![image](https://cloud.githubusercontent.com/assets/308572/8674633/11e547ba-2a37-11e5-948a-b4c6af624db3.png)

**Comment by georgybu** [comment] 2015-07-16 07:50
duplicate discussion: https://github.com/angular-ui/bootstrap/issues/3151

**Comment by deeg** [comment] 2015-10-26 16:29
+1 for adding RTL support.

Is this something you guys are still considering adding in?

**Comment by icfantv** [comment] 2015-10-28 15:50
Closing in favor of #4762.

**Closed by icfantv** 2015-10-28 15:50 UTC
Labels: component: $position, component: tooltip, needs: investigation, type: bug

**Comment by evilaliv3** [comment] 2016-04-04 00:56
the fix of @mevjak mixed with the following would probably help:

```javascript
var dir = document.documentElement.dir;
if (dir === 'rtl') {
   return x;
} else {
   return z;
}
```

this way depending on ```<html dir=rtl/ltr>``` all will work automagically and the dir attribrut could be changed at runtime by a possible language selector.

**Comment by evilaliv3** [comment] 2016-08-27 09:18
Any new on this ticket?

I really makes the library not usable for RTL projects :(

https://github.com/globaleaks/GlobaLeaks/issues/1755

**Comment by blowsie** [comment] 2016-08-30 09:48
@evilaliv3 I used this, alongside some custom glyphicon > font-awesom less mapping (possibly one or two other fixes) and everything works a charm.

https://github.com/morteza/bootstrap-rtl

**Comment by evilaliv3** [comment] 2016-08-30 21:43
thanks @blowsie 

i'm already using https://github.com/MohammadYounes/RTL-bootstrap but the issue is in mixing it with the javascript provided by angular-ui
