### ISSUE TITLE
tooltip-html is confusing

### ISSUE THREAD

**Issue by oliversalzburg** [angular-ui/bootstrap#3790] opened 2015-06-10 10:55 UTC
I use `tooltip-html-unsafe` in our code. Now I get a deprecation warning:

> tooltip-html-unsafe is now deprecated. Use tooltip-html or tooltip-template instead.

The results are still fine, but I thought I give `tooltip-html` a try. [The documentation](http://angular-ui.github.io/bootstrap/#/tooltip) doesn't mention `tooltip-html`, so I assumed that its interface is identical to `tooltip-html-unsafe` and I simply removed the `-unsafe` part from our usage.

Now I get an uncaught error:

```
Uncaught Error: [$parse:syntax] Syntax Error: Token 'Abbott' is an unexpected token at column 9 of the expression [Kenneth Abbott ist momentan anwesend.] starting at [Abbott ist momentan anwesend.].

http://errors.angularjs.org/1.3.15/$parse/syntax?p0=Abbott&p1=is%20an%20une…0Abbott%20ist%20momentan%20anwesend.&p4=Abbott%20ist%20momentan%20anwesend.REGEX_STRING_REGEXP @ angular.js:63
Parser.throwError @ angular.js:12070
Parser.parse @ angular.js:12023
$parse @ angular.js:12737
$get.Scope.$eval @ angular.js:14466
$get.compile.ttScope.contentExp @ ui-bootstrap-tpls.js:2915
show @ ui-bootstrap-tpls.js:2827
showTooltipBind @ ui-bootstrap-tpls.js:2804
jQuery.each.jQuery.event.special.(anonymous function).handle @ jquery.js:4765
jQuery.event.dispatch @ jquery.js:4435
jQuery.event.add.elemData.handle @ jquery.js:4121
```

**Comment by rvanbaalen** [comment] 2015-06-10 14:17
We can't help you out without a plunkr that reproduces your problem.

**Comment by oliversalzburg** [comment] 2015-06-10 14:23
You need a plunker to make a judgement call regarding the interface of a component? Alright, I'll whip one up.

**Comment by oliversalzburg** [comment] 2015-06-10 14:29
http://plnkr.co/edit/6nPdNOFpPju2YTEVGuY3?p=preview

**Comment by wesleycho** [comment] 2015-06-10 14:57
The reason we ask for a Plunker is because it verifies that it is indeed an issue, and it allows us to debug the issue thoroughly - unfortunately we can't read minds, so having a reproducible scenario is the next best thing.

**Comment by wesleycho** [comment] 2015-06-10 15:17
This actually appears to be just a confusion with usage.

[Here](http://plnkr.co/edit/v4NQXJjNDuyjl4agjtA0?p=preview) is a working version of your Plunker.

This does need to be documented better though.

**Comment by wesleycho** [comment] 2015-06-10 15:19
Actually, looking at the documentation, there is a working example in https://github.com/angular-ui/bootstrap/blob/master/src/tooltip/docs/demo.html .

I am closing this as this appears to be a usage issue.

I hope my example helps!

**Closed by wesleycho** 2015-06-10 15:19 UTC
Labels: component: tooltip

**Comment by oliversalzburg** [comment] 2015-06-10 15:27
@wesleycho That does indeed help. Thanks.

**Comment by koryhopkins** [comment] 2015-07-17 16:31
Does the tooltip-html not work with functions?  In this plunker I have one tooltip-html use a variable and that works.  I have a tooltip use a function and that works.  But, if I try a tooltip-html with a function it does not work.

http://plnkr.co/edit/RnA1KF4DfpYLxd0lWKUd?p=preview

**Comment by Quirksmode** [comment] 2015-07-30 07:08
I also have this warning message appearing in my console and I am not even using tooltips, I have simply imported the full Bootstrap UI library during dev. I only use it for modals and the warning still shows
