### ISSUE TITLE
The accordion directive should offer a callback?

### ISSUE THREAD

**Issue by joshkurz** [angular-ui/bootstrap#2217] opened 2014-05-18 18:14 UTC
It seems that the tabs and accordion directives are similar. They each hide and show DOM. The tabs directives offers a callback function that is very useful. 

Should the accordion directive offer this same functionality?

**Comment by wesleycho** [comment] 2015-09-11 01:26
Closing as a duplicate of #1685

**Closed by wesleycho** 2015-09-11 01:26 UTC
Labels: component: accordion, type: enhancement
