### ISSUE TITLE
$uibModal is not defined

### ISSUE THREAD

**Issue by tiagoovieira** [angular-ui/bootstrap#4603] opened 2015-10-13 12:18 UTC
I'm getting an `$uibModal is not defined` 

In my app.js file:

`angular.module('myApp', ['ngRoute', 'ngCookies', 'ngFileUpload', 'ngAnimate', 'ui.bootstrap'])` 
I'm including the ui.bootstrap

and in my controller

`angular.module('myApp').controller('ShowArticleCtrl', [
  '$scope', '$location', 'article', 'user', '$routeParams', '$uibModal',`

when I click on the open modal button I get a $uibModal is not defined

**Comment by pkozlowski-opensource** [comment] 2015-10-13 12:28
What is the version of the library that you are using? `$uibModal` was renamed from `$modal` only recently: https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md#0140-2015-10-09

**Comment by tiagoovieira** [comment] 2015-10-13 12:31
I'm using the 0.14.1

**Comment by Foxandxss** [comment] 2015-10-13 13:07
It should work. Check the demo on our website and see how it works. Your problem is elsewhere.

Are you sure you updated to 0.14.1?

**Comment by wesleycho** [comment] 2015-10-13 17:13
This needs a reproduction - the demo Plunker works, as can be seen [here](http://plnkr.co/edit/KeAKh9nspW3GNX4hsZLX?p=preview).

**Comment by mtraynham** [comment] 2015-10-13 19:43
I get a similar problem with the $uibModal not working.  It's because I'm uglifying the library and get the following error:
```
Error: [$injector:unpr] Unknown provider: fProvider <- f
http://errors.angularjs.org/1.4.7/$injector/unpr?p0=fProvider%20%3C-%20f
```

**Comment by Foxandxss** [comment] 2015-10-13 19:46
@mtraynham We are pretty strict with our minification. Could you try the .min version we provide and see if it fails? Or perhaps that comes from your own code?

**Comment by mtraynham** [comment] 2015-10-13 19:52
@Foxandxss Well it works with the distributed minified version, but if I do any minification (such as using wiredep) on my side it breaks.

**Comment by mtraynham** [comment] 2015-10-13 19:58
Interestingly enough, if I switch my small app's code back to using `$modal` instead of `$uibModal`, works fine.

**Comment by wesleycho** [comment] 2015-10-13 20:35
I'm not seeing anything particular wrong in the `$uibModal` code - the only thing different is the injection of the `$uibModalStack` string and consuming it as a `$modalStack` argument, but that should not be the culprit.

**Comment by mtraynham** [comment] 2015-10-13 21:09
Found the issue, may not be related to OP.  Old $modal always passed `$scope`, `$modalInstance` as the parameters to the controller.  New one doesn't.

**Comment by pkozlowski-opensource** [comment] 2015-10-13 21:14
@mtraynham it always used di, afaik...

**Comment by mtraynham** [comment] 2015-10-13 21:18
@pkozlowski-opensource You might be right, although something changed as the following used to work after minification.  I've added the necessary `/*ngInject*/` to fix it:
```
$modal.open({
    templateUrl: ...
    controller: function ($scope, $modalInstance) {
    }
});
```

**Comment by tiagoovieira** [comment] 2015-10-14 10:49
@wesleycho here is the [plunk] (http://plnkr.co/edit/qzzCLYkEbHpJjW82teJE?p=preview) 
It looks like a dependency issue

**Comment by Foxandxss** [comment] 2015-10-14 10:52
@tiagoovieira $uibModal es 0.14.0+. That plunk is using 0.13.3.

I am closing this out.

**Closed by Foxandxss** 2015-10-14 10:52 UTC
Labels: component: modal, needs: info, needs: investigation, needs: plunkr

**Comment by tiagoovieira** [comment] 2015-10-14 10:57
actually plunk doesn't have access to angular-ui-bootstrap more recent than 0.13.3. But what I'm using is 0.14.1
![screen shot 2015-10-14 at 11 57 04 am](https://cloud.githubusercontent.com/assets/3091256/10481751/bfd7cf5c-726a-11e5-8713-54742cc00560.png)

**Comment by Foxandxss** [comment] 2015-10-14 11:01
You can manually put 0.14.1 in the URL that loads it. Your plunker has like loots of errors apart from bootstrap.

**Comment by tiagoovieira** [comment] 2015-10-14 11:13
@Foxandxss I updated the plunkr, please let me know what errors might still persist.

**Comment by Foxandxss** [comment] 2015-10-14 11:16
Save it or share the new link (if it changed). I still see the old one.

**Comment by tiagoovieira** [comment] 2015-10-14 11:17
my bad, [here it is] (http://plnkr.co/edit/qzzCLYkEbHpJjW82teJE?p=preview)

**Comment by Foxandxss** [comment] 2015-10-14 11:22
Your plunker needs:

Proper ng-app tag.
Use a controller in template
Not load jquery nor bootstrap.js (they are not needed at all)
Load app.js as script tag.
Fix your array syntax to load dependencies (they are not in sync with controller parameters)
Fix the controller that you're using for the modal.

With that, you can see that it works.

**Comment by tiagoovieira** [comment] 2015-10-14 11:33
@Foxandxss it seems to be partially working, but it doesn't display the modal. Locally I get an `Error: [$compile:tpload] Failed to load template: modal_conversation.html (HTTP status: 404 Not Found)`

**Comment by Foxandxss** [comment] 2015-10-14 11:38
http://plnkr.co/edit/roTslCwkpewbp7nJ3Pea?p=preview

**Comment by tiagoovieira** [comment] 2015-10-14 14:35
Odd thing. It works, but only after clicking the second time on the button to open up the modal.

**Comment by Foxandxss** [comment] 2015-10-14 14:46
You probably need to cache your template first, plunker is not doing that.

**Comment by tiagoovieira** [comment] 2015-10-14 15:04
you mean by adding `<script type="text/ng-template" id="template.html">` to the modal?

**Comment by Foxandxss** [comment] 2015-10-14 15:08
No, not exactly. http://plnkr.co/edit/wxNn5445S2Eqk23ZORG6?p=preview

**Comment by tiagoovieira** [comment] 2015-10-14 15:36
:+1:  cool, it's working :smiley:

**Comment by agupta1989** [comment] 2015-10-21 10:52
@pkozlowski-opensource Thanks ! I was using old build.

**Comment by pykiss** [comment] 2015-10-28 15:00
@mtraynham 
I have the same problem.

How do you solve it?

**Comment by icfantv** [comment] 2015-10-28 15:16
@mtraynham, you might try again with the latest version of the code or a build off of `master` which has had all the deprecation warnings removed.

**Comment by mtraynham** [comment] 2015-10-28 15:52
@icfantv I was able to resolve the issue on an earlier build, thanks though!

@pykiss I was creating my `$modal` controller's incorrectly in the following way:
```
var modalInstance = $modal.open({
    templateUrl: 'templates/messagedialog.tpl.html',
    controller: function ($scope, $modalInstance) {
```
After minification, the controller would look like:
```
var a = b.open({
    templateUrl: 'templates/messagedialog.tpl.html',
    controller: function (c, d) {
```
For some reason (as I was obviously doing this wrong before hand), `$modal` worked properly with `c` & `d` being mapped to `$scope` & `$modalInstance`, respectively.  After the upgrade to `$uibModal`, this was no longer the case as angular was looking to inject `c` which is not a valid injection.
My fix was to add the [necessary minification annotations](http://jerodsanto.net/2013/08/you-dont-have-to-annotate-your-angularjs-injections-anymore/) to the controller which would properly inject `$scope` and `$modalInstance`.  Or use [ngAnnotate](https://github.com/olov/ng-annotate) which does that for you:
```
var modalInstance = $modal.open({
    templateUrl: 'templates/messagedialog.tpl.html',
    controller: /*@ngInject*/ function ($scope, $modalInstance) {
```

**Comment by icfantv** [comment] 2015-10-28 16:41
Good deal, thanks.

**Comment by SaadBinShahid** [comment] 2015-11-09 14:24
I had the same issue with exact same error. I just replaced my old file with the latest one; ui-bootstrap-tpls-0.14.3.min.js... No more error ! [Solved]

**Comment by bob-lee** [comment] 2016-02-12 00:23
Had similar inject error for $uibModal after upgrading from 0.14.3 to 1.1.2.
Some pages were working but some were not.
The reason was not injecting 'ngAnimate' into the app module.

**Comment by csulok** [comment] 2016-04-29 13:19
Leaving this comment here for the future: had a similar issue, basically I had to upgrade ng-annotate to v1.1+ which includes fixes for $modal -> $uibModal change, otherwise it doesn't recognize the ModalInstanceController functions... $scope and $uibModalInstance aren't recognized there.

**Comment by icfantv** [comment] 2016-04-29 16:59
@csulok, IMO relying on a third-party library to keep UIBS and your code happy is a recipe for lots of unhappiness.  While the angular team does not specifically say using a third-party strictDi library like ng-annotate is bad - as you and others have found out, doing so can be cause for grief.

**Comment by csulok** [comment] 2016-04-29 17:52
You're quite right. ng-annotate is a trade-off between correctness and convenience. Perhaps it takes 1-2 cases like this for that to be understood though. For me certainly.
