### ISSUE TITLE
Tooltip causing scroll bars to quickly show

### ISSUE THREAD

**Issue by jfarago** [angular-ui/bootstrap#4458] opened 2015-09-23 18:04 UTC
[Plunk](http://plnkr.co/edit/HdHyjJ?p=preview)

Resize the window so it comes up almost to the bottom of the button. Constantly move back and forth over the button to trigger the tool tip. Notice the scroll bar briefly showing sometimes.

**Comment by njoy-codilime** [comment] 2015-09-28 12:03
Yeah, please fix it :(

**Comment by pkozlowski-opensource** [comment] 2015-09-28 12:18
> Yeah, please fix it :(

@njoy-codilime we would love to have your pull request that fixes this issue. We very much appreciate all the help we can get. Thnx!

**Comment by RobJacobs** [comment] 2015-09-28 15:53
This is fixed in master under PR #4195.  Please let us now if you can replicate the issue using the latest build from master and I will re-open the issue.

**Comment by RobJacobs** [comment] 2015-09-28 16:04
This issue is fixed in master under PR #4195.  Let me know if you can reproduce the issue with the latest build from master and I wil -re-open the issue.

**Comment by jfarago** [comment] 2015-09-28 19:55
It is still happening but far less often

**Comment by icfantv** [comment] 2015-09-28 20:05
I can't reproduce this in chrome.  This also smells like a positioning issue.  What happens if you set `overflow: hidden` on the parent element?  Does it still happen?

Also, what use case are you applying when you "move the cursor back and forth over the button to trigger the tooltip?"  I'm trying to think of a normal user scenario where this would apply.

**Comment by RobJacobs** [comment] 2015-09-28 21:47
Here is an updated [plunk](http://plnkr.co/edit/765sij90xdVnH0R3yyg3?p=preview) with the latest from master.  I'm not seeing the problem with this version...

**Comment by jfarago** [comment] 2015-09-28 23:45
It is defiantly a positioning issue, if i move back and forth over the button with a tool tip over and over every once and awhile i will see the tooltip briefly show underneath which is moving outside the viewport. I just tried the plunker and am not seeing the issue. I will be sure to grab the latest tomorrow when i get to work and try it again. I appreciate your quick responses.

**Comment by icfantv** [comment] 2015-09-28 23:46
Souds good @jfarago, please keep us posted.  Thanks.

**Comment by jfarago** [comment] 2015-09-29 12:13
@icfantv I have confirmed that is no longer an issue, thanks again.

**Comment by RobJacobs** [comment] 2015-09-29 14:32
You would need to clone the repository to your local machine, then run 'npm install', then run 'grunt' and the compiled files will show up in the dist folder.  You could also copy the contents of the bootstrap-ui.js files in the plunk I created as that is a build from master as of yesterday.

**Comment by icfantv** [comment] 2015-09-29 16:33
@jfarago cool, thanks.

**Comment by jfarago** [comment] 2015-09-30 15:51
@RobJacobs & @icfantv  i updated my project with a build from today and the problem is back. Here is a [plunk.](http://plnkr.co/edit/HdHyjJ?p=preview)

**Comment by icfantv** [comment] 2015-09-30 15:59
@jfarago, any particular reason you're including UI Bootstrap twice?  I'm also not seeing that this is a SNAPSHOT build from `master`.

**Comment by jfarago** [comment] 2015-09-30 17:11
@icfantv including it twice was an accident. To get the latest I downloaded the project and did a build myself.

**Comment by icfantv** [comment] 2015-09-30 17:31
I'm a little confused.  When we do SNAPSHOT builds, the header indicates thus as follows:
```
foo at bar in ~/source/oss/forks/bootstrap/dist on tabs_prefix
± head ui-bootstrap-tpls-0.14.0-SNAPSHOT.js
/*
 * angular-ui-bootstrap
 * http://angular-ui.github.io/bootstrap/

 * Version: 0.14.0-SNAPSHOT - 2015-09-30
 * License: MIT
 */
```

**Comment by jfarago** [comment] 2015-09-30 17:33
I dont know how you generate a snapshot build. I followed the directions that @RobJacobs provided above.

"You would need to clone the repository to your local machine, then run npm install and then run grunt. The the compiled files will show up in the dist folder.

You could also copy the contents of the bootstrap-ui.js files in the plunk I created as that is a build from master as of yesterday."

**Comment by icfantv** [comment] 2015-09-30 18:01
So, I'm assuming you just did the latter?  Humor me please, and do a command-line build.  Note that those instructions assume you have grunt installed via the `-g` flag.

**Comment by jfarago** [comment] 2015-09-30 18:13
I actually did the former

**Comment by icfantv** [comment] 2015-09-30 18:20
I'm not sure how you're doing your builds then because you should be getting the SNAPSHOT version in the header - if you're only seeing 0.14.0 without the SNAPSHOT, that seems to indicate you're building the 0.14.0 release version and not the latest from `master`.

Please try the attached file (rename to JS as apparently GitHub doesn't support the .js extension) and let us know.  Also, you haven't answered my question about use case.  What use case are you covering when you move the cursor rapidly over an item with a tooltip/popover?  I would argue that this is not a normal scenario.

[ui-bootstrap-tpls-0.14.0-SNAPSHOT.txt](https://github.com/angular-ui/bootstrap/files/5430/ui-bootstrap-tpls-0.14.0-SNAPSHOT.txt)

**Comment by jfarago** [comment] 2015-09-30 18:29
Thanks, i will look into why i am not building the latest. To answer your question, there is not a use case for rapidly moving over an item, that was just a quick way to see it happen. The scroll bars are popping up only sometimes when you move over the item. I updated the [plunk](http://plnkr.co/edit/HdHyjJ?p=preview) with the code you provided and the problem persists.

**Comment by icfantv** [comment] 2015-09-30 18:47
Ok.  This is such a corner case, I can't promise that we'll be able to do anything about it.

**Comment by jfarago** [comment] 2015-09-30 19:37
Okay, I appreciate you looking into this. When a control with a tooltip is on the bottom of a page it displays the scroll bars somewhat consistently but I am assuming most pages dont have controls that close to the viewport.

**Comment by icfantv** [comment] 2015-09-30 19:42
You're welcome and sorry we couldn't do more easily.  I would agree that having controls that close to the bottom of the viewport is probably not typical.  Additionally, since angular is designed for single paged apps, one could also argue that scrolling is not needed/desired for the entire viewport.  If this is the case, you _might_ consider setting `overflow: hidden` on `<body>` and that would certainly prevent the scrollbars from showing.

Also, having smart positioning on the tooltips/popovers should, in theory, also rectify this.  However, we don't have smart positioning.  It's something we are considering for NG2 support w/ BS4 via an implementable interface (so one could plug in something like Tether) - but that's only an idea on the roadmap at this point.

**Comment by simonstiphanos** [comment] 2015-10-01 22:43
I can confirm this issue also on build 0.13.4 on Chrome 45. Since my app requires vertical scrolling, I also cannot use the overflow fix on <body>. I can also confirm the issue is not present in 0.13.3.

BTW this is occuring with the tooltip placed on a tag at both the top and the middle of the page. Haven't been able to conjure a solution yet, though.

**Comment by jfarago** [comment] 2015-10-02 13:34
@icfantv I understand this is not high on your priority list but can you open the bug?

**Comment by icfantv** [comment] 2015-10-02 15:05
Yes.

**Comment by cassilup** [comment] 2015-10-08 13:33
Found out that Angular's digest cycle is sometimes causing a delay between the moment the tooltip element is added to the DOM and the moment that it is correctly positioned. Discovered that if the tooltip is hidden by default (`display: none`) and only displayed once it is positioned (`display: block`), the bug goes away.

**Comment by RobJacobs** [comment] 2015-10-14 17:49
Suggested fix is to add top: -9999px and left: -9999px to the tooltip template style [here](https://github.com/angular-ui/bootstrap/blob/master/src/tooltip/tooltip.js#L126).  Updated [plunk](http://plnkr.co/edit/B54wQI?p=preview) that shows the results.

**Closed** 2015-10-14 20:28 UTC
Labels: component: tooltip, needs: investigation, PRs plz!

**Comment by armanforghani** [comment] 2016-12-25 12:12
This issue persists in RTL direction.
This can be for fixing with ```top: -9999px and left: -9999px```. This hack does not work and should not be used for RTL pages.
