### ISSUE TITLE
Autofocus no longer working in modal

### ISSUE THREAD

**Issue by haquex19** [angular-ui/bootstrap#6333] opened 2016-11-23 21:10 UTC
### Bug description:

Starting with the newest release (2.2.0) the autofocus attribute is no longer working. I have a modal window that has a few form elements including a button and an input field. I add the autofocus attribute to the input field and it does not focus. This was working correctly in version 2.1.4

### Link to minimally-working plunker that reproduces the issue:

https://plnkr.co/edit/PQMmKv4BpW6rXuF4T5OR?p=preview

Notice how the button is focused, whereas the input field should be focused since it is the one with the autofocus attribute

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.8

UIBS: 2.2.0

Bootstrap: 3.3.7

**Comment by pkozlowski-opensource** [comment] 2016-11-23 21:25
Duplicate of #6289

**Closed by pkozlowski-opensource** 2016-11-23 21:25 UTC
