### ISSUE TITLE
*-append-to-body rendering performance when set to true/false

### ISSUE THREAD

**Issue by wiibaa** [angular-ui/bootstrap#6198] opened 2016-08-23 13:20 UTC
Hi, "asking the experts" out of curiosity

I was wondering why append-to-body default value is false when eventually setting it to true globally would fix sometimes more problem for starters without bringing evident drawbacks. 

Can it be related to DOM or even Angular internals and performances ?

**Comment by wesleycho** [comment] 2016-08-23 16:03
Can you be more specific about what component and situation you mean (ideally with minimal reproduction in Plunker)?

**Comment by RobJacobs** [comment] 2016-08-23 20:25
Depending on which component you are talking about, it will not scroll with the target element.

**Comment by wiibaa** [comment] 2016-08-24 03:59
To say it differently, when a component renders correctly in both cases *append-to-body=true* or *append-to-body=false* should one be the preferred ? and why ? 
In my specific use case, I intend to use lot of tooltip in a table or listing and I'm wondering about rendering impact like "DOM reflow" that could be different but don't known how to benchmark it

**Comment by wesleycho** [comment] 2016-08-24 14:18
The main purpose of using a feature such as `append-to-body` is to avoid some CSS bugs which can cause the appended element to cut off in appearance to the user. It does do some DOM style computation in order to calculate how to position the element in both cases, although I would suspect the `append-to-body` computation to be more expensive in style calculation. I believe the tooltip causing reflow would be minimal because it should be absolutely positioned.

Note that these are somewhat educated conjectures based on my knowledge of how the tooltip works, one should do a deep dive into the source/profile them otherwise.

Going to close this as a support issue.

**Closed by wesleycho** 2016-08-24 14:18 UTC

**Comment by wiibaa** [comment] 2016-08-24 14:32
@wesleycho Thanks for sharing your thoughts and time involved
