### ISSUE TITLE
In DatePicker, date's prototype become invalid if we don't initialize it on page. 

### ISSUE THREAD

**Issue by ashishpce29** [angular-ui/bootstrap#3420] opened 2015-03-23 04:38 UTC
When we don't initialize the date variable on the page. Then the generated date object by datepicker shows the proto type  as "Invalid Date". 

So when i send this date in a object to server. It changes the time zone of date.

**Comment by wesleycho** [comment] 2015-03-23 04:52
Can you create a [Plunker](http://plnkr.co/) reproducing this?

**Comment by RobJacobs** [comment] 2015-03-23 17:28
@ashishpce29  @wesleycho I think there may be some confusion as to what is setting the date prototype toString method to return Invalid date.  I set up a [plunk](http://plnkr.co/edit/8ZOqPRUESFwoqleMp1Ei?p=preview) that demonstrates using console.log the date prototype values.  As you can see, the testDate that does not get touched by the datepicker directive at all, still logs the prototype as Invalid Date.

**Comment by chrisirhc** [comment] 2015-03-23 17:34
Logging the prototype shouldn't be meaningful, because it'll attempt to use a value that isn't there (hence, invalid).

**Comment by wesleycho** [comment] 2015-08-06 07:08
Closing this issue due to lack of actionable information or reproduction.

**Closed by wesleycho** 2015-08-06 07:08 UTC
Labels: component: datepicker, needs: info, resolution: no info
