### ISSUE TITLE
the translate down animation when modal appears doesn't always work

### ISSUE THREAD

**Issue by github-libra** [angular-ui/bootstrap#4472] opened 2015-09-25 07:59 UTC
from the official site, I can see that,about the modal module, the first modal opens with little slide down transition, but the second doesn't. I am wondering why? is there any way to make it consistent?

**Comment by wesleycho** [comment] 2015-09-28 04:41
Closing as a duplicate of #4263

**Closed by wesleycho** 2015-09-28 04:41 UTC
