### ISSUE TITLE
Adding Tooltips to Radio Buttons Allows Multiple Buttons in Group to Appear Active

### ISSUE THREAD

**Issue by dustymiller** [angular-ui/bootstrap#3220] opened 2015-01-23 16:50 UTC
If you put the tooltip directive on each button acting as a radio button in a group, clicking the button does not cause the other buttons in the radio button group to be deselected, and therefor it appears that multiple radio buttons in the group are selected.  It appears that the "active" css class is being added to the button that was clicked but not removed from the other buttons in the group.  When the tooltip directive is removed, the "active" css class is added and removed as expected.  My tooltip directive options are:

tooltip="string"
tooltip-add-to-body="true"
tooltip-placement="right"
tooltip-trigger="mouseenter"

![image](https://cloud.githubusercontent.com/assets/1385228/5878566/de856c88-a2f5-11e4-97ff-98d2db0d3f36.png)

![image](https://cloud.githubusercontent.com/assets/1385228/5878588/10495a9a-a2f6-11e4-9d10-29fc9cbfcd77.png)

**Comment by karianna** [comment] 2015-01-23 18:39
@dustymiller - can you provide a plunkr to show the problem?

**Comment by bendrexl** [comment] 2015-03-12 17:11
Seeing same symptoms with ng-repeat:

http://plnkr.co/edit/osjEffTA6zZvheaXYGhz?p=preview

**Comment by wesleycho** [comment] 2015-08-01 05:08
This appears to be unrelated to a tooltip then, as far as I can see based on `master` [here](http://plnkr.co/edit/EWAwbNb8PSbZ9QcFcbqN?p=preview).

**Comment by icfantv** [comment] 2015-08-01 06:32
As previously mentioned, the tooltips appear to be a red herring.  The issue appears to be the `ng-repeat`.  A first crack at debugging this appears that the `scope.$eval` calls are the culprit:

https://github.com/angular-ui/bootstrap/blob/42e1af5c606b2f623f37c56bbfb37aad2c936527/src/buttons/buttons.js#L22
https://github.com/angular-ui/bootstrap/blob/42e1af5c606b2f623f37c56bbfb37aad2c936527/src/buttons/buttons.js#L35

When the value of `btn-radio` is an expression, that call is returning `undefined` and clearing out the model data.  It also has the effect of preventing the buttons from being initialized to a given state.  @wesleycho mentioned possibly turning this into a `$parse` function.

**Comment by icfantv** [comment] 2015-08-01 14:02
I think I've found a solution, or at least the start of one.  I'll play with it more later and write some tests.  We'd need to add something similar to the `btnRadio` directive's linker:
```
var modelParser = $parse('btnRadio');
function parseValue() {
  var parsed = modelParser(attrs);
  return scope.$eval(parsed) || parsed;
}
```
and change the `scope.$eval(attrs.btnRadio)` call to `parseValue()`.

**Comment by wesleycho** [comment] 2015-08-02 07:08
Doing some more investigation, we should disallow interpolation for `btn-radio` - it already accepts angular expressions, there is absolutely no reason for an interpolation there.

**Comment by wesleycho** [comment] 2015-08-02 07:26
Closing as not an issue - since it already accepts an expression, the proper usage would be like [this](http://plnkr.co/edit/slPZtXzu30iGTlCcZeZP?p=preview).

If there is any particular issue with reproduction, feel free to open a new issue.

**Closed by wesleycho** 2015-08-02 07:26 UTC
Labels: component: tooltip, PRs plz!, type: bug
