### ISSUE TITLE
Modal without controller, but with directive/component as template

### ISSUE THREAD

**Issue by jeserkin** [angular-ui/bootstrap#6162] opened 2016-08-15 22:23 UTC
### Feature request description:
As far as I can tell, it is not supported at the moment. Current solution requires controller to be specified to manage/work with `$uibModalInstance`. But if one would take component approach, then modal template could be a component or directive of type `'E'`, that can already have a direct cotroller bind to it.

Would be nice to have a way to pass/get `$uibModalInstance` inside this component to mange current modal.

### Link to an approach, that would be nice to have:
http://jsbin.com/rimexuf/2/edit?html,js,output

### Version of Angular, UIBS, and Bootstrap

Angular: 1.4.9

UIBS: 0.14.3

Bootstrap: 3.3.6

**Comment by wesleycho** [comment] 2016-08-15 23:05
Closing as a duplicate of #5683 :)

**Closed by wesleycho** 2016-08-15 23:05 UTC
