### ISSUE TITLE
Carousel slides in wrong order

### ISSUE THREAD

**Issue by mikefrey** [angular-ui/bootstrap#5731] opened 2016-04-03 23:42 UTC
Essentially this is the same bug as #3764
A carousel with 13 or more items will not cycle through the items in order.

Plunkr: http://plnkr.co/edit/Tom4ECLK6uxF3d5cUNda?p=preview

Angular 1.5.3
UIBS 1.2.5
Bootstrap 3.2

**Comment by wesleycho** [comment] 2016-04-04 00:38
Closing as fixed by 434c1c595b48103460194ac5df7f16e272c41906, and duplicate of #5638

**Closed by wesleycho** 2016-04-04 00:38 UTC
