### ISSUE TITLE
Typeahead Doesn't Work With NgModelOptions

### ISSUE THREAD

**Issue by kmccullough** [angular-ui/bootstrap#3258] opened 2015-02-05 03:31 UTC
As demonstrated in [this plunker](http://plnkr.co/edit/6pDRf5aWxegOEqQRUn0Y?p=preview), typeahead doesn't work with ng-model-options="{ updateOn: 'blur' }". Type a "1" into each of the fields to see the behavior. The top field's typeahead works fine, but the others use validation on blur and the typeahead doesn't appear at all, until the field loses focus.

**Comment by pkarikh** [comment] 2015-04-14 15:34
Any updates about this issue? I've got the same prbolem while trying to use ng-model-options ans angular getterSetter feature. Looks like typeahead knows nothing about `ng-model-options` directive.

I've inspected typeahead's code (version 0.12.1) and as far as I understand, typeahead doesn't use `ng-model-options` at all. Am I right?

Also, if there are any patches or workarounds for it, I would be glad to be informed.

**Comment by akholodenko** [comment] 2015-05-01 00:29
Same issue. trying ng-model-options on typeahead field for onBlur model update and no typeahead showing.

**Comment by mattvague** [comment] 2015-06-03 22:12
Would be nice if `debounce` was supported as well

**Comment by pkarikh** [comment] 2015-06-16 08:44
I've tried `ng-model-options="{getterSetter: true, debounce: 5000}"` and debounce time has been changed to 5 seconds (and getterSetter was not applied). So, looks like some optrions of ngModelOptions are supported (but I have not found anything about debounce support in sources), and some - not. Since ngModelOptions is angularjs feture, my gues is in some cases typeahead shadows ngModelOptions values. Ans in some - not.
I've posted a bug about `getterSetter` option here: https://github.com/angular-ui/bootstrap/issues/3823

**Comment by stijnherreman** [comment] 2015-11-25 10:24
The problem is that typeahead plugs into the `$parsers` pipeline, so it only executes when the `ng-model` value changes. It would need to use the form value instead, but perhaps that's undesirable as well because it could break other things.

**Comment by wesleycho** [comment] 2015-11-30 14:47
Closing this in favor of #4981.

**Closed by wesleycho** 2015-11-30 14:47 UTC
Labels: component: typeahead, type: enhancement

**Comment by noah2233** [comment] 2017-08-13 05:57
Any updates on this issue? do you know any good work around?
