### ISSUE TITLE
uib-popover unexpectedly closes with "outsideClick" and uib-datepicker

### ISSUE THREAD

**Issue by Luxor001** [angular-ui/bootstrap#5979] opened 2016-06-10 09:34 UTC
### Bug description: 
popover unexpectedly closes with popover-template, "outsideClick" trigger and a datepicker in it: in fact, the popover unexpectedly closes when clicking on the datepicker itself.
Closing issue comes on the second click of the datepicker, not the first one: this seems to be related to a bug present in function "bodyHideTooltipBind", precisely in condition

> if (!element[0].contains(e.target) && !tooltip[0].contains(e.target)) {
                hideTooltipBind();
              }

(reference of e.target seems broken while clicking the second time; also, the datepickers seems to "split" itself when clicking the first time, if you put a breakpoint on the condition. Maybe it's a related issue?).

### Link to minimally-working plunker that reproduces the issue: 
http://plnkr.co/edit/ESto8dgDbh52g0nl7g03?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.3

UIBS: 1.3.3

Bootstrap: 3.3.6

It's my first issue report ever, so please contact me for any additional information you might need.

**Comment by icfantv** [comment] 2016-06-10 15:00
@Luxor001 please extend us the courtesy of searching both open and closed issues prior to entering anything.  This is a duplicate of #5628.

**Closed by icfantv** 2016-06-10 15:00 UTC

**Comment by Luxor001** [comment] 2016-06-10 15:29
@icfantv thanks a lot. I'm sorry for the duplicate entry: i'll keep in mind to search more deeply next time.
