### ISSUE TITLE
Popover should appear on load when popover-is-open="true"

### ISSUE THREAD

**Issue by csymeonides** [angular-ui/bootstrap#4264] opened 2015-08-24 15:14 UTC
Trying to make a popover appear as soon as page loads. It seemed like this can be achieved by setting popover-is-open="true" but it doesn't work. [Plunker](http://plnkr.co/ELIoqLMlIGNOcZSkCUrg)

**Comment by icfantv** [comment] 2015-08-24 15:40
@csymeonides this is not yet supported:  https://github.com/angular-ui/bootstrap/blob/master/src/tooltip/tooltip.js#L151-L153

**Comment by csymeonides** [comment] 2015-08-24 16:12
Thanks for clarifying - any idea if there's a temporary workaround?

**Comment by icfantv** [comment] 2015-08-24 16:24
I just remembered that I'm pretty sure we implemented this in #590.  Try using the master branch in your plunker and not the 0.13.3 release.

**Comment by icfantv** [comment] 2015-08-24 16:31
Yea, this is fixed in the 0.13.4-SNAPSHOT and will be released soon.  See [this plunker](http://plnkr.co/edit/DMqpDWJyRgDRPRbYr1Mx) for the code.

**Closed by icfantv** 2015-08-24 16:31 UTC
Labels: component: popover, component: tooltip, needs: info

**Comment by csymeonides** [comment] 2015-08-24 16:43
Excellent thank you!

**Comment by jikkujj** [comment] 2015-10-01 15:45
Doesnt look this issue ie pop-over/tooltip opening on load is fixed in 0.13.4. Have the changes from 0.13.4-SNAPSHOT not been included in 0.13.4 ?
http://plnkr.co/edit/A38xRnjhaCMW97f2uh4Q?p=preview

**Comment by icfantv** [comment] 2015-10-01 16:43
@jikkujj - that's because `*-is-open`, by design, expects an expression (otherwise, it's not [and can't be] programmatic) and you're passing it a string.  in your plunker, in the `PopoverDemoCtrl` controller, set `$scope.openOnLoad = true;` and then in the HTML, say `popover-is-open="openOnLoad"` and you will see that it works.

**Comment by jikkujj** [comment] 2015-10-01 17:51
But true is an expression isnt it into contrast to 'true'.

What i mean is that there should be a difference between "true" and "'true'"

**Comment by icfantv** [comment] 2015-10-01 18:05
It all depends on context and how it's used:  `true` by itself, is a boolean.  `"true"`, `'true'`, and `"'true'"` are all strings in this context because they are attributes and the `$parse` service expects an expression.

[Here's what](https://github.com/angular-ui/bootstrap/blob/master/src/tooltip/tooltip.js#L145) we are doing.

The thing to remember is this attribute was added to allow people to programmatically control whether or not a popover or tooltip would display.  Even if we allowed the user to hard-code a boolean `true` value, there's no way to change it - at least, not very easily.

What problem are you trying to solve whereby you want to just put the string value of a boolean in there and have it magically work?

**Comment by nadyav** [comment] 2016-04-05 20:24
icfantv, perhaps, documentation should be more clear. All it says here https://angular-ui.github.io/bootstrap/ is "popover-is-open (Default: false) - Whether to show the popover." So yes, people assume that by passing "true", it will work. Thanks.

**Comment by nadyav** [comment] 2016-04-05 20:32
@icfantv, but isn't it the same as passing "true"? Adding $scope.openOnLoad = true; in the controller and then popover-is-open="openOnLoad" in the view doesn't make the popover show on page load. The effect is exactly the same as popover-is-open="true". Thank you.

**Comment by nadyav** [comment] 2016-04-06 06:47
It's said on https://angular-ui.github.io/bootstrap/ "For any non-supported value, the trigger will be used to both show and hide the popover. Using the 'none' trigger will disable the internal trigger(s), one can then use the popover-is-open attribute exclusively to show and hide the popover.", but adding popover-trigger="none" to the above code doesn't help as well. Popover just doesn't get displayed at all.

**Comment by icfantv** [comment] 2016-04-06 13:18
@nadyav, I'm on mobile at the moment.  Can you please file a complete and new issue documenting the issue you think is a bug, complete with a minimally wor minting plunker and we will investigate.  Please make sure you adhere to the issue template fully and use the latest versions of the requisite libraries in your reproduction.  Also please link this issue in your new one. thanks.

**Comment by nadyav** [comment] 2016-04-10 20:38
@icfantv, I have created a new issue here https://github.com/angular-ui/bootstrap/issues/5773. Perhaps, there is no bug, and I'm using settings incorrectly, but any help is highly appreciated. Thank you very much in advance.
