### ISSUE TITLE
Modal - On mobile, scrolling causes the page in the back to scroll

### ISSUE THREAD

**Issue by riyunoa** [angular-ui/bootstrap#4261] opened 2015-08-24 06:50 UTC
I've encountered an issue on mobile where scrolling causes the page in the back to scroll instead of the modal itself. 

To reproduce this:
- Go to https://angular-ui.github.io/bootstrap/#/modal
- Click "Open Me" and scroll. You'll find that the page in the back will be scrolling. 

Anyone know how to fix this? Thanks!

**Comment by wesleycho** [comment] 2015-08-24 06:58
I am not able to reproduce this.

However, one should note that you can use CSS to add `overflow: hidden` to the body element on modal opening.

**Comment by riyunoa** [comment] 2015-08-24 07:03
Hi @wesleycho, what device have you used to test this? I'm getting this on Note 4 and iPhone 5S - drag to scroll with the modal open, and the page in the background moves.

**Comment by wesleycho** [comment] 2015-08-24 07:23
I tried it on the Chrome mobile emulator, and was not able to reproduce there for any mobile devices.

It appears this is an issue with Safari and Chrome on iOS (Chrome essentially being a Safari reskin), but I am not sure we can do much about this if I remember correctly - Safari is behaving incorrectly here with regards to respecting expected DOM behavior.

I need to test this on Android Chrome on a physical device, but I suspect that it shouldn't be reproducible, given that Chrome's emulation did not display any issues.

I welcome any PRs if you are able to come up with a good fix, or more detailed information on what is failing which could potentially aid us in crafting a good fix, but this would be a time consuming bug to fix due to needing physical devices on hand.

**Comment by wesleycho** [comment] 2015-11-29 15:45
After having to actually fix this behavior in code at work within the past month or so, this turns out to be a CSS issue, and can be fixed with the approach usage of `overflow: hidden` in one's own code in tandem with the use of options when opening the modal such as `windowClass`.

**Closed by wesleycho** 2015-11-29 15:45 UTC
Labels: component: modal, resolution: support

**Comment by elmalto** [comment] 2015-12-10 17:51
```overflow: hidden``` does not actually solve the issue (in my tests). It primarily locks the screen and prevents all scrolling, even down. If the body is at scrollY 0 and you try to scroll up, it will lock all mousemove events until you release. Scrolling down will only work at that point.

IMHO this needs to be solved with javascript

**Comment by glaucocustodio** [comment] 2016-09-20 14:45
It is still happening on Safari (iOS 8.3). I am with 3.3.7 version. Any update about this?
