### ISSUE TITLE
Popover placement "top" positioning issue when window is being resized or the orientation changes 

### ISSUE THREAD

**Issue by cloud9amit** [angular-ui/bootstrap#5292] opened 2016-01-18 12:41 UTC
Hi,

I see an issue with popover top placement when window is re-sized. on small screen devices/window it overlaps the button control used to bring the popover.
Also, popover gets misplaced if orientation of the device is changed.

I have added a plunkr for the same. http://plnkr.co/edit/2p3JxVpTH2MACfvhy5Bu?p=preview

Please click on button "D" to reproduce the issue. Go to full screen mode and then resize the window after opening the popover. On small windows it even overlaps the button.

**Comment by icfantv** [comment] 2016-01-18 15:46
@cloud9amit, in this instance, you may want to try `popover-placement="auto"` so you don't have to worry about this.  My other question for you is what you mean by small screen devices.  If you mean mobile or tablets, we've basically decided that from a UX perspective, tooltips and popovers don't make sense on non-mouse devices.  As such, we've not given that area much love in the way of support.

Please let us know.  Thanks.

**Comment by cloud9amit** [comment] 2016-01-19 07:10
![popover issue on small devices](https://cloud.githubusercontent.com/assets/6944272/12412033/9760bcf6-bea9-11e5-9b86-20a736f55340.JPG)
@icfantv , Yes from small screen devices I meant mobile and tablets where popover positioning is not proper. Same can be replicated by re-sizing browser window on any desktop similar to the size of a mobile device. On mouse supported devices popover works perfectly so no issues with that. My issue was more specifically for mobile devices.  You can close the ticket in case mobile devices are not part of your support.
attached is an image where popover is overlapping with button control to which it is attached.

Thanks for your support.

**Comment by cloud9amit** [comment] 2016-01-19 09:33
Thanks for pointing out on popover-placement="auto". I missed that in documentation, sorry on that part. Popover placement is much better after using that. As stated in my previous comment you can close this ticket if there is no support for mobile devices. I will look for some workarounds.

**Comment by icfantv** [comment] 2016-01-19 17:46
@cloud9amit, after speaking to the team, while tooltips and popovers may work on mobile devices, we are not going to support tooltip/popover issues on mobile platforms because we believe (and this was confirmed by speaking to UX engineers) that they do not make sense on mobile devices.

As such, I'm sorry but we will need to close this issue.  If you're looking for workaround - take a look at the Tether library.

**Closed by icfantv** 2016-01-19 17:46 UTC
Labels: component: popover, needs: info

**Comment by cloud9amit** [comment] 2016-01-19 18:20
@icfantv , thanks for your response. Since we are working on responsive web design which needs to support all platforms so it got carried over from desktop version. I will look for workarounds as suggested by you.

Thanks
