### ISSUE TITLE
Datepicker does not re-open after selecting a date. 

### ISSUE THREAD

**Issue by zackarychapple** [angular-ui/bootstrap#2540] opened 2014-08-03 02:06 UTC
I have multiple datepickers on my page and am having trouble getting them to work as expected.  They all open fine and allow for selecting a date without issue.  However after selecting the date the datepicker will no longer open for that given element.    I have included both the HTML and JS I am using with the datepicker. 

How can I make it so the datepicker can be opened more than once for any given element. 

```html
<input type="text" ng-model="myOjbect.dateOfBirthStr" datepicker-popup="MM/dd/yyyy"
                           is-open="dateOfBirthStrOpened"
                           name="dateOfBirthStr" id="dateOfBirthStr" class="form-control" close-text="Close">
<span class="input-group-addon" ng-click="openDatepicker($event, 'dateOfBirthStrOpened')">
    <i class="ss-icon ss-calendar"></i>
 </span>
```

```javascript
  $scope.openDatepicker = function ($event, elementOpened) {
    $event.preventDefault();
    $event.stopPropagation();

    $scope[elementOpened] = !$scope[elementOpened];

  };
```

**Comment by tdhsmith** [comment] 2015-01-14 18:39
I think the answer @zackarychapple links in #2584 gives the best explanation of the root cause: http://stackoverflow.com/a/25308180/3697161

*(I'm still pretty new to angular and I learned and reinforced a lot through this issue, so I wanted to write up a summary:)*

----------------------------------

The `datepickerPopup` directive creates an **isolate scope** ([set up on L438](https://github.com/angular-ui/bootstrap/blob/0938d3fec3434436e5fab6ed1d12d82b69f922ee/src/datepicker/datepicker.js#L438)). This means the popup doesn't live in the same scope as the input/button that triggers it. The line `isOpen: '=?'` activates two-way binding between the isolate scope's `isOpen` *variable* and the `isOpen` *attribute* on the date field. However, due to the way scope inheritance works, setting a javascript primitive in a child scope will not write to the parent scope's variable. Angular's GitHub wiki has a well-diagrammed article describing some of this [here](https://github.com/angular/angular.js/wiki/Understanding-Scopes).

So when you open the popup, `$parentScope.opened` is set to true, which the popup can see when it reads `$popupScope.opened`. But when you close it, `$popupScope.opened = false` **sets its own value in the popup's scope**. The parent scope has no idea this happened; `$parentScope.opened` is still true and it has no way to affect the divergent value in the popup's scope because it's being shadowed.

Thus, the most straightforward solution is to use an object instead, because when child scopes set object values, they actually check if there is an inherited parent value first.

This is what I'm using now:
```html
<input type="date"
	class="form-control"
	ng-model="propietary_things.date" 
	datepicker-popup="yyyy-MM-dd"
	is-open="datepicker.opened" />
```
```javascript
$scope.openDatepicker = function($event) {
	$event.preventDefault();
	$event.stopPropagation();
	$scope.datepicker = {'opened': true};
	// succinct way to ensure object has been created *and* set the property
}
```
------------------------------------

Having an isolate scope seems to be a good thing because it prevents a lot of issues with mucking up the parent scope (for example, multiple pickers could end up all opening and closing at once or writing over the same data). Avoiding binding primitives is considered good practice in angular, so the docs should probably be updated regardless of whether there is a "fix" for the code. I can get around to that if no one else does.

**Comment by juanpablopola** [comment] 2015-03-06 16:19
I had this trouble but I found my solution by this way, hope this can help you:

        <div class="col-md-4" ng-repeat="travel in travels">
            <table>
                <tr>
                    <td colspan="2">
                        {{"TOTALPASSENGERS" | translate}}
                    </td>
                </tr>
                <tr>
                    <td>
                        {{"DATE" | translate}}
                    </td>
                    <td>
                        <p class="input-group">
                            <input type="text" name="$index" class="form-control" datepicker-popup="shortDate" ng-model="travel.Travel.date" is-open="openeds[$index]" datepicker-options="dateOptions" date-disabled="disabled(date, mode)" ng-required="true" close-text='{{"CLOSE" | translate}}' />
                            <span class="input-group-btn">
                              <button type="button" class="btn btn-default" ng-click="open($event, $index)"><i class="glyphicon glyphicon-calendar"></i></button>
                            </span>
                        </p>
                    </td>
                </tr>
.....

In my controller I have the following code:

    $scope.openeds = new Array();

    for(var i = 0; i <$scope.travels.length; i++)
    {
        $scope.openeds[i] = false;
    }

    $scope.open = function($event, index) {
        $event.preventDefault();
        $event.stopPropagation();

        $scope.openeds[index] = true;
      };

**Comment by wesleycho** [comment] 2015-08-02 17:02
This appears to be an old issue - feel free to open a new issue based on current `master` or 0.13.2 if this is still an issue with current UI Bootstrap.

**Closed by wesleycho** 2015-08-02 17:02 UTC
Labels: component: datepicker, PRs plz!, type: doc

**Comment by Coffee-Tea** [comment] 2016-01-29 10:17
michelrtm and tdhsmith .
Thank you guys, that simple solution and it WORKS!
