### ISSUE TITLE
Typeahead Fails to Work with Arrow Keys When Using a Table in Template

### ISSUE THREAD

**Issue by noamichael** [angular-ui/bootstrap#5867] opened 2016-04-30 03:17 UTC
### Bug description:
For the typeahead component, when using a custom popup and result template that utilizes a table structure instead of a list, the typeahead component fails to highlight the currently selected table row when using the arrow keys and throws an error. The correct result is selected upon hitting enter, however.

The error is caused by the fact that the component explicitly looks for the LI tag in order to scroll to the selected element. [This can be seen here](https://github.com/angular-ui/bootstrap/blob/master/src/typeahead/typeahead.js#L409).

My suggestion would be to a add a directive or an id which would allow the user to specify the element to highlight/scroll to when using the arrow keys. Otherwise, this is a great autocomplete plugin.

### Link to minimally-working plunker that reproduces the issue:
[Plunker](https://plnkr.co/edit/ziiVYOS3Sh9eVHrLiK43?p=preview)
### Version of Angular, UIBS, and Bootstrap

Angular:
**1.5.3**
UIBS:
**1.3.2**
Bootstrap:
**3.3.6**

**Comment by icfantv** [comment] 2016-05-02 17:07
This smells more like an enhancement to me.  Thoughts @wesleycho or @Foxandxss?

**Comment by wesleycho** [comment] 2016-05-02 20:09
Closing as a duplicate of #5848.

**Closed by wesleycho** 2016-05-02 20:09 UTC
Labels: component: typeahead, needs: investigation
