### ISSUE TITLE
Shouldn't disabled accordion header be unfocusable?

### ISSUE THREAD

**Issue by 1pete** [angular-ui/bootstrap#4095] opened 2015-08-04 02:25 UTC
http://angular-ui.github.io/bootstrap/#/accordion

If accordion header is disabled, you can still focus it by click, also can navigate by using keyboard (press tab).
Is this what it should be?

Thanks

**Comment by wesleycho** [comment] 2015-08-04 02:31
Closing as a duplicate of #4067 - you are definitely correct though.

**Closed by wesleycho** 2015-08-04 02:31 UTC
Labels: component: accordion, resolution: duplicate
