### ISSUE TITLE
Tooltip not positioned properly when inside a relative inline-block

### ISSUE THREAD

**Issue by robianmcd** [angular-ui/bootstrap#2780] opened 2014-10-04 01:53 UTC
Tooltips don't appear to be positioned properly if they are inside something with

```CSS
position:relative; display:inline-block;
```

For example http://plnkr.co/edit/6xieMEKrNinJ2QDfHicp?p=preview

So something like some buttons in a `btn-group` with tooltips won't work because `btn-group` uses relative positioning and inline-block display. It seems like the tooltip isn't able to go past the right border of the parent element.

**Comment by vprasanth** [comment] 2015-06-06 15:46
Considering the plunkr is based on 0.11.2 and that I can't reproduce on versions >0.11.2, should this be marked closed now?

@pkozlowski-opensource @robianmcd

**Comment by chrisirhc** [comment] 2015-06-08 08:02
Thanks for checking, @vprasanth . I'm closing this then.

**Closed by chrisirhc** 2015-06-08 08:02 UTC
Labels: component: $position, component: tooltip, type: bug
