### ISSUE TITLE
display issues when opening modal

### ISSUE THREAD

**Issue by jessehart** [angular-ui/bootstrap#5183] opened 2016-01-08 22:16 UTC
reproducible on demo: http://angular-ui.github.io/bootstrap/#/modal

issue 1:
open modal and pay attention to the page in the background. notice it shifts down briefly before returning to normal.

issue 2:
turn off animation. open a large or small modal and pay attention to how the modal content area displays as its opened. notice it shrinks or expands before displaying as expected.

**Comment by icfantv** [comment] 2016-01-08 22:38
Thanks for the report.

**Comment by jasonwells** [comment] 2016-01-08 23:10
I am experiencing the same issue. It looks like for me it is rendering the content of the modal (with code from angular such as `Modal Content: {{ variableHere }}` inside the top of the page before moving it to the modal window which is why it is shifting down while opening.

**Comment by LeleDev** [comment] 2016-01-09 10:05
same here

**Comment by serhalp** [comment] 2016-01-09 23:40
This is preventing us from upgrading our apps to 1.0.  All our karma tests that open modals are broken, and I can't figure out how to fix them.  They look like this:

<img width="1275" alt="screen shot 2016-01-09 at 3 32 46 pm" src="https://cloud.githubusercontent.com/assets/1377702/12219026/4a14ad92-b6e6-11e5-9521-497861f50f57.png">

where the contents above the navbar should be in a modal.  I've blindly tried a few combinations of `$digest()`ing and `$timeout.flush()`, but nothing seems to trigger a proper render.  Not sure if relevant, but I can also see in the DOM that the `.modal-backdrop` is present, and "obscuring" the entire page, including what should be the contents of the modal – so the modal contents can't even be interacted with correctly.

As far as I can tell, these are all the changes in 1.0.0 that affected modals: https://github.com/angular-ui/bootstrap/commit/726ccc3 https://github.com/angular-ui/bootstrap/commit/b8969d1 https://github.com/angular-ui/bootstrap/commit/e9c4977 https://github.com/angular-ui/bootstrap/commit/2635f0d https://github.com/angular-ui/bootstrap/commit/742132a https://github.com/angular-ui/bootstrap/commit/e28cced.  I imagine this has to have been introduced in one of those?

**Comment by icfantv** [comment] 2016-01-10 17:48
@jasonwells, @serhalp - please do not hijack the thread.  If you are experiencing the same issue then all you need to do is indicate thus - or better yet, help us investigate the issue.  If you are experiencing a different issue, then you need to follow the instructions [here](https://github.com/angular-ui/bootstrap#found-a-bug).

Secondly, all of you need to make sure you look at the CHANGELOG to ensure none of the breaking changes affect you.  By far the biggest one is the removal of all the old directive names.  Prior to 1.0, but only in 0.14.x, you would get deprecation warning messages in your console about the change and how to mitigate (namely add a `uib-` prefix).

Finally, 1.0 is only compatible with Angular 1.4+, so please make sure you're using that.

All that said, we're aware of the original issue posted by @jessehart.

**Comment by philBrown** [comment] 2016-01-11 03:32
Seeing this too.

What appears to happen is an element looking like

    <div uib-modal-window="modal-window" window-class="..." size="..." index="0" animate="animate" modal-animation="true">
        
    </div>
    
is inserted at the top of the `<body>` element. As this element has none of the standard modal CSS classes, it appears as a block of content at the top of the page.

The modal dialog should be cloaked / hidden until it is completely compiled.

**Comment by philBrown** [comment] 2016-01-11 04:06
I'm currently working around this via the following CSS

    body > [uib-modal-window]:not([modal-render]) {
        display: none;
    }

**Comment by Domitnator** [comment] 2016-01-11 08:50
Seeing this too!

**Comment by mattlewis92** [comment] 2016-01-11 09:03
Confirmed that the workaround posted by @philBrown works as a temporary fix, thanks for that! :smile:

**Comment by bboyle** [comment] 2016-01-11 15:03
have also seen this bug (tip: use the 'break on subtree modifications' debug option to catch it step by step) Appears that the modal contents are added to the DOM, then removed, then added and displayed properly, causing a flash (our pages don't scroll much so we see the modal content appear briefly)

ty @philBrown for interim fix!

**Comment by OACDesigns** [comment] 2016-01-14 14:18
on top of the flash of un-compiled template, the modal should be appended to the body/appendTo emenet, not prepended as is currently the case.

**Closed** 2016-01-16 05:41 UTC
Labels: component: modal, needs: investigation

**Comment by athimannil** [comment] 2016-01-17 06:26
@philBrown Thanks for the solution mate 👍

**Comment by Reboog711** [comment] 2016-01-26 15:16
I was experiencing the same issue.  Extra Kudos to @philBrown as his work-around fixed it for me too.

**Comment by Craig1f** [comment] 2016-06-01 13:01
The fix from @philBrown has no effect for me. Has anyone else had trouble getting it to work?

**Comment by zdonato** [comment] 2016-06-05 18:34
@Craig1f I was able to get it to work by adding an element at the bottom of my body and then using the appendTo option of the open method.

**Comment by Craig1f** [comment] 2016-06-06 18:49
I have no idea why nothing I try has worked. I tried the appendTo also. 

This gets me what I need: 
app.config(['$modalProvider', function($modalProvider)  {
  $modalProvider.options.animation = false;
}

The backdrop still kind of flickers, but the modal itself no longer flickers at the end, so it's less irritating. It'll do for now.

**Comment by zdonato** [comment] 2016-06-06 19:05
@Craig1f Originally the appendTo wasn't working for me, so not sure if you ran into this as well or  not but appendTo works with angular's $document.find function from jqLite which only works on element tags. This is what worked for me:

appendTo: $document.find('add-modal')

and in the modal template I have an empty element at the bottom of the body:  
<add-modal></add-modal>

**Comment by sskasim** [comment] 2016-06-09 15:56
philBrown work around works for me too. Thanks.

**Comment by jmusser73** [comment] 2016-07-21 21:11
@philBrown workaround worked for me.  Thanks.

**Comment by Benjanver** [comment] 2016-07-27 17:46
@philBrown thanks mate

**Comment by bmsdave** [comment] 2016-10-31 17:09
@philBrown, you genius!

**Comment by Gu3** [comment] 2016-11-18 09:49
@philBrown, 2 words : Thanks You !

**Comment by NachoColl** [comment] 2017-02-13 17:23
In my case it shifts to the right, so I just added:

body.modal-open {
	padding-right: 0!important;
}

**Comment by krazylearner** [comment] 2018-01-04 16:16
is there any official fix for this ? my whole app looks bad due to this

**Comment by thargenediad** [comment] 2018-08-19 21:27
still required @philBrown's CSS fix in late 2018
