### ISSUE TITLE
$uibModal is not minification-safe

### ISSUE THREAD

**Issue by thedmi** [angular-ui/bootstrap#5069] opened 2015-12-14 14:47 UTC
We recently updated angular-ui bootstrap from 0.12.0 to 0.14.3. In the process, we changed all injected services to the "uib" prefixed variants to avoid the deprecation warning. 

During testing of the minified version of our application, we discovered that `$uibModal` is not injected properly **into directives**. Our other usages of the `$uibModal` service are in controllers, these work as expected.

The error message we receive is 

    Error: [$injector:unpr] Unknown provider: nProvider <- n

To rule out a problem with our ng-annotate build step we added the annotation explicitly:

    module.directive('theDirective', ['$uibModal', function($uibModal) { ... } ]);

This had the effect that the injector error mentioned above was not thrown anymore, but the injected service was `undefined`.

Reverting back to use `$modal` fixes the issue, and we were able to suppress the deprecation warning with `module.value('$modalSuppressWarning', true)`.

Environment:
- Angular 1.3.20
- AngularUI Bootstrap 0.14.3 (unminified, through bower)

**Comment by wesleycho** [comment] 2015-12-14 15:58
This does not sound like a UI Bootstrap problem - perhaps this is an ng-annotate problem? I don't recall seeing this issue at all in my own use though while using ng-annotate.

**Comment by wesleycho** [comment] 2015-12-14 16:08
Closing as a not a UI Bootstrap problem.

**Closed by wesleycho** 2015-12-14 16:08 UTC

**Comment by icfantv** [comment] 2015-12-14 17:26
@thedmi, you might also consider upgrading Angular JS to the latest version if you plan on using 0.14+.  1.3.2 is over a year-old at this point which is a lifetime in OSS days.

**Comment by SilentDirge** [comment] 2016-01-07 05:46
I'm seeing almost the exact same issue running with AngularJS 1.4.8 and AngularUI 14.3. Basically I'm just doing an injection of $uibModel like so:
```javascript
controllers.controller('HeaderController', ['$scope', '$routeParams', '$log', '$uibModal',
    function($scope, $routeParams, $log, $uibModal) {
```

With no minification, works perfectly. With minification, it doesn't work at all and I get this error in the console log:
```
Error: [$injector:unpr] http://errors.angularjs.org/1.4.8/$injector/unpr?p0=%24uibModalProvider%20%3C-%20%24uibModal%20%3C-%20HeaderController
    at Error (native)
    at http://localhost:9000/assets/javascripts/angular-1.4.8/angular.min.js:6:416
    at http://localhost:9000/assets/javascripts/angular-1.4.8/angular.min.js:41:121
    at Object.d [as get] (http://localhost:9000/assets/javascripts/angular-1.4.8/angular.min.js:39:92)
    at http://localhost:9000/assets/javascripts/angular-1.4.8/angular.min.js:41:195
    at d (http://localhost:9000/assets/javascripts/angular-1.4.8/angular.min.js:39:92)
    at Object.e [as invoke] (http://localhost:9000/assets/javascripts/angular-1.4.8/angular.min.js:39:362)
    at M.instance (http://localhost:9000/assets/javascripts/angular-1.4.8/angular.min.js:80:336)
    at D (http://localhost:9000/assets/javascripts/angular-1.4.8/angular.min.js:61:362)
    at http://localhost:9000/assets/javascripts/angular-1.4.8/angular.min.js:69:223
```

ng-annotate is a red herring -- I don't use it at all.

Any ideas?

**Comment by dgreene1** [comment] 2016-02-15 21:37
@thedmi did you ever figure this out?

**Comment by evilanubhav** [comment] 2016-03-30 08:01
I recently encountered a similar issue. The problem is not with $uibModal, it was with one of the resolves which had a dependency injection which was already injected in the factory. Removing this duplicate injection resolved my issue.
Apparently, $modal doesn't break with this but $uibModal does on minification.
