### ISSUE TITLE
Missing class from css overrides.

### ISSUE THREAD

**Issue by topless** [angular-ui/bootstrap#3492] opened 2015-04-05 15:41 UTC
.nav, `.navbar-brand`, .pagination, .carousel, .panel-title a { cursor: pointer; }

**Comment by wesleycho** [comment] 2015-04-05 15:44
I am confused about this issue - can you explain in more detail, and perhaps a reproduction?

**Comment by chrisirhc** [comment] 2015-04-05 16:42
This looks like an issue for Twitter Bootstrap https://github.com/twbs/bootstrap . There aren't CSS overrides in this repository except for animations.

**Comment by wesleycho** [comment] 2015-04-06 13:16
Closing as invalid unless there is more information - we do not bundle CSS for UI Bootstrap.

**Closed by wesleycho** 2015-04-06 13:16 UTC
Labels: resolution: invalid
