### ISSUE TITLE
Support for Bootstrap 4

### ISSUE THREAD

**Issue by elesdoar** [angular-ui/bootstrap#4868] opened 2015-11-10 19:50 UTC
Hi, 

Do you think support Bootstrap 4?
http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/

**Comment by wesleycho** [comment] 2015-11-10 21:08
Closing as a duplicate of #4234

**Comment by icfantv** [comment] 2015-11-10 21:08
Closing as a duplicate of #4234.  @elesdoar, please take a moment to search both open and closed issues for your topic before opening a new one.  When you don't, you create unnecessary busy work for us.  Thanks.

**Closed** 2015-11-10 21:08 UTC
