### ISSUE TITLE
right and left icon on popup calendar and the value

### ISSUE THREAD

**Issue by c0debreaker** [angular-ui/bootstrap#2504] opened 2014-07-23 22:28 UTC
Is it possible to capture the click event of these two icons? What I'm planning to do is capture the click event then also capture the value that is displayed on top of popup(prior to clicking a date). I need it so I can disable prior and next month dates that is also displayed on the current month being displayed.

Or is it possible to only display the dates of the month we are viewing? I don't want to see the last few days of the previous month as well as the first few days of the next month. If so, I don't need the click event on left/right icons anymore.

Any help would be greatly appreciated!

Thanks!

**Comment by wesleycho** [comment] 2015-11-03 06:08
Closing as a duplicate of #3309.

**Closed by wesleycho** 2015-11-03 06:08 UTC
Labels: component: datepicker, PRs plz!, type: enhancement
