### ISSUE TITLE
Directives doesnt get processed

### ISSUE THREAD

**Issue by meivin123** [angular-ui/bootstrap#4687] opened 2015-10-22 09:38 UTC
Hi,
first I tried using the timepicker and it didnt work (I copyed the exact code from the example).
Now I am trying to use accordion and it doesnt work too.
At the moment I am using modal and datepicker too and both of them work great.
But when I use directives with custom html tags they dont get processed.
I have included the following files:
```code
bower_components/bootstrap/dist/css/bootstrap.min.css
bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js
bower_components/angular-bootstrap/ui-bootstrap.min.js
```

And my accordion markup is very basic:
```html
<uib-accordion>
  <uib-accordion-group heading="Lorem ipsum dolor sit amet">
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
      Facere nobis ipsum temporibus quidem expedita qui placeat, 
      et aspernatur incidunt ex debitis, voluptatum fuga facilis 
      porro, dicta at, dolor vitae officiis.
    </p>
  </uib-accordion-group>
  <uib-accordion-group heading="Lorem ipsum dolor sit amet">
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
      Facere nobis ipsum temporibus quidem expedita qui placeat, 
      et aspernatur incidunt ex debitis, voluptatum fuga facilis 
      porro, dicta at, dolor vitae officiis.
    </p>
  </uib-accordion-group>
</uib-accordion>
```

My app is grouped into several subpages. Each page has an own Controllers-Module.
These modules are registered as depenencies in an main app.js to the app module.
And in the app module ui.bootstrap gets registered as a dependency, too.

And the rendered Markup in Chrome is exactly the same.
So why does the markup does not get processed but modals and datepickers work?

**Comment by daniel7912** [comment] 2015-10-22 13:10
+1 same thing happening for me

**Comment by d-ash** [comment] 2015-10-22 14:18
+1, even the simplest <uib-progressbar value="55"></uib-progressbar> is not processed
(I'm trying to use this in a Rails app)

**Comment by RobJacobs** [comment] 2015-10-22 14:26
Since there is no plunk demonstrating the problem which makes it extremely difficult to help resolve problems.  

I'm going to take a guess at what the problem is and close this issue.  You are loading both the templates package (bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js) and the non-template package (bower_components/angular-bootstrap/ui-bootstrap.min.js), you should only be loading 1, most likely the package with the templates - bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js

**Closed by RobJacobs** 2015-10-22 14:26 UTC

**Comment by d-ash** [comment] 2015-10-22 15:36
Found it: `'uib-'` prefix was added just a month ago.
I'm using a Rails gem that has not been updated, so it uses just `<accordion>` not `<uib-accordion>`.

**Comment by simonh1000** [comment] 2016-01-28 09:40
Same issue here. This from bower.json

    "version": "1.1.1",
    "main": ["./ui-bootstrap-tpls.js"],

And I have this in a directive template

```
        <uib-accordion>
            <uib-accordion-group heading="Area x">
                Location Y
            </uib-accordion-group>
            <uib-accordion-group heading="Area x">
                Location Y
            </uib-accordion-group>
            <uib-accordion-group heading="Area x">
                Location Y
            </uib-accordion-group>
```
