### ISSUE TITLE
Uglify2 vs uib-datepicker-popup

### ISSUE THREAD

**Issue by char0n** [angular-ui/bootstrap#4648] opened 2015-10-18 08:17 UTC
There seems to be a problem with uib-datepicker-popup vs uglify2.

Affected seems to be version 0.14.2 and file ui-bootstrap.tpls.js. If I use ui-bootstrap.tpls.min.js and run my project and this file via uglify process, everything works as expected.

This is my uglify2 configuration options:

```javascript
compress: {
            sequences: true, // breaks uib-datetimepicker !!!
            properties: true,
            dead_code: true,
            drop_debugger: true,
            unsafe: true, // default false
            conditionals: true,
            comparisons: true,
            evaluate: true,
            booleans: true,
            loops: true,
            unused: true,
            hoist_funs: false, // breaks build !!!
            hoist_vars: false, // default false (increase size)
            if_return: false, // breaks build in FireFox !!!
            join_vars: false,
            cascade: true,
            warnings: false,
            negate_iife: true,
            pure_getters: true,
            pure_funcs: null,
            drop_console: true,
            keep_fargs: false
          }
```

It seems problem is with the `sequences`. When I change it to false, again everything works as expected. 

Does anybody encountered the same problem or has some more additional info about this ?

**Work around**
1.) in your uglify2 config set sequences: false
2.) use ui-bootstrap.tpls.min.js insted as ui-bootstrap.tpls.js

**Comment by Foxandxss** [comment] 2015-10-18 11:01
Could you please give more information? What kind of error you get? Does it uglify? or it fails upon usage?

**Comment by char0n** [comment] 2015-10-18 14:31
- Yes it uglifys with no problems
- Yes it fails upon usage with no errros

Currently I have no more info, I had to solve the problem in our app in no time and used workaround 2.) I guess I will have more info during the week.

**Comment by wesleycho** [comment] 2015-10-18 16:18
What type of error is it? Where is the error? This is the basic information we need before we can even investigate this.

**Comment by char0n** [comment] 2015-10-18 17:14
It seems like datepicker is not propagated to ng-model correctly. When I click on the dates in picker,  picker stays opened and nothing seems to happen (ng-model is not changed).

Anyway I created plnkr: http://plnkr.co/edit/0Lh5kErDJ90KxUUxCEJJ?p=preview
I isolated minified angular-bootstrap from my distribution build and used the minified code in plnkr; everything seems to be working fine here so the problem is more elusive that I originally thought.

I suspected the reason to be new angular-bootstrap 0.14.x, because everything works fine when downgraded to 0.13.x or when using ui-bootstrap.tpls.min.js. 

It seems problem may be in my compile process - when building ui-boostrap (not minified version) with number of other 3rd party libraries. I am using grunt-contrib-uglify=0.9.2

**Comment by Foxandxss** [comment] 2015-10-18 17:29
Sorry, got lost. The plunker seems to be working right?

and I don't think that an uglifier can modify a library behavior without giving errors.

Seems like the issue is in your end.

**Comment by char0n** [comment] 2015-10-18 17:31
> Sorry, got lost. The plunker seems to be working right?
Yes it does

> Seems like the issue is in your end.
Seems like it. I will investigate further

**Comment by wesleycho** [comment] 2015-10-18 17:33
Closing as it seems like a user problem & not a library issue.

**Closed by wesleycho** 2015-10-18 17:33 UTC
Labels: needs: info, type: build
