### ISSUE TITLE
make templateUrl configurable

### ISSUE THREAD

**Issue by sym3tri** [angular-ui/bootstrap#743] opened 2013-08-01 18:21 UTC
Now all templates must reside in the root directory under `/template`. This is not ideal for some larger projects.

**Comment by tom10271** [comment] 2015-05-29 02:30
This hack does not always work. For tooltip you cannot set custom template to dedicated URL.

I use require.js to construct and boot Angular application. Files are putting in different folders.

Angular UI NEVER able to grab the correct URL. It forces me to develop my own directive. It is good to provides UI component to developers but it is working yet not quite working great at all I am afraid.

**Comment by aariacarterweir** [comment] 2015-10-08 06:53
How do you not see a strong enough use case? Don't you develop locally?

**Comment by wesleycho** [comment] 2015-10-08 06:55
You can already specify a custom template url for each component that uses a template currently in UI Bootstrap on an instance basis.

**Comment by aariacarterweir** [comment] 2015-10-08 07:19
I've installed via bower. I do not want to put the templates in my root directory as that makes absolutely no sense. I am developing locally and do not wish to compile every time i make a change.

Basically I'm a regular user - and you don't cater to me.

**Comment by wesleycho** [comment] 2015-10-08 07:29
You do not need to put the templates anywhere - they are available in memory via $templateCache when consumed via the `angular-bootstrap` bower package.

`Basically I'm a regular user - and you don't cater to me.`

This is a poor attitude & highly disingenuous given that most developers have been able to work around this with minimal overhead - this attitude has no place in open source software or software development of any kind.

**Comment by pkozlowski-opensource** [comment] 2015-10-08 08:20
@aariacarterweir I've got an impression that you are misunderstanding the idea behind the open source software: it is not a free software delivery service where you can demand any feature and have it done for free. It is a collaborative effort where anyone is free to contribute code via PR if one sees area of improvement. 

Having said the above I don't think there is anything to "fix" here as we do distribute scripts with embeded templates,  see the full details here: https://github.com/angular-ui/bootstrap/wiki/FAQ#im-using-modal-service-but-it-cant-find-its-templates

**Comment by aariacarterweir** [comment] 2015-10-09 00:30
@pkozlowski-opensource I've got the impression that you're completely disconnected from the real world and over-burdened with the needless and illogical complexity of angular in general.

I don't expect to be able to demand features. I do however expect anyone who has influence on this project to try and listen to their users. You just come across as a defensive and unreasonable.

The templateUrl should be configurable. It absolutely blows my mind that you cannot see the reason for this.

I could submit a PR with changes made to implement this, but you wouldn't merge it - so what's the point?

**Comment by BobbieBarker** [comment] 2015-10-09 00:53
Hey you're attitude isn't welcome here, your derogatory commentary doesn't reflect the spirit of discussion that we aspire towards in this community. Please refrain from further posts like this and if you don't like the way the library works you're more than welcome to fork it and make it work how you want.

**Comment by wesleycho** [comment] 2015-10-09 00:53
@aariacarterweir I think there is a misunderstanding - this issue has been reconsidered in the past couple of months and I implemented configurable templateUrl for every component in UI Bootstrap myself. One can see the current documentation on the project homepage to see that it it is present on every component.

Please refrain from childish attacks on @pkozlowski-opensource though - he did nothing to deserve that, especially considering that most developers in open source work on the software in their spare time. He created this project in his spare time as a service to the developer community, there is no reason for this level of disrespect - this type of behavior drives developers away, and creates a negative atmosphere. His company consumes the library, so he is a real world user of the library as well.

**Comment by BobbieBarker** [comment] 2015-10-09 00:53
I locked the conversation because further negative commentary like this isn't what we need here.

**Comment by BobbieBarker** [comment] 2015-10-09 00:59
Apparently my peers don't feel like I should of locked the thread. I don't want to see a flame war in the issues section on this repo though. Please, please refrain from further negative commentary or I will start locking threads.

**Comment by ProLoser** [comment] 2015-10-09 01:02
Okay guys. Everyone take a :sunglasses: :pill:

**Comment by aariacarterweir** [comment] 2015-10-09 01:04
I hope you can understand why I was a bit ruffled by the wording of @pkozlowski-opensource's reply to me. I honestly felt like it was conceited and snotty. Criticizing me for my reply and defending his seems a little one-sided and overly sensitive. My suggestion is that the decision to make the templateUrl base path not simply configurable be explained in clear language. There are clearly users out there who would benefit from this feature and judging by the number of questions posed about this issue I'm far from alone.

I didn't mean to come across as derogatory and I apologize for any offence caused.

**Comment by ProLoser** [comment] 2015-10-09 01:05
@aariacarterweir I've actually been a bit frustrated with having to override templates via the cache too. I started exploring avoiding templates almost completely in ui-mention and discussions around rewriting ui-select. In ui-select we explored providing a configurable `theme` which would adjust what templateUrl was used, but none of these solutions were terribly wonderful.

**Comment by aariacarterweir** [comment] 2015-10-09 01:14
@ProLoser I agree. For me the issue is that '/templates' is hard-coded. I don't believe this should be the case and nobody has made a solid argument for it as far as I can see. Criticizing me for my 'attitude' and declaring me unfit for software development of any kind is a bit OTT!

When we understand something it becomes easy. When we find ways around problems then the problems sort of cease to exist for us. But for newer users, a high barrier to entry begins to build up sometimes without us realizing. angular-bootstrap is a great resource, by contributing on this issue thread I thought I was furthering robust discussion around something I deemed important. I think I have a pretty good attitude and I'm happy to admit when I'm wrong.

**Comment by wesleycho** [comment] 2015-10-09 03:17
`People criticizing me for my 'attitude' and declaring me unfit for software development of any kind is a bit OTT!`

Let me be clear before moving to technical discussion since this statement seems to suggest that the earlier comments in this issue are acceptable (even ignoring the fact that nobody said anything about being unfit for software development) - the Angular team itself has made clear that [they will actively work to marginalize anyone who does not act with respect towards others](https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md), and I am in full agreement & enforce it. Let me lay out the offending comments that were said without any prior instigation.

`Basically I'm a regular user - and you don't cater to me.`

`@pkozlowski-opensource I've got the impression that you're completely disconnected from the real world and over-burdened with the needless and illogical complexity of angular in general.`

These are highly offensive, offtopic, & clearly meant to escalate/incite/harm and nothing that has been said that warranted any response on this level - Pawel did not mean to offend, and his conduct throughout his open source contributions illustrates this vastly. I also take offense since after being involved in development for the past half year, it hurts to have it suggested that I don't care about how people use this library. Pawel's company (not Google) and my company are both consumers of this library, and my original involvement with UI Bootstrap starting a half year ago was not for work, but purely for wanting to help people with pain points in using a popular library that saw minimal development work for more than half a year prior. This type of non-professional emotional outburst helps drives developers to give up maintaining open source libraries - such incidents in the past have made me reconsider my own involvement at times, as it is extra undeserved abuse that I don't need to put up with.

If there is a belief that any of the maintainers misunderstand the request, simply lay it out in detail - we help maintain this project for the community, thus we have no problem with (re-)considering any request that has merit. We need details though as to why x situation does not work, especially given that there are ways of overriding templates and that we already support instance level overriding of templateUrl - we are not mind readers unfortunately (although it would be awesome if we were, it would solve a lot of problems :grinning: ).

Now, to explain the history & situation - the use of a hardcoded url is simply because the templates need to live in a location due to how Angular works. This is the origin of the hardcoded `template/component/templateHtml.html` url came about. The templates are currently bundled in `$templateCache` to be available in memory for performance reasons of avoiding a roundtrip to the server to fetch templates, to serve as a sensible default for most users, and to serve as an example of a recommended best practice for most apps to pre-build templates into $templateCache.

Previously, Angular did not provide great flexibility to modify templateUrl dynamically - this was not added until Angular 1.1.4 if I recall correctly, and this library predates that. This originally would have been difficult to accommodate different use cases. With the allowance of functions with templateUrl, we can allow configuring of the url at minimal cost. There have been other issues where the use case has been made clear that this would be a useful feature, and so within the past couple of months, I implemented instance level overriding of the templateUrl string used - [here](http://angular-ui.github.io/bootstrap/#/dropdown) is one documented example.

Correct me if I am wrong, but the one missing configuration feature is a global setting of the default templateUrl string, even though it can be overridden on an instance basis. There are several approaches we much consider here, and this is where it gets murky as to whether there are good technical solutions here.

1) A global configuration object where users can override all templateUrls for each component that every component is dependent upon
2) Configuration injectables for each component
3) A global configuration object where users can modify the base templateUrl and keep the rest

Example of 1
```js
angular.module('ui.bootstrap.config', [])
.constant('uibConfig', {
  alert: {
    templateUrl: 'foo/bar.html'
  },
  dropdown: {
    templateUrl: 'baz/boo.html'
  },
  ...
});
```

Example of 2
```js
angular.module('ui.bootstrap.dropdown', [])
.constant('uibDropdownConfig', {
  templateUrl: 'foo/bar.html'
});

angular.module('ui.bootstrap.pagination', [])
.constant('uibPaginationConfig', {
  templateUrl: 'baz/boo.html'
});

...
```

Example of 3
```js
angular.module('ui.bootstrap.config', [])
.constant('uibConfig', {
  baseTemplateUrl: 'foo/'
});
```

All three approaches have major usage issues. The first two allow maximum flexibility, but the first has a problem of potentially unnecessary configurations polluting modules users are consuming (and adds to code bloat), and the second puts the user in a mess inside a configuration block. The problem with the third example is that it is not flexible enough.

I do not see a good solution here that does not result in pain, and while it may be tempting to go with any solution that accomplishes a desired goal, the problem is that the UI Bootstrap team will be left with the maintenance burden of poor choices, so we must consider requests carefully.

I am open to other suggestions too, but it must meet the criteria of good API design, accomplishing maximal ease of use, and avoiding unnecessary breaking changes. All three options I laid out I am seeing currently fails the first criteria, and in the third example, the second criteria. I don't mind necessarily settling, but it requires thought.

**Comment by aariacarterweir** [comment] 2015-10-09 03:38
@wesleycho Right okay, I take your point.

I disagree with this:

`These are highly offensive, offtopic, & clearly meant to escalate/incite/harm and nothing that has been said that warranted any response on this level`

I think you're being overly sensitive. I accept that my response to @pkozlowski-opensource's reply was out of line:

`@pkozlowski-opensource I've got the impression that you're completely disconnected from the real world and over-burdened with the needless and illogical complexity of angular in general.`
I should have bitten my tongue, but I did not as I had interpreted his reply as being quite impolite at first.

You've made your point very clearly @wesleycho, you've accused me of being:
* childish
* emotional
* having a poor attitude & highly disingenuous
* having an attitude unsuitable for software development of any kind

In some cases I think you're assessment of my behavior is fair. I was frustrated when I wrote my original comment. However I'd also like to point out that you've reacted with plenty of emotion of your own.

Sometimes tone & nuance is lost over the internet. Sometimes I let my emotions run a little too hot too.

So I'd like to sincerely apologize for any offence I've caused. Despite how I feel about angular, it's great work you all do here and you should know that I do appreciate it. So from me to you, thank you, sorry, here's an olive branch - and keep up the great work.

<3

**Comment by wesleycho** [comment] 2015-10-09 04:01
I stand by all my comments in the context of the original discussion - they are merely labels of the the behavior exhibited prior. They are not *ad hominem* as they are descriptions of the behavior. Not once did I say things that don't follow from the behavior such as "you're a terrible person" or "you're a liar" - I held my tongue.

The poor attitude part was that the aforementioned comments were counterproductive towards coming towards accomplishing the end goal of trying to figure out a way to try to meet your needs - I ended up writing an essay instead of writing code :wink: , and all people experienced emotional blowback instead before we moved this towards trying to resolve the issue.

It looks like we all calmed down some, and I accept your apology, as well as apologize if my characterizations caused you distress.

Do you have thoughts on my assessment of options for finding a way to globally configure the templateUrl? I would still like to try to choose an approach to get this in the library to help simplify people's code.

**Comment by aariacarterweir** [comment] 2015-10-09 04:21
Thanks for accepting my apology @wesleycho, I really don't want to cause offence.

`I do not see a good solution here that does not result in pain`
I agree now that I understand the matter more clearly.

Obviously on build, everything will go into $templateCache which also makes sense. However during local dev when the developer does not wish to build to test changes I see the value in having something like option 2, with a 'fallback' of option 3.

This meaning that option 2's custom template takes precedence over the base path set in option 3. Right now there is a way (as you pointed out before - and indeed I think you developed this functionality) to change the template per directive so maybe that can stand in for option 2.

From a user-end perspective this makes sense to me. There may be use cases where this doesn't make sense however and it may not even be possible at all.

**Comment by BobbieBarker** [comment] 2015-10-09 05:55
"However during local dev when the developer does not wish to build to test changes"

If you're using proper tooling isn't that a null point?

**Comment by Foxandxss** [comment] 2015-10-09 10:16
I highly recommend you @aariacarterweir to cache your templates even in development. There are some race conditions between template loading and directive initialization that can't be really avoided (even when I don't think we have this issue here).

So it is highly recommended by the angular team that you always cache your templates when working with them.

It shouldn't be a problem with proper tooling. You can have a task (gulp, but include others) that looks for every template in your app and cache them into `$templateCache` automatically. That works good for dev and prod. Look for `gulp-angular-templatecache` for example.

**Comment by ProLoser** [comment] 2015-10-09 17:18
@Foxandxss race conditions from templates sounds like poor directive design :/

**Comment by Foxandxss** [comment] 2015-10-09 17:20
@ProLoser Angular team doesn't have the same opinion.

**Comment by pkozlowski-opensource** [comment] 2015-10-09 17:21
@ProLoser what @Foxandxss was saying is that in ng2 compiler sync and async compilation goes through 2 different paths and you could, in theory, run into different issues (we add the time component here, as soon as we fetch things from the server). But I'm not sure if $templateCache changes much here, as we still go through the asyn path

**Comment by Foxandxss** [comment] 2015-10-09 17:23
To be concrete. I have a directive which I initialize manually (makes sense that way), there is no human way to wait until a template is loaded so I can trigger the initialization. The official response to that, cache all your templates beforehand.

**Comment by SoundLogic** [comment] 2015-10-16 16:40
you could just use this helper to pass a template to `template` rather than using `templateUrl` (I think most places that have `templateUrl` also have `template` options?):

```javascript
(function () {
    'use strict';

    angular
        .module('app')
        .factory('templateHelpers', templateHelpers);

    templateHelpers.$inject = ['$http', '$templateCache'];

    function templateHelpers($http, $templateCache) {
        var service = {
            getTemplatePromise: getTemplatePromise
        };

        return service;

        function getTemplatePromise(templateUrl) {
            return $http.get(angular.isFunction(templateUrl) ? (templateUrl)() : templateUrl, { cache: $templateCache }).then(function (result) { return result.data; });
        }
    }
})();

**Closed** 2015-10-16 22:07 UTC
Labels: needs: investigation
