### ISSUE TITLE
Carousel does not do smooth transitions in v0.13.0

### ISSUE THREAD

**Issue by canebat** [angular-ui/bootstrap#3752] opened 2015-06-03 19:14 UTC
The Carousel no longer smoothly transitions into the next slide in v0.13.0.  What happens now is it instantly switches to the next slide.

It was working in v0.12.1.

**Comment by rvanbaalen** [comment] 2015-06-03 19:42
Use the search please. Duplicate of #3648

From that thread:
> Adding the ngAnimate dependency solved this issue

**Closed by rvanbaalen** 2015-06-03 19:42 UTC
Labels: component: carousel, needs: plunkr, type: ngAnimate
