### ISSUE TITLE
Close button for popovers

### ISSUE THREAD

**Issue by krnlde** [angular-ui/bootstrap#3906] opened 2015-07-07 13:11 UTC
I had a few discussions and a lot of testing around with snippets from stackoverflow and the rest of the internet to accomplish the goal. The best solution I ended up with is the following:

directives.js
```js
app.directive('dismiss', ['$rootScope', '$timeout', function ($rootScope, $timeout) {
  return {
    restrict: 'A',
    link: function (scope, $element, attrs) {
      $element.on('click', function () {
        $timeout(function () {
          var $context = $element.closest('.' + attrs.dismiss);
          var $contextScope = $context.scope();
          $contextScope.$apply(function () {
            $contextScope.isOpen = false;
          });
        });
      });
    }
  };
}]);
```

popover-content.html
```html
<div id="my-content">
  <button type="button" class="close" data-dismiss="popover" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  // ... stuff
</div>
```
It at least works, but it has one catch: When I closed it via the dismiss I'll need to click 2 times on the opener again since I don't have access to the closure logic of the tooltip (e.g. `hide()`, `hideTooltipBind()` or `removeTooltip()`).

Here's the thing: I really want to use bootstrap-ui - [all solutions](http://stackoverflow.com/a/28447475/622041) in the internet suggested a new directive which makes your popoverTemplate directive obsolete.

Any suggestions?

**Comment by realityking** [comment] 2015-07-07 13:58
This is closely related to #590. Unfortunately no solution there either.

**Comment by krnlde** [comment] 2015-07-07 14:12
It is and this [plunkr](http://plnkr.co/edit/iiP0t8?p=preview) seems to work so far. I will test it the next few days and give feedback.

**Comment by krnlde** [comment] 2015-07-08 08:54
Just an update: Right now this plunkr is restricted to `popover-template` and will not work with `popover`. Further updates will be discussed in the #590 directly.

**Comment by wesleycho** [comment] 2015-07-21 05:22
One cannot rely on `element.scope()` since it does not work if `$compileProvider.debugInfoEnabled(false)` is run.

Maybe exposing a function like `$scope.$close` in the tooltip service would be able to create support for this in the popup component.

**Comment by icfantv** [comment] 2015-07-28 03:45
@wesleycho it'd be nice to have an option as to whether or not to show the close button, but the problem is, with custom triggers, we won't know whether or not the trigger makes it so that the close button is even accessible.  i like the idea of exposing a function for closing - would something similar to $modal's close promise be worth it?

**Comment by wesleycho** [comment] 2015-07-28 03:46
I don't think UI Bootstrap should have a close button built in - having a `$close` function on `$scope` would allow users to implement one nicely for their popups though, which is the point of my suggestion.

**Comment by icfantv** [comment] 2015-07-28 03:50
Yea, $modal can't really have one by default since the template can really be anything.

**Comment by icfantv** [comment] 2015-08-27 03:34
Closing this as #590 has been addressed, and one can easily add a close button in the header of the popover or override the template and do it.

**Closed by icfantv** 2015-08-27 03:34 UTC
Labels: component: popover, PRs plz!, type: enhancement

**Comment by mootieth** [comment] 2017-02-16 04:26
fghfhdsghbdsgb

**Comment by mootieth** [comment] 2017-02-16 04:27
egewrgergergegerge

**Comment by mootieth** [comment] 2017-02-16 04:27
dfgdsfgdegsdfg
