### ISSUE TITLE
Progress bar with multiple bars doesn't pass scope variables to bars

### ISSUE THREAD

**Issue by blessingc** [angular-ui/bootstrap#3838] opened 2015-06-19 01:11 UTC
When I use <progressbar> it works correctly, but when I use <progress><bar> it won't take what I specify in the "max" scope. It only uses 100 as the max.

In my plunker you'll see I have each bar set to 50, and the max set to 500, but the whole bar is already full.
http://embed.plnkr.co/N5JEOPFOHo44jktPp8kt/preview

I guess it makes sense if you assume it's percentages instead of just values, but the full progressbar doesn't work that way so I figured this wouldn't work that way either.

**Comment by groupsky** [comment] 2015-06-23 07:38
Possible duplication of #3618

**Comment by wesleycho** [comment] 2015-06-27 04:05
Ah, missed this issue - this sounds like a duplicate of #3618, which is now fixed in `master`

**Closed by wesleycho** 2015-06-27 04:05 UTC
Labels: component: progressbar
