### ISSUE TITLE
Datepicker can no longer bind to a string date representation

### ISSUE THREAD

**Issue by cen1** [angular-ui/bootstrap#4690] opened 2015-10-22 14:54 UTC
Maybe I am missing something but this could be a regression.

Datepicker can no longer bind to a string representation of a Date. If I receive a JSON object from REST API that contains date as "1989-07-12T22:00:00.000+0000" it should be possible to bind it directly to datepicker. This used to work in 0.12.x but seems to be broken in 0.14.2.

Plunker: http://plnkr.co/edit/JLqDTMNl9tlQ5E831c4x?p=preview
example.js line 4

**Comment by icfantv** [comment] 2015-10-22 15:54
@cen1, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.

This was changed and is documented [here](http://angular-ui.github.io/bootstrap/#/datepicker).  `ng-model` must be a date object.  There were too many issues in parsing user strings so we now require a date object.

Additionally, this is also a duplicate of #4662, #4554, #4424, #4324, and probably more.  Please search both open and closed issues before entering anything.

**Comment by wesleycho** [comment] 2015-10-22 15:54
This is an intentional breaking change, as one can see in the changelog [here](https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md#0132-2015-08-02).

There are cross-browser issues with supporting it as a string, so we removed support.

**Closed by icfantv** 2015-10-22 15:54 UTC

**Comment by cen1** [comment] 2015-10-22 16:25
So what is the alternative? We have to instantiate each date now?

**Comment by icfantv** [comment] 2015-10-22 16:27
@cen1, solutions were posted in those other issues.  If you know that all your dates from the server are in a certain format you can use an HTTP interceptor to convert them to date objects - or you can do it in your own service.  Whatever you want.

And yes.  You need to pass in a JS `Date` object so you will need to construct one on your end.

**Comment by cen1** [comment] 2015-10-22 16:41
Sorry for not seeing other issues. 
It seems to me that this could be solved without breaking it. If there was an extra option to tell datepicker in what format to expect the string for example.

**Comment by wesleycho** [comment] 2015-10-22 16:44
No, because of how munged the logic was, where state was difficult to follow, and the cross-browser issues with string representations is completely unsolvable - it was a broken feature without a fix.

**Comment by aro1976** [comment] 2017-02-05 00:32
Even though you say it was broken feature in several browsers, it used to work great in my application. 

Actually I had used to hold all form information inside a single object, that would be used as the payload in every REST call. 

Now I have to create another object, just to hold the dates and convert manually, whenever I have to call the backend API in several places in my application. 

This is one of the dumbest API breaking decisions I've ever seen.
