### ISSUE TITLE
Mouse cursor doesn't show as hand hovering on tab header

### ISSUE THREAD

**Issue by elgs** [angular-ui/bootstrap#5247] opened 2016-01-14 15:45 UTC
"name": "angular-bootstrap",
"version": "1.0.3",

See the example code here: http://plnkr.co/edit/?p=preview

**Comment by icfantv** [comment] 2016-01-14 15:54
this is because we had to change the tab template to use `<div>` instead of `<a>` to prevent a bug whereby browsers were interpreting the click as a navigation and the page was reloading.  Let me look at the Bootstrap CSS to see what they do and we may need to add `cursor: pointer` to our `tab.css`.

**Comment by icfantv** [comment] 2016-01-14 15:58
This is working on our demo page and your plunker link is invalid.

**Comment by icfantv** [comment] 2016-01-14 15:59
I'm closing until this is fixed and it can be confirmed that it's a legitimate bug.

**Comment by elgs** [comment] 2016-01-14 16:11
The plunker link is from your demo page. The plunker link is the real working code. That should count. Your demo page could use a different set of source code. I don't think your demo page should count. You should not close this ticket until it's fixed or you rejected it.

**Comment by icfantv** [comment] 2016-01-14 16:20
@elgs, the plunker is a button that when you click sends our tab demo HTML/JS to plunker to create a new, working one from which you can test stuff out.  If you look at a legitimate plunker URL, it has an ID string after the URL - the one you pasted does not.

Our demo page does not use different source code - it uses the exact same code for the project - not doing this defeats the entire purpose of having a demo page.  You can see this by executing a build yourself and looking in the `dist` folder at the `index.html` file that is created.

RE your comment about not closing a ticket until it's fixed or rejected:  please read my comments on your other issue entered (that I also closed due to not following instructions, #5248).  Researching every issue someone enters can take quite a bit of time.  Basically, it boils down to this:  if people cannot be bothered to take the time to read our documentation for how to properly enter issues (which makes our jobs enormously easier) then why should we enable that behavior with negative reinforcement by doing a person's work for them?

**Comment by elgs** [comment] 2016-01-14 16:34
Hmmm... interesting. When I clicked the blue Edit in Plunker button, it indeed showed that url in my browser bar. But indeed, it's a wrong url. What you said is correct. Now I clicked the save button, and a new url is generated: http://plnkr.co/edit/GZyaXHpYWVLoypXWSldf?p=preview

**Comment by icfantv** [comment] 2016-01-14 16:55
Thank you.  I have confirmed that this is a bug and have a fix.

**Comment by icfantv** [comment] 2016-01-14 17:20
@elgs, I'd forgotten we had this listed in our breaking changes section [here](https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md#breaking-changes) so I cannot guarantee that #5250 will be merged.  However, this was before we realized we need to add our own `tab.css` file to manage the changes of switch to a `<div>` from an `<a>`.

Unfortunately, this also means you did not read our CHANGELOG or did not read it thoroughly enough.  This goes back to my previous statements about respecting our time by putting forth the effort to properly research the issue on your end first.  I hope by now you can put yourself in our shoes to see how much time this takes (and this is just ONE issue).  Imagine having dozens of issues and doing this in your spare time.

**Comment by elgs** [comment] 2016-01-14 17:37
@icfantv ok, I read the follow statement from the breaking changes:

tab: This causes the cursor style to be removed from the tab - implement CSS on the .uib-tab > div selector, or similar, accordingly

Does it mean I should implement something like this in my own css code?

```
.uib-tab > div {
   cursor: pointer;
}
```

I understand your time is precious. My time is also precious. I would certainly post my problem here rather than spending hours to figure it out, unless I'm really interested in the dirty details of the code. I assume people with expertise or who had similar problems could give a hint just in a minute.

If you use that fact that it is being listed in the breaking changes as an excuse that this is not a problem and may not fixed, I would assume this is a new feature of the `uib-tab`, rather than a bug at all. If this is the case, I have no problem, and I apologize your time being wasted by me.

**Closed** 2016-01-14 21:07 UTC
Labels: component: tab
