### ISSUE TITLE
min-date attribute does not disable the day prior to the given min-date

### ISSUE THREAD

**Issue by Asvarduil** [angular-ui/bootstrap#3437] opened 2015-03-25 16:29 UTC
Reproduction Plunker can be found [here](http://plnkr.co/edit/XdUTSlx9koKFHctohdlg?p=preview)

**Steps to Reproduce:**
 # In the reproduction plunker, observe that '2000-01-02' is pre-set as the min-date for the datepicker.
 # Click the text field to open the calendar
 # Navigate to January 2000
 # Observe that 1/1/2000 is selectable

**Observed Results:**
1/1/2000 is selectable, with a min-date of 1/2/2000.

**Expected Results:**
1/1/2000 should not be selectable, with a min-date of 1/2/2000.

**Comment by RobJacobs** [comment] 2015-03-25 18:13
If you use the date format you specified (MM/dd/yyyy - 01/02/2000) or bind to an actual date it works as expected.

**Comment by Asvarduil** [comment] 2015-03-25 19:10
That's not noted in the documentation.  I referred to the sample code snippet.  I'll change that and report on the result.

**Comment by RobJacobs** [comment] 2015-03-25 19:25
Let's give others a chance to comment, I'm not sure if that's the intended behavior or not.

**Comment by chrisirhc** [comment] 2015-03-30 05:01
Actually, there is a bug here, if the input is a string, we're not parsing it with the format specified. I would've expected that this would be resolved by changing the format to `yyyy-dd-MM`.
We should also clarify this behavior on the documentation once it's fixed.

Plunker with reproduction:
http://plnkr.co/edit/bUVOwxo2eDM1pkvpminW?p=preview

**Comment by stevecavanagh** [comment] 2015-05-08 04:01
I think my PR #3606 will cover this one. It considers the format when parsing the min-date and max-date.
https://github.com/stevecavanagh/bootstrap/blob/fix(datepicker)MinMaxInputValidation/src/datepicker/datepicker.js#L601

**Comment by wesleycho** [comment] 2015-11-03 05:50
Can reproduce [here](http://plnkr.co/edit/1txYUH9kbpD5e0C5acLT?p=info).

This looks like potentially a timezone bug because of the manual string conversion into a date object.

**Comment by davious** [comment] 2015-11-27 00:08
Much of this boils down to how javascript interprets the `MM-dd-yyyy` format.
```
new Date('1/2/2000')
Sun Jan 02 2000 00:00:00 GMT-0500 (EST)
new Date('2000-01-02')
Sat Jan 01 2000 19:00:00 GMT-0500 (EST)
```

**Closed** 2015-12-14 19:49 UTC
Labels: component: datepicker, PRs plz!, type: bug
