### ISSUE TITLE
Collapse broken in 0.13.0

### ISSUE THREAD

**Issue by NitroInside** [angular-ui/bootstrap#3676] opened 2015-05-15 15:38 UTC
In 0.12.1 'collapse' works well, but in 0.13.0 the transition is lost. The element just hide/shows in a frame.

**Comment by rvanbaalen** [comment] 2015-05-15 16:02
Demonstrate in a plunkr please. And since 0.13.0, ngAnimate is a requirement for transitions and animations. Please include ngAnimate and try again. 

We know, the docs still lack this information.

**Comment by EvilJohnny** [comment] 2015-05-22 10:46
@rvanbaalen I was having exactly the same problem. Including ngAnimate fixes it :+1: 

And yes, it would be very useful to include a heads up for this in the docs... I've been looking around and testing stuff for one an hour before reaching this post :laughing: :laughing: 

But anyways, thanks a lot for all the hard work!!!!

**Comment by NitroInside** [comment] 2015-05-23 21:09
@rvanbaalen I have included "angular-animate" version 1.3.0-rc.4 via Bower since a long time in my project (and just broke with this version of angular-ui-bootstrap)... can I use that module or must be ngAnimate mandatory?

And  I think the error is due because I'm using this module via Bower (through the wrapper https://github.com/angular-ui/bootstrap-bower) and it has no other dependencies than Angular, so I suppose that their bower.json must include the dependency. I'm I right?

Thank you so much for the help and hard work!

**Comment by rvanbaalen** [comment] 2015-05-23 21:22
@EvilJohnny Sorry for that pal :wink: We too make some mistakes sometimes haha.

@NitroInside It's never recommended to use an Release Candidate version if there's a stable release available instead.

**Comment by NitroInside** [comment] 2015-05-24 03:25
@rvanbaalen totally agree with that, is an inherited project and it's dependencies are being gradually upgraded =)

**Comment by TimonVS** [comment] 2015-05-28 15:17
@NitroInside I created a gist with my solution for ngAnimate 1.4: https://gist.github.com/TimonVS/a40514121fb220495d8c.

**Comment by pcnate** [comment] 2015-06-03 20:42
I have a similar issue. The element is hidden on page load, I set an initial `$scope.collapse = false;` as the first line in my controller. It just pops into view well after page load with no animation. Animation works after that.

**Comment by wesleycho** [comment] 2015-06-04 17:56
@pcnate can you reproduce this in a [Plunker](http://plnkr.co/)?

**Comment by lucienbertin** [comment] 2015-06-05 09:37
I had problems with this too, could you update the dependencies on the [home page](http://angular-ui.github.io/bootstrap/#/getting_started)

also, the plunker for the collapse does not work due to the missing ngAnimate so that's a bit desorienting

**Comment by arn80** [comment] 2015-06-11 10:43
I have the same issue with v0.13.0 as @pcnate :

"The element is hidden on page load, I set an initial $scope.collapse = false; as the first line in my controller. It just pops into view well after page load with no animation. Animation works after that."

In v0.12.1 and older there was no issue regarding this.
It happens the most in Chrome and Firefox. IE seems to handle it better !?!

I have made a <a href="http://plnkr.co/edit/VSbgaHR4vlxOyAz69iVz?p=preview" target="_blank">Plunker</a> with the issue.

Try to Run / Stop the Plunker a few times, because the issue is not as obvious in all cases.

**Comment by wesleycho** [comment] 2015-06-11 14:53
I'm confused - is the expectation that there is an initial animation to the uncollapsed state?

**Comment by pcnate** [comment] 2015-06-11 15:39
**0.12.x results**

1. `$scope.collapse = false`
2. Item is visible
3. Animation works by toggling `$scope.collapse`

**0.13.0 results**

1. `$scope.collapse = false`
2. Item is hidden
3. n seconds later element pops into view with no transition
4. Animation works by toggleing `$scope.collapse`

I am experiencing this on Chrome 44.0.2403.39

**Comment by wesleycho** [comment] 2015-07-31 14:17
This should currently be fixed on `master`.

It should also be noted, `ngAnimate` is an optional dependency - the animations won't occur without it, which allows users the choice.

**Closed by wesleycho** 2015-07-31 14:17 UTC
Labels: component: collapse, needs: plunkr, type: ngAnimate
