### ISSUE TITLE
windowTemplateUrl how to acess $scope

### ISSUE THREAD

**Issue by jareddlc** [angular-ui/bootstrap#3384] opened 2015-03-13 20:42 UTC
I am trying to use windowTemplateUrl with a custom template to reference a controller so I can toggle a class on the top level div such that I can use ng-class with the template. I tried various ways to try to get the template to use a controller without success. 

template:
```HTML
<div tabindex="-1" role="dialog" class="modal fade" ng-class="{in: animate}" ng-style="{'z-index': 1050 + index*10, display: 'block'}" ng-click="close($event)">
    Hello: {{test}}
    <div class="modal-dialog" ng-class="{'modal-sm': size == 'sm', 'modal-lg': size == 'lg'}"><div class="modal-content" modal-transclude></div></div>
</div>
```

JS
```javascript
myModal = $modal.open({
      templateUrl: '/static/partials/myModal.html',
      controller: 'MyModalCtrl',
      backdrop: 'static',
      keyboard: 'false',
      windowTemplateUrl: '/static/partials/template_myModal.html'
    });

********

.controller('MyModalCtrl', ['$scope', '$modalInstance', function MyModalCtrl($scope, $modalInstance) {
  $scope.test = ", world!";
```

I would expect my modal to show: "Hello, world!" , but it isn't and i cannot find any documents as how to do so.

**Comment by jareddlc** [comment] 2015-03-13 23:27
I found the bug: it has been PR'd #3133 please merge

**Comment by wesleycho** [comment] 2015-03-17 06:21
I have a question here - if you provide a scope via the `scope` option, shouldn't you have it available in the `modal-window` directive template?

**Comment by bORm** [comment] 2015-04-13 19:07
+1

**Comment by rvanbaalen** [comment] 2015-06-03 20:53
@jareddlc Can you please answer @wesleycho's question?

**Comment by jareddlc** [comment] 2015-06-03 22:17
@rvanbaalen I cant quiet remember, I know i've tried various ways and nothing ended up working correctly. I am certain I tried doing just that, but when you pass $scope I believed it only looked for specific objects. I ended up abandoning that entire feature because I couldn't get it working.

**Comment by rvanbaalen** [comment] 2015-06-03 22:38
Either way; please add a plunkr reproducing your problem.

**Comment by readme42** [comment] 2015-07-30 10:55
+1

Same issue here. Would like to define different modal wrapper by using windowTemplateUrl for wrapper like this:

```html
<div class="modal-content">
    <div class="modal-header">
        <h3 class="modal-title">I'm a modal!</h3>
    </div>
    
    <div class="modal-body" modal-transclude></div>

    <div class="modal-footer">
        <button class="btn btn-primary" ng-click="$close(vm.selected)">OK</button>
        <button class="btn btn-warning" ng-click="$dismiss('dont need it')">Cancel</button>
    </div>
</div>
```

and then using different templateUrls for different content.

**Comment by wesleycho** [comment] 2015-09-01 20:19
Closing due to needing more information - feel free to provide more information if this is indeed an actual issue.

**Closed by wesleycho** 2015-09-01 20:19 UTC
Labels: component: modal, needs: info, needs: plunkr
