### ISSUE TITLE
Dropdown label doesn't update properly when Google map is present

### ISSUE THREAD

**Issue by soul2197** [angular-ui/bootstrap#3517] opened 2015-04-08 20:43 UTC
If you have a Google map before the dropdown, the label only updates when you hover the mouse over it.

See simplified test case here: http://codepen.io/soul2197/pen/azgowj?editors=101

Versions:
Angular: 1.3.15
Angular Bootstrap: 0.12.1
Bootstrap: 3.3.2
Google Maps: v3

**Comment by soul2197** [comment] 2015-04-08 20:47
Also filed with google maps: https://code.google.com/p/gmaps-api-issues/issues/detail?id=7881

**Comment by Delapouite** [comment] 2015-04-10 13:35
It appears to be Chrome specific, I can't reproduce it on Firefox

**Comment by rvanbaalen** [comment] 2015-04-13 19:37
Have you tried implementing http://angular-ui.github.io/angular-google-maps/?

I can indeed confirm that this issue appears in Chrome. Also in Safari.

**Comment by rvanbaalen** [comment] 2015-04-13 20:10
I've done quite some testing in this plunkr:

http://plnkr.co/edit/nQvMHyfsEvZiFiRZ4KcD?p=preview

So far I can only conclude that this is some glitch caused by Google Maps. As you can see, the second and third dropdown in my plunkr works just fine. Unfortunately it has nothing to do with it (the third dropdown) being wrapped in another `<div class="container">` element.

I'm closing this now as it doesn't seem to be an issue related to UI Bootstrap but rather a Google Maps issue.

**Closed by rvanbaalen** 2015-04-13 20:10 UTC
Labels: browser: chrome, browser: safari, component: dropdown, needs: investigation
