### ISSUE TITLE
There is no way to append the selected value into the existing input value

### ISSUE THREAD

**Issue by sh977218** [angular-ui/bootstrap#6249] opened 2016-09-20 21:33 UTC
I tried to implement this feature and google to find the solution. Then I realize there is no way to do this. Can we have this feature in the future?

**Comment by wesleycho** [comment] 2016-09-25 01:01
I have no clue what you are talking about - can you explain in more detail, and have a reproduction of the general situation that helps with understanding the scenario?

**Comment by wesleycho** [comment] 2016-10-02 12:44
Closing due to lack of actionable information

**Closed by wesleycho** 2016-10-02 12:44 UTC
Labels: needs: info, needs: plunkr
