### ISSUE TITLE
Popover to remain open when hovering over it

### ISSUE THREAD

**Issue by boillodmanuel** [angular-ui/bootstrap#3515] opened 2015-04-08 17:09 UTC
Popover triggered by mouseenter event hide himself as soon as the mouse leave the target element. And it's impossible to click on a link which was in the popover.

I've found some solution in SO which can help for the PR :
- link to SO: http://stackoverflow.com/questions/20267967/create-hoverable-popover-using-angular-ui-bootstrap
- direct link to jsfiddle: https://jsfiddle.net/6awhrcec/

And another link with a vanilla js solution: http://jsfiddle.net/WojtekKruszewski/Zf3m7/22/

Could you add this feature?

**Comment by RobJacobs** [comment] 2015-04-08 19:47
The popover-trigger attribute allows you to define which triggers show and hide the popover using the following format:
 
    popover-trigger="showtrigger hidetrigger"

The directive is simply doing the following for you:

    element.bind(showtrigger, showTooltipBind)
    element.bind(hidetrigger, hideTooltipBind)

The [plunker](http://plnkr.co/edit/ScAI7a5lliaCpxWPVaA6?p=preview) demonstrates using  'mouseenter click' trigger that will leave the popup open during interaction.  While this get's us most of the way there, it's not as stable as I would like it to be.  

I have been working on a blurNotChildren trigger that will not call the close method until the trigger element or the popup are no longer the document.activeElement.  Here is a [plunker](http://plnkr.co/edit/C6peZ8ZEWgSlcfw3Q65E?p=preview) that demonstrates that approach.

The other ways I've seen of accomplishing this require listeners on several elements and document body click which get's messy to clean up and doesn't necessarily account for a blur event.

**Comment by chrisirhc** [comment] 2015-04-13 07:26
I'm marking this as Purgatory as I think this sort of custom handling should be left to the user/developer. Instead, we should expose the triggers through a directive controller to allow users to show/hide the tooltip/popovers with their custom handling logic.

If this becomes a high frequency problem, we can consider it further. However, right now, this adds a new feature that isn't there on Bootstrap and I'm worried about bloating this directive with features that most users wouldn't use.

**Comment by tmcgee123** [comment] 2015-04-23 16:26
I had a similar issue and addressed it by creating a close delay that I could set through the popover directive. The problem is that if you attempt to override the fade class that bootstrap provides or attempt to hijack the listeners, things get a little wonky. I have created this feature via PR #3576 https://github.com/angular-ui/bootstrap/pull/3576

**Comment by erquhart** [comment] 2015-06-02 17:30
@chrisirhc you mentioned exposing the triggers to allow custom handling logic - is that on the roadmap by chance?

**Comment by plong0** [comment] 2015-07-13 23:31
hmm... I found this link for plain bootstrap:
http://jsfiddle.net/wojtekkruszewski/zf3m7/22/

this is exactly the functionality I am looking for, but not sure how to implement in angular-ui-bootstrap

**Comment by tmcgee123** [comment] 2015-07-16 14:56
I believe that you should have specific control over the delay to close the tooltip/popover, as you have control over the opening delay it only makes sense. Creating a custom trigger often becomes a little hacky, as the template that get's shown is in a completely different element than the popover when it is being appended to the body of the page.

**Comment by icfantv** [comment] 2015-08-03 05:38
This issue sounds identical to #3855.  @wesleycho, I think we can close this.

@boillodmanuel, please see the comments in the referenced issue above for the proper solution.

**Comment by wesleycho** [comment] 2015-08-03 05:41
Closing as per comments.

**Closed by wesleycho** 2015-08-03 05:41 UTC
Labels: component: popover, type: enhancement

**Comment by odedkeren1** [comment] 2016-08-24 09:57
I have solved it in a very cleaned way and thought to share it: .popover is being created not as a child of the uib-popover so the idea is to wrap uib-popover with a parent and to control show&hide on hovering the parent. .popover and uib-popover are children of this parent so just left to set popover-trigger=none and you have what you are wishing for.

I created a plunk example: https://plnkr.co/edit/6vzrrH1KUyQeLHDz1hWp?p=preview

**Comment by evenicoulddoit** [comment] 2017-06-15 15:24
Here's another pretty clean way, which doesn't require that the tooltip and the trigger elementactually overlap:

https://plnkr.co/edit/GBjrZiGqXSucPiiXTg0C?p=preview

Essentially, in order to allow the user to "jump" between the elements, we just need to add some sort of grace period (in this case, 500ms) after which we mark the popover as closed.

**Comment by odedkeren1** [comment] 2017-06-15 16:01
evenicoulddoit: its the same thing as in my answer the only difference is that you added popover-popup-close-delay

**Comment by evenicoulddoit** [comment] 2017-06-16 07:57
@odedkeren1 The timeouts in my version allow the tooltip to not be immediately touching the parent, though the actual solution I've come up with for work also works for `tooltip-append-to-body`

**Comment by VenkatRamReddyK** [comment] 2017-11-20 22:31
Easiest way to have a mouse-event using uib-popover
Look at the below working example !
https://plnkr.co/edit/9oMYadXPNJcRPrig71iF?p=preview

**Comment by odedkeren1** [comment] 2017-11-21 17:32
@VenkatRamReddyK 
its the same as my answer.
and by the way you have popover-trigger="outsideClick" no meaning to have it, you can use "none"

**Comment by bmrinal** [comment] 2017-11-28 03:25
@evenicoulddoit it doesn't work for popover-append-to-body="true". how this can be resolved?

**Comment by evenicoulddoit** [comment] 2017-11-28 08:16
@bmrinal https://plnkr.co/edit/kciyLQ6LZQRNdkj1xQNB?p=preview

**Comment by bmrinal** [comment] 2017-12-04 11:04
@evenicoulddoit  it still closes the popover when cursor is inside it

**Comment by changus** [comment] 2017-12-06 18:13
@bmrinal @evenicoulddoit I am in need of it working with popover-append-to-body="true" as well!
