### ISSUE TITLE
typeahead-editable binding

### ISSUE THREAD

**Issue by DavidBanksNZ** [angular-ui/bootstrap#4947] opened 2015-11-24 20:27 UTC
When trying to replace old directive names with the `uib-` prefixed versions, I run into `$parse` errors with `uib-typeahead`. Previously, with the un-prefixed directive, I could use `typeahead-editable="{{editable}}"`  where editable is defined on the controller scope, but now this causes a `$parse` error. See http://plnkr.co/edit/vmF98QeXxj5E5pDRYOSQ?p=preview

**Comment by icfantv** [comment] 2015-11-25 04:08
This is still a bug in `master`.

**Comment by icfantv** [comment] 2015-11-25 04:08
@DavidBanksNZ, thanks for catching this.

**Comment by wesleycho** [comment] 2015-11-29 20:43
In this case, this is easy to fix by not using {{ }}, as seen [here](http://plnkr.co/edit/IpRIWAQBAIVuc6GiB4GX?p=preview)

**Comment by wesleycho** [comment] 2015-11-30 06:37
Going to close this as not a bug - did some git history tracing, it doesn't look like this was officially supported with interpolation for quite a long time, if ever.

**Closed by wesleycho** 2015-11-30 06:37 UTC
Labels: component: typeahead

**Comment by DavidBanksNZ** [comment] 2015-11-30 06:43
Yes it's an easy workaround thanks. Perhaps it used to be 'unintentionally supported'
