### ISSUE TITLE
angular-bootstrap version 0.14.x and tooltip-append-to-body="true" causes vertical scroll bar to flicker.

### ISSUE THREAD

**Issue by shenlong** [angular-ui/bootstrap#4613] opened 2015-10-14 07:04 UTC
Hi Guys, I have the scroll bar appearing and changing size issue for this new release angular-bootstrap version 0.14.2 when tooltip-append-to-body="true".

Plunker as follows:
http://plnkr.co/edit/HxTIllqhV0QSmDoZGtB3?p=preview

**Comment by icfantv** [comment] 2015-10-14 13:41
Closing as a duplicate of #4458.  Please search both open and closed issues before opening one.  For my part, I have been unable to reproduce this.

**Closed by icfantv** 2015-10-14 13:41 UTC

**Comment by shenlong** [comment] 2015-10-14 13:47
Hi @icfantv,
In the plunker i provided, i have tested with 0.14.2 and it seems to affect only when tooltip-append-to-body="true", so i am not really sure if it is a duplicate.

**Comment by icfantv** [comment] 2015-10-14 15:55
I still can't reproduce this.  What platform/browser are you using?

**Comment by RobJacobs** [comment] 2015-10-14 16:03
I don't see the problem either?  FYI, the example in your plunk, tooltip-append-to-body is set to false. I set that value to true and still didn't see the issue.

**Comment by shenlong** [comment] 2015-10-14 17:26
I updated the plunker. you need to:
1. resize your vertical height to a small size window
2. make sure you see the vertical scroll.
3. mouse over and out and over.

Did you see the scroll bar jumping?

**Comment by icfantv** [comment] 2015-10-14 17:47
Ok, I'm on a mac which hides the scrollbar after like 500ms which is why this is so hard to reproduce.  I can see it, but it's VERY hard to reproduce on a mac.

Additionally, this IS a duplicate of #4458 so leaving as closed.

**Comment by RobJacobs** [comment] 2015-10-14 17:47
@shenlong @icfantv I believe this is similar to #4458 with the fix being add top: -9999px and left: -9999px to the tooltip template style [here](https://github.com/angular-ui/bootstrap/blob/master/src/tooltip/tooltip.js#L126).  Here is an updated [plunk](http://plnkr.co/edit/9FQQ767smSUWBcwbQZBZ?p=preview) with those suggested changes.  Here is issue #4458's [plunk](http://plnkr.co/edit/B54wQI?p=preview) with the same changes.

**Comment by icfantv** [comment] 2015-10-14 18:14
@RobJacobs, let's run that by @wesleycho and see if he's good with that.  TBH though, It smells like a hack to me unless this is an industry "standard."

**Comment by wesleycho** [comment] 2015-10-14 18:42
It's a hack, but a well-known one...I don't have a huge opinion on it, and would be fine with it.

**Comment by RobJacobs** [comment] 2015-10-14 18:47
It's documented in [ng-hide](https://github.com/angular/angular.js/blob/master/src/ng/directive/ngShowHide.js#L179) and TWBS uses it for the [modal-scrollbar-measure](https://github.com/twbs/bootstrap/blob/master/less/modals.less#L125) class

**Comment by wesleycho** [comment] 2015-10-14 18:50
Sounds good to me then

**Comment by icfantv** [comment] 2015-10-14 20:22
Works for me as well.  @RobJacobs you wanna make a PR?

**Comment by shenlong** [comment] 2015-10-14 23:43
Hi guys, thanks for the workaround. It looks good.

Background information: This existing issue is prominent when I am using ng-view with static headers. The vertical scrollbar only appears under the ng-view for overflow content. but having this bug will show another vertical scrollbar that appears at the header and since I did not style a slim scrollbar for the page, the re-flow of contents to accommodate 2 scrollbars width makes a annoying flickering.

**Comment by icfantv** [comment] 2015-10-15 04:37
@shenlong, just a head's up that we're committing a fix for this.  The PR is #4623 and should be merged either tonight or tomorrow.  So you won't necessarily have to implement a workaround on your end.

**Comment by shenlong** [comment] 2015-10-15 05:39
Hi icfantv,

Thanks for the heads up. I will prepare my bower for it! Hopefully get it asap as i need to implement the fix on my production site! Cheers!

**Comment by icfantv** [comment] 2015-10-15 15:05
@shenlong, you want `npm` and `grunt`, not `bower`.  In fact, don't use Bower anymore - it's kind of dying off.  Check out that git revision, run an `npm install` and then `grunt` and it will put everything in the `dist` folder.

Looks like that PR was merged so you should be good to go.

**Comment by shenlong** [comment] 2015-10-16 03:42
Hi @icfantv , my production server automatically bowers updates the "bower_component" folder. A gulp script then minifies and modify the link with CDN for production releases.

Will there be official version release for this?
Just curious how frequent do you update the release here: https://github.com/angular-ui/bootstrap/releases and the https://github.com/angular-ui/bootstrap-bower

Even though PR is merged, I need version tracking for third party framework.
