### ISSUE TITLE
modal's backdropClass hook does not work when there is already a modal present

### ISSUE THREAD

**Issue by mrvicadai** [angular-ui/bootstrap#4843] opened 2015-11-08 18:43 UTC
As specified in the [Modal](https://angular-ui.github.io/bootstrap/#/modal) component, we can always use `backdropClass` hook to redefine the className of the backdrop of a new modal. However when there is already an existing modal, and we open another modal on top of it, this option no longer works.

**Comment by wesleycho** [comment] 2015-11-08 19:19
Closing as a duplicate of #2678

**Closed by wesleycho** 2015-11-08 19:19 UTC
