### ISSUE TITLE
Cannot read property 'direction' of undefined after upgrade to 0.13.0

### ISSUE THREAD

**Issue by ScottFred** [angular-ui/bootstrap#3619] opened 2015-05-05 03:20 UTC
After upgrading to 0.13.0, we are getting the following errors when we navigate across a top menu system we implemented; this used to work in 0.12.x

```javascript
TypeError: Cannot read property 'direction' of undefined
    at Object.beforeAddClass [as fn] (ui-bootstrap-tpls.js:615)
    at angular-animate.js:739
    at forEach (angular.js:323)
    at run (angular-animate.js:727)
    at Object.before (angular-animate.js:768)
    at performAnimation (angular-animate.js:1411)
    at angular-animate.js:1217
    at angular-animate.js:539
    at Scope.$digest (angular.js:14358)
    at Scope.$apply (angular.js:14571)
```

------- ui-bootstrap-tpls.js:608 - 616 ------ 
```javascript
function ($animate) {
  return {
    beforeAddClass: function (element, className, done) {
      // Due to transclusion, noTransition property is on parent's scope
      if (className == 'active' && element.parent() &&
          !element.parent().scope().noTransition) {
        var stopped = false;
        var direction = element.isolateScope().direction;  // <----- FAILS here
        var directionClass = direction == 'next' ? 'left' : 'right
```

**Comment by rvanbaalen** [comment] 2015-05-05 04:48
Can you add a plunkr so we can reproduce and debug this ourselves?

**Comment by ScottFred** [comment] 2015-05-05 05:03
We are preparing for a demo and so I may not be able to do this for a few days, but I'll try to get you something.

**Comment by rvanbaalen** [comment] 2015-05-19 17:17
Smells like a ngAnimate issue. ngAnimate should be added separately to your project.

**Comment by iorlas** [comment] 2015-06-02 15:29
Sooo... what's a solution here?

**Comment by rvanbaalen** [comment] 2015-06-02 16:42
@iorlas There is no solution since @ScottFred didn't post a plunkr for us to reproduce the problem yet. When he does, we're able to check what's wrong and draw a conclusion. But it seems like, like I've said in my last comment, you should just include `angular-animate` in your project.

**Comment by iorlas** [comment] 2015-06-02 18:16
@rvanbaalen sadness ;_;
I'll try to make plnkr in spare time, but I'm not sure right now how to isolate problematic code part.
Btw, `angular-animate` is included in project, since its function mentioned in error traceback. But it is definitely something wrong with animation API in ng13, since it was reworked in ng13, I'm not sure.

**Comment by infoTrainingym** [comment] 2015-06-12 15:23
Here a plunker with error:

Version 1.3.16 angular 
http://plnkr.co/edit/aVohFEpxBTlcQYG9cXhE?p=preview

Version 1.4.0 angular

http://plnkr.co/edit/Xq5UfcGdUZX1HITYE3UJ?p=preview

Hope this help

**Comment by infoTrainingym** [comment] 2015-06-12 16:00
See console log erros

**Comment by infoTrainingym** [comment] 2015-06-15 15:12
Hi,

@rvanbaalen, @iorlas  

Any advice or how to deal with this issue? is another thing the error?

regards,

**Comment by Sharkam** [comment] 2015-07-01 09:27
Hello,

is there any news about this error ?

Thanks.

**Comment by ncknt** [comment] 2015-07-15 22:00
Hi,

I ran into the same bug. It looks like the issue is that the ".item" animation tries to access an isolate scope which is defined through the carousel directive (line 342). My code (and the plunkr above) doesn’t use the carousel directive because I just want to use the bootstrap CSS.

So in short, it happens when you try to use .item elements without the carousel directive.

Ideally the animation would be changed so it’d still work if the “.item” has no carousel parent.

In the meantime, you could:
1) use a custom build without carousel (I won’t because of https://github.com/angular-ui/bootstrap-bower/issues/18). That is if you don't use carousel somewhere else in your code.
or
2) rename “item” in the bootstrap CSS and in your code.

**Comment by wesleycho** [comment] 2015-08-05 06:18
The carousel should work properly in 1.3 and 1.4 in `master` with ngAnimate.

Closing this as old.

**Closed by wesleycho** 2015-08-05 06:18 UTC
Labels: needs: investigation, type: ngAnimate
