### ISSUE TITLE
Popover too small and shown with offset

### ISSUE THREAD

**Issue by miguel-guedes** [angular-ui/bootstrap#3412] opened 2015-03-19 17:29 UTC
I've created a test case to illustrate the issue [here](http://plnkr.co/edit/bBCXFX3BmKgsjxYWRlq1?p=preview).  Simply place the mouse over the question mark icons and you'll immediately see that the popovers are shown with an offset compared to the element they refer to **and** with the size is also too small.

Interestingly, this is caused by the `float` property on the `main` selector.  If you disable that property, it works as expected.

I also created a [test case](http://plnkr.co/edit/jczrbu1eGB2fYpQaqwgu?p=preview) using only Bootstrap (no Angular) and it worked as expected.

**Comment by miguel-guedes** [comment] 2015-03-19 17:30
Fix title

**Comment by chrisirhc** [comment] 2015-03-21 22:25
This Plunker seems to be using a very old version of UI Bootstrap. The newest version seems to be less severe.

http://plnkr.co/edit/yymb6IfA1eUwgvpsoRBL?p=preview

Might want to test whether #1848 fixes this.

**Comment by icfantv** [comment] 2015-08-03 06:05
@miguel-guedes, as you pointed out, the CSS styling you added was messing with the position offset so I'm not convinced this is actually a bug in UI Bootstrap.

Popover templates have been added so can you please retest this with more recent versions of both Angular, Bootstrap CSS, and UI Bootstrap and see if the issue is still present?

I'm going to close this, but please feel free to reopen with an updated plunker if you think it's not been addressed.

**Closed by icfantv** 2015-08-03 06:05 UTC
Labels: component: $position, component: popover, needs: investigation
