### ISSUE TITLE
Change keyboard dismissal from modal controller

### ISSUE THREAD

**Issue by emgeee** [angular-ui/bootstrap#3448] opened 2015-03-27 00:01 UTC
Is there anyway to disable the dismissal of the modal via the escape key from within the modal controller? The use case for this would be a modal that makes an http request. When a user opens the modal and is interacting with it, it's convenient to allow them to dismiss the modal via the escape key. Once a request has been sent, however, you want to remove that ability so they modal isn't closed accidentally before the request completes.

**Comment by BobbieBarker** [comment] 2015-03-27 05:29
In my humblest of opinions this request is far to nuanced and based on your specific use case to justify exposing an API to disable certain key bindings.

**Comment by wesleycho** [comment] 2015-03-27 06:31
I don't think this should have been closed so fast.

This has some valid use cases, such as if the intent is to force user action on something.

**Comment by RobJacobs** [comment] 2015-03-27 16:03
See #3371

**Comment by pkozlowski-opensource** [comment] 2015-05-11 16:03
Yeh, this is duplicate of #3371

**Closed by pkozlowski-opensource** 2015-05-11 16:03 UTC
Labels: component: modal
