### ISSUE TITLE
Angular-ui bootstrap rating not working in Bootstrap modal 

### ISSUE THREAD

**Issue by sharmavikram** [angular-ui/bootstrap#5706] opened 2016-03-29 11:42 UTC
Hello Everyone,
### Bug description:
I am using **ui.bootstrap.rating** it is working fine but when i used rating in  **ui.bootstrap.modal**  it show error in console.
### Error
```
angular.js:12722 TypeError: Cannot read property 'end' of undefined
    at B (angular-animate.js:2251)
    at angular-animate.js:2165
    at Scope.$digest (angular.js:16145)
    at Scope.$apply (angular.js:16359)
    at HTMLButtonElement.<anonymous> (angular.js:23939)
    at HTMLButtonElement.n.event.dispatch (jquery.min.js:3)
    at HTMLButtonElement.r.handle (jquery.min.js:3)
```
### Html Code

```
<script type="text/ng-template" id="CommentAndRatingModalContent.html">
          <div class="modal-header bg-aqua">
              <h4 class="modal-title">Comment And Rating of Job
              </h4>
          </div>
          <div class="modal-body">
             <div class="row">
             <div class="col-md-12">
             <div class="form-horizontal">
               <div class="form-group">
                      <label for="rating" class="col-sm-2 control-label">Rating</label>
                      <div class="col-sm-10">
                      <rating ng-model="rate" max="max" read-only="isReadonly" on-hover="hoveringOver(value)" on-leave="overStar = null" titles="['one','two','three']" 
                         aria-labelledby="default-rating">
                      </rating>
                      <span class="label" ng-class="{'label-warning': percent<30, 'label-info': percent>=30 && percent<70, 'label-success': percent>=70}" ng-show="overStar && !isReadonly">{{percent}}%</span> </div>
              </div>
              <div class="form-group">
                <label for="comment" class="col-sm-2 control-label">Comment</label>
                  <div class="col-sm-10">
                        <textarea class="form-control" id="comment" placeholder="Write your comment" rows="5"></textarea>
                  </div>
              </div>
              <div class="form-group">
              <div class="col-md-offset-2 col-sm-10">
              <button type="button" class="btn btn-info pull-right">Comment and rating</button>
              </div>
              </div>
             </div> 
              </div> 
           </div>
         </div> 
      </script>
```

### Controller
```
function WithCommentAndRatingJobAjaxCtrl(items,$scope,DTOptionsBuilder, DTColumnBuilder,$http,UserService,localStorageService, $compile,$uibModal,$window,$log,$stateParams) {
  console.log(items);
  $scope.rate =0;
  $scope.max =5;
  $scope.isReadonly = false;
  $scope.hoveringOver = function(value) {
    $scope.overStar = value;
    $scope.percent = 100 * (value / $scope.max);
    console.log($scope.percent);
  };
}
```
### Versions
Angular: 1.4.9
Bootstrap: v3.3.5
Angular-Ui Bootstrap : v1.1.2

**Comment by wesleycho** [comment] 2016-03-29 12:53
Closing, due to being a support issue and for ignoring the reproduction in Plunker section of the issue template.

**Closed by wesleycho** 2016-03-29 12:53 UTC
