### ISSUE TITLE
Datepicker timestamp validation stills fails

### ISSUE THREAD

**Issue by f1ght4fun** [angular-ui/bootstrap#4802] opened 2015-11-02 09:44 UTC
Can anyone help as it is still not working for me. I'm on the last 0.14.3 release

"1990-08-01T00:00:00" datetime field is not handled correctly in validator func and returns undefined so on validation form fails

angular.IsNumber and angular.IsDate obv return false when trying to parse this timestamp.

As date format is set to dd.MM.yyyy in datepicker so upon trying to execute next if block

if (angular.isString(value)) {
      var date = dateParser.parse(value, dateFormat);
      return !isNaN(date);

it fails because Parser uses exact format.

Any ideas?

**Comment by wesleycho** [comment] 2015-11-02 14:54
We currently are only supporting using date objects in the model due to unfixable cross-browser issues with other formats - can you post a Plunker clearly illustrating your problem?

**Comment by f1ght4fun** [comment] 2015-11-02 15:38
http://embed.plnkr.co/jXyvWEz4ddMBIHHyq7st/preview

Please check.

Also i managed to fix that issue by updating validator function by adding 

else if (!isNaN(Date.parse(value))) {
        return true;
    }

**Comment by icfantv** [comment] 2015-11-02 15:54
@f1ght4fun, I'm sorry, but I'm not able to reproduce this.  [Here's a working plunker](http://plnkr.co/edit/jhVuiGhbWjltzwKDgQHQ) based on our demo site.

**Comment by f1ght4fun** [comment] 2015-11-02 16:01
Well i posted just now where u can see that model is set to string with timestamp and form validates to false. 

What do u mean you cannot reproduce!?

**Comment by icfantv** [comment] 2015-11-02 16:51
@f1ght4fun, my bad.  I missed your error in your plunker.  As @wesleycho pointed out, `ng-model` **MUST** be a Javascript `Date` object and **NOT** a string.

**Comment by icfantv** [comment] 2015-11-02 16:51
Closing as user error.

**Closed by icfantv** 2015-11-02 16:51 UTC
Labels: component: datepicker, needs: plunkr
