### ISSUE TITLE
Typeahead not closing the popup when using ng-touch ng-click on mobile browser

### ISSUE THREAD

**Issue by nishesj** [angular-ui/bootstrap#4047] opened 2015-07-30 12:51 UTC
angular & angular touch version 1.4.3
Android 5.1 chrome 43
http://embed.plnkr.co/zX9ojMXRGBweID9RglZY/preview

**Comment by wesleycho** [comment] 2015-07-30 13:37
I am not able to reproduce this using Chrome's emulation on that Plunker. Is there any other reliable way to reproduce this?

**Comment by nishesj** [comment] 2015-07-30 13:43
I can reproduce this using Chrome's emulation as well.
when the matches are shown eg. if u type A on the input field and if you click the link while the popup is open,  the popup should be hidden but remains open.

**Comment by RobJacobs** [comment] 2015-07-30 14:10
I'm seeing issues being reported (outside of this library) in regards to Android 5 in chrome where touch events are not firing click events.

**Comment by wesleycho** [comment] 2015-07-30 14:14
Ahh, so this is only reproduceable if you click on a link - it sounds like a potential Android bug, and I am not sure there is much we can do about this.

**Comment by nishesj** [comment] 2015-07-30 14:19
Seems like related to this https://github.com/angular/angular.js/issues/9872 but not sure ..

**Comment by wesleycho** [comment] 2015-07-30 14:26
I think in light of that Angular issue, we should not hack around that.

I believe that any fix should be made in ngTouch - if you read the issue and the referenced SO link, it provides a good suggestion for how it can be fixed in Angular.

**Closed by wesleycho** 2015-07-30 14:26 UTC
Labels: component: typeahead
