### ISSUE TITLE
Carousel broken with Angular 1.4.3 + UI-Bootstrap 0.13.2 + ng-animate + modal dialog

### ISSUE THREAD

**Issue by alpeshgaglani** [angular-ui/bootstrap#4119] opened 2015-08-05 20:55 UTC
I'm aware of the issue #3811 , and have the latest fixes from master. The carousel works just fine outside of a dialog box. However, when I use ngAnimate inside a $modal dialog, I see just the first slide. The navigation anchors are hidden, and I cant move to the second slide. Any ideas?

**Comment by wesleycho** [comment] 2015-08-06 00:44
Looks like you are correct to a degree, I am able to reproduce [here](http://plnkr.co/edit/b3ddvoTPVFjBx5H92pFx?p=preview) incorrect behavior of a different nature.

**Comment by wesleycho** [comment] 2015-08-06 00:53
Ah, now I see the behavior you describe (Plunker was behaving weird for me there).

**Comment by wesleycho** [comment] 2015-08-06 01:36
Investigating this, this appears to be a problem with the modal service, and it not being converted to handle $animateCss support. There seems to be some interplay problems between the two due to the new restrictions in ngAnimate.

**Comment by wesleycho** [comment] 2015-08-06 04:30
This should be fixed in `master` now - thanks a lot for this find, I almost cut a new release today before encountering this issue (& the tooltip/popover one).

I highly recommend checking out the comments in #4121, it is highly relevant if you're living on the edge :) .

**Closed** 2015-08-06 04:29 UTC
Labels: component: carousel, component: modal, type: bug, type: ngAnimate
