### ISSUE TITLE
$modal + ngTouch input issues on iOS/Android

### ISSUE THREAD

**Issue by slane** [angular-ui/bootstrap#2280] opened 2014-05-30 11:53 UTC
There is a weird issue with modal windows containing input fields on iOS and Android if ngTouch is used. For some reason, you can only focus on an input field with a long touch gesture. A regular touch gesture won't focus on the field (and thus won't open the virtual keyboard). On desktop browsers the issue does not exist but it also seems to work as it should on Mobile IE (WP8).

Here's a plunkr demonstrating the issue: http://plnkr.co/edit/X95ZBUd6FK2I2R14e3Lr?p=preview

**Comment by tomasreichmann** [comment] 2015-01-08 08:32
removing ng-touch from .modal solved the problem for me as well. You can't just move it to the backdrop, because the .modal covers entire viewport and .modal-backdrop is actualy behind .modal and can't be clicked.

I saw somewhere else people solved it by stopping event propagation on .modal-body but I didn't manage to make it work for me.

What is the event that busts the click called? I have zero experience with event propagation, can someone look into it? I guess this would help a lot of people.

**Comment by karianna** [comment] 2015-01-08 08:41
Fixed via #3044

**Comment by liadlivnat** [comment] 2015-01-13 15:27
HI, how can i get the latest fixed?

is it merged already to the master branch?

**Comment by antoinepairet** [comment] 2015-01-13 20:57
@liadlivnat This fix is included in master.

**Comment by liadlivnat** [comment] 2015-01-14 06:59
@antoinepairet when i'm doing bower update angular-ui-bootstrap i get Version: 0.11.2 - 2014-09-26, how can i get this version?

**Comment by memolog** [comment] 2015-06-24 05:15
@chrisirhc I'd like to know how the fix is going. I'm sorry to bother you, but it is essential for our product.

**Comment by piotrd** [comment] 2015-07-02 17:38
@chrisirhc see here https://github.com/angular-ui/bootstrap/pull/3044#issuecomment-102533597. The fix apparently was merged and then reverted due to "not following merging guidelines" and has been forgotten since :(

**Comment by vdeturckheim** [comment] 2015-07-08 15:06
Hi, is there any news regarding the re-merging of the fix?

Thanks a lot.

**Comment by adgoncal** [comment] 2015-07-08 15:30
+1

This is a very annoying bug.

**Comment by vdeturckheim** [comment] 2015-07-08 16:02
BTW:
@jdhiro's [fix worked](https://github.com/angular-ui/bootstrap/issues/2017) for me!

**Comment by twhamilton** [comment] 2015-07-23 15:33
+1 Why has this not been released. It is clearly a serious pain for everyone

**Comment by sean-stanley** [comment] 2015-07-23 19:39
I had this issue but it took me an embarassingly long time to realise I had it. The directive approach did fix this issue for me though since I use ngTouch in other parts of my UI. I suppose another approach would be divide the portions using ngTouch into a seperate module and just have that module depend on ngTouch. That might mean ngTouch won't interfere with modals.

A PR solution could look like the directive provided though really the angularjs team should fix this one. The issue is scheduled to be fixed in either angularjs 1.4.x or 1.5.x so we might have to wait a while for them. 

Fixing it ourselves here would help other people having the problem and not knowing about it or who can't wait on a new version of angularjs.

**Comment by ximon** [comment] 2015-08-20 15:33
This issue also affects selects on modals (see plunker http://plnkr.co/edit/2phDw62EVl1z9egd8EkA?p=preview) @jdhiro's fix https://github.com/angular-ui/bootstrap/issues/2017 gets around this issue too.

Having the modal in a separate module doesn't get around this issue unfortunately.

**Comment by entrity** [comment] 2015-08-26 16:52
:+1:

**Comment by rbalicki2** [comment] 2015-08-27 14:59
The following fixed the issue for me. My best guess is that the clicks are continuing to propagate, and eventually result in the modal getting focus, but I have not confirmed that hypothesis:

    (function() {
      angular.module('redbox.framework.directives')
        .directive('input', [
          function() {
            return {
              restrict: 'E',
              link: link
            };
          }
        ]);

      angular.module('redbox.framework.directives')
        .directive('textarea', [
          function() {
            return {
              restrict: 'E',
              link: link
            };
          }
        ]);

      function link(scope, elem) {
        // bind the events iff this is an input/textarea within a modal
        if (elem.parents('.modal').length) {
          elem.on('touchstart', function(e) {
            elem.focus();
            e.preventDefault();
            e.stopPropagation();
          });
        }
      }
    })();

I did not test whether both `preventDefault` and `stopPropagation` were necessary, as I assume I'll remove these directives when it's patched in ngTouch / angular / angular-ui-bootstrap :)

**Closed** 2015-09-07 18:48 UTC
Labels: component: modal, component: touch, type: bug
