### ISSUE TITLE
Incorrect 'hasFocus' check in asynchronous typeahead

### ISSUE THREAD

**Issue by SantjagoCorkez** [angular-ui/bootstrap#3223] opened 2015-01-26 11:39 UTC
https://github.com/angular-ui/bootstrap/blob/master/src/typeahead/typeahead.js#L133

When setting up a typeahead with:
```html
                        <input
                            data-ng-disabled="!regions_selector.selected || city_selector_loading"
                            data-ng-model="city_selector"
                            data-typeahead="city.name for city in getCities($viewValue)"
                            data-typeahead-loading="city_selector_loading"
                            data-typeahead-min-length="2"
                            data-typeahead-wait-ms="500"
                            type="text"
                            class="form-control"
                            id="citySelector"
                            aria-describedby="citySelectorDescription"/>
```
and controller as:
```javascript
                        getCities: function(query) {
                            return $http.get('{{ url_for('internalapi.json_kladr_get_cities') }}', {
                                params: {
                                    region_id: $scope.form.region_id,
                                    query: query,
                                    simple: 1
                                }
                            }).then(function(response) {
                                return response.data;
                            });
                        },

```
I get an empty `matches` in inner scope for a list of results to select from. While debugging I've seen than at the line I pointed at, `hasFocus` is false making all populating code being skipped. Commenting out that check helped.

I also ensured multiple times, the defer in query callback returns an array of objects, where `.name` property is always set.

AngularJS: 1.3.9
ui-bootstrap: 0.12.0
third-party modules: None for this case

If that matters, the typeahead is declared inside a $modal view.

**Comment by dmitriz** [comment] 2015-04-24 11:14
@SantjagoCorkez  Could you write a unit test for `typeahead` that is failing because of this but shouldn't?

**Comment by SantjagoCorkez** [comment] 2015-04-24 13:50
Well, actually I can't. I'm not so skilled ATM for writing UTs.

BTW, I've found that browsers automatically de-focus DOM elements that become `disabled`. Can't this be the root of the issue (and then could lead to a resolution like `misusage` or so). If so, then it could be especially noticed in documentation that using `ng-disabled` on typeahead-bound fields is highly discouraged and leads to unpredictable behaviour.

**Comment by davodotnet** [comment] 2015-10-06 06:28
I have had the same problem and found that arround line 3600 if I changed if (onCurrentRequest && hasFocus)

to 

if (onCurrentRequest)


everything works ok

**Comment by wesleycho** [comment] 2015-11-04 05:33
We need a reproduction in Plunker in order to debug this, especially since the referenced line number is out of date given that `master` has changed significantly.

Otherwise we cannot help at all.

**Comment by pkozlowski-opensource** [comment] 2015-12-01 10:46
Closing as we don't have plunker that would help us reproduce the issue.

**Closed by pkozlowski-opensource** 2015-12-01 10:46 UTC
Labels: component: modal, component: typeahead, needs: plunkr
