### ISSUE TITLE
can't use variables with typeahead-popup-template-url like with typeahead-template-url.

### ISSUE THREAD

**Issue by yahyaKacem** [angular-ui/bootstrap#5000] opened 2015-12-03 15:01 UTC
Hi, when using a variable to determine the template's name for typeahead-template-url, it work but not for typeahead-popup-template-url, due to the use of $parse in uibTypeaheadMatch directive [typeahead.js#L608](https://github.com/angular-ui/bootstrap/blob/master/src/typeahead/typeahead.js#L608), which is not the case for uibTypeaheadPopup directive [typeahead.js#L567](https://github.com/angular-ui/bootstrap/blob/master/src/typeahead/typeahead.js#L567).
Here's a [plunker that shows the error](http://plnkr.co/edit/s7mWAtwdupP41GGO7dcZ?p=preview).
> Check devTools for the error.

**Comment by wesleycho** [comment] 2015-12-03 17:08
Closing as a duplicate of #4266

**Closed by wesleycho** 2015-12-03 17:08 UTC

**Comment by yahyaKacem** [comment] 2015-12-03 18:44
@wesleycho, I'm not looking for a global override like mentioned in the #4266, I'm only looking to make the typeahead-popup-template-url accept variables, my approach for globally changing the template is just to override this template `uib/template/typeahead/typeahead-popup.html` in my app, that will give me a global custom popup template, my need is for making the typeahead-popup-template-url accept variables so I can use a variable like `assets/tpls/typeahead-popup-{{custom}}.html`, where custom could be home, profile...
I don't see how this is duplicating the other issue !?
If your opinion still remain the same, could you please explain more? thanks in advance.

**Comment by wesleycho** [comment] 2015-12-03 18:49
Ahh, I was mistaken - sorry, a little sleep deprived.

I don't think we are going to support variables, since once a template is instantiated, it should not be swapped in the same component. This means that the data present in the attribute needs to be static, so supporting a string suffices.

One should be able to do `typeahead-popup-template-url="{{myTypeaheadPopupTemplateUrl}}"` or something similar to use a variable.

**Comment by yahyaKacem** [comment] 2015-12-04 09:22
Ahh, OK, that's may mistake I didn't mean a variable the way you described it, I meant what you exactly said one should be able to do:
>One should be able to do typeahead-popup-template-url="{{myTypeaheadPopupTemplateUrl}}" or something similar to use a variable.

but that's not the case here since as seen in this [plunker](http://plnkr.co/edit/s7mWAtwdupP41GGO7dcZ?p=preview) we get an error:
> GET http://run.plnkr.co/oUf9rz729n522zQA/%7B%7Bapp.TPLS%7D%7D/custom_popup_template.html 400 (Bad Request)
 GET http://run.plnkr.co/oUf9rz729n522zQA/%7B%7Bapp.templatePopupUrl%7D%7D 400 (Bad Request)

You see the `%7B%` and `%7D%` surrounding the `app.templatePopupUrl` and in the code it is different from the `typeahead-template-url` where it works as expected but for the `typeahead-popup-template-url` it doesn't .

**Comment by pkozlowski-opensource** [comment] 2015-12-04 09:23
But `typeahead-popup-template-url` is an expression and not an interpolated expression so you can't use `{{}}` inside.

**Comment by yahyaKacem** [comment] 2015-12-04 11:00
@pkozlowski-opensource, now I'm confused when you say it's an expression you mean I should change this `typeahead-popup-template-url="{{app.templatePopupUrl}}"` to this `typeahead-popup-template-url="app.templatePopupUrl"`?
if so, that doesn't work too, and if you mean it should only be a string, meaning I should hard code the template path in the html like so: `typeahead-popup-template-url="assets/tpls/custom_popup_template.html"`, then that's the only way it will work, not like the other directive uibTypeaheadMatch where we can do this `typeahead-template-url={{app.templateUrl}}` and it will work like in the [plunker](http://plnkr.co/edit/s7mWAtwdupP41GGO7dcZ?p=preview), the first work with only `typeahead-template-url="app.templateUrl"` attribute but the second with the `typeahead-popup-template-url="{{app.templatePopupUrl}}"`, so why we have 2 different behaviour for 2 attributes on the same elements !!?? confusing right?
one would expect the same behaviour from both attribute!!

**Comment by dhakan** [comment] 2016-03-10 13:49
Any new insights on the confusion described by @yahyaKacem ? Nothing is working for me when using the popup-template-url, but it works when using the regular template-url.

**Comment by bel-mont** [comment] 2016-03-29 23:17
Same issue. The variable is not evaluated. Line 6882 does the following:
`templateUrl: function(element, attrs) {
        return attrs.popupTemplateUrl || 'uib/template/typeahead/typeahead-popup.html';
      }`.
Which causes popupTemplateUrl to be the exact string you send there.

I'm still new at angular so I don't really know how to override this behavior, other than changing the source and attempting to get the template in the link function like uibTypeaheadMatch does, or figuring out how to make angular process the variable before templateUrl is used.

**Comment by jaguergo** [comment] 2016-04-08 15:07
Well the dirty solution for me is to add the following jquery/angular script to make it work

<script>
    var popupTemplateUrl = "url-to-the-template.html";
    $("input[uib-typeahead]").attr("typeahead-popup-template-url", popupTemplateUrl);
</script>

Dirty but it works, you could also do it inside a controller like angular.element("input[uib-typeahead]").attr("typeahead-popup-template-url", popupTemplateUrl);

regards
