### ISSUE TITLE
DatePicker - Performance issues with popup + other stuff

### ISSUE THREAD

**Issue by DumboJet** [angular-ui/bootstrap#3451] opened 2015-03-27 10:15 UTC
Using one of Chromes add-ons for performance evaluation, I have seen this:

![image](https://cloud.githubusercontent.com/assets/8492662/6865702/38fd23e0-d479-11e4-842c-76be403524cd.png)

I have only one datepicker (if I am not mistaken) in sight, so this is quite disturbing...
I cannot imagine what happens with more...
Do you think it would be possible to remove the popup from the DOM when it is not needed to be visible?
I think that would help a lot.
(I am referring mainly to `datepickerPopup`, but it may apply to other places as well)

---

Also, the popup doesn't work so good when placed inside some containers having CSS positioning and floating.
If you could make it work good in all cases (e.g. positioning it with JS) it would be nice.
(Then you might face problems with scrolling while the popup is open, but that's bearable)

---

Also, another issue:
I was using an old version of your library and I came across some issues with the week numbers.
I have found a correct version of the `getISO8601WeekNumber()` that you use:

```
Date.prototype.getWeekNumber = function () {
    var d = new Date(+this);
    d.setHours(0, 0, 0);
    d.setDate(d.getDate() + 4 - (d.getDay() || 7));
    return Math.ceil((((d - new Date(d.getFullYear(), 0, 1)) / 8.64e7) + 1) / 7);
};
```

I have noticed that in newer versions of you lib, you have improved this function, but I think it is still not the same to the one I use.
If you like, take a look at this implementation and compare, just to make sure you got it right.

**Comment by karianna** [comment] 2015-03-27 10:34
I *think* most of this is fixed in master - but we'll keep this around for reference

**Comment by wesleycho** [comment] 2015-03-27 13:56
We actually had a meeting yesterday, and performance is an issue that we know of with the datepicker.  We are focusing on getting everything functional with Angular 1.3 first (1.4 compatibility should not be difficult from there from what I understand) for the 0.13.0 release, and then we intend on tackling performance optimizations across the board, but especially with the datepicker and pagination.

This is on our todo list :) .

**Comment by hamfastgamgee** [comment] 2015-03-31 02:07
FWIW, just using one-time bindings in the template gets you a long way towards good performance.

**Comment by 311chaos** [comment] 2015-04-17 00:12
Just found this. I am currently on 1.12.1, but I came here looking for performance related issues with the datepicker. I am on a $asqwatch hunt (see ng-conf talks for this reference), and I found that a single datepicker brings along 232 watches. There are 5 per 'day', which is the bulk of them. 

I can fork 1.12.1 and change the templates to one time bindings (using a bindonce 3rd party library) , but I do not want to bother with that if the 0.13 release is getting close. I would rather wait for 0.13 and submit a pull request with official bind once support. 

Any idea on how close the 0.13 release really is? This month? Within the next 30 days? Possibly longer?

I would love to contribute, however I have looked at the current issues (tagged as 1.3 related) and I am not sure that I could help to resolve any of those items. Besides pull requests is there anything else that I could assist with?

**Comment by RobJacobs** [comment] 2015-04-17 00:52
Related to PR #3443

**Comment by chrisirhc** [comment] 2015-04-17 05:56
@311chaos , we could use help in testing the changes in #3443 . If you find any bugs caused by the PR, do report on it. Otherwise, it's also good to indicate that it works for you.

**Comment by AndrewIsh** [comment] 2015-04-17 16:06
@hamfastgamgee I'm having real problems with this due to having a number of datepickers in my view. I'm intrigued by your suggestion of using one-time bindings in the template, but I can't figure out where I'd use them (I'm fairly new to Angular). Can you please advise? Here is an example datepicker from my markup:
```
<div class="input-group">
    <input
        ng-change="save()"
        type="text"
        class="form-control"
        datepicker-popup="{{mC.datePicker.format}}"
        ng-model="metadata.validity_start"
        ng-required="true"
        is-open="mC.datePicker.validitystartopen"
        close-text="Close"
    />
    <span class="input-group-btn">
        <button type="button" class="btn btn-default" ng-click="mC.datePickerOpen('validitystart', $event)">
            <i class="glyphicon glyphicon-calendar"></i>
        </button>
    </span>
</div>
```

I assume I'd use them in the ng-model attribute, as per:
```
ng-model="::metadata.validity_start"
```
but that didn't work at all.

**Comment by hamfastgamgee** [comment] 2015-04-17 16:20
I meant in the angular-ui datepicker templates.  AKA PR #3443 :)

**Comment by RobJacobs** [comment] 2015-04-17 17:25
@AndrewIsh PR #3443 only solves part of the problem, the datepicker popup needs to be wrapped in an ng-if as there is a lot of overhead rendering the elements.  PR #1915 implements the ng-if but you could also use an inline datepicker and wrap that in an element that uses ng-if.

**Comment by AndrewIsh** [comment] 2015-04-17 18:03
Thanks very much @hamfastgamgee and @RobJacobs , I'll take a look at those PRs :)

**Comment by wesleycho** [comment] 2015-11-02 14:13
Closing, as this is an issue still, but likely to be tackled in more granular tasks.

**Closed by wesleycho** 2015-11-02 14:13 UTC
Labels: component: datepicker, needs: investigation, type: performance
