### ISSUE TITLE
Arrows of Carousel won't work with Angular Material

### ISSUE THREAD

**Issue by butaixianran** [angular-ui/bootstrap#3582] opened 2015-04-23 04:04 UTC
When Angular material is used in same module, the left/right arrows of carousel can only click once, then they just won't work anymore.

check this:
http://plnkr.co/edit/sKYU5SyHNlKklYQpErtR?p=preview

Angular Material Version: 0.83

**Comment by hmillet** [comment] 2015-05-01 07:23
Same experience, with angular 1.3.15 as @butaixianran, but without materiel.
I have so many vendors js library that I cannot detect which one make arrows work only once

**Comment by wesleycho** [comment] 2015-05-11 13:46
If I had to guess, this might be caused by angular-material decorating $$rAF - this may be an angular-material bug.

**Comment by karianna** [comment] 2015-05-11 13:57
@wesleycho see @hmillet 's comment

**Comment by wesleycho** [comment] 2015-05-11 14:14
This is not reproduceable in just 1.3.15 - removing the `ngMaterial` module from the dependencies illustrate that it works fine.

**Comment by hmillet** [comment] 2015-05-11 15:56
if this can help, here is my (rich) bower.json : 

    "bootstrap": "~3.3.1",
    "angular": "~1.3.12",
    "angular-i18n": "~1.3.12",
    "angular-sanitize": "~1.3.12",
    "angular-animate": "~1.3.4",
    "angular-bootstrap": "~0.12.0",
    "angular-ui-utils": "~0.2.1",
    "angular-ui-select": "~0.9.6",
    "angular-typeahead": "0.2.*",
    "angular-touch": "~1.3.15",
    "angular-ui-calendar": "latest",
    "angular-filter": "0.5.*",
    "angular-hotkeys": "chieffancypants/angular-hotkeys#~1.4.5",
    "angularjs-toaster": "~0.4.10",
    "bootstrap-chosen": "~1.0.0",
    "bootstrap-dialog": "~1.34",
    "chosen": "https://github.com/harvesthq/chosen/releases/download/v1.3.0/chosen_v1.3.0.zip",
    "slimscroll": "~1.3.3",
    "datatables": "1.10.*",
    "datatables-plugins": "1.0.*",
    "moment": "2.8.*",
    "numbro": "~1.1.1",
    "animate-css": "~3.2",
    "angular-bootstrap-nav-tree": "master",
    "verge": "latest",
    "jquery.actual": "~1.0",
    "ng-device-detector": "latest",
    "decimal.js": "~4.0.2"

**Comment by schulzzw** [comment] 2015-05-20 20:41
I would try to remove angular-animate. That seemed to do the trick for me.

**Comment by hmillet** [comment] 2015-05-21 07:22
I upgrade my "angular-bootstrap" 0.12.1 version to the 0.13.0.

Now the bug is no more, that's working fine for me (with all the other plugins, including angular-animate)

**Comment by wesleycho** [comment] 2015-05-21 14:09
Closing as resolved - if it is an issue still, let us know.

**Closed by wesleycho** 2015-05-21 14:09 UTC
Labels: component: carousel

**Comment by hmillet** [comment] 2015-05-21 14:54
That's correct ! :+1: 

@butaixianran: I try with your plunkr, I change the "angular-bootstrap" version from 0.12.1 to 0.13.0, and I can see that it's now working. 

@wesleycho: thanks for your contribution to this usefull project
