### ISSUE TITLE
uib-popover-html not working

### ISSUE THREAD

**Issue by sdesmond** [angular-ui/bootstrap#5613] opened 2016-03-09 19:03 UTC
### uib-popover-html is not working starting at 1.2.0

This Plunker works as is, but if you change the UIBS version to 1.2.0+ it breaks.  I didn't see any breaking changes that would cause this in the changelog.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.0

UIBS: 1.2.0

Bootstrap: 3.3.6

**Comment by icfantv** [comment] 2016-03-09 21:15
@sdesmond, please be respectful of our time by searching existing open and closed issues before opening a new one.  This is a duplicate of #5602 and has already been fixed in `master`.

**Closed by icfantv** 2016-03-09 21:15 UTC

**Comment by sdesmond** [comment] 2016-03-09 21:51
@icfantv, I would also ask that you be respectful and not assume I haven't searched the issues.  The default search for issues includes the tag is:open, so I searched and found no results.  We're all on the same team here.  Sorry I missed it, and that's for pointing out the fix.

**Comment by icfantv** [comment] 2016-03-09 22:08
@sdesmond, the apology is appreciated, the attitude is not.  we deal with dozens of issues per week the large majority of which are varying degrees of issues like yours.  some people are just lazy, some are in such a rush to have their issue addressed they don't read, and some are so entitled they actually get demanding and abusive.  please remember that the next time you don't appreciate what you might view as a sharp remark.  most are not actually bugs.

the above creates an enormous amount of work for us because this library is so popular.  you need to remember that we are all unpaid volunteers and the processes we have in place not only make our lives easier, but allow us to address YOUR needs faster.

when developers get lazy, the entire community suffers.  and quite frankly, that's not fair to anyone.

**Comment by sdesmond** [comment] 2016-03-10 05:23
@icfantv, I've been following this project for a while now and know how far it's come, especially in the last little while.  I absolutely appreciate what you all do to keep this going.  Not trying to be disrespectful at all, just hoping for the benefit of the doubt as I tried to submit the issue in the most helpful way possible.  Obviously my fault for only searching open issues, so we can leave it at that.  Thanks again for the hard work.
