### ISSUE TITLE
Popover displays tooltip on itself and every element

### ISSUE THREAD

**Issue by shlomogoldstein** [angular-ui/bootstrap#5598] opened 2016-03-08 08:39 UTC
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.4.8

UIBS:

Bootstrap: 1.1.0

Just create a popover with a title. Open the popover, then move your mouse on the popover, you will see a tooltip with the popover's title. Put a "<a href..." in your popover and the tooltip will appear on the link too........

**Comment by icfantv** [comment] 2016-03-08 14:32
@schlomogoldstein, there's a reason we have an issue template.  It is to save us time in determining what is wrong and potentially how to fix it.  In the future, please be respectful of that time by following the issue template and creating a reproduction.

**Comment by wesleycho** [comment] 2016-03-14 21:12
Closing due to lack of reproduction & inability to reproduce this.

**Closed by wesleycho** 2016-03-14 21:12 UTC
Labels: component: popover, needs: investigation
