### ISSUE TITLE
Issue with closable tabs

### ISSUE THREAD

**Issue by stefanwalther** [angular-ui/bootstrap#3750] opened 2015-06-03 12:08 UTC
Hi,

I am having an issue with closable tabs. I wanted to add an icon to the tabs to be able to close the tab.
Strangely the content-panel is removed, but not the tab itself.
It is important for me that the directive itself is solving that.

Here is the example demonstrating that:
https://jsfiddle.net/stefanwalther/k9n17609/6/

Regards
Stefan

**Comment by rvanbaalen** [comment] 2015-06-03 15:52
Possible duplicate of #3728 ?

**Comment by stefanwalther** [comment] 2015-06-03 18:02
Hi, yes and no, but I realize that my question is about creating a **new directive** which is based on the AngularUI directive and also allows deleting a tab from within the tab.
So I posted the question on http://stackoverflow.com/questions/30619994/remove-tabs-from-angularui-tabs/30621529#30621529

**Comment by stefanwalther** [comment] 2015-06-03 18:02
... ;-) although I still think it should work and is more or less a bug ;-)

**Comment by rvanbaalen** [comment] 2015-06-03 19:43
Well since it's an issue with your **new directive** and not with UI Bootstrap, StackOverflow is indeed the right place to go.

**Closed by rvanbaalen** 2015-06-03 19:43 UTC
Labels: component: tab, needs: info

**Comment by stefanwalther** [comment] 2015-06-03 20:44
Any help would still be very appreciated ;-)

**Comment by rvanbaalen** [comment] 2015-06-03 20:46
Yes, but not here. This is an issue tracker with 400+ issues that need attention, not a forum for help.

**Comment by stefanwalther** [comment] 2015-06-03 21:00
;-) You are right, sorry!
