### ISSUE TITLE
Date change event

### ISSUE THREAD

**Issue by swapy** [angular-ui/bootstrap#5609] opened 2016-03-09 14:55 UTC
Hello everyone,

I want to get the event when user clicks on any date in calendar. I want this date to bind with timepicker's min and max.

If we change date, how 
As per requirements of timepicker requires **new Date object for min and max values**.
If I simply set like this 

```
var d = new Date();
d.setHours( 2 );
d.setMinutes( 0 );
$scope.minTime = d;

var d = new Date();
d.setHours( 11 );
d.setMinutes( 0 );
$scope.maxTime = d;

```
`<uib-timepicker ng-model="mytime" min="min" max="max" show-meridian="false" min="minTime"   max="maxTime"></uib-timepicker>
`

This works only for today because of new Date() object., I am not able to get datepicker on date click event to fetch selected date.

**Comment by wesleycho** [comment] 2016-03-09 14:58
Have you tried ng-change on the datepicker?

**Comment by swapy** [comment] 2016-03-09 15:00
Yes, but it did not work, I don't understand why

**Comment by wesleycho** [comment] 2016-03-09 15:03
Can you post a minimal reproduction in Plunker?

In the future, please don't ignore the issue template when opening an issue - it is there for a reason.

**Comment by swapy** [comment] 2016-03-10 10:03
I tried to reporoduce it but could not completly.
Date change works here but min max dosent

http://plnkr.co/edit/KzgnmBjxjL087npimrFh?p=preview


In my own code, however timepicker boxes turn red. I dont know  whats wrong.

**Comment by icfantv** [comment] 2016-03-10 17:50
@swapy, it's starting to sound like this is a support issue.  If you concur, please direct that request to StackOverflow (per our documentation) because the audience is _significantly_ wider than here - and you are far more likely to get a faster response).

We'll let you respond before closing this as a user issue.

**Comment by swapy** [comment] 2016-03-11 06:50
Now, date change event gets binded, however, timepicker min max does not work.
I have posted the question on stackoverflow too:
http://stackoverflow.com/questions/35933473/bind-angular-datepicker-and-timepicker

**Comment by swapy** [comment] 2016-03-16 05:49
I think this is a bug in timepicker. Timepicker will goes red colour for min(value specified for min) time too.

**Comment by wesleycho** [comment] 2016-03-20 18:05
I highly recommend against using the same date for the datepicker and timepicker - while it is currently supported, it creates flawed model situations just due to the nature of the problems that each component has to solve, and the difficult nature of JS dates.

This needs a little looking into, but we may end up deciding to nix support for shared date model usage.

**Comment by wesleycho** [comment] 2016-04-04 04:30
Going to close this as won't support - we need to make a breaking change in order to fix #5485 where shared model usage will not be possible between the two components without side effects.

**Closed by wesleycho** 2016-04-04 04:30 UTC
Labels: component: datepicker, needs: investigation

**Comment by swapy** [comment] 2016-04-15 11:52
@wesleycho , but both timepicker and datepicker are components of same project right?

**Comment by icfantv** [comment] 2016-04-15 13:46
@swapy, clearly they are, but you have yet to give us solid reasoning as to why this feature should be supported.  In reality, the time picker model should have never been a date object and we have aims to make it a 2- or 3-field object instead.

**Comment by swapy** [comment] 2016-04-15 18:26
Exactly, I also feel the same , ie timepicker should not at all be associated with date. Because of that association these problems have arised. I would suggest  that timepicker should be like this

`<uib-timepicker min="10:00" max="21:00"  />`

passing new Date()  or any date to timepicker is really annoying.

I would request you to add this feature, and plz show what exactly error is if timepicker turns **red**
