### ISSUE TITLE
Popover directive doesn't work with Safari when using popover-trigger="focus"

### ISSUE THREAD

**Issue by kienpham2000** [angular-ui/bootstrap#3687] opened 2015-05-18 22:38 UTC
Hi guys,

Ex: this works on chrome and firefox, but not on Safari (8.0.6). I'm on Mac OS X Yosemite
< a href="" popover="hola!" popover-trigger="focus">Hello!< / a >

When in Safari, when I click on that link, nothing shows up.

Thanks!

**Comment by rvanbaalen** [comment] 2015-05-19 12:58
Please provide a plunkr reproducing your problem.

**Comment by kienpham2000** [comment] 2015-05-19 16:50
@rvanbaalen http://plnkr.co/edit/qXQEMJZPj7zUHhg2DZhL

**Comment by RobJacobs** [comment] 2015-05-19 17:07
I've found focus to be flaky in Safari, does it work when you switch to a click trigger.

**Comment by kienpham2000** [comment] 2015-05-19 17:33
@RobJacobs awesome, your suggestion work perfectly! Thanks.

**Comment by rvanbaalen** [comment] 2015-05-19 17:35
Glad you have a workaround. That still leaves this as a bug for Safari though, right @RobJacobs ?

**Comment by RobJacobs** [comment] 2015-05-19 17:53
I don't think it's a bug in our code, Safari just doesn't seem to propagate the focus event from a click event.

**Comment by rvanbaalen** [comment] 2015-05-19 18:00
It's unfortunate that references as [this one](http://www.quirksmode.org/dom/events/blurfocus.html) aren't up to date with the newest browsers.

**Comment by kienpham2000** [comment] 2015-05-19 18:05
Maybe a fix is to document such workaround for Safari at the Tooltip Set Trigger section?
http://angular-ui.github.io/bootstrap/#/tooltip

**Comment by chrisirhc** [comment] 2015-05-23 23:52
Similar issue at Twitter Bootstrap: https://github.com/twbs/bootstrap/issues/11788

**Comment by wesleycho** [comment] 2015-06-05 13:17
We should probably put a workaround in UI Bootstrap then, even if Safari's buggy behavior is the culprit in this case.

**Comment by Astray-git** [comment] 2015-06-15 06:43
Firefox on OSX has the same problem

**Comment by sethflowers** [comment] 2015-09-18 14:51
+1

**Comment by icfantv** [comment] 2015-09-18 15:00
Can anyone confirm whether or not 1) this is still an issue and 2) if Apple intends on releasing a new version of Safari with El Capitan?  And if so, is anyone running the beta that can test to see if this is still an issue?  Thanks.

**Comment by wesleycho** [comment] 2015-09-18 15:05
Even if they do, we should still investigate this - Safari 7 is still the most used version of Safari out in the wild, it may take a while before we see this fixed at the browser level.

**Comment by sethflowers** [comment] 2015-09-18 15:06
Just confirmed in saucelabs that it does not work in El Capitan with Safari 8.1. I used the following plunk: http://plnkr.co/edit/ZDdiKt1VvQVAwxwblwvW?p=preview

**Comment by icfantv** [comment] 2015-09-18 15:14
@wesleycho, agreed.

I'm a little confused.  Is the fix [this](https://github.com/twbs/bootstrap/issues/11788#issuecomment-40015422) or is it [this](https://github.com/twbs/bootstrap/pull/14156)?  @chrisirhc, do you remember?

@wesleycho, what type of workaround do we want?  something like:
```
if (isMac && (browser === safari) && (version >= 7)) {
  // stuff
}
else {
  // other stuff
}

please note that I had to hold my nose while typing that...

**Comment by RobJacobs** [comment] 2015-09-18 15:15
From TWBS PR [#141456](https://github.com/twbs/bootstrap/pull/14156) seems the fix is to use  <a tabindex="0">  instead of  <button> . Relevant links on MDN:

[button](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus)

[anchor](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Clicking_and_focus)

**Comment by icfantv** [comment] 2015-09-18 15:29
Nice @RobJacobs.  I'm ok with this being a wontfix then and adding comments to both the FAQs and popover/tooltip docs with a Nota Bene for OSX Safari 7.0+ users.  @wesleycho, you cool with that?

**Comment by wesleycho** [comment] 2015-09-18 17:05
I'm fine with that resolution, although perhaps @foxandxss might have something to say about the docs

**Comment by Foxandxss** [comment] 2015-09-18 17:15
Yeah, it is always good to document this stuff.

If I understood correctly, OSX safari users needs to use an element with a tagindex if they want to use `popover-trigger` with focus, right? Does that affect tooltip as well?

**Comment by wesleycho** [comment] 2015-09-18 17:17
Anchor tag with tabindex* - looks like it. I just am not sure where is the best place to put it

**Comment by Foxandxss** [comment] 2015-09-18 17:18
Depend if tooltip also has the issue or not ;)

**Comment by icfantv** [comment] 2015-09-18 17:29
Yes, it's an issue for both and the `<a tabindex="0">` hack works.  See [this](http://plnkr.co/edit/tbcvKDqgjist7zYYLG39) for the example.

**Comment by Foxandxss** [comment] 2015-09-18 17:33
Alright, will create a PR to fix this via doc.

**Comment by wesleycho** [comment] 2015-10-02 18:41
@Foxandxss don't forget about this :) .

**Comment by Foxandxss** [comment] 2015-10-02 18:45
Wari wari! Will write it down on my todo list.

**Comment by wesleycho** [comment] 2015-12-15 07:31
Looks like this is already in the docs from 4e60e22c49528155a6db7b004d507b48e601dbf3 - closing as resolved.

**Closed by wesleycho** 2015-12-15 07:31 UTC
Labels: browser: safari, component: popover, type: bug

**Comment by QuaoQuo** [comment] 2015-12-21 04:31
html:
<a href="javascript:void(0)" data-html="true" class="popupover" data-placement="bottom" data-toggle="popover" data-trigger="click" title="Popover" data-content=""></a>

JS:
$('[data-toggle="popover"]').popover();
jQuery("body").on("click touchstart", '[data-toggle="popover"]', function() {
	$(this).popover("show");
	$('[data-toggle="popover"]').not(this).popover("hide"); // hide other popovers
	return false;
});
jQuery("body").on("click touchstart", function() {
	$('[data-toggle="popover"]').popover("hide"); // hide all popovers when clicked on body
});

**Comment by wesleycho** [comment] 2015-12-21 04:42
We do not support the Twitter Bootstrap JS @QuaoQuo - please do not comment on closed issues for technical support, GitHub issues are not the place for that.
