### ISSUE TITLE
uib-pagination initial current page

### ISSUE THREAD

**Issue by amilcar-calles** [angular-ui/bootstrap#5858] opened 2016-04-29 02:26 UTC
### Bug description:
- When I give an initial value into the uib-pagination the value is changed to 1, even if the original value was another. 

### Code that reproduces the issue:

Example:

JS:
`
angular.controller('myController', function() {
    this.pager = { currentPage: 3 }
})
`

HTML
`<uib-pagination ng-model="vm.pager.currentPage"></uib-pagination>`

Then the value in vm.pager.currentPage will be changed to 1 automatically when the controller starts.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.0

UIBS: 0.14.3

Bootstrap: 3.1.1

**Comment by wesleycho** [comment] 2016-04-29 13:55
Please post a Plunker reproduction - this should already be fixed as this is a duplicate of #2956.

**Comment by wesleycho** [comment] 2016-05-16 15:39
Going to close this as fixed - the fix is in 1.0.0, but not 0.14.3.

**Closed by wesleycho** 2016-05-16 15:39 UTC
Labels: component: pagination, needs: plunkr

**Comment by jay-gandhi** [comment] 2016-08-10 12:36
Hi, I'm using 2.0.1 and I'm putting page number in query string and UIB-pagination changes to value to 1.

> http://localhost:9000/emailtrack/?Page=4

but it's changing to 

> http://localhost:9000/claimtracker/claims/?Page=1

**Comment by wesleycho** [comment] 2016-08-10 13:36
If there is a legitimate issue, please post a minimal reproduction in Plunker in a separate issue.

**Comment by samzhao2008** [comment] 2016-11-13 00:39
@jay-gandhi  
+1

**Comment by pc3b3r** [comment] 2016-11-24 10:57
I had the same problem and I solved in this way:

1. use `ng-click` instead of `ng-change`
2. set your page model after `total-items` has been set

**Comment by daric81** [comment] 2016-12-19 10:05
I was having the same issue after moving from v 0.13.x to 1.3.3. Setting the total items after the current page used to work.

I used the solution from @pc3b3r to get round the problem.

**Comment by kostalihas** [comment] 2017-04-11 14:53
use in the template `<ul uib-pagination total-items="totalPages" ng-model="pagination.currentPage" ng-change="pageChanged()" items-per-page="20" max-size="5" boundary-links="true"></ul>`
and in your controller 
`$scope.pagination = {currentPage:  1 }; 
$scope.loadMovies = function(){
            serviceAjax.popular($scope.pagination.currentPage).then(function(data){
                $scope.movies = data.data.results;
                $scope.totalPages = data.data.total_pages;
            });  };
$scope.pageChanged = function(){
           $scope.loadMovies();
        };`

**Comment by deepeeess** [comment] 2017-09-05 01:54
I am experiencing this issue with 2.5.0.

**Comment by bzashev** [comment] 2017-11-05 10:27
The trick that helped me is to initialize the totalPages variable with a number bigger than the page size. I used 1000. This will not reset the current page. Hope that helps you too.
