### ISSUE TITLE
Min attribute in timepicker doesn't work with 0 value.

### ISSUE THREAD

**Issue by turakvlad** [angular-ui/bootstrap#4606] opened 2015-10-13 13:54 UTC
"Min" attribute with 00:00 time doesn't work. Plunkr: http://plnkr.co/edit/q6IlxftsS71QN3yIfC8Y?p=preview.

If we set its to 01:00 or 02:00 time or whatever else except for 00:00 everything is OK. Plunkr: http://plnkr.co/edit/ktWo3eETGjDN1ooUnWax?p=preview.

The problem is in noDecrementHours function. We pass to addMinutes function our date, that is 00:00 and addMinutes returns to us value that is bigger than our "Min" and noDecrementHours function return false instead of true.

**Comment by BobbieBarker** [comment] 2015-10-15 17:48
I think the problem is that we don't take into account the day change, we're only looking at the hrs/mins so if you're at 00:00 and you decrement you're now at 23:59 which is greater than 00:00 so it passes the check. I'll try to have something for this in the next 24 hrs.

**Comment by BobbieBarker** [comment] 2015-10-18 04:05
This was a bit of an odd issue. At first glance it does seem like an no brainer and the fix is obvious etc. Upon further inspection I discovered that the way the time picker is intended to work is to only consider the hours and minutes of the date object ([proof of intention can be seen here](https://github.com/angular-ui/bootstrap/blob/master/src/timepicker/test/timepicker.spec.js#L274).) If we accept that the time picker is only for adjusting the hours and minutes of any given 24 hour time period, then the observed behavior of the min attribute when set to 00:00 makes sense. 00:00 is literally the minimum time you could specify; it is the equivalent of setting it to 0 or none. I'm closing the issue as I believe it is working as intended.

**Closed** 2015-10-18 04:05 UTC
Labels: component: timepicker, resolution: wontfix

**Comment by turakvlad** [comment] 2015-10-19 07:55
@BobbieBarker BobbieBarker, so I can't use these timepickers for creating range timepickers? In my project user can choose some daily interwal. 

It can be:
09:00 - 18:00
14:00 - 15:30

But can't be (because these are different days):
23:30 - 14:00

So, I need to set min attribute for "start" timepicker to 00:00 and max attribute for "end" timepicker to 23:59, but can't.

To my mind, it isn't working as intended.

**Comment by turakvlad** [comment] 2015-10-21 12:31
@BobbieBarker, I'm sorry, but can you answer? Thanks.
