### ISSUE TITLE
Controller 'tabset', required by directive 'tabContentTransclude', can't be found

### ISSUE THREAD

**Issue by brandonam** [angular-ui/bootstrap#3692] opened 2015-05-20 07:22 UTC
I'm not sure if I'm perhaps doing something incorrectly as I'm still fairly new to AngularJS but after missing around I noticed I was getting the following errors on my states loading with tabs in them

Controller 'tabset', required by directive 'tabContentTransclude', can't be found!
https://docs.angularjs.org/error/$compile/ctreq?p0=tabset&p1=tabContentTransclude

Am I missing something? Currently using 1.3.15 angular and ui-bootstrap 0.13.0. All the packages are loading correctly and the tabs are actually working correctly, but i get this error in the console every time I load the page.

I cant seem to get the plunker to do it either, but the website I'm creating internally at my company is suffering from this issue.

**Comment by brandonam** [comment] 2015-05-22 05:20
I thought the issue had resolved itself but I started noticing it again. I've narrowed down this issue this time though, it only occurs after the first time the view containing the tabs initially loads. Refreshing the page from then on through browser causes the console error to appear.

**Comment by chrisirhc** [comment] 2015-05-23 23:34
Could you please provide a Plunker that reproduces this issue?

**Comment by zifnab87** [comment] 2015-06-26 19:25
I have the exact same issue with company code.. unfortunately not plunkable.. The scripts are on a aspx file and there are also asp files that are concatenating other javascript libraries.. All the angular code is after those scripts and at the bottom of <body>. I had the same issue even when I added angular-ui-bootstrap from github instead of local copy, tried different versions of angular 3.13-3.16 and moving things around - none worked

**Comment by vectortiny** [comment] 2015-06-27 00:51
I have created a plunker: http://plnkr.co/edit/AJDxjM?p=preview
Wenn using ui-router, the parent state with tabset works fine. If you change to the child state, the error can be reproduced. But the tabset code in the ui-view container should be replaced with the code from the child state. Am I doing something wrong here?

**Comment by zifnab87** [comment] 2015-07-01 17:33
@vectortiny Were you able to make a plunkr that has the same problem without using any tabs? I have the same issues with just typeahead being used for example..

**Comment by m19** [comment] 2015-07-03 02:54
I have the same problem when bootstrapping on the body.

```
// throws error
angular.bootstrap(document.body, ['my-app']);
```

```
//  no error
angular.bootstrap(angular.element('#specific-div')[0], ['my-app']);
```

I can't provide much more information either :(

**Comment by andrepitombeira** [comment] 2015-07-16 11:59
Same problem here. It's exactly like @vectortiny describe it.

**Comment by piotrd** [comment] 2015-07-16 12:59
I have the same issue as @zifnab87 described - I don't even use `tabset` in my app, but I keep getting the error from time to time in Rollbar.

**Comment by wohugb** [comment] 2015-07-17 13:39
When use angularjs 1.4.1,have the same problem

**Comment by brandonam** [comment] 2015-07-20 06:18
@wohugb also still occurs after updating to 1.4.3

**Comment by agriboz** [comment] 2015-07-22 12:17
I have the same exact issue as @zifnab87 mentioned and @piotrd added.

**Comment by zifnab87** [comment] 2015-07-29 18:31
@chrisirhc I found the issue was with some code using data-tab to store data on a list item. 
@agriboz  @brandonam could you check your code for similar things like tab=" " or data-tab=" " etc??
I think it would have been better if the directive doesn't allow usage as an attribute

**Comment by agriboz** [comment] 2015-07-30 06:34
@zifnab87 i tried your suggestion even i don't have `tab=" "` or `data-tab=" "` , however, still no luck.

**Comment by piotrd** [comment] 2015-07-30 07:39
@zifnab87: Checked in my project. No `data-tabs` nor `tabs` arguments at all :-/

**Comment by brandonam** [comment] 2015-07-30 13:03
I'm at AnDevCon, notable to check my code right now but will report back
when I can

**Comment by zifnab87** [comment] 2015-07-30 14:32
@agriboz @piotrd  I see - probably you have a different related problem.. it could be anything like data-tab, tab with or without values in your html.. For you it could be that you are actually using tabs in tabsets and your file dependencies are not set in the right order?

**Comment by agriboz** [comment] 2015-07-31 07:19
@zifnab87 i have the correct order of my dependencies. I am not clear on what you are saying which is using bootstrap in tabsets.

```
<tabset>
  <tab heading="welcome"></tab>
  <tab heading="goodbye"></tab>
</tabset>
```

**Comment by piotrd** [comment] 2015-07-31 08:09
I searched my code again and can confirm: I am not using `tabset` nor `tab` element (not even as attribute) at all in my project. That's odd, because our users keep receiving these errors anyway ;/

**Comment by piotrd** [comment] 2015-07-31 08:18
Maybe this data will give anyone a hint. This is a sample stacktrace my error tracking tool reports:

```
Error: [$compile:ctreq] Controller 'tabset', required by directive 'tab', can't be found!
http://errors.angularjs.org/1.3.16/$compile/ctreq?p0=tabset&p1=tab

1. File "bower_components/angular/angular.js" line 7887 col 42 in de
for (var directive, directives = $injector.get(name + Suffix),
2. File "bower_components/angular/angular.js" line 8067 col 15 in me
throw $compileMinErr('multidir', 'Multiple directives [{0}, {1}] asking for {2} on: {3}',
3. File "bower_components/angular/angular.js" line 15759 col 15 in l
var sce = shallowCopy(SCE_CONTEXTS);
4. File "bower_components/angular/angular.js" line 17156 col 49 in $eval
if ((pos - i) % group === 0 && i !== 0) {
5. File "bower_components/angular/angular.js" line 17156 col 49 in $digest
if ((pos - i) % group === 0 && i !== 0) {
6. File "bower_components/angular/angular.js" line 17156 col 49 in $apply
if ((pos - i) % group === 0 && i !== 0) {
7. File "bower_components/angular/angular.js" line 1590 col 28 in a
throw ngMinErr('areq', "Argument '{0}' is {1}", (name || '?'), (reason || "required"));
8. File "bower_components/angular/angular.js" line 7039 col 94 in u
return nodeName_(node) !== 'foreignobject' && node.toString().match(/SVG/) ? 'svg' : 'html';
9. File "bower_components/angular/angular.js" line 1456 col 14 in a
injector.invoke(['$rootScope', '$rootElement', '$compile', '$injector',
10. File "bower_components/angular/angular.js" line 1476 col 12 in ke
return doBootstrap();
11. File "bower_components/angular/angular.js" line 1370 col 5 in $e
bootstrap(appElement, module ? [module] : [], config);
12. File "bower_components/jquery/dist/jquery.js" line 3100 col 15 in l
memory = false; // To prevent further calls using add
13. File "app.min.js" line 66454 col 8 in fireWith
14. File "app.min.js" line 66488 col 13 in ready
15. File "app.min.js" line 66504 col 9 in j
```

Also, I noticed that out of 25 occurrences of this error in my app, all of them happened in Safari/MacOSX. Here is a summary: of  and number of occurrences:

User agent string | Occurrences
------------ | -------------
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.6.3 (KHTML, like Gecko) Version/7.1.6 Safari/537.85.15|9
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.6.3 (KHTML, like Gecko) Version/8.0.6 Safari/600.6.3|8
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12|4
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2|1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17|1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/7.1.5 Safari/537.85.14|1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/7.1.7 Safari/537.85.16|1

**Comment by zifnab87** [comment] 2015-08-01 20:43
@piotrd could it be that ```data-tab``` attributes are added in html from javascript before angular-ui-bootstrap runs?  i would check the entire loaded html of your website for those attributes .. as well. Also for my case, the error stack trace didn't include any of my code at all. the error happens all the time during phases of $injector, $eval, $digest etc..

**Comment by zifnab87** [comment] 2015-08-01 20:44
@agriboz yeah that's what I meant - proper html , and correct order of file.. dependencies .

First angular then angular-ui-boostrap, then any code that involves tabs/tabsets etc

**Comment by piotrd** [comment] 2015-08-03 09:02
> @piotrd could it be that data-tab attributes are added in html from javascript before angular-ui-bootstrap runs?

Rather not. I searched the entire project, including all my javascript and plugins and found no mention of either `tabset` nor `tab` (other than in `bower_components/angular-bootstrap`).

> i would check the entire loaded html of your website for those attributes

Not that easy, as I was never able to reproduce this error on my machine. I will keep trying, though...

**Comment by piotrd** [comment] 2015-08-03 09:02
My another finding, after analyzing other users' error reports, is that they all have these common browser plugins installed:

* Shockwave Flash v. 17 or 18
* NortonInternetSecurityBF
* Microsoft Office for Mac SharePoint Browser Plug-in

I have no idea if any of this can cause the issue, but thought that maybe it would helpful to note this.

**Comment by agriboz** [comment] 2015-08-03 10:53
@zifnab87 you are right, however, there is a plnkr example to show the exact issue. 

http://plnkr.co/edit/AJDxjM?p=preview

**Comment by zifnab87** [comment] 2015-08-03 13:53
@agriboz does the same happen when the templates are in separate files instead of inline? It seems that there could be an incompatibility of ui-router and bootstrap in that respect..or when the state changes some things should be initialized again for some reason..

**Comment by maxim-naumov** [comment] 2015-08-05 06:42
@zifnab87 i have exactly the same issue, our templates are in separate files. and this error occurs only when moving from the parent state with tabs to a child state.

**Comment by Karpo72** [comment] 2015-08-18 09:07
The issues appears if transclude directive wraps a directive with tabs inside. I can't provide example because of the complex project structure.

Error: [$compile:ctreq] Controller 'tabset', required by directive 'tabContentTransclude', can't be found!
http://errors.angularjs.org/1.4.3/$compile/ctreq?p0=tabset&p1=tabContentTransclude
    at REGEX_STRING_REGEXP (angular.js:68)
    at getControllers (angular.js:8007)
    at nodeLinkFn (angular.js:8154)
    at compositeLinkFn (angular.js:7541)
    at publicLinkFn (angular.js:7416)
    at $get.boundTranscludeFn (angular.js:7560)
    at controllersBoundTransclude (angular.js:8177)
    at ngRepeatAction (angular.js:27192)
    at Object.$watchCollectionAction [as fn] (angular.js:15548)
    at Scope.$get.Scope.$digest (angular.js:15683)(anonymous function) @ angular.js:12330$get @ angular.js:9109$get.Scope.$digest @ angular.js:15701$get.Scope.$apply @ angular.js:15951done @ angular.js:10364completeRequest @ angular.js:10536requestLoaded @ angular.js:10477

**Comment by brandonam** [comment] 2015-08-21 12:42
I can confirm that I do not have `tab=''` or `data-tab=''` as attributes set in my html, I do however have a `tab` and `tabset` elements set, I'm not sure if this is of any help, but here is the basic structure of my html:

```html
<section class="grid-wrap">
        <tabset justified="true" data-images-loaded>
            @*HOME*@
            <tab id="home" active="activetab.home">
                <tab-heading>
                    <i class="fa fa-table"></i> All
                </tab-heading>
                <div class="container">
                    ...
                </div>
            </tab>
            @*FAVOURITES*@
            <tab active="activetab.favourites">
                <tab-heading>
                    <i class="fa fa-heart"></i> Favourites
                </tab-heading>
                <div class="container">
                    ...
                </div>
            </tab>
            @*ICU*@
            <tab active="activetab.icu">
                <tab-heading>
                    <i class="fa fa-bug"></i> ICU
                </tab-heading>
                <div class="container">
                    ...
                </div>
            </tab>
            @*SETTINGS*@
            <tab>
                <tab-heading>
                    <i class="fa fa-gear"></i> Settings
                </tab-heading>
                <div class="container">
                    ...
                </div>
            </tab>
        </tabset>
</section>

This is the load order of my scripts as they appear on the loaded page

<script src="/site/Scripts/jquery-2.1.4.js"></script>
<script src="/site/Scripts/modernizr-2.8.3.js"></script>
<script src="/site/Scripts/bootstrap.min.js"></script>
<script src="/site/Scripts/angular.min.js"></script>
<script src="/site/Scripts/angular-ui-router.min.js"></script>
<script src="/site/Scripts/angular-ui/ui-bootstrap.min.js"></script>
<script src="/site/Scripts/angular-ui/ui-bootstrap-tpls.min.js"></script>

Sorry if this doesn't help at all

**Comment by wesleycho** [comment] 2015-09-04 16:44
[This](http://plnkr.co/edit/kFtrHR?p=preview) makes it clearer - toggling between the parent and child with the console open illustrates this problem.

This needs investigation, but I'd like to get this fixed for the next release.

**Comment by grtjn** [comment] 2015-10-19 10:35
Runs fine for me if I use angular#1.4.6 together with angular-bootstrap#0.14.2. I did prefix all elements with `uib-` to prevent deprecation warnings in the console..

**Comment by icfantv** [comment] 2015-10-19 16:11
@grtjn, did you mean to type Angular 1.13?  UI Bootstrap 0.13.x and higher requires angular 1.3.x or higher.

**Comment by grtjn** [comment] 2015-10-19 18:25
Sorry, I meant angular#1.3.x gave me trouble, angular#1.4.6 worked okay (with deprecation warnings which were easy to fix)..

**Comment by nozshand** [comment] 2015-10-21 01:36
It just happened to us today, we are using <uib-tabset> syntax, revert back to tabset seems to working fine except the deprecation warnings

ui-bootstrap 0.14.2
angular 1.4.7

**Comment by liamdawson** [comment] 2015-10-26 00:04
I'm having this issue when trying to transclude tabs into a tabset.

**Comment by wesleycho** [comment] 2015-10-29 06:45
I believe one should not nest the tabs inside a `<ui-view>` element - the error disappears on the Plunker above when one moves it out, as demonstrated [here](http://plnkr.co/edit/nghKYm?p=preview). If one wants to control display, one can use a simple ng-show/ng-hide or ng-if.

One should not put any directives in between tabs and the tabset, nor wrap it in a directive using transclusion. Thinking about this more, I am going to close this as a won't support for this usage. If someone gives a strong argument in a new issue, I am willing to reconsider, but it seems like there hasn't been much brought up that is a compelling use case for supporting this.

**Closed by wesleycho** 2015-10-29 06:45 UTC
Labels: component: tab, needs: investigation, type: bug

**Comment by piotrd** [comment] 2015-10-29 09:01
@wesleycho what recommendation would you have for what I reported above? (in https://github.com/angular-ui/bootstrap/issues/3692#issuecomment-126602872 and others)

**Comment by sieira** [comment] 2015-11-04 09:06
I don't know if this could help someone, but in my case the problem was, that in my jade template I was doing this:

```jade
uib-tabset
  each module in modules
    ng-include&attributes({'src': module})
```
*Wild problem appeared* when I commented some stuff for a quick dirty test:
```jade
    uib-tabset
    //-
      each module in modules
        ng-include&attributes({'src': module})
    -//
        ng-include(src='"/admin/users"')
```
this was generating

```html
<uib-tabset></uib-tabset>
 <!-- -->
 <uib-tab>...</uib-tab>
 <uib-tab>...</uib-tab>
 <uib-tab>...</uib-tab>
```

So, like the thing explodes when somehow the uib-tab is not contained in an uib-tabset

**Comment by jeson114** [comment] 2016-01-18 10:53
i have the same issue . i thought it was a problem with angular-material but looks like it's an angular issue.
Error: [Ara Error] [$compile:ctreq] Controller 'mdRadioGroup', required by directive 'mdRadioButton', can't be found!
http://errors.angularjs.org/1.4.8/$compile/ctreq?p0=mdRadioGroup&p1=mdRadioButton Object {exception: Error: [Ara Error] [$compile:ctreq] Controller 'mdRadioGroup', required by directive 'mdRadioButton'…, cause: undefined}

**Comment by epferrari** [comment] 2016-06-29 22:23
@wesleycho I'd implore you to revisit this issue. There are many use cases in which a set of tabs contain common logic or represent similar data structure across the group. Writing a custom tab directive that wraps `tab` is much more effective than repeating code between `n` number of similar tabs.

As an aside, our project is using Angular 1.5.5 and ui-bootstrap 0.13, and the error is only revealing itself in karma tests when we mock the custom tab element. For us it doesn't affect production code, but we'd prefer to have code coverage around it if possible. Thanks.
