### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by regisnew** [angular-ui/bootstrap#4869] opened 2015-11-10 20:59 UTC
We should add an option to define the language of components.

**Comment by icfantv** [comment] 2015-11-10 21:15
@regisnew, aside from the one-time binding of certain labels in the datepicker (see #4692), what component are you thinking needs i18n support?

**Comment by regisnew** [comment] 2015-11-10 21:23
Datepicker

**Comment by icfantv** [comment] 2015-11-10 21:39
Ok, I'm going to close this as a duplicate of #4692 then.  Maybe we decide to use this one over that one, but we don't want multiple issues tracking i18n of the datepicker.  Thanks.

**Closed by icfantv** 2015-11-10 21:39 UTC
Labels: type: i18n
