### ISSUE TITLE
multiple modals appended to their parent element in reversed order

### ISSUE THREAD

**Issue by anakreon** [angular-ui/bootstrap#5649] opened 2016-03-18 10:09 UTC
When multiple modals are open at the same time, they are attached to their parent element in order, which is opposite to the order in which they were opened. This behavior first appeared in version 1.0.

If a custom window template is specified for the modals, this forces us to specify z-indexes for modals (using the ugly ng-style="{'z-index': 1050 + index*10}" in window template).
Before version 1.0, it was possible to define a single z-index for modals in a CSS file and the natural order of html displayed the modals in a correct order.

Furthermore, there seems to be a bug in the indexing system. Let's say multiple modals are open at the same time. When I close any modal other than the one on the top and then open a new modal, the newly opened modal has the same index & z-index as the last open modal, i.e. breaking the z-index calculation. All of which worked before version 1.0 with the natural order of modals.

Is closing modals in the middle of modal stack unsupported? Can we get the non-reversed order of modals back?

Angular: 1.4.7
UIBS: 1.2.4
Bootstrap: 3.3.6

**Comment by icfantv** [comment] 2016-03-18 16:39
@anakreon please be respectful of our time and use the issue template we've put in place.  The reason we have it is that 1) in makes the investigative portion of our jobs that much quicker (and thus, able to react to YOUR needs faster), and more importantly 2) it forces you to really think about your problem and requires to to reproduce it in a sandboxed environment.

I'm going to close this until you can create a minimal reproduction.  Feel free to use the plunker link from our demo site to get you started.

**Closed by icfantv** 2016-03-18 16:39 UTC
