### ISSUE TITLE
tooltip blocked by javascript alert in firefox

### ISSUE THREAD

**Issue by aszharite** [angular-ui/bootstrap#3284] opened 2015-02-11 08:48 UTC
If you put tooltip on a button, on action you show an alert for confirmation and load a modal after pressing OK, the tooltip will remain active over the modal and won't disappear.

**Comment by wesleycho** [comment] 2015-04-06 13:34
Can you reproduce this with [Plunker](http://plnkr.co/)?

**Comment by wesleycho** [comment] 2015-09-11 02:18
Closing due to lack of a reproduction

**Closed by wesleycho** 2015-09-11 02:18 UTC
Labels: component: tooltip, needs: plunkr
