### ISSUE TITLE
error appears when year or date on top on popup is clicked when using datepicker-mode

### ISSUE THREAD

**Issue by c0debreaker** [angular-ui/bootstrap#2499] opened 2014-07-23 06:26 UTC
This screenshot shows the error on the console after I clicked the year and when using datepicker-mode="'month'". http://i.imgur.com/ASCYoc2.png

The error:
Error: [$compile:nonassign] Expression ''month'' used with directive 'datepicker' is non-assignable!

However, if I remove the single quotes, the error goes away but it doesn't display the 12 months choices by default anymore. It shows all the dates of a month.

Here is my code

on my controller:
```
$scope.dateOptionsMonth = {
    'year-format': "'yyyy'",
    'starting-day': 0,
    'show-weeks' : false,
    'datepicker-mode' : "'month'",
    'min-mode' : "month"
};
$scope.dateOptionsDay = {
    'year-format': "'yyyy'",
    'starting-day': 0,
    'show-weeks' : false,
    'datepicker-mode' :"'day'",
    'min-mode' : "day"
};
```
on my html:

```                             
<input type="text" class="datepickerClass datePickerPosition" ng-click="open($event)"
    datepicker-popup="{{$parent.formatMonth}}"
    ng-model="$parent.dt"
    is-open="$parent.opened"
    show-button-bar="false"
    min-date="$parent.minDate"
    max-date="$parent.maxDate"
    datepicker-options="$parent.dateOptionsMonth"
    ng-required="true"
    close-text="Close"
    min-mode="month"
    datepicker-mode="'month'"
/>
```

**Comment by adamors** [comment] 2015-01-03 14:04
This issue is still present. Here's a plunkr to reproduce what @c0debreaker is saying: 
http://plnkr.co/edit/K3vjEygZEcG4robCeqHo?p=preview

**Comment by c0debreaker** [comment] 2015-01-03 18:59
Thank you @adamors . I'm not sure why no one has responded to my post. Maybe the devs couldn't figure out a fix yet.

**Comment by AztecXocolatl** [comment] 2015-01-13 03:41
I hit this issue today, and am editing the datepicker directive to get around it until I find a better (less hacky) fix. It works for me since I am always setting my datepickerMode and minMode to the same value when using this directive. See // REMOVED and // ADDED lines below:

.directive( 'datepicker', function () {
  return {
    restrict: 'EA',
    replace: true,
    templateUrl: 'template/datepicker/datepicker.html',
    scope: {
      // datepickerMode: '=?',         // REMOVED
      dateDisabled: '&'
    },
    require: ['datepicker', '?^ngModel'],
    controller: 'DatepickerController',
    link: function(scope, element, attrs, ctrls) {
      var datepickerCtrl = ctrls[0], ngModelCtrl = ctrls[1];
      scope.datepickerMode = datepickerCtrl.minMode;        // ADDED

      if ( ngModelCtrl ) {
        datepickerCtrl.init( ngModelCtrl );
      }
    }
  };
})

**Comment by c0debreaker** [comment] 2015-01-13 10:33
Thank you @AztecXocolatl I'll try it later :)

**Comment by c0debreaker** [comment] 2015-01-13 16:52
Awesome @AztecXocolatl ! It worked!!! :)

**Comment by wesleycho** [comment] 2015-11-02 06:36
Closing, as I believe this has already been fixed as far as I can tell [here](http://plnkr.co/edit/IE9KKtL5l4pCKwQRcWc2?p=preview).

**Closed by wesleycho** 2015-11-02 06:36 UTC
Labels: component: datepicker, type: bug
