### ISSUE TITLE
minDate property not working properly

### ISSUE THREAD

**Issue by kanchan1991** [angular-ui/bootstrap#6213] opened 2016-08-30 04:59 UTC
Datepicker Popup directive enables use of input box to toggle a datepicker. When we set a minDate property for the datepicker and manually enter the date lesser than minDate in the input box, it accepts that date and throws no exception. This is allowing selection of disabled date in the datepicker.

**Comment by readme42** [comment] 2016-09-06 12:48
I had the same problem long time ago. Some day it was fixed (IIRC) but now its back :(

**Comment by steffi501** [comment] 2016-09-06 12:50
+1

**Comment by RopoMen** [comment] 2016-09-15 06:14
I have noticed the same thing.

Simple way to test this is to create a date object
```js
$scope.date = new Date(2016, 8, 15)
```

and
```html
<input type="text" class="form-control" uib-datepicker-popup="dd.MM" ng-model="date" />
```

This will return date with year 1900, I noticed that in dateparser there is default year 1900, but I'm expecting it to fallback to given date object year -> 2016 in this case

**Comment by readme42** [comment] 2016-09-30 13:01
Same thing with maxDate. Datepicker-Popup does not set invalid class on input if manually entered date is out of minDate/maxDate-restrictions. Can be seen in current docs.

**Comment by readme42** [comment] 2016-09-30 13:03
This issue seems to be a duplicate of #6124

**Comment by wesleycho** [comment] 2016-11-27 10:43
Going to close as a duplicate, follow #6124 for progress on this issue.

**Closed by wesleycho** 2016-11-27 10:43 UTC
