### ISSUE TITLE
problem with Pagination

### ISSUE THREAD

**Issue by atmfans** [angular-ui/bootstrap#5034] opened 2015-12-08 10:31 UTC
console always say : Error: [$parse:syntax] Syntax Error: Token ':' not a primary expression at column 1 of the expression [::getText('first')] starting at [::getText('first')]

What's the problem........

Thank you for help

**Comment by pkozlowski-opensource** [comment] 2015-12-08 10:36
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

**Comment by wesleycho** [comment] 2015-12-14 04:33
Closing due to lack of actionable information

**Closed by wesleycho** 2015-12-14 04:33 UTC
Labels: component: pagination, needs: plunkr

**Comment by joshmouch** [comment] 2016-01-23 17:05
Wish this wasn't closed....

**Comment by icfantv** [comment] 2016-01-24 05:04
@joshmouch, while we here on the UIBS team would like to believe we are smart, unfortunately, we are not savants.  We cannot read people's minds.  This is the reason (well, one of the reasons) we have documented procedures for how to properly report a bug.

While the text of the original issue was not the most egregious we've seen, it's pretty bad.  We have no idea what the user was doing or was trying to do.  All we were given was an error message and absolutely no context.

If you're getting this exact same error, might I suggest recreating the problem in a minimally working plunker?  At least then, we would have something to look at.  Thanks.

**Comment by joshmouch** [comment] 2016-01-24 14:31
I understand that in general, but this is a pretty specific error message that, if I had enough experience with Angular, I would say to myself: "Angular can't handle '::'?" That's odd... Angular shouldn't have any trouble with that... it must not be the newest version.  Then I'd say "Check the top of your angular.js file and see what version it is."

That was the problem in my case.  I had the right version of Angular in bower.json, but a different dependency in bower.json was causing version 0.14.3 of Angular to be resolved instead of 1.1.0.  So I had to add an entry to my "resolutions" section in bower.json to force the newest version of Angular.

**Comment by icfantv** [comment] 2016-01-24 15:27
And if you'd had created a plunker like we've asked and documented you would have either seen or not seen the error and had you seen the error, we would have caught it because library versions are the first, and easiest things, for us to look at (and change).

I can totally understand your frustration as I've been in similar situations.  In this case, however, I disagree and fail to see how this is suddenly our fault and/or responsibility.  If the end-user cannot be bothered to read our documentation and follow basic instructions, it is difficult for us to want to put forth an exorbitant amount of effort to extract what is really going on.

I'm glad you found the issue.

**Comment by joshmouch** [comment] 2016-01-24 15:47
I understand.

In this case a plunker would not have reproduced the error (unless it also included the 50 other dependencies in my bower.json).

Just to clarify for Google searchers, a general parsing error inside angular.ui is probably a version issue.
