### ISSUE TITLE
datepicker should be easier to be aligned to the right

### ISSUE THREAD

**Issue by jrencz** [angular-ui/bootstrap#2208] opened 2014-05-15 20:03 UTC
now it calculates `left` and sets it as inline property so I have to use `left: auto !important; right: 0` to make right border of the input and datepicker aligned. And as everyone should I'm trying to avoid `!important` as much as possible.
`left: 0` may be set on class so it's easier to override it.
What's more: simple classes to stick the picker to the left or to the right may be provided.

**Comment by lloiser** [comment] 2015-04-16 21:37
+

**Comment by chrisirhc** [comment] 2015-04-17 05:59
Duplicate of #1012

**Closed by chrisirhc** 2015-04-17 05:59 UTC
Labels: resolution: duplicate
