### ISSUE TITLE
Datepicker: weird interaction with jQuery after upgrade to 1.2.x

### ISSUE THREAD

**Issue by pmarchezz** [angular-ui/bootstrap#5739] opened 2016-04-04 17:48 UTC
I am experiencing a weird issue after upgrading to angular-ui bootstrap 1.2.x (from 0.14.x) with the datepicker component. I use the datepicker inside a custom directive that needs to know if the user clicked inside or outside it (to run validation logic and close itself if the click was outside). I solved the issue with a couple of lines of jQuery that roughy look like this:

```html
<div id="my-directive">
    <uib-datepicker ng-model="model"></uib-datepicker>
    <div>
        [... other stuff ...]
   </div>
</div>
```
```javascript
$document.on('click', function(event) {
    var parentFound = $(event.target).closest('#my-directive').length > 0;
    if(parentFound) {
        // user clicked inside directive; do nothing
    } else {
        // user clicked outside; validate and do other stuff needed
    }
});
```
Unfortunately this solution produces inconsistent behaviour after upgrading to 1.2.5: clicking (almost) any button on the timepicker component does trigger the `else` clause, which is unexpected. Clicking on labels seems to work fine.

I debugged the issue quite a bit and cannot figure out what's going on. It looks like that, for some reason, the `closest` function cannot reach some ancestors of the event target, thus failing to find the root of my directive.

I reproduced a stripped-down version of the issue in this codepen: http://codepen.io/anon/pen/BKmKzK

Is this a bug or I'm missing something? This issue goes away after reverting back to 0.14.x.

Angular version: 1.4.10,
Bootstrap version: 3.6.6,
Angular-UI Bootstrap version: 1.2.5.

**Comment by icfantv** [comment] 2016-04-04 18:29
@pmarchezz, it's not at all clear to me what you're trying to accomplish.

also, you also use both datepicker and timepicker in your comments and they are separate/different components.  did you mean to just say datepicker?

finally, the issues forum is not for support requests.  i am not seeing a bug here but will wait for your explanation before closing this as such.

i await your response.

**Comment by wesleycho** [comment] 2016-04-04 20:47
e283cea probably is the cause of this, from 1.2.0.

It might be better to create a custom directive on an element closer to the event with a listener for the click event to do this sort of detection.

**Comment by pmarchezz** [comment] 2016-04-05 06:58
Yes, I meant datepicker where i wrote timepicker.

About what I'm trying to accomplish, think about a popup behaviour: I have a directive that opens a popover-like panel that allows the user to pick a date and other information. I'm not using the provided datepicker-popup because I need to include other components in the popup, not just the datepicker. I also need to detect if the user clicked inside/outside the popup to be able to close it if the click is outside. I was able to do so with the approach outlined in the first post with angular-ui bootstrap 0.14.x but I am unable to do so with the latest version, if the user clicks the datepicker - everything works fine for the rest of the directive. I guess this is caused by that stopPropagation added in the commit you linked.

If this falls under support requests, then feel free to close it. I thought it could be a bug since it was working on an old version and I found no information about this change in changelogs. I'm still not sure how I'll solve it; the issue is about clicks inside the datepicker, so creating a custom directive to handle those would imply modifying the datepicker code, I suppose.

Thanks for your time.

**Comment by icfantv** [comment] 2016-04-05 13:10
@pmarchezz, it was marked as a breaking change.  You need to read the changelog thoroughly and for every version from your current to the one to which you are upgrading.

**Comment by pmarchezz** [comment] 2016-04-05 14:31
@icfantv you're right, I missed that change. I wasn't looking for something related to event bubbling, and I probably overlooked that. However, even if I comment out the code changed in the commit @wesleycho linked, the issue is still there. I suspect it's not related at all with event bubbling (unless for some reason $.closest() uses that to navigate the DOM, which seems very unlikely to me...).

**Comment by wesleycho** [comment] 2016-04-28 04:29
Closing this due to lack of actionable tasks on the library side, and being a support issue.

**Closed by wesleycho** 2016-04-28 04:29 UTC
Labels: needs: info
