### ISSUE TITLE
modal does no translation if size set to lg or sm

### ISSUE THREAD

**Issue by osterbaer** [angular-ui/bootstrap#5036] opened 2015-12-08 19:55 UTC
Click the sample buttons on:
https://angular-ui.github.io/bootstrap/#/modal

You will see that the modal translates from the top, if you click the button "Open me!". This doesn't work, if the size is set to sm or lg. Just try clicking the buttons "Large modal" and "Small modal". 
I've found out that something in line 5 of file template/modal/window.html causes this behavior:
```
<div class="modal-dialog" ng-class="size ? 'modal-' + size : ''">
```
If you change it to:
```
<div class="modal-dialog {{size ? 'modal-' + size : ''}}">
```
it works.

Sorry for my bad english and probably my poor understanding of angular.
Best regards!
Jo

**Comment by wesleycho** [comment] 2015-12-08 22:14
That is interesting...what might be happening is that ng-class is evaluated at the wrong time.

Need to investigate further, but thanks for finding something that works!

**Comment by wesleycho** [comment] 2015-12-09 07:19
I did a simple investigation - the suggested change adds an undesirable flicker, as can be seen [here](http://plnkr.co/edit/?p=preview). This is not a good solution to this problem.

**Comment by wesleycho** [comment] 2015-12-10 15:59
Going to close as a duplicate of #4263

**Closed by wesleycho** 2015-12-10 15:59 UTC
Labels: component: modal, needs: investigation
