### ISSUE TITLE
Pagination paging causes form.$dirty

### ISSUE THREAD

**Issue by Arkiliknam** [angular-ui/bootstrap#5874] opened 2016-05-05 13:23 UTC
### Bug description:
Paging using uib's Pagination within a form causes the form to become dirty.

### Link to minimally-working plunker that reproduces the issue:

I'm having trouble setting this up in Plunker (not experienced Plunker user). The code is simple enough and is as follows. You can see the Dirty flag gets raised when pages are changed.

    <p>DIRTY: {{ auditFormForm.$dirty }}</p>
    <form class="form-horizontal" name="auditFormForm" novalidate warn-dirty>
        
        <div class="form-group">
            <label class="col-sm-2 control-label" for="auditFormName">Name</label>
            <div class="col-sm-6">
                <input id="auditFormName" name="auditFormName" class="form-control" type="text" ng-model="auditForm.auditFormName" placeholder="Enter a name" required/>
                <div class="text-danger" ng-show="auditFormForm.auditFormName.$error.required && auditFormForm.auditFormName.$dirty">Please enter a name for this audit form.</div>
            </div>
        </div>

        <pagination ng-model="page" total-items="recordCount" items-per-page="pageSize" boundary-links="true" max-size="10" rotate="false"></pagination> 

    </form>

### Version of Angular, UIBS, and Bootstrap

Angular: v1.5.0

UIBS: v0.13.0

Bootstrap: v3.3.6

**Comment by icfantv** [comment] 2016-05-05 14:28
@arkiliknam, you can use the blue Edit in Plunker link from our demo page.  Just find the pagination section and it will be at the bottom.

As we are all volunteers on this project, we simply do not have the time to assist every person entering an issue they think is a bug in creating a reproducible plunker.

Please give that a go first.  Thanks.

**Comment by Arkiliknam** [comment] 2016-05-05 14:51
Thanks for the tip. Here's the Plunk I came up with: http://embed.plnkr.co/8CDK4Q8xPzdBWtiP5BCw/

**Comment by RobJacobs** [comment] 2016-05-05 17:03
Does the pagination directive need to be in your form?

**Comment by icfantv** [comment] 2016-05-05 22:02
@Arkiliknam, as @RobJacobs was eluding to, you should not be putting the pagination element in your form.  By default, the form controller is going to respond to events emitted by elements with the `ng-model` directive to report validation, changed, etc... which is why your form is getting marked as dirty.

By FAR, the easiest way is to remove the pagination component from your form.  If you simply MUST have it there, you will need to wrap the `uib-pagination` directive with an `ng-form` element and tell the form controller to NOT propagate events out via something like (or you can possibly make a new directive that requires ngModel and mucks with it instead):

```
function IsolateFormDirective($timeout) {

  return {
    restrict: 'A',
    require: '?form',
    link: function link(scope, $element, attrs, formController) {

      if (!formController) {
        return;
      }

      $timeout(function () {
        // Remove this form from parent controller
        var parentFormController = $element.parent().controller('form');
        parentFormController.$removeControl(formController);

        // Replace form controller with a 'null-controller'
        var isolateFormCtrl = {
          $addControl: angular.noop,
          $removeControl: angular.noop,
          $setValidity: angular.noop,
          $setDirty: angular.noop,
          $setPristine: angular.noop
        };

        angular.extend(formController, isolateFormCtrl);
      });
    }
  };
}
```

I'm closing this as it is not a bug, but rather a usage issue on your part and supporting this use case is beyond the scope of this library.

**Closed by icfantv** 2016-05-05 22:02 UTC
Labels: component: pagination, needs: plunkr

**Comment by Arkiliknam** [comment] 2016-05-06 08:45
@icfantv, thanks for looking into this and for your response. My solution was also to remove the pagination from our form elements, luckily all of the instance we have allowed for this. I thought I would report it here as it seemed to be a bug, (ie, not changing any input fields but form still becomes dirty when using a 3rd party lib that is not a form input). I wasn't aware that AngularJS's ng-model directive was the cause, as you say. That's something I will be sure to look out for in the future!

**Comment by icfantv** [comment] 2016-05-06 15:13
@Arkiliknam, the best way to see this, is for you to put `<pre>{{ your_form_name | json }}</pre>` in your template and you will see all the form properties and models on the form in your template and you will see them change, live.

**Comment by MrRobWad** [comment] 2018-12-12 19:17
Using a directive something like the below "ignore-dirty", you can prevent the pagination's model from making the form dirty.

`<pagination ignore-dirty ng-model="page" ...></pagination>`

`myApp.directive('ignoreDirty', [function () {
	return {
		restrict: 'A',
		require: '?ngModel',
		link: function (scope, elm, attrs, ctrl) {
			if (ctrl !== null) {
				ctrl.$setPristine = function () {};
				ctrl.$pristine = false;
			}
		}
	};
}]);`
