### ISSUE TITLE
rating directive glitch when ngAnimate is imported

### ISSUE THREAD

**Issue by davidda** [angular-ui/bootstrap#3154] opened 2015-01-04 11:17 UTC
I noticed a weird glitch with the rating directive. When you go over it with the mouse rather quickly the active state of the individual icons tends to get "stuck". So it will have the active css class even if the mouse left the control.

At first I couldn't reproduce it, but then i fugured it out: It happens as soon as you import ngAnimate! So just importing, not using it at all and the rating control glitches out.

See this [Plunker](http://plnkr.co/edit/2AasoNs7PxLv4OZlIm06?p=preview)

The events seem to fire correctly, the value is set. For my untrained eye it seems as if ngClass is not updating correctly.

**Comment by rvanbaalen** [comment] 2015-03-31 14:50
So you're just hovering over the stars really quick and at a certain point they get 'stuck' on their active state? 

If that's the case, I can't reproduce that in your plunker on Chrome. Which browser do you use?

**Comment by davidda** [comment] 2015-03-31 16:35
Yes, exactly. I checked again with Firefox 37 and IE 11.

**Comment by Blewin** [comment] 2015-07-04 15:03
Have same probleems on
38.0 Mozilla Firefox for Ubuntu canonical - 1.0 
on two different machines (glitch can be reproduced on your demo)
![pasted_image_at_2015_07_04_04_29_pm](https://cloud.githubusercontent.com/assets/8094272/8508399/a11a5b6c-226e-11e5-9a89-4c53e8c79d95.png)

**Comment by wesleycho** [comment] 2015-08-06 07:24
I am not able to reproduce this at all.

Something tells me this is going to be a tricky one...

**Comment by dennismuys** [comment] 2015-08-12 11:20
I notice the same behaviour, I am developing a site on my local pc and the hovering works fine, even if I go mental on the mouse.
If my coworker connects to my site over lan he can get the same hover problem as OP in firefox AND in chrome (he has to try harder for chrome though)

**Comment by wesleycho** [comment] 2015-08-19 18:13
Do you happen to know whether the versions of Chrome and Firefox are up to date on his machine?

**Comment by wesleycho** [comment] 2016-03-05 22:44
Is this reproducible for anyone still with Angular 1.5?

**Comment by davidda** [comment] 2016-03-06 07:57
Good news: It's gone.
I took my original [punklr](http://plnkr.co/edit/2AasoNs7PxLv4OZlIm06?p=preview) and changed to Angular 1.5 and the issue disappeared. Tested on Firefox 44.0.2 and Edge 25.

**Comment by wesleycho** [comment] 2016-03-06 15:14
Great - this sounded like an ngAnimate issue to me, didn't think there was anything we could do here.

Closing as fixed.

**Closed by wesleycho** 2016-03-06 15:14 UTC
Labels: browser: firefox, browser: IE11, component: rating, needs: investigation
