### ISSUE TITLE
On Android tablet touching popover causes an overlay over navbar

### ISSUE THREAD

**Issue by karolinkas** [angular-ui/bootstrap#3696] opened 2015-05-21 14:48 UTC
I´m using Angular-UI Version 0.11.2 and Bootstrap v3.3.4, my popovers are looking all find and are the way I want them now, but there´s this strange sideeffect. The overlay in the same color like the navbar. 
These are the popover options:  
thepopover = {
                                                        animation: 'compare comparepopover' + i,
                                                        title: d.data.name,
                                                        content: '<div class="attribute"><p class="small">' + scope.datasource.comparating.name + '</p><p class="bold">' + scope.datasource.comparation[i].value + '%</p></div><div class="attribute"><p class="small">JUGADOR</p><p class="bold">' + d.data.value + '%</p></div>',
                                                        target: $circ,
                                                        container: 'body',
                                                        placement: placem,
                                                        trigger: 'mouseenter',
                                                        html: true,
                                                        delay: {show: 1000, hide: 0}
                                                    };

**Comment by rvanbaalen** [comment] 2015-05-21 15:02
Please update to the latest UI Bootstrap 0.13.0. We dont support older versions.

**Comment by karolinkas** [comment] 2015-05-22 09:31
Angular-UI is being updated,  when doing "bower update angular-bootstrap"? Just did, but still the overlay.

**Comment by rvanbaalen** [comment] 2015-05-30 22:02
Provide a plunkr reproducing your problem. That way we can help investigating it.

**Comment by pkozlowski-opensource** [comment] 2015-12-01 10:45
Closing as the issue is not clear and we don't have plunker.

**Closed by pkozlowski-opensource** 2015-12-01 10:45 UTC
Labels: component: popover, needs: plunkr, type: mobile
