### ISSUE TITLE
Typeahead trigs function when going below typeahead-min-length

### ISSUE THREAD

**Issue by loveaurell** [angular-ui/bootstrap#2632] opened 2014-08-26 12:55 UTC
When removing characters, typeahead automatically triggers my search function when going below the typeahead-min-length amount. For example, my typeahead-min-length is set to '3' and the input field is populated with the word 'testsearch'. When quickly erasing all the characters it still triggers my function with the string 'tes'.

Is this correct behavior?

**Comment by rvanbaalen** [comment] 2015-05-30 21:58
Please provide a plunkr and verify this is still an issue in Angular 1.3 with UI Bootstrap 0.13.

**Comment by pkozlowski-opensource** [comment] 2015-08-16 18:57
Closing due to the lack of reproduction scenario.

**Closed by pkozlowski-opensource** 2015-08-16 18:57 UTC
Labels: component: typeahead, needs: plunkr
