### ISSUE TITLE
Mutliple modals, double click closes two modals instead top.

### ISSUE THREAD

**Issue by Advarius** [angular-ui/bootstrap#6061] opened 2016-06-29 14:25 UTC
When there are two nested modals, i.e. one modal is shown from another, double click on backdrop of the top modal results in closing of both modals instead only top.

Problem is reproduced even if double click is done when cursor is above first modal. As in the attached image from plunker, need to click in selected area.

![image](https://cloud.githubusercontent.com/assets/5681534/16455754/2d7eb0d2-3e1e-11e6-99d8-c8e521870df7.png)

http://plnkr.co/edit/Fidgh0aBW6LMi9nUaetg

**Comment by icfantv** [comment] 2016-07-02 22:31
@Advarius this is expected behavior because you have the modals configured to close when the backdrop is clicked.  You can turn this off via the `backdrop` property.

**Comment by Advarius** [comment] 2016-07-03 06:56
This is not expected behavior, because as I mentioned, first modal will be closed even if double click is above selected area on the screenshot. In other words, first click is on the backdrop of the top modal, but second click is on the content of the first modal. Why modal is closed when I click it's content?

**Comment by icfantv** [comment] 2016-07-03 14:09
@advarius, ah, thank you for the better example.  I'll flag for investigation.

**Comment by daimoonis** [comment] 2016-07-19 13:56
Hello, i'm facing the same issue.
Both modals are simply taken out of its stack and it happens twice as there happen two click actions on backdrop.

**Comment by jkoontz2010** [comment] 2016-07-24 05:18
I didn't realize this, but this issue was corrected by #6104

**Comment by wesleycho** [comment] 2016-07-24 06:35
Closing as fixed

**Closed by wesleycho** 2016-07-24 06:35 UTC
Labels: component: modal, PRs plz!, type: bug
