### ISSUE TITLE
datepicker-popup maxDate and minDate issue

### ISSUE THREAD

**Issue by lnu** [angular-ui/bootstrap#5795] opened 2016-04-13 07:13 UTC
Since the beginning(version 0.7) we were using the maxDate and minDate(dynamically) options of the datepickerPopup. 
After the changes in version 1.3.0, it's not possible anymore. The maxDate can only be set from the datepickerOptions and not from attributes in the html.
How can I get the old behavior back? 
I don't really want to create datepickerOptions variable on scopes everywhere and to add watch in controllers to keep the maxDate minDate up to date.

Here is a a plunker:http://plnkr.co/edit/HJi8zfRjq7z9erAvSraG?p=preview

It works with version 1.2.5. Try to change the version to 1.3.0 and you'll see it doesn't work anymore.

**Comment by wesleycho** [comment] 2016-04-13 15:01
Looks like a bug: http://plnkr.co/edit/8KM7ZNZR6s6oXsolx25Y?p=preview

We moved away from the attributes since the attributes added an excessive number of watches to people's applications & created state maintenance problems on our side. It also cluttered the HTML templates for usage.

**Comment by wesleycho** [comment] 2016-04-13 15:09
Updated Plunker - this is not a bug, and this is an intentional change.

Closing as won't change.

**Closed by wesleycho** 2016-04-13 15:09 UTC
Labels: component: datepicker-popup
