### ISSUE TITLE
Impossible to close modals in 0.13.0

### ISSUE THREAD

**Issue by slawo** [angular-ui/bootstrap#3800] opened 2015-06-11 10:31 UTC
Modals won't close with version 0.13.0.

Switching back to 0.12.1 fixes the issue:

    $scope.animationsEnabled = true;
    $scope.open = function (opca) {
      var modalInstance = $modal.open({
        animation: $scope.animationsEnabled,
        templateUrl: 'OpcaResult.html',
        controller: function ($scope, $modalInstance, opca) {
          $scope.opca = opca;

          $scope.ok = function () {
            $modalInstance.close();
          };

          $scope.cancel = function () {
            $modalInstance.dismiss('cancel');
          };
        },
        resolve: {
          opca: function () {
            return opca;
          }
        }
      });

      modalInstance.result.then(function (selectedItem) {
        $scope.selected = selectedItem;
      }, function () {
        $log.info('Modal dismissed at: ' + new Date());
      });
    };

**Comment by TimonVS** [comment] 2015-06-11 15:16
Will the modal not close, or does the backdrop not go away?
I'm experiencing the latter problem because of breaking changes in angular-animate 1.4.

It's also better to show the problem using a Plunkr, JSFiddle or JSBin demo :).

**Comment by slawo** [comment] 2015-06-11 15:22
The backdrop remains and the entire page becomes unresponsive.

Looking into it, indeed the project uses angular-animate 1.4. But despite that it works with 0.12.1 but not with 0.13.0.

**Comment by TimonVS** [comment] 2015-06-11 15:59
As a temporary solution I used `animation: false`. But this needs a fix.

**Comment by pgrodrigues** [comment] 2015-06-11 16:02
Backdrop is not closing here as well. I will go back to 0.12.1 while this isn't fixed.

**Comment by rvanbaalen** [comment] 2015-06-11 17:51
Please [use the search function](https://github.com/angular-ui/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+modal+backdrop)

Closing as a duplicate of #3633

**Closed by rvanbaalen** 2015-06-11 17:51 UTC
