### ISSUE TITLE
Datepicker displays off the bottom of the screen

### ISSUE THREAD

**Issue by cgastin** [angular-ui/bootstrap#1837] opened 2014-02-22 04:44 UTC
Since the popup for the datepicker always displays under the input, this becomes a problem when the input is at the bottom of the screen because the popup for the datepicker displays off the bottom of the screen. 

A better solution is to detect the bottom of the screen and re-position the popup above the input. 

I have actually modified v0.10.0 to do this, and will be making a pull request to fix this problem.

**Comment by gitnik** [comment] 2015-02-11 08:34
:+1: for this functionality. This render the datepicker pretty much unuseable

**Comment by rvanbaalen** [comment] 2015-05-19 18:38
@cgastin Can you provide a plunkr and confirm this is still an issue in UI Bootstrap 0.13.0?

**Comment by rvanbaalen** [comment] 2015-05-30 21:49
Closing due to inactivity. Please re-open if you can provide a plunkr and confirm this is still an issue with Angular 1.3 and UI Bootstrap 0.13.

**Comment by cgastin** [comment] 2015-06-16 14:19
Here is a plunker demonstrating the problem.  

http://plnkr.co/edit/5G45sNCYErtvIqczJRRk

While the scroll bar appears now, and the user can get to the calendar, which I don't believe was the case in earlier versions. When the calendar is going to extend past the bottom boundary of the screen then the calendar should re-position itself to above the input box the same way the datepicker does in Bootstrap.

**Comment by cgastin** [comment] 2015-06-16 14:29
Since it was closed by the owner, I can not reopen after adding the plunker. Will you reopen, or should I open a new issue.

**Comment by wesleycho** [comment] 2015-08-08 05:46
The Plunker is invalid - it was lost somewhere it looks like, and needs another reproduction.

**Comment by icfantv** [comment] 2015-10-28 15:47
Closing in favor of #4762.

**Closed by icfantv** 2015-10-28 15:47 UTC
Labels: component: $position, component: datepicker, needs: plunkr
