### ISSUE TITLE
Dynamic typeahead expression no longer works

### ISSUE THREAD

**Issue by oliversalzburg** [angular-ui/bootstrap#4631] opened 2015-10-15 12:55 UTC
http://plnkr.co/edit/W2ghwZQogQX25ZaJO5t7?p=preview

Throws: `Error: Expected typeahead specification in form of "_modelValue_ (as _label_)? for _item_ in _collection_" but got "{{expression}}".`

Worked fine with `typeahead`, no longer works with `uib-typeahead`.

**Comment by pkozlowski-opensource** [comment] 2015-10-15 13:00
I don't think it is a use case that we ever intended to support. I would suspect that it is more to do with the Angular version change, but this is pure speculation.

In short: IMO this is won't fix - you shouldn't be using interpolation where we do expect an expression

**Comment by pkozlowski-opensource** [comment] 2015-10-15 13:00
More importantly - we don't want to "observe" this attribute as it would have a negative perf implications

**Comment by Foxandxss** [comment] 2015-10-15 13:04
I never thought of typeahead being used like that. I do agree with @pkozlowski-opensource in here.

Out of curiosity, using latest ui-bootstrap and the deprecated non-prefixed version. Does it work?

**Comment by oliversalzburg** [comment] 2015-10-15 13:10
@Foxandxss It works perfectly fine when replacing `uib-typeahead` with `typeahead`. As in, the deprecated version works fine.

**Comment by Foxandxss** [comment] 2015-10-15 13:17
Then it is a bug.

**Comment by pkozlowski-opensource** [comment] 2015-10-15 13:22
@Foxandxss I don't think it is a bug and I still don't think we should "fix" it. It might used in the past but this was never intentional. If it worked it was "by chance", side effect of the existing implementation. As such it isn't part of the API we've intended to provide.

What I'm trying to say is that not every change in impl is a regression (otherwise bug fixes would be considered regressions as well!) and we shouldn't strive to support each and every exotic use case. I feel like we've got part of responsibility in providing and supporting sane APIs. And it is not like we are not covering particular use-cases here: we still observe parts of the expressions from the micro-syntax. I see no point in observing it twice

**Comment by oliversalzburg** [comment] 2015-10-15 13:26
We're using the typeahead in another directive and allow the typeahead expression to be set on the parent directive. I thought that we way we implemented this was the right way to do it, since it seemed to work just fine. If this is considered exotic and wrong, I'd be happy to adjust our implementation to the correct way to do it.

Any pointers would be appreciated.

**Comment by pkozlowski-opensource** [comment] 2015-10-15 13:33
@oliversalzburg if you are wrapping typeahead it is kind of extending it. Unfortunately there is no great story for extending directives in ng right now, but there are certain techniques that make it possible.

Without going too much into the details, I would suggest either decorating the typeahead directive or re-compiling your directive template. I know that this is more work as compared to what you've been doing right now....

**Comment by oliversalzburg** [comment] 2015-10-15 13:35
@pkozlowski-opensource Knowing that there is no easy solution is already assuring that I'm not missing something :) Thanks

**Comment by Foxandxss** [comment] 2015-10-15 13:41
I see where the problem relies. In the deprecated version, we are parsing the typeahead attribute in the postlink (where it gets interpolated) and in the prefixed one, we are doing it on the controller (where is not  interpolated).

Personally, I would fix it, we are not meant to break the existing users on their way of updating to use prefixes. It is a mere single line of code.

The user could hack it together, but that is a pain.

**Comment by pkozlowski-opensource** [comment] 2015-10-15 13:45
> Personally, I would fix it, we are not meant to break the existing users on their way of updating to use prefixes. It is a mere single line of code.

Send a PR then. I'm not opposing to "fixing" this provided  that there are no code code / runtime perf consequences. But we need to be clear about the fact that this is not sth that we recommend / intend to support.

**Comment by Foxandxss** [comment] 2015-10-15 13:48
I totally agree Pawel, I am not trying to make happy everyone in here and I agree that a dynamic expression for that is a bit fishy (like if you were going to do that in a ng-repeat). My issue is that we wanted to make the migration as painless as possible and if we start to break the people code, that means we are not really doing it well.

But actually the problem wasn't in the migration, but a refactor that @wesleycho made to move the logic to the controller.

I am trying to see if there is a better solution.

**Comment by wesleycho** [comment] 2015-10-15 13:48
If this is to be "fixed", I recommend using the init function to run the logic for parsing.

In addition, a unit test should be added.

**Comment by wesleycho** [comment] 2015-10-15 13:49
I should also note that there was longstanding work to turn typeahead into a controller in #1754 - I did not anticipate such a undocumented use such as this.

**Comment by Foxandxss** [comment] 2015-10-15 13:54
No one is blaming you Wes, since this is not a supported behavior, we didn't have tests for it.

As a middle ground (perhaps not the best deal), I hacked it a bit creating a `uib-typeahead-dynamic` for this use case http://plnkr.co/edit/AVtgtog2TLSogWKj8fAN?p=preview

Not to merge with this lib but as a workaround.

**Comment by Foxandxss** [comment] 2015-10-15 14:18
@pkozlowski-opensource the changes would be:

`var parserResult = typeaheadParser.parse(attrs.uibTypeahead);`

For:

`var parserResult = typeaheadParser.parse($interpolate(attrs.uibTypeahead)(scope));`

$interpolate won't add overhead, but that means that we are supporting the feature then :/

**Comment by wesleycho** [comment] 2015-10-19 07:05
Did we come to a decision here? I don't think this is a good thing to support, as this is undocumented, and something that has performance implications - any change to "fix" this hardens support for something we want to recommend against.

**Comment by wesleycho** [comment] 2015-11-08 21:50
After talking with @Foxandxss , we've decided to close this as something we won't support. We never intended to support this usage, and any code change will harden support for this.

**Closed by wesleycho** 2015-11-08 21:50 UTC
Labels: component: typeahead, type: bug

**Comment by oliversalzburg** [comment] 2015-11-08 23:07
I understand. We'll be able to work around the issue with the contributions from @Foxandxss (thanks btw!) until we come up with a proper solution. Cheers :)

**Comment by dwightdegroff** [comment] 2015-12-02 17:32
Sad to see that this is not something that will be supported. I also used this functionality as part of some dynamic form generation, a la:
```
<input id="{{field.id}}" name="{{field.name}}" ng-pattern="{{field.validation.pattern}}" typeahead="field.typeahead" />
```

**Comment by wesleycho** [comment] 2015-12-02 17:37
One can dynamically generate form HTML with desired string and then $compile it, or even create a wrapper typeahead component to do this for you in tandem with the dynamic form generation.

**Comment by scfbarbat** [comment] 2015-12-16 17:12
Just for the record, I tried to use dynamic expressions too. Trying workarounds now...

**Comment by fbarbat** [comment] 2015-12-16 17:14
Just for the record, I tried to use dynamic expressions too. Trying workarounds now...

**Comment by dwightdegroff** [comment] 2015-12-17 18:20
While I have been able to work around this issue, it continues to stick in my mind every time I see it. I have not come across other angular-ui bootstrap components that cannot be used in this fashion(see: tooltip, popover as two examples that follow this pattern). Lack of support for this usage also seems to go against Angular Best Practice "let users use expressions whenever possible" (https://github.com/angular/angular.js/wiki/Best-Practices). Is there any chance you would reconsider support?

**Comment by wesleycho** [comment] 2015-12-17 18:35
@dwightdegroff problem here is that this actually adds performance overhead baked into the typeahead component itself if we were to address it there - this has negative repercussions on all users not using the dynamic string, which was undocumented to begin with and never intended to be supported.

**Comment by manusa** [comment] 2016-01-09 12:05
I'm running into this issue too, I've got a form dynamically generated using schema-form with a custom typeahead field.
Can anyone publish any of the workarounds you are mentioning?

**Comment by f0ster** [comment] 2016-01-20 00:14
@manusa if you want to do it with dynamic expressions, you either have to build your own typeahead directive/controller (something like http://www.sitepoint.com/creating-a-typeahead-widget-with-angularjs/ ). Or add a custom link function in your directive to compile the expression from js.  Perhaps something like...
```
   return{
        link: function(scope, element){
            var template = '<input id="{{field.id}}" name="{{field.name}}" ng-pattern="{{field.validation.pattern}}" typeahead="' + field.typeahead + '" />';
";
            var linkFn = $compile(template);
            var content = linkFn(scope);
            element.append(content);
        }
    }
```

**Comment by asilverstein** [comment] 2016-02-15 23:25
Here is a [modified version](https://github.com/asilverstein/bootstrap/blob/master/src/typeahead/typeahead-dynamic-expression-support.js) which supports dynamic angularjs expressions in `uib-typeahead` attribute.

**Comment by robstove** [comment] 2016-02-29 22:44
Since this isn't planned to be supported what are the options for having portions of the clause dynamic:

For example:
```
item as item for item in ctrl.itemsSource | filter: $viewValue | limitTo:{{ctrl.itemLimit || 10}}
```

As others have stated this worked before the controller refactor.

**Comment by Trial-In-Error** [comment] 2016-07-07 17:39
I realize that it's been quite a few months, but I also tried to extend the typeahead component using a dynamic typeahead expression; the project I'm working on now wraps all 3rd party directives we use (from 3 different open source projects and a few homegrown) to provide a consistent API, and the lack of support is unfortunate! I'll give the suggestions here a try, but I'd also like to voice my desire for some variety of support.

I'm completely unfamiliar with the codebase, but it seems that adding an attribute (data-uib-dynamic-typeahead?) could let users who want this functionality to opt into the more expensive linking operations, with the normal use case seeing little-to-no increase in overhead (just the check for the attribute's existence).
