### ISSUE TITLE
Datepicker does not work properly when put inside Dropdown

### ISSUE THREAD

**Issue by dougeff** [angular-ui/bootstrap#4333] opened 2015-09-03 16:53 UTC
Hello:

In my application, I was using the Datepicker within a Dropdown.  This was working fine with ui-bootstrap-tpls-0.13.0.js but when I tried upgrading to the newest version, there seems to be a conflict somewhere and the Datepicker will just close the Dropdown after picking a date, rather than just closing the Datepicker itself.  Also, an error is thrown when I try to open the Dropdown again:

Error: [ngTransclude:orphan] Illegal use of ngTransclude directive in the template! No parent directive that requires a transclusion found. Element: <li ng-transclude="">

I tried versions 13.1 and 13.2 but they close the Dropdown as well.  However, no errors are thrown and I'm able to open the Dropdown again.  Still, I can't use it.

Plunker is here:
http://plnkr.co/edit/0gEyveP9agzPh2UhN7P5

Let me know if you need anything else from me.  

Thanks.

**Comment by wesleycho** [comment] 2015-09-03 19:44
Closing as a duplicate of #4197

**Closed by wesleycho** 2015-09-03 19:44 UTC
