### ISSUE TITLE
Can't inject resolve into another resolve

### ISSUE THREAD

**Issue by Astray-git** [angular-ui/bootstrap#4318] opened 2015-09-01 05:47 UTC
I'm using angular 1.3.15, angular-bootstrap 0.13.3
I try to inject the first resolve into the second one:
``` javascript
$modal.open({
    resolve: {
        companyId: function () {
            return 1;
        },
        categories: [
            'companyId',
             function (companyId) {
                 return  Service.getCategories(
                     companyId
                 );
            }
        ],
    },
    //...
});
```
result in error:
`Error: [$injector:unpr] Unknown provider: companyIdProvider <- companyId`

**Comment by wesleycho** [comment] 2015-09-01 05:56
There is no support for this in UI Bootstrap.

If you want, you could try creating an implementation for this feature - otherwise, it is not likely that this would make it in any time soon.

**Comment by wesleycho** [comment] 2015-09-11 02:24
Closing as a duplicate of #3405

**Closed by wesleycho** 2015-09-11 02:24 UTC
Labels: component: modal, PRs plz!, type: enhancement
