### ISSUE TITLE
Issue with <select> inside modal on mobile Firefox for Android

### ISSUE THREAD

**Issue by charlie** [angular-ui/bootstrap#1960] opened 2014-03-20 14:37 UTC
Issue: On all other browsers I've tested, both mobile and desktop, it appears to work as expected. On Firefox for Android (v23.0 is what I've got on my phone atm), the select menu is non-functional. You can open it, but selecting an option is impossible; the menu closes, but the selection does not change. Maybe I'm simply Doing It Wrong(tm)?

Demonstration: http://c23r.org:8888/

Code: https://github.com/charlie/ui-bootstrap-modal-select-bug

I've connected the remote FF debugger to the Android Firefox app running on my phone; no errors/crashes are apparent.

(The demonstration is a not-quite-completely-pared-down version of the project I'm working on, which was based off ngBoilerplate; probably it would've been better if I removed the dependency on ui-router but ... I didn't.)

**Comment by rvanbaalen** [comment] 2015-05-08 16:12
Please demonstrate this issue in a standalone plunkr and not in your own project.

**Comment by wesleycho** [comment] 2015-08-01 19:18
If I had to suspect, this might be because the select element is not inside a form element - I have encountered weird issues with Firefox in that situation.

Unfortunately I don't have an Android phone handy at the moment to test this on.

**Comment by wesleycho** [comment] 2015-10-15 06:31
Closing as this needs more info in a stripped down example - I highly suspect my observation is the cause, as I have seen Firefox issues in the past when a select element is not inside a form element.

**Closed by wesleycho** 2015-10-15 06:31 UTC
Labels: component: modal, needs: info, needs: investigation
