### ISSUE TITLE
tasks/tasks.html  doesn't work. 

### ISSUE THREAD

**Issue by mkharal** [angular-ui/bootstrap#5682] opened 2016-03-22 20:39 UTC
If I place a file named `tasks.html` inside a directory `tasks`, the path is not reachable and I get the error of 'Missing Template' However, if I rename either directory or file name differently, there is no issue.  

Below is the sample code:

        $uibModal.open({
            templateUrl: 'MyProject/Views/tasks/tasks.html',
            size: 'md',
            controller: 'myTestController',
            },
        });

**Comment by wesleycho** [comment] 2016-03-22 21:00
Closing due to lack of following the issue template & providing a reproduction.

**Closed by wesleycho** 2016-03-22 21:00 UTC
