### ISSUE TITLE
Angular UI Bootstrap Carousel Transition issues with AngularJS v1.4.3

### ISSUE THREAD

**Issue by alokrajiv** [angular-ui/bootstrap#3953] opened 2015-07-16 11:59 UTC
As https://angularjs.org/ tells 1.4.x is the latest stable branch (master on Github), with regular bug fixes and is the default download option, I was using it with Angular UI Bootstrap and noticed issues. 

Sample Code with Angular 1.4.3 showing issues while transition. Infact buttons don't work after one click!
http://jsbin.com/dikeli/edit?html,js,output

Same Code with Angular 1.3.9 working perfectly
http://jsbin.com/hayuqoq/edit?html,js,output

**Comment by RobJacobs** [comment] 2015-07-16 19:41
Closing as duplicate of #3811.  Please do a search for open issues/pull requests before creating new ones.

**Closed by RobJacobs** 2015-07-16 19:41 UTC

**Comment by alokrajiv** [comment] 2015-07-16 19:45
Oops..sorry, don't know how i missed it.
