### ISSUE TITLE
typeahead remains invalid if the user write a full suggestion vaue

### ISSUE THREAD

**Issue by emaish** [angular-ui/bootstrap#3423] opened 2015-03-23 14:31 UTC
typeahead remains invalid if the user write a full suggestion in the input without selecting it from the suggestion. when typeahead-editable="false"

**Comment by wesleycho** [comment] 2015-03-23 19:03
Can you reproduce this in a [Plunker](http://plnkr.co/)?

**Comment by RobJacobs** [comment] 2015-03-23 19:43
Here is a [plunk](http://plnkr.co/edit/SK9ocj5RYSRa4vzDdDm4?p=preview) I used to test required validation.  @emaish Please feel free to update this plunk accordingly to demonstrate your issue.

**Comment by emaish** [comment] 2015-03-23 21:33
Sorry i was away from my laptop, i updated the plunk with property typeahead-editable="false",
when you click "tab" key it's fine and the item selected and the model update, but if you write the whole word Alabama and just clicked away with the mouse the model not updated

**Comment by RobJacobs** [comment] 2015-03-23 22:23
This is because when using the Tab or Enter key, it calls the:

    element.bind('keydown', function (evt)

 and then falls into

    else if (evt.which === 13 || evt.which === 9) {
        scope.$apply(function () {
            scope.select(scope.activeIdx);
          });

Where the dismissClickHandler function calls resetMatches() and closes the popup.  Not sure if this is desired behavior or not.

**Comment by emaish** [comment] 2015-03-23 22:45
It should be configurable at least, because when using typeahead-editable="false" the directive should accept the proper value by all means and revert to blank otherwise, leaving text in the input isn't consistent with the nature of this attribute "imo" this attribute should act as following
1- if value isn't among the suggested then it's invalid so model and input should revert to previous state
2- input bluring should be handled as tab and enter keys, because some users is used to work with mouse and they may want to move to next functionality by clicking away

**Comment by wesleycho** [comment] 2015-03-23 23:34
Looking at this, I think I agree.  Marked as a bug.

**Comment by emaish** [comment] 2015-03-24 12:57
i think [#3365](https://github.com/angular-ui/bootstrap/pull/3365) is related

**Comment by wesleycho** [comment] 2015-03-24 13:26
That issue is a little different.

**Comment by emaish** [comment] 2015-03-24 13:52
>While using the typeahead directive, we desired that it automatically select an item when the user
>input exactly matches the option in the dropdown

That part is same in our issue here

**Comment by emaish** [comment] 2015-04-05 20:02
[feat(typeahead): implement 'select on blur' option. #3445](https://github.com/angular-ui/bootstrap/pull/3445)

**Comment by wesleycho** [comment] 2015-08-06 07:07
Seeing as #3445 is merged, I believe this should no longer be an issue.

**Closed by wesleycho** 2015-08-06 07:07 UTC
Labels: component: typeahead, type: bug
