### ISSUE TITLE
tabset state and navigating to tabs programmatically 

### ISSUE THREAD

**Issue by imiten** [angular-ui/bootstrap#6009] opened 2016-06-15 04:26 UTC
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
uib-tabset, uib-tab are not switching programmatically or using back button does not keep state of active tab

steps:
open link it show tabs.
choose second tab - backup list - shows some dummy data
click first item edit button.
open update page for item.
click back button or browser back.  desired outcome: go back to backup list tab.  current outcome: shows first tab instead.

### Link to minimally-working plunker that reproduces the issue:
https://plnkr.co/edit/Bw3gQG9QZubW89U7gvfO?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular:1.5.6

UIBS:1.3.3

Bootstrap:3.3.6

**Comment by icfantv** [comment] 2016-06-15 04:38
@imiten, per my comment in your previously entered issue, #6001, the issues forum is not for support requests.

supporting browser history navigation combined with tab navigation is not something we support or will support in the library.

if you want this feature yourself, you need to sort of do what you are doing in your plunker in that you must pass either a query or route parameter on the URL and use that value in your controller to set the active tab.  this is going to be the only way to get the browser forward and back buttons working for tab navigation.

to programmatically set the active tab, you use the `active` property on the `uib-tabset` directive.  i don't know if we've fixed it yet, but we used to only allow integers as `uib-tab`'s `index` property - there was a bug to also allow strings.  regardless, the index values _must be unique_.

as before, I'm going to close this as a support issue and not a bug/feature request in the library.

**Closed by icfantv** 2016-06-15 04:38 UTC

**Comment by imiten** [comment] 2016-06-15 05:50
I have tried in my plunk what you said like url param and integer index and uib-tabset active property as its shown in bootstrap site plunk.  since it was not working and after I checked with irc also I report here both for support and bug.
