### ISSUE TITLE
Accordion very slow and laggy when  expanded in IE11

### ISSUE THREAD

**Issue by DaneEdwards** [angular-ui/bootstrap#3829] opened 2015-06-17 08:01 UTC
Hi, i have an accordion, when scrolling pass the expanded accordion its very laggy. this isn't an issue in chrome
i'm using 0.13.0

<accordion close-others="false" ng-hide="hideContainer">
      <accordion-group ng-repeat="group in groups" is-open="group.open"> 
        <accordion-heading  >
        <div class="lms-task-heading" ng-click="expandGroup()"  tooltip="Expand/Collapse Task Group">{{group.taskGroup}} ({{group.tasks.length}})</div>
        </accordion-heading>
        <table class="table table-bordered">
          <tbody>
            <tr>
              <td>
                <div class="row lms-task-bold">
                  <div class="col-xs-2">Current Activity</div>
                  <div class="col-xs-2 ">Task Name</div>
                  <div class="col-xs-2 ">Description</div>
                  <div class="col-xs-1">Assigned To</div>
                  <div class="col-xs-1">Status</div>
                   <div class="col-xs-1">Actioned</div>
                  <div class="col-xs-2">Comments</div>
                  <div class="col-xs-1 pull-right">Actions</div>
                </div>
              </td>
            </tr>
           
            <tr data-ng-repeat="t in group.tasks | orderBy:sortorder">
              
              <td>
                <div class="row">
                  <div class="col-xs-2">
                    <b>{{ t.Current_x0020_Activity }}</b>
                  </div>
                  <div class="col-xs-2"><a  ng-click="ShowViewTaskDialog(t.ID)">{{ t.Title }}</a></div>
                   <div class="col-xs-2"  contenteditable="false" data-ng-bind-html="t.Body"></div>

                  <div class="col-xs-1">{{ t.AssignedTo.Title }}</div>
  
                  <div class="col-xs-1" ng-class="{'label label-default': t.Status == 'N/A','label label-success': t.Status=='Complete'}">{{ t.Status }}</div>
                   <div class="col-xs-1" >{{ t.Actioned}}</div>
                  <div class="col-xs-2"><div id="comment{{t.ID}}Tasks" ng-init="ngBuildComments(t.ID)"></div></div>
                  
                    <div class="col-xs-1 pull-right">
       
                      <ul>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<div class="menu-item-icon ms-ellipsis-a">
									<img class="ms-ellipsis-icon" src="/_layouts/15/images/spcommon.png?rev=23" alt="Open Menu"></div>
								<div class="menu-item-text"></div>
							</a>
							<ul class="dropdown-menu pull-right">
								<li>
		                          <a ng-click="t.Status='Not Started'; saveChanges(t)">Not Strarted</a>
		                        </li>
		                        <li>
		                          <a ng-click="t.Status='In Progress'; saveChanges(t)">In Progress</a>
		                        </li>
		                        <li>
		                          <a ng-click="saveChanges(t);t.Status='Complete'">Complete</a>
		                        </li>
		                        <li>
		                          
		                          <a ng-click="t.Status='N/A';saveChanges(t)">Mark as N/A</a>
		                        </li>
		                        <li>
		                          <a ng-click="open('md', t)">Assign</a> 
		                        </li>
		                        <li>
									<a ng-click="ShowEditTaskDialog(t.ID)">Edit</a>
								</li>
		                       	<li>
									<a ng-click="ngShowModalcommentsNew(t.ID)">Comment</a>
								</li>
							</ul>
						</li>
					</ul>
                    
                  </div>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </accordion-group>
    </accordion>

Regards, 
Dane

**Comment by rvanbaalen** [comment] 2015-06-19 02:25
Please clean up this messy issue text. And provide a plunkr.

**Comment by wesleycho** [comment] 2015-09-11 02:36
Closing due to lack of reproduction.

**Closed by wesleycho** 2015-09-11 02:36 UTC
Labels: browser: IE11, component: accordion, needs: plunkr, needs: work

**Comment by Soyofuki** [comment] 2016-10-25 00:51
I also meet this problem.
A list of 600 items rendered in 10 seconds in Chrome but 60 seconds in IE 11.
This issue should not be closed.
