### ISSUE TITLE
Validation of datepicker popup input not recognizing ISO as valid input

### ISSUE THREAD

**Issue by immertreu** [angular-ui/bootstrap#4324] opened 2015-09-01 21:14 UTC
I have a date field that can be modified by the datepicker popup or by another date range selector. This date range selector will provide dates as ISO strings. As of angular bootstrap 0.13.3 the date validator will find these dates invalid. 

For example if I have the following in my html:
```
<input type="text" ng-model="start_time" datepicker-popup="{{format}}" datepicker-options="dateOptions" name="startTime"/>

```
And I initialize $scope.start_time to '2015-08-01T00:00:00-05:00'. This will set startTme.$invalid to true

**Comment by wesleycho** [comment] 2015-09-01 22:21
This was an intentional breaking change, because supporting turning these strings into date objects was the cause of many bugs - see all of the issues closed as a result of this commit https://github.com/angular-ui/bootstrap/commit/ab4580fd .

**Comment by wesleycho** [comment] 2015-09-01 22:22
Your best workaround is to convert the ISO string into a date object.

**Closed by wesleycho** 2015-09-01 22:21 UTC

**Comment by pdorgambide** [comment] 2015-09-04 16:21
I just have the same problem on update to 0.13.3.
I think that the exposed workaround is hard to implement since it require change String to Date and from the server always  received Strings (JSON). 
It will be more accurate if the directive will validate the model before mark invalid the field taking in consideration all cases: model is a date object; model is a string as ISO 8601 from server; model is the  user string with date format 'dd/MM/yyyy', ..

**Comment by wesleycho** [comment] 2015-09-04 16:34
The string fallback caused lots of issues though - for example, strings turns out to have different validity depending on what formats the Date constructor supports in different browsers. There is no reliable way to unify the behavior, or make it make sense consistently in any fashion.

It also caused bugs with the validation itself.

The workaround is to have an intermediary layer convert the string to the date object manually before setting - this is a best practice in general.

**Comment by lodnert** [comment] 2015-09-14 09:50
I would appreciate if you we could find a better solution for this than the workaround. Could we maybe bring the fallback back with as a option?

**Comment by wesleycho** [comment] 2015-09-14 15:05
Bringing it back would cause cross-browser bugs to reappear, as well as a validation bug, and this was the only valid fix - these bugs needed to be fixed in the library itself.

Bringing it back is not an option unless it is implemented with all necessary fixes to handle all cases.

**Comment by tech-no-logical** [comment] 2015-09-15 13:41
does that mean that this :

    $log.error('Datepicker directive: "ng-model" value must be a Date object, a number of milliseconds since 01.01.1970 or a string representing an RFC2822 or ISO 8601 date.');

is now no longer true ? (it's still in the code as of 0.13.4) because '2015-08-08' is valid in ISO 8601, but it's no longer accepted : the input is marked with ng-invalid-date

**Comment by mgibas** [comment] 2015-09-16 01:16
Silly that its not implemented here (cuz datepicker its about dates right ? :wink:  ) but i think that cleanest workaround is to wrap it with our own directive like this:

```javascript
angular.module('app')
	.directive('myDatepicker', function () {
	    var directive = {
	        templateUrl: 'datepicker.directive.html',
	        controller: 'myDatepickerController',
	        bindToController: true,
	        controllerAs: 'vm',
	        scope: {
	            value: '=',
	            label: '@',
	            required: '=',
	            name: '@value'
	        }
	    };
	    return directive;
	});

angular.module('app')
	.controller('myDatepickerController', function ($scope) {
	    var vm = this;

	    $scope.$watch('vm.value', function (newValue) {
	        if (typeof newValue === "string")
	            vm.value = new Date(newValue);
	    });
	});
```
```html
<input datepicker-popup aa-label="{{vm.label}}"
       name="{{vm.name}}"
       aa-field-group="vm.value"
       is-open="vm.isOpen"
       ng-click="vm.isOpen=!vm.isOpen"
       type="text"
       ng-change="vm.onChangeCallback(value)"
       ng-required="vm.required"/>
```
usage
```html
 <my-datepicker label="My Label" value="vm.model.issueDate" ng-required="true" />
```

Unfortunately I don't see any other option than using $watch which makes whole job for me:
```javascript
  $scope.$watch('vm.value', function (newValue) {
	        if (typeof newValue === "string")
	            vm.value = new Date(newValue);
	    });
```

**Comment by tech-no-logical** [comment] 2015-09-16 09:54
@mgibas I tried something similar yesterday, but couldn't get it to work (well, not elegantly).
so now I've resorted to converting the date on save and load, also ugly, but it works. annoyingly, because the datepicker uses UTC, when I select 16-09-2015 I get 

    2015-09-15T22:00:00.000Z

because I'm two hours ahead of UTC. so discarding the time, I get a date that's a day early. so to correct for that I now use : 

    d = new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().substr(0,10);

to get an ISO date.

you're right though, it would be nice if the picker discarded the time(zone) info internally, it's not a datetimepicker

**Comment by bob-lee** [comment] 2015-09-28 01:49
As a workaround suggested by wesleycho, I could avoid this issue by doing below at page load
```
if (my.viewModel.date1) { my.viewModel.date1 = Date.parse(my.viewModel.date1); }
```
Not sure this would change in future release after 0.13.3
