### ISSUE TITLE
Modal does not load in Bootstrap

### ISSUE THREAD

**Issue by I-am-viSHnu** [angular-ui/bootstrap#4822] opened 2015-11-05 10:53 UTC
I am having two tab in html . The body of both are identical I have created a modal in the body . The issue I am getting is when I click the button to load the modal in first tab modal get loaded but if I go to second tab and click the button to load the modal only fade function work the content does not load Below is the code Help needed urgently 
<button  type="button"
    class="btn btn-info glyphicon glyphicon-plus"
    data-toggle="modal"
    data-target="#myModal{{$parent.$parent.$index}}{{$index}}">
        Add URL
</button>

{{category.name}}{{$parent.$parent.$index}}{{$index}}

<div class="modal fade" id="myModal{{$parent.$parent.$index}}{{$index}}" role="dialog">
     {{$parent.$parent.$index}} -- {{$index}}
     <div class="modal-dialog" role="document">
          
          <div class="modal-content" >{{category.name}}
              <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>
              <div class="modal-body">
                  <form>
                      <p>
                          <input type="text" class="form-control"
                           name="uri" placeholder="Add URL" ng-model="uri">
                      </p>
                   </form>
               </div>
               <div class="modal-footer">
                   <button type="button" ng-click="addCustom()"
                           class="btn btn-success btn-sm col-lg-2 col-md-offset-3 glyphicon glyphicon-ok"
                           data-dismiss="modal">Add</button>
                   <button type="button"
                           class="btn btn-success btn-sm col-lg-2 col-md-offset-7 pull-centre glyphicon glyphicon-remove"
                           data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
   </div>
</div>

**Comment by pkozlowski-opensource** [comment] 2015-11-05 11:06
@I-am-viSHnu it doesn't appear as you are using modal from this library. If you believe that you do and you bumping into a bug, please provide detailed info to reproduce, as requested here: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

More specifically, you need to have a reduced, live reproduce scenario with plunker or similar. Otherwise this is not actionable.

**Comment by I-am-viSHnu** [comment] 2015-11-05 14:40
@pkozlowski-opensource 	
when I used chrome debugger I found in the first tab <div class="modal fade ng-binding in" id="myModal00" role="dialog" style="display: block; padding-right: 17px;"> is comming while in second tab <div class="modal fade ng-binding " id="myModal00" role="dialog" > is comming

**Comment by pkozlowski-opensource** [comment] 2015-11-05 14:54
@I-am-viSHnu once again, if you believe that there is a bug in this library provide all the context / reproduction scenario as requested here: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

**Comment by wesleycho** [comment] 2015-11-07 08:00
Closing due to lack of actionable information & likely not a bug.

**Closed by wesleycho** 2015-11-07 08:00 UTC
