### ISSUE TITLE
Datepicker choose day and timezone offset 

### ISSUE THREAD

**Issue by isimonov** [angular-ui/bootstrap#4113] opened 2015-08-05 10:55 UTC
If Datepicker field empty and we choose a date, then creates a new date object with the given timezone offset (depends on locale), i.e. if I choose an empty field 2015-01-02, it turns out the date 2015-01-01 21:00:00 (if the timezone offset is +3 hours), i.e. yesterday, unless you consider time. This is not quite correct when sent to the server, if there is not taken into account the timezone offset or it works with UTC. Maybe there could be something to do?

**Comment by isimonov** [comment] 2015-08-06 05:28
If a server is using UTC (timezone offset is 0 hours), and the browser's local timezone (timezone offset is +3 hours) may occur such a situation: all dates are returned from the server is correct, for example 2015-01-02 00:00:00, and if the date entered for the first time the datepicker will create you same date as 2015-01-01 21:00:00 When I pass this 2 dstes on server, this is will be different dates from his point of view. It is very inconvenient to use, but it's a feature of Javascript works with dates in the browser.

**Comment by nipec** [comment] 2015-08-06 16:47
+1
I have the same problem in my project. It's a really nasty bug.

**Comment by isimonov** [comment] 2015-08-06 17:07
Possible solution to this problem https://github.com/isimonov/note/commit/9190c253a7e354c22afbfa4a58386677ba522e0d It seems to me that this should be made optional. For most cases this could be the solution, but there may be exceptions.

**Comment by nipec** [comment] 2015-08-07 05:53
Hi Ivan,

thank you, I think this could be the right approach. One line below I had to add:
dt.setUTCFullYear( date.getFullYear(), date.getMonth(), date.getDate() );

Now it works for me, but I do not know, if there could be any side effects.

Cheers,
Nikola

**Comment by nipec** [comment] 2015-08-11 06:28
Hi Ivan,

is this reproducing your error?

http://plnkr.co/edit/RkByqVhCrcSCXWGXGkWo

Cheers,
Nikola

**Comment by isimonov** [comment] 2015-08-11 07:07
Hi, Nikola! A little different, see below, I will try to explain in pictures
http://plnkr.co/edit/gMyC6ZEPaL0HGak0ksFO
![000](https://cloud.githubusercontent.com/assets/2580203/9192100/6f130852-4010-11e5-861e-9a36a53498b8.png)

**Comment by wesleycho** [comment] 2015-08-12 12:00
This is actually a duplicate of a few open issues.

**Comment by wesleycho** [comment] 2015-11-07 17:36
Closing this in favor of #4113 - the ngModelOptions directive provides a hook where we can wire in specification of custom timezones

**Closed by wesleycho** 2015-11-07 17:36 UTC
Labels: component: datepicker, type: enhancement

**Comment by cmlenz** [comment] 2015-11-17 13:06
@wesleycho So this issue is closed in favor of, ehem, this issue? And #2952 is also closed in favor of this issue.

**Comment by ired** [comment] 2015-11-17 13:20
@cmlenz +1

**Comment by icfantv** [comment] 2015-11-17 15:44
@cmlenz, this is how we maintain some sense of control and understanding of outstanding issues and feature requests - by consolidating.  Otherwise, it's so easy to lose track of what needs to be done to what component.  Take a look at #4762 and #4772 and see how many issues were closed by consolidating everything (41).  I seriously doubt anyone would say managing 41 separate issues and PRs is better than managing two.  The onus is on us to ensure that the consolidated issue captures everything from those closed issues.  We're totally open to suggestions if you have a better way.  Thanks.

@ired, please do not add just `+1` to issues.  It does nothing to add to the discussion and just clutters up the thread.  Thanks.

**Comment by icfantv** [comment] 2015-11-17 15:46
@cmlenz, I should add that less than 6 weeks ago, we had over 230 open, outstanding issues and @wesleycho has worked insanely hard in fixing and closing items in preparation for the 1.0 release.  We are currently at 86.

**Comment by cmlenz** [comment] 2015-11-17 15:48
@icfantv I was in no way complaining about issues being consolidated in general, the problem is that this issue was closely in favor of no other open issue AFAICT, but in favor of itself.

**Comment by icfantv** [comment] 2015-11-17 15:58
Ah, understood.  Thanks for the clarification.  I see now.  I've updated the issue number so that it's correct.

**Comment by wesleycho** [comment] 2015-11-17 16:00
That was my fault - I linked the wrong issue. #4837 is what was meant to be linked.

**Comment by cmlenz** [comment] 2015-11-17 16:01
Thanks @wesleycho and @icfantv
