### ISSUE TITLE
Datepicker datepickerMode and minMode not watched

### ISSUE THREAD

**Issue by yesman85** [angular-ui/bootstrap#6276] opened 2016-10-06 19:23 UTC
In the documentation under the Datepicker it shows a watch icon for datepickerMode and minMode, but they don't actually watch, you need to manually trigger some sort of update before it's updated.

In the code it looks like minMode is watched, but not on the options object.

**Comment by Jiia** [comment] 2016-10-07 06:56
Same problem with the latest ui-bootstrap and angular 1.5.8 here. Mode and minMode can't be changed on the fly regardless of whether you're using an options object or passing them in as attributes.

I'm gonna try implementing this as a work around: https://gist.github.com/cgmartin/3daa01f910601ced9cd3#file-datepicker-decorator-js-L10

**Comment by wesleycho** [comment] 2016-10-13 13:27
Closing due to lack of reproduction.

**Closed by wesleycho** 2016-10-13 13:27 UTC

**Comment by yesman85** [comment] 2016-10-13 13:58
Honestly that's a bit lazy. Your docs are wrong and you could have seen that too, you want me to put a screenshot of the docs where it says it's watched but it's actually not?

**Comment by wesleycho** [comment] 2016-10-13 14:01
What is lazier is not providing a reproduction in this case - I have in the past created a reproduction that worked, and there are unit tests around it as well. A reproduction is the minimum bar, as per [contributing.md](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug) which is present on every new issue file attempt on GitHub, as well as the expected place to first read before filing any issue on any GitHub repository if the file is present.

**Comment by yesman85** [comment] 2016-10-13 14:05
Ok I will reproduce it as soon as the CDN gets it back together.

**Comment by thSteve** [comment] 2017-06-15 20:35
Still facing this issue

https://plnkr.co/edit/EUKuxsAorFoyRslT0mn9?p=preview
