### ISSUE TITLE
Problems with Typeahead

### ISSUE THREAD

**Issue by kumarharsh** [angular-ui/bootstrap#4034] opened 2015-07-29 07:13 UTC
I'm using the ui.bootstrap.typeahead plugin in my site, and it's working OK on the face of it... But when I open console, it keeps spitting out these errors:

```
Error: args is null
$parseFunctionCall@http://localhost:8000/apps/main.js:26255:1
$parseFieldAccess@http://localhost:8000/apps/main.js:26188:24
OPERATORS<["+"]@http://localhost:8000/apps/main.js:25632:10
$parseBinaryFn@http://localhost:8000/apps/main.js:25981:15
$parseObjectLiteral@http://localhost:8000/apps/main.js:26318:1
regularInterceptedExpression@http://localhost:8000/apps/main.js:26760:22
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:8000/apps/main.js:28150:35
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:8000/apps/main.js:28421:14
NgModelController</this.$$debounceViewValueCommit@http://localhost:8000/apps/main.js:37241:8
NgModelController</this.$setViewValue@http://localhost:8000/apps/main.js:37213:8
baseInputType/listener@http://localhost:8000/apps/main.js:33634:8
jQuery.event.dispatch@http://localhost:8000/apps/main.js:9066:16
jQuery.event.add/elemData.handle@http://localhost:8000/apps/main.js:8753:7
```

I've tried more or less everything, but the error persists... Funny enough, trying to reproduce it on plunkr is somehow not triggering the same error.

Does anyone have pointers as to what is going on here? Maybe I'm missing something, or doing something wrong? Or is it really a ui.bootstrap bug?

**Comment by pkozlowski-opensource** [comment] 2015-07-29 07:39
Sorry, we will need a minimal reproduce scenario to be able to help you: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

**Comment by kumarharsh** [comment] 2015-07-29 07:56
Some helpful info (until I can reproduce it)

Angular version: `1.3.15`
Library Version: `0.13.0 - 2015-05-02`

**Comment by pkozlowski-opensource** [comment] 2015-08-15 11:25
Closing due to the lack of reproduction scenario. Happy to re-open when we've got one.

**Closed by pkozlowski-opensource** 2015-08-15 11:25 UTC
Labels: component: typeahead, needs: plunkr
