### ISSUE TITLE
tooltip-html not placing arrows in correct positions.

### ISSUE THREAD

**Issue by farfromguam** [angular-ui/bootstrap#5653] opened 2016-03-18 20:42 UTC
### Bug description:
tooltip-html not placing arrows in correct positions. using uib-tooltip vs uib-tooltip-html produces visually different tooltips

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/KSw5lE?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.1

UIBS: 1.2.4

Bootstrap: 3.3.6

**Comment by icfantv** [comment] 2016-03-18 21:03
I'm about 98% sure this is a duplicate of #5610 and is fixed in `master`.  @farfromguam, please, do a build by pulling the repo, using the appropriate `-tpls.js` file in the `dist` folder, updating your plunker to use this file (you can create a new JS file and just paste the contents), change the reference in `<head>` and retest.

This should take you about 3 minutes.  Thanks.

**Comment by wesleycho** [comment] 2016-03-19 15:06
This looks like a bug.

An aside, please don't abuse `div` as buttons - use the more semantically correct `button` tag.

**Comment by RobJacobs** [comment] 2016-03-20 12:57
The angular-ui-bootstrap js referenced in the original plunk is incomplete, updated [plunk](http://plnkr.co/edit/vsAXvY?p=preview) demonstrates behavior works as expected.

**Closed by RobJacobs** 2016-03-20 12:57 UTC
Labels: component: $position, component: tooltip, severity: broken expected use, type: bug

**Comment by icfantv** [comment] 2016-03-20 15:39
Thanks @RobJacobs.
