### ISSUE TITLE
modal template code not deleted from body after close or dismiss.

### ISSUE THREAD

**Issue by gunaskr** [angular-ui/bootstrap#3877] opened 2015-06-30 10:32 UTC
I'm able to open the modal window and when i click on ok or cancel the modal window disappears and i can get the values in the modal window back into my main controller. However the modal window html code which is responsible for the modal window is not deleted after clicking on ok or dismiss. Hence, I'm unable to access the parent page even after the modal window is disappeared.

I was not able to recreate the issue when i tried in simple environment. I've included lots of css files and thirdparty angular directives and such. I suspect it could be because of some conflicting dependencies. Please let me know if this is because of some conflicting javascript or css files if any.

**Comment by romain10009** [comment] 2015-06-30 14:27
Hello gunaskr. I ran in the same issue : my modal is closed, and yet the angular-rangeslider plugin present on the modal modifies my objects further. It's not verry clear. Here is my list of dependencies, what is yours? maybe we can find common points.

    "jquery": "~2.1.1",
    "angular": "~1.4.1",
    "bootstrap": "~3.3.0",
    "angular-route": "~1.4.1",
    "angular-sanitize": "~1.4.0",
    "angular-bootstrap": "~0.13.0",
    "lodash": "3.x.x",
    "ngDraggable": "ngdraggable-custom.git#~2.0.1",
    "angular-rangeslider": "~0.0.14"

**Comment by rvanbaalen** [comment] 2015-06-30 16:11
As @romain10009 mentioned, this is a duplicate of #3873

**Closed by rvanbaalen** 2015-06-30 16:11 UTC
