### ISSUE TITLE
Version 0.13 - modal does not close correctly

### ISSUE THREAD

**Issue by djvs** [angular-ui/bootstrap#3873] opened 2015-06-30 00:29 UTC
Backdrop still remains and modal itself is still there, just with opacity of 0.  Don't think this is a duplicate of https://github.com/angular-ui/bootstrap/issues/3633 .    Does not occur with 0.12.

**Comment by djvs** [comment] 2015-06-30 00:34
Disabling animation on a modal eliminates the bug.

**Comment by wesleycho** [comment] 2015-06-30 06:46
Can you create a reproduction with [Plunker](http://plnkr.co/)?

**Comment by esion** [comment] 2015-06-30 10:00
I got this issue too after migrate to angular 1.4

unfortunatly I can't reproduce on plkr : http://plnkr.co/edit/xofiwx?p=preview  
I need to investigate a bit more

**Comment by esion** [comment] 2015-06-30 12:37
sorry I didn't read others issues, I suppose this is more complicated than just an angular upgrade

**Comment by esion** [comment] 2015-06-30 14:56
> TL;DR: In order to fix : set animate: false or remove angular-animate from dependencies

Since there is no version specified in this issue, I use angular 1.4.

This is what I found : 

I've updated http://plnkr.co/edit/xofiwx?p=preview to make backdrop not removed
it only requires to add angular-animate

in ui-bootstrap we use the event `$animate:close` which is never fired so the backdrop is never removed from dom : https://github.com/angular-ui/bootstrap/blob/master/src/modal/modal.js#L238

the actual doc for `angular.element(selector').one()` says it doesn't support namespaces I m not sure if it is related.

Hope this help to fix.

**Comment by djvs** [comment] 2015-06-30 15:17
Yes, thank you esion, wish I caught this 20 minutes ago.  Made a sad plunker which doesn't duplicate it, http://plnkr.co/edit/NCmCk722weDma3Mj2b9m?p=preview.

**Comment by djvs** [comment] 2015-06-30 15:21
However removing ng-animate doesn't seem to resolve it for me, while it does on your plunker...

**Comment by djvs** [comment] 2015-06-30 15:26
Ah got it - ngMaterial will *also* conflict and produce this issue.

**Comment by djvs** [comment] 2015-06-30 15:29
AND this...https://github.com/homerjam/angular-ui-router-anim-in-out

**Comment by esion** [comment] 2015-07-01 09:42
I see ui-router-anim requires ngAnimate. 
But no idea for ngMaterial

**Comment by esion** [comment] 2015-07-01 10:14
So I think this the same discussion as in #3633 so this one should be closed

**Comment by djvs** [comment] 2015-07-01 14:41
If you look at Daniel's plunker, the behavior is different.

**Comment by esion** [comment] 2015-07-01 15:37
He said it has been resolved by adding ngAnimate
https://github.com/angular-ui/bootstrap/issues/3633#issuecomment-106861328

Without it,  ui-bootstrap has no idea when remove modal from DOM. So it removes it asap on 1.3. It's just a "bug" in documentation not in code.

In case of angular 1.4, BC breaks have been added arround ngAnimate, so the event used to remove backdrop and modal window from DOM is not triggered anymore see L.238 as I mentionned, this has been discussed here : https://github.com/angular-ui/bootstrap/issues/3633#issuecomment-113516753

(Obviously there is lot of mess in the issue :p and two "bugs")

**Comment by chrisirhc** [comment] 2015-07-04 23:46
Should be fixed now via #3895

Working Plunker: http://plnkr.co/edit/R8322USvwVICHy8wjM7Y?p=preview

**Closed** 2015-07-05 00:46 UTC
Labels: component: modal, needs: plunkr

**Comment by esion** [comment] 2015-07-05 06:59
Thank you @chrisirhc, I found some bugs, i'll talk about it in PR
