### ISSUE TITLE
Datepicker  - Validation issue

### ISSUE THREAD

**Issue by KarlXOL** [angular-ui/bootstrap#6190] opened 2016-08-21 14:44 UTC
Still an issue in 2.2.0
### Bug description:
I get a date value as string from a remote server (database).
Therefore I use a directive with to convert the string to a dateobject and set it with $setViewValue.
This works fine until bootstrap version 1.3.3

Since version 2.0.0 the input field validation fails for a field which has been set this way ($invalid is true). 

This totally breaks UI-Logic as the user opens a records and the form is showing that previously entered fields are all invalid

### Link to minimally-working plunker that reproduces the issue:
https://plnkr.co/edit/pKCUSTsf6mfn2OEnMb4A

### Version of Angular, UIBS, and Bootstrap
Angular: 1.5.5
UIBS: 2.1.1
Bootstrap: 3.3.6

**Comment by wesleycho** [comment] 2016-08-21 19:37
That is an empty Plunker - [this](https://plnkr.co/edit/TLYdSu342fvFrDZQnUhh?p=preview) should help you get started for a reproduction of the issue.

**Comment by KarlXOL** [comment] 2016-08-21 19:44
Please try plunker again. You should be able to see it now. 
Thanks

**Comment by antch** [comment] 2016-08-22 16:28
@KarlXOL That Plunker is far from minimal. I suspect it's going to be difficult to pin-point the issue with all of that other stuff going on.

**Comment by KarlXOL** [comment] 2016-08-25 14:14
Ok, I could clean up the plunker a bit. But there isn't so much overhead in  the plunker as I need some code to reproduce my use case  from getting a date as string and converting this datestring to a date to make it useable for the datepicker.
From my recherche, this is a general issue/use case people have when using bootstrap directives. Therefor I hope this makes it worth investigating this issue
Thanks

**Comment by KarlXOL** [comment] 2016-08-30 10:12
Found an old thread on stackoverflow describing the same behaviour
[](http://stackoverflow.com/questions/33626232/parse-date-string-to-date-object-when-loading-angular-ui-bootstrap-datepicker)

At least this was working in 1.3.3

**Comment by wesleycho** [comment] 2016-10-13 13:22
Looking at the custom directive, you should not run `ngModel.$setViewValue` inside a formatter - this breaks the expectations of Angular's $formatter/$parser design.

In addition, for your use case, you probably should also be checking if the input is dirty for display of the message.

**Comment by KarlXOL** [comment] 2016-10-13 13:33
Thanks for feedback. 
Indeed, using "ngModel.$setViewValue" isn't the preferred way, but it is the only workaround for the problem that "Datepicker" is not able to deal with string input. This is also discussed in stackoverflow (find above one thread). And this workaround has worked fine < version 2.0.0 (Angular version has remained unchange)
As this is a real world requirement when working with e.g. databases, ... I'd suggest to make "Datepicker" string compatible. I would also appreciate another solution, if there is ???

**Comment by wesleycho** [comment] 2016-10-13 13:36
Supporting strings with how the datepicker is designed currently creates timezone issues - these issues are absent in the successor, ng-bootstrap, due to avoiding using date models under the hood.

I would recommend converting from string models to date objects in your app where you receive the data. It is a minor step, as much less prone to any issues such as having to hack around the library - it is the more architecture sound path.

**Comment by KarlXOL** [comment] 2016-10-13 13:47
When working with REST-APIs with JSON I have to use what I get from the remote system. And date information will always be returned as strings. 
The conversion from string to date is what I do in my directive which generates some kind of conflict??
Again, what I'm doing is the angular way for doing this. 

Creating another directive for encapsulation of the "Datepicker" make things more complex , but maybe that's the way for workaround this.

**Comment by wesleycho** [comment] 2016-10-13 13:50
I'm not saying create a directive - I'm saying create a helper function in a service and all areas that are fetching the data, do the conversion before returning the data to be bound to the client.

**Comment by KarlXOL** [comment] 2016-10-13 13:53
Ok, and the right place for calling this service would be in the formatter, for being conform to angular.
Wouldn't make a difference then.

I'd be happy if behaviour of current "Datepicker" version would be the same as it had been before 2.0.0

**Comment by wesleycho** [comment] 2016-10-13 13:57
I said nothing about using it in the formatter - this is not where you want to use it. You want to use it at the point of data query.

Closing this as a support issue, as there is definitely an adequate workaround, and it is being avoided in favor of an approach that is a no-go for supporting.

**Closed by wesleycho** 2016-10-13 13:57 UTC
Labels: component: datepicker-popup, resolution: support, severity: broken expected use
