### ISSUE TITLE
Tooltip exception: Unable to get property 'prop' of undefined or null reference.

### ISSUE THREAD

**Issue by VitalyVoroshilov** [angular-ui/bootstrap#2785] opened 2014-10-06 08:54 UTC
If the second tooltip issued to show at the time of the first tooltip show an error will occur.

Error:
name: TypeError
message: Unable to get property 'prop' of undefined or null reference
stack:
TypeError: Unable to get property 'prop' of undefined or null reference
   at positionElements (http://localhost:61722/Components/bower_components/angular-bootstrap/ui-bootstrap-tpls.js:920:9)
   at positionTooltip (http://localhost:61722/Components/bower_components/angular-bootstrap/ui-bootstrap-tpls.js:2490:15)
   at Anonymous function (http://localhost:61722/Components/bower_components/angular-bootstrap/ui-bootstrap-tpls.js:2525:51)
   at wrappedCallback (http://localhost:61722/Components/bower_components/angular/angular.js:11319:15)
   at Anonymous function (http://localhost:61722/Components/bower_components/angular/angular.js:11405:11)
   at $eval (http://localhost:61722/Components/bower_components/angular/angular.js:12412:9)
   at $digest (http://localhost:61722/Components/bower_components/angular/angular.js:12224:15)
   at $apply (http://localhost:61722/Components/bower_components/angular/angular.js:12516:13)
   at hideTooltipBind (http://localhost:61722/Components/bower_components/angular-bootstrap/ui-bootstrap-tpls.js:2536:15)
   at handle (http://localhost:61722/Components/bower_components/jquery/jquery.js:4993:5)

**Comment by tomauty** [comment] 2015-05-15 18:43
Pretty sure this is IE10 only

**Comment by charwking** [comment] 2015-05-19 21:16
I've been able to reproduce this in Chrome and Firefox. After some digging, I'm fairly sure [this change](https://github.com/angular-ui/bootstrap/commit/853fa4578a1f127fee9283e725d6e19789882121#diff-e8665eb306ddd26399e5b80f00dae5bbR125), available in `v0.13.0` has resolved the issue.

**Comment by wesleycho** [comment] 2015-06-10 13:14
I cannot reproduce this, as shown in this [Plunker](http://plnkr.co/edit/uZwqj7YtOFnHxm90n7Vw?p=preview) based off of current master.

Closing as resolved - if this is still an issue, feel free to comment here or create a new ticket.

**Closed by wesleycho** 2015-06-10 13:14 UTC
Labels: component: tooltip, needs: investigation, type: bug

**Comment by tsclaus** [comment] 2015-11-02 22:41
I am still getting a similar error with the newest version (0.14.3)

Stacktrace:

    Uncaught TypeError: Cannot set property 'isOpen' of null
        hide @ ui-bootstrap-tpls.js:3496
        TooltipBind @ ui-bootstrap-tpls.js:3454

Given the local variable name for null is ttScope and the tooltip directive creates its own scope with that property, I am fairly certain this error is caused by an asynchronous piece of tooltip code trying to access a scope that angular has already destroyed (which is somewhat hard to reproduce).

**Comment by icfantv** [comment] 2015-11-02 22:47
@tsclaus, please also try against a build from `master` so we can try to narrow this down to either a user issue or possibly a release-specific issue.  If it still happens in your code, please open a new issue following [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).  New comments on closed (and really old) issues is a good way for them to get lost.  Thanks.

**Comment by josephhelmrich** [comment] 2017-01-04 20:11
This still occurrs in v2.1.3.  The problem is that the if (!tooltip) check is outside of the $timeout() code.  It needs to be moved into the $timeout code to ensure this error doesn't occur
