### ISSUE TITLE
M!/d!/yyyy does not Validate in the Dateparser Example

### ISSUE THREAD

**Issue by jlien-calwater** [angular-ui/bootstrap#5225] opened 2016-01-12 23:39 UTC
http://angular-ui.github.io/bootstrap/

Format defined: M!/d!/yyyy

Failed
![image](https://cloud.githubusercontent.com/assets/3473846/12280248/4dfddd22-b941-11e5-9e6d-47b4000cc62a.png)

Expecting:
![image](https://cloud.githubusercontent.com/assets/3473846/12280330/f9c9f76c-b941-11e5-84b1-1d0121760532.png)

**Comment by wesleycho** [comment] 2016-01-13 04:00
I think this is actually a datepicker validation issue - I seem to remember seeing this before with the new format, thought I fixed it but apparently not.

**Comment by devjeff** [comment] 2016-01-14 19:02
I'm seeing a similar issue that might be related. When I set  the format to 'M!/d!/yyyy' the exclamation points appear in the datepicker input, e.g. "1!/15!/2016". It then does not accept any inputs with prepended zeroes. 

Using angular-ui-bootstrap 0.14.3 via webjars.  uibDateParser service is injected into app; is there all that needs to be done for it to override the default?

**Comment by wesleycho** [comment] 2016-01-14 20:10
@devjeff the ! string fix is in 1.0.3

**Comment by devjeff** [comment] 2016-01-14 20:40
thanks wesleycho; will test out newer version.

**Comment by devjeff** [comment] 2016-01-15 18:58
Tested this out with angular 1.48, bootstrap 3.2.0, angular UI bootstrap 1.0.3.  Datepicker no longer works; firebug saying "dateParser.fromTimezone is not a function". Any idea what might be breaking?

**Comment by wesleycho** [comment] 2016-01-15 19:00
Please post a reproduction in a separate issue - let's not clutter up this issue thread.

**Comment by countergram** [comment] 2016-01-26 17:27
Looks like 428beaff4c9d9dde1e6d3c0851e09597e9254ff6 broke this. The `!' are being stripped out of the display format, but it reused the same variable that is used for validation.

**Comment by wesleycho** [comment] 2016-02-01 04:19
Looking into this some more, this feature requires a superset of the Angular date filter...this is a mess to fix, but I am in the process of crafting a fix.

**Closed** 2016-02-01 16:15 UTC
Labels: component: datepicker, needs: investigation
