### ISSUE TITLE
Carousel bug with ngAnimate when debugInfoEnabled=false

### ISSUE THREAD

**Issue by rbosneag** [angular-ui/bootstrap#3810] opened 2015-06-12 08:06 UTC
Just discovered that our carousels won't work when deploying to production. 
Problem found was in *beforeRemoveClass* function: 

    if (className == 'active' && element.parent() &&
              !element.parent().scope().noTransition)

where *.scope()* and *.isolateScope()* is undefined with debugInfoEnabled = false as per https://github.com/angular/angular.js/issues/9515.
Setting it to **true** is a fix but not a good option for deployment. 

check http://plnkr.co/edit/g4zOqw

**Comment by intellix** [comment] 2015-06-12 08:13
Duplicate of: #3794 
And appears to have been fixed and merged

**Comment by rbosneag** [comment] 2015-06-12 08:15
I just noticed it was comitted and closed 2h ago :)

**Closed** 2015-06-12 08:18 UTC
