### ISSUE TITLE
Problem with uib-typeahead

### ISSUE THREAD

**Issue by richtera** [angular-ui/bootstrap#5208] opened 2016-01-11 18:02 UTC
When using and expression like
```
uib-typeahead="item.$id as item.name for item in items | filter:$viewValue | limitTo:8"
```
It seems to display item.$id as the display value after selecting and item in the dropdown.
Changing it to
```
uib-typeahead="item as item.name for item in items | filter:$viewValue | limitTo:8"
```
Fixes the display values, but then the ng-model is obviously set to the object instead of the $id.
Thanks
Andy

**Comment by wesleycho** [comment] 2016-01-11 18:23
Can you post a reproduction in [Plunker](http://plnkr.co/edit/IfzJMio2AwHkwcc59htF?p=preview)? This is a bit confusing.

**Comment by richtera** [comment] 2016-01-11 18:25
I found this
http://stackoverflow.com/questions/19680616/angular-ui-typeahead-show-label-but-bind-to-value-only
which describes the same problem.
I am using a workaround right now by adding two additional $watch to
monitor a variable containing the selected object and the $id separately.

On Mon, Jan 11, 2016 at 1:24 PM, Wesley Cho <notifications@github.com>
wrote:

> Can you post a reproduction in Plunker
> <http://plnkr.co/edit/IfzJMio2AwHkwcc59htF?p=preview>? This is a bit
> confusing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/bootstrap/issues/5208#issuecomment-170642056>
> .
>



-- 

Andreas Richter LLC
<http://richtera.org/>
n: *Andreas Richter*
e: andy@richtera.org
c: 215-518-2619
o: 484-238-0538
s: andyxp.richteralsi
gt: andy@richtera.org
g+: google.com/+AndreasRichterLLC
l: linkedin.com/in/richtera <http://www.linkedin.com/in/richtera>
t: @richtera <https://twitter.com/richtera>
a: richtera@me.com
y: richterar66home

**Comment by icfantv** [comment] 2016-01-11 18:26
@richtera, i've edited your post to remove all your personal contact info.  In the future, it's a good idea to not reply to GitHub emails.  :-).

**Comment by richtera** [comment] 2016-01-11 20:03
Ah, thanks. Sorry to convolute the thread.

**Comment by coli** [comment] 2016-01-19 17:39
Same issue here, the typeahead need to display the "label" value when given "select as label for value in sourceArray". 
ng-model should bind to select.

Currently it is displaying "select" and binding to "select" as well.

**Comment by wesleycho** [comment] 2016-01-19 17:49
Closing due to lack of reproduction - [this Plunker](http://plnkr.co/edit/FT1qChjAnHKPCICnLZGy?p=preview) seems to indicate that it does work, and the source code also appears to do the right thing.

**Closed by wesleycho** 2016-01-19 17:49 UTC
Labels: component: typeahead, needs: plunkr

**Comment by anzeo** [comment] 2016-02-12 15:38
@wesleycho The Plunker you've linked is actuallyshowing the broken behaviour?

**Comment by mdickin** [comment] 2016-02-24 14:49
@anzeo I thought the same thing. After coming across [this post](http://stackoverflow.com/a/17994624/706551) I created a [new plunker](http://plnkr.co/edit/UZTuHxBQVzKHpkwjwZNs?p=preview) that I think accomplishes what we need.

**Comment by anzeo** [comment] 2016-02-24 15:11
@mdickin thanks! :+1:
