### ISSUE TITLE
$scope.active is not resetting on tab click

### ISSUE THREAD

**Issue by cullsin** [angular-ui/bootstrap#5937] opened 2016-05-29 00:52 UTC
Hi, 

Can you please suggest me why active is not getting reset ?

        <uib-tabset active="active">
                <uib-tab index="0" heading="Basic" ng-click="active=0">
                        <div class="panel panel-primary">
                        </div>
                </uib-tab>
        </uib-tabset>
       <button type="button" class="btn btn-default" ng-click="next()">Next</button
    
        /* Controller */
                 $scope.next = function() {
                        $scope.active += 1;
                 }

PS : It's working when the page Init, But If I Click the tab it is not resetting and next is not working.

Please correct me if I am wrong.

Thanks,
Raja K

**Comment by wesleycho** [comment] 2016-05-29 01:07
Please post a reproduction in Plunker.

**Comment by cullsin** [comment] 2016-05-29 01:08
Hi, 

Sure. I will let you know asap.

Raja K

**Comment by imiten** [comment] 2016-06-12 12:26
I am facing similar issue and unable to setup plunker since it needs to use routeProvider.  Just create page with 2 tabs and on load try to use url as #/page/tab1 or #page/tab2 to select the tab.  It is not working.  Also if I have Page 1 with tab 1 and 2.  From tab 2 I open page 2 which wants to now show page 1 tab 2 how to do that ?  Also if the two pages have different controllers how to do this routing ?

**Comment by icfantv** [comment] 2016-06-12 13:06
@imiten, you can still use routes in plunker.  And just a note that OSS maintainers, in general, are pretty unsympathetic to the line "I can't create a plunker because...".  Most of us are unpaid volunteers with full time jobs and we simply do not have the time to chase  vague or poorly written issues.

**Comment by wesleycho** [comment] 2016-06-13 21:42
Going to close this as not a library issue/not enough information

**Closed by wesleycho** 2016-06-13 21:42 UTC
Labels: component: tab, needs: issue template, needs: plunkr

**Comment by imiten** [comment] 2016-06-14 09:42
https://plnkr.co/edit/Bw3gQG9QZubW89U7gvfO?p=preview
not sure how to jump to tab like if I have page with tabs and I want to load page and also switch to second tab or using back button from some page go to previous page with tab.  example on the plunk I have dummy data.  you see first page has two tabs.  go to second tab backup list and choose edit.  Now use broswer back button or Back button.  Desired would be to take to backup list tab of previous page but does not.  I have tried even using url params.

**Comment by icfantv** [comment] 2016-06-14 13:42
@imiten, it is considered poor form to hijack issues threads or to spam the issues forum with the same question in an effort to get noticed.  As previously mentioned, our project documentation indicates how to receive help.
