### ISSUE TITLE
Flexbox vendor prefixing

### ISSUE THREAD

**Issue by plondon** [angular-ui/bootstrap#5457] opened 2016-02-09 22:39 UTC
Is there no mixin for flexbox vendor prefixing? Something like https://github.com/thoughtbot/bourbon/blob/v4-stable/app/assets/stylesheets/css3/_flex-box.scss would be great.

**Comment by icfantv** [comment] 2016-02-09 22:42
@plondon, please extend us the courtesy of searching existing issues (both open and closed) prior to posting an issue.  Closing as duplicate of #4234.

**Closed by icfantv** 2016-02-09 22:42 UTC
