### ISSUE TITLE
Datepicker 0.13.0 - throws date error on textbox change with Angular 1.3.5 stable

### ISSUE THREAD

**Issue by johnsonlin** [angular-ui/bootstrap#3609] opened 2015-05-04 02:12 UTC
I tried to implement the new angular ui bootstrap with angular 1.3.5 stable.
Here's a plunker demo:
http://plnkr.co/edit/6jWsI4nk6hyjh2l6O5Pd?p=preview

when I change the year of second date, which is generated by `new Date()`, everything updates accordingly.

But when i change the year of first date, which is generated by `new Date(1430229600000)`, it throws an error unless I manually select another date from the datepicker.

`Datepicker directive: "ng-model" value must be a Date object, a number of milliseconds since 01.01.1970 or a string representing an RFC2822 or ISO 8601 date.`

After selecting another date from the datepicker, it behaves like the second date with no errors.

**Comment by chrisirhc** [comment] 2015-05-04 05:16
What is the error message you're seeing?
I don't see an error message when I change the year by replacing 2015 with 2016 on the first date .

**Comment by johnsonlin** [comment] 2015-05-04 05:19
Datepicker directive: "ng-model" value must be a Date object, a number of milliseconds since 01.01.1970 or a string representing an RFC2822 or ISO 8601 date.

**Comment by chrisirhc** [comment] 2015-05-04 05:37
Ah, I see. This is related to #3294 . 
Actually, `new Date('28/04/201')` fails because 28 cannot be the value of the months field (in US date locale). `new Date('03/05/201')` parses but actually fails, because it's interpreting 03 as the months.

This is a known issue, I believe we intend to break this behavior soon. When we merge in #3294, the ng-model should get `null` when the format is invalid. In this case, the format is invalid because the `yyyy` is not satisfied, there should be 4 digits in the year and the model should not parse.

**Comment by johnsonlin** [comment] 2015-05-04 05:51
@chrisirhc 
Hi Chris,
the date format is correct as I'm using Australian date locale (dd/MM/yyyy) in the demo.
so `new Date('28/04/201')` is actually `28-April-201`
try deleting the last 2 digits of 2015 and putting 01 after it
then you'll see the js error on the first date but not the second date as the second date converts the year.

and after trying a few different date formats from the dropdown, it looks like datepicker will fail to parse any formats that end with 'yyyy'

Please look into it.

Thanks

**Comment by chrisirhc** [comment] 2015-05-04 05:55
Yes, it works only because you're in Australia. This behavior shouldn't be relied upon because it will not work, in say, USA where the locale is different. I think the failure to parse is actually the correct behavior as it's more expected and reliable. However, it shouldn't throw that error in the console. It should just set the ng-model to null. We'll fix that soon once that PR is merged.

**Comment by johnsonlin** [comment] 2015-05-04 06:49
Hi Chris,
Just want to make sure that I understand the fix.
When I try to change the date value `28/04/2015` to `28/04/2005`, I select `15` then start typing the first letter `0`.
Then datepicker will failed to parse the value and fail.
What do I see in the text box?
 - Do I see `28/04/200`? (After I type the other letter `5`, will it pass the date parse and work again?)
OR
 - Do I see the text box value get empty as ng-model is set to null?

**Comment by chrisirhc** [comment] 2015-06-04 07:42
You should see `28/04/200` in text box and typing `5`, it'll pass the date parsing. That's the intended behavior, but it might be broken. See #3736

**Closed** 2015-07-31 16:10 UTC
Labels: component: datepicker, type: bug
