### ISSUE TITLE
Tooltip flickering and wrong positioned when inside of a right aligned (text) element

### ISSUE THREAD

**Issue by loxy** [angular-ui/bootstrap#5746] opened 2016-04-05 12:35 UTC
### Bug description:

Imagine following HTML snippet:

```
<p class="text-right">
  <span uib-tooltip="Hi here, this is loxy!" >Hello Tooltip</span>
</p>
```

This does not work correctly if it has to break the text and there is too little space at the right border. The tooltip appears and disappears on mouseover. It is also slightly shifted to the bottom.

### Plunker

https://embed.plnkr.co/EdDuIV/

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.1
UIBS: 1.3.0
Bootstrap: 3.3.6

**Comment by icfantv** [comment] 2016-04-05 13:14
@loxy, reproduction?  Please do not ignore the issue template.

**Comment by deeg** [comment] 2016-04-05 13:31
Could be related to #4857

**Comment by RobJacobs** [comment] 2016-04-05 15:10
This is because the tooltip is trying to render outside of the page.  Use a tooltip-placement="auto top" and the tooltip will render where it has enough space to display.

**Comment by icfantv** [comment] 2016-04-05 15:27
Closing as a support issue.

**Closed by icfantv** 2016-04-05 15:27 UTC
Labels: component: tooltip, resolution: support

**Comment by eugenevk** [comment] 2018-02-04 15:32
For anyone still interested I had my tooltip also flickering and not correctly positioned on top when I set the uib-tooltip for a Font Awesome icon (I use that e.g. to show an Info icon next to an input field). I discovered that when setting the width for the tooltip, it renders correctly and doesn't flicker. I added this to my project's style sheet:
```
.tooltip-info + .tooltip {
    width: 200px;
}

.tooltip-info + .tooltip > .tooltip-inner {
    width: 190px;
}

```
And in my html:
```
<span class="tooltip-info" uib-tooltip="{{infoTooltip}}" tooltip-placement="{{infoTooltipPlacement}}" ng-show="infoTooltip">
	<i class="fas fa-info-circle" aria-hidden="true"></i>
</span>

```
(The html is part of an Angular directive. "fas fa-info-circle" is the new style FontAwesome 5.0)

**Comment by itsvkv** [comment] 2019-02-15 10:27
> For anyone still interested I had my tooltip also flickering and not correctly positioned on top when I set the uib-tooltip for a Font Awesome icon (I use that e.g. to show an Info icon next to an input field). I discovered that when setting the width for the tooltip, it renders correctly and doesn't flicker. I added this to my project's style sheet:
> 
> ```
> .tooltip-info + .tooltip {
>     width: 200px;
> }
> 
> .tooltip-info + .tooltip > .tooltip-inner {
>     width: 190px;
> }
> ```
> And in my html:
> 
> ```
> <span class="tooltip-info" uib-tooltip="{{infoTooltip}}" tooltip-placement="{{infoTooltipPlacement}}" ng-show="infoTooltip">
> 	<i class="fas fa-info-circle" aria-hidden="true"></i>
> </span>
> ```
> (The html is part of an Angular directive. "fas fa-info-circle" is the new style FontAwesome 5.0)

Worked perfectly with this change
