### ISSUE TITLE
Datepicker popup directive throws an error when inside of ngRepeat

### ISSUE THREAD

**Issue by Hallian** [angular-ui/bootstrap#2292] opened 2014-06-03 14:22 UTC
Example of the problem: http://jsfiddle.net/NZH5m/ (see console)

As far as I can tell, the directive responds to an ngModel change, presumably caused by ngRepeat creating the child scope, before dateFormat variable is set by the attribute observer.

The issue can be fixed by setting the dateFormat directly from the linking function on line 456 of datepicker.js, like so:
```javascript
dateFormat = attrs.datepickerPopup || datepickerPopupConfig.datepickerPopup;
attrs.$observe('datepickerPopup', function(value) { ...
```
Although this does make the issue go away, I'm not sure if there's something else going on in here.

**Comment by rvanbaalen** [comment] 2015-05-30 21:52
Please update the example code (preferably provide a plunkr) and confirm this is still an issue with Angular 1.3 and UI Bootstrap 0.13.

**Comment by RobJacobs** [comment] 2015-10-07 19:43
Closing as I can't reproduce against latest master build.  Example provided produced no errors in console although dates used for ng-model binding must be actual date objects, not strings.

**Closed by RobJacobs** 2015-10-07 19:43 UTC
Labels: component: datepicker, needs: plunkr
