### ISSUE TITLE
typeahead does not reset 'editable' flag when ng-model is changed from controller

### ISSUE THREAD

**Issue by zorkus** [angular-ui/bootstrap#3129] opened 2014-12-19 12:59 UTC
I have typeahead input field with typeahead-editable='false'.

To reset validty after changing ng-model from controller I have to call

$scope.myForm.myField.$setValidity('editable', true);

It should be called by directive somewhere in function pushed to modelCtrl.$formatters

**Comment by acgentry** [comment] 2015-01-06 15:30
+1

I believe I am hitting the same issue, setting Pristine on the form doesn't remove the validation errors, for "typeahead-editable='false'" inputs. Maybe a 1.3 angular issue had to do the same hack of $setValidity manually, all other controls work just fine with pristine:

                if($scope.myForm.$error.editable){
                        var typeaheadErrors = [].concat($scope.myForm.$error.editable);
                        angular.forEach(typeaheadErrors, function(control, key){
                           control.$setValidity('editable', true)     
                        });
                }
                $scope.myForm.$setPristine();

**Comment by rvanbaalen** [comment] 2015-04-08 16:00
@zorkus Can you setup a plunkr reproducing your problem? And have you tried if the master branch has this issue fixed?

**Comment by wesleycho** [comment] 2015-08-16 18:50
I am not able to reproduce this based on current `master` [here](http://plnkr.co/edit/v08kSLp6pSmfvcKrjUX5?p=preview).

Closing as resolved. Feel free to open a new issue with a reproduction if this is still an issue.

**Closed by wesleycho** 2015-08-16 18:50 UTC
Labels: component: typeahead, needs: info

**Comment by Squiggle** [comment] 2015-08-17 14:17
Just a note to say I can see this was a bug in 1.3.8 and is now fixed in 1.4.3.

http://plnkr.co/edit/GX5lF5

All is well.
