### ISSUE TITLE
Accordion - callback function on heading open/close (feature request)

### ISSUE THREAD

**Issue by joesteel2010** [angular-ui/bootstrap#5518] opened 2016-02-22 12:44 UTC
Hi,

I had a need for a function to be triggered on a heading being opened/closed (to redraw a graph I was using), and I thought it may be a useful feature for others too. It's be nice if it was in future releases so I don't have to keep adding it back in after each release. My code is below:

```javascript
// The accordion-group directive indicates a block of html that will expand and collapse in an accordion
.directive('uibAccordionGroup', function($window) {
  return {
    require: '^uibAccordion',         // We need this directive to be inside an accordion
    transclude: true,              // It transcludes the contents of the directive into the template
    replace: true,                // The element containing the directive will be replaced with the template
    templateUrl: function(element, attrs) {
      return attrs.templateUrl || 'uib/template/accordion/accordion-group.html';
    },
    scope: {
      heading: '@',               // Interpolate the heading attribute onto this scope
      isOpen: '=?',
      isDisabled: '=?',
      headingChange: '&' // MY CHANGE HERE!!!
    },
    controller: function() {
      this.setHeading = function(element) {
        this.heading = element;
      };
    },
    link: function(scope, element, attrs, accordionCtrl) {
      accordionCtrl.addGroup(scope);

      scope.openClass = attrs.openClass || 'panel-open';
      scope.panelClass = attrs.panelClass || 'panel-default';
      scope.$watch('isOpen', function(value) {
        if (value) {
          accordionCtrl.closeOthers(scope);
        }
		element.toggleClass(scope.openClass, !!value);
      });

      scope.toggleOpen = function($event) {
        if (!scope.isDisabled) {
          if (!$event || $event.which === 32) {
            scope.isOpen = !scope.isOpen;
            // And here!!!
	    scope.headingChange();
          }
        }
      };
    }
  };
})
```

**Comment by icfantv** [comment] 2016-02-22 14:31
I'm pretty sure this is a duplicate, but can't check as I'm on my mobile at the moment.

**Comment by wesleycho** [comment] 2016-02-22 15:30
Use a $watch on the variable bound to `isOpen` - this does not require any modification in UI Bootstrap to do this.

**Comment by joesteel2010** [comment] 2016-02-22 16:45
@wesleycho that's fine in some cases, but it does mean the user has to create and close event listeners when the scope is destroyed. In my particular instance, I'm creating the accordion inside a nested ngRepeat, and isOpen is bound to an element in an associative array taking a string + $index as the key to avoid collisions. I could have created a function to handle this inside my own code, but it was far simpler to make a 2 line change UI Bootstrap.

**Comment by wesleycho** [comment] 2016-02-22 16:57
At the cost of bloat - IMO the correct solution is to fix the model used with ng-repeat.

Going to close this as a won't support case, this is a usage issue.

**Closed by wesleycho** 2016-02-22 16:57 UTC
Labels: component: accordion, resolution: support

**Comment by joesteel2010** [comment] 2016-02-22 17:09
Thanks anyway.

**Comment by icfantv** [comment] 2016-02-22 18:22
Yep, this is a duplicate of #2217 which was a duplicate of #1685.  @joesteel2010 please extend us the courtesy of searching both open and closed issues before entering a new one as forcing us to do extra work means it takes us more time to address your (and other users') needs.  Thanks.

**Comment by joesteel2010** [comment] 2016-02-22 18:30
Apologies @icfantv and the rest of the team! Appreciate the hard work.
