### ISSUE TITLE
Datepicker not validating input correctly

### ISSUE THREAD

**Issue by fuelmx** [angular-ui/bootstrap#3835] opened 2015-06-18 13:04 UTC
I found a situation where Datepicker module does not validate input field. I'm using dd.MM.yyyy format as an example and this can be reproduced in https://angular-ui.github.io/bootstrap/#/datepicker

First I change input value 18.06.2015 to 1A8.06.2015 and datepicker correctly informs me that this is invalid value. But if I take the A away it does not validate input field until I remove the first 1. And if I start with 8.06.2015 => A8.06.2015 => 8.06.2015 it works correctly.

**Comment by Srogozins** [comment] 2015-06-19 16:09
I think, I might have found a related issue that is also reproduceable in https://angular-ui.github.io/bootstrap/#/datepicker on Firefox 38, but not on Firefox 32 or Chrome. If A single digit is deleted from a month or day field in the first popup example, the console log will throw out this:

`Datepicker directive: "ng-model" value must be a Date object, a number of milliseconds since 01.01.1970 or a string representing an RFC2822 or ISO 8601 date.`

This will also seemingly break the model binding, no future changes to the input's value will affect the model until page reload.

**Comment by yoorek** [comment] 2015-06-24 05:39
I also noticed the same problem and here is demo: http://jsfiddle.net/yoorek/mug2e381/

I can change anything in correct date and it's marked $invalid PERMANENTLY

**Comment by wesleycho** [comment] 2015-06-27 04:04
This appears to be a duplicate of #3713

**Comment by wesleycho** [comment] 2015-08-03 06:14
This appears to have been fixed in `master` in the past couple of days - 0.13.2 should fix all of the issues here.

**Closed by wesleycho** 2015-08-03 06:14 UTC
Labels: component: datepicker
