### ISSUE TITLE
I cannot manipulate the order of carousel slide via array

### ISSUE THREAD

**Issue by thakerng** [angular-ui/bootstrap#3331] opened 2015-02-24 11:17 UTC
Example

 if we have an array such as slides = [slide1,slide2,slide3,slide4]; then we need to insert slide5 to between slide3 and slide4 by splice function,So we have [slide1,slide2,slide3,slide5,slide4] we expect the view result should be sorted as the same order.But actually the library perform slide5 displayed at the last of slide like we push slide5 to the last of array, I think this is bad practice for me I expect the slides should be sorted as the same order of an array it hard to sort like dynamic slide.

**Comment by karianna** [comment] 2015-02-24 11:48
plunkr please

**Comment by ayakovlevgh** [comment] 2015-03-18 21:35
I think it's a duplicate of https://github.com/angular-ui/bootstrap/issues/488
And I have this problem too.

**Comment by chrisirhc** [comment] 2015-03-19 07:56
Indeed this is a duplicate of #488 . Closing as duplicate.

**Closed by chrisirhc** 2015-03-19 07:56 UTC
Labels: component: carousel, needs: info
