### ISSUE TITLE
Some failure when use modal with angular-touch

### ISSUE THREAD

**Issue by dannyphung** [angular-ui/bootstrap#4356] opened 2015-09-07 05:01 UTC
Hi team,
I got error when use modal directive on tablet with angular-touch. Below plnkr reproduce the issue, open dialog and try to toggle radio. This fail both on Chrome's ipad 3/4 simulate and real tablet.
http://plnkr.co/edit/Nys6b2WTYIyWtxXVpHNK?p=preview
When I remove ng-click="close(event)" on modal window and.. puf! radio works again. 
Thanks for your time.
Best regards

**Comment by chrisirhc** [comment] 2015-09-07 05:17
Duplicate of #2280

**Closed by chrisirhc** 2015-09-07 05:17 UTC
