### ISSUE TITLE
Carousel stops working after some while

### ISSUE THREAD

**Issue by johannesjo** [angular-ui/bootstrap#5796] opened 2016-04-13 11:04 UTC
### Bug description:
Using angular 1.5.3 and angular-bootstrap 1.3.1 the carousel controls and auto-cycling stops working after the tab of the app is idle for some while.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/4Y35sULcPkDSReTdzUWm?p=preview

### Version of Angular, UIBS, and Bootstrap
angular 1.5.3, uibs 1.3.1, bootstrap 3.3.6

**Comment by RobJacobs** [comment] 2016-04-13 12:18
Possible duplicate of #5471

**Comment by deeg** [comment] 2016-04-13 14:39
@RobJacobs, fairly certain it is. The other issue references that this should be fixed by a 1.5.4 release of Angular.

**Closed** 2016-04-13 14:40 UTC
Labels: component: carousel, resolution: duplicate

**Comment by johannesjo** [comment] 2016-04-13 14:41
@deeg Shouldn't at least one of the two issues be open then?

**Comment by deeg** [comment] 2016-04-13 15:12
No as the other issue state:

> Closing as fixed in Angular via angular/angular.js@2b327f0

It is already fixed in angular core, it just has not been released yet.

**Comment by johannesjo** [comment] 2016-04-13 19:29
@deeg ah ok! Good to know! Thank you for mentioning that again!
