### ISSUE TITLE
Datepicker malfunctioning in Firefox: fails to update the model when manually updating the date

### ISSUE THREAD

**Issue by darkbls** [angular-ui/bootstrap#3159] opened 2015-01-06 16:46 UTC
Manually changing the date value, after the it was inserted, fails to update the model on Firefox.
It seems to deletes the content (?).

Check the fiddle for a proper example, open it on chrome and firefox.
http://jsfiddle.net/HB7LU/9779/

**Comment by darkbls** [comment] 2015-01-07 08:59
Anything I can do to help more?

**Comment by glorat** [comment] 2015-01-10 05:24
Changing to 
$scope.format = 'yyyy-MM-dd';

fixes it. It seems that it is a date editor, not a datetime editor. One issue (related?) in doing this is you'll find dates are internally expressed as datetimes at midnight local timezone. Remote the format filter in your display to see how it looks

**Comment by karianna** [comment] 2015-01-11 16:57
@darkbls I assume this was with Angular 1.3?

**Comment by darkbls** [comment] 2015-01-12 08:42
@karianna yes it was
@glorat  thank you, is there any suggestion that would allow one to keep using the hour and minute?

**Comment by wesleycho** [comment] 2015-03-17 04:32
Transferred to [Plunker](http://plnkr.co/edit/4WK9g3BNjWNiKzJROTcR?p=preview) for working version.

I will investigate.

**Comment by wesleycho** [comment] 2015-03-17 04:53
Interestingly, this might have to do with how the browsers interpret dates.  The object set in the view for both Chrome and Firefox is a date when the user clicks on the date.

When the user deletes a character, say from `2015-03-18 00:00:00` to give `2015-03-1 00:00:00`, Chrome thinks that `new Date('2015-03-1 00:00:00)` is a valid date string, while Firefox disagrees.

This [new Plunker](http://plnkr.co/edit/CDx8gATkoz5lBPugbMrc?p=preview) illustrates this.

In this case, Firefox's behavior looks to be more strict than Chrome's.  It turns out that Safari also agrees with Firefox here, and Chrome is the outlier.  I will investigate how IE behaves, but I believe that Chrome's behavior is actually the strange one here.  I am not sure we should support this behavior.

**Comment by newmanw** [comment] 2015-03-18 01:18
Not sure if it helps but, this format works in FF.  Not entirely sure why

```javascript
    $scope.format = 'MM/dd/yyyy HH:mm:ss';
```

Also FWIW I think it should be fixed.  Not sure what to do about new Date('2015-03-1 00:00:00), but seems like once you type in a valid date, ie add a 7 to the end new Date('2015-03-17 00:00:00) the input should re-validate to a correct date, but it doesn't.

I will look into it more to see what else I can find.

**Comment by wesleycho** [comment] 2015-03-22 19:16
Well, that sort of makes sense - the string in the input does not match the format expected otherwise.

Maybe changing the $formatter so that it displays the date in the expected format would fix this issue.

**Comment by wesleycho** [comment] 2015-03-22 19:36
I think I've identified the cause - the date parser cannot recognize the `HH:mm:ss` format - I will work on adding support for that and have that fixed within the next couple of days.

**Closed** 2015-04-06 00:34 UTC
Labels: AngularJS 1.3, component: datepicker, PRs plz!

**Comment by Lux90** [comment] 2015-07-17 10:53
Single quotes at the end of a date format fix the date typing issue in Firefox.
In my case solution looks as follows: <b> datepicker-popup="yyyy-MM-dd''" </b>

**Comment by ratheeshkannan** [comment] 2015-11-27 09:07
Thanks Lux90, we had a similar issue and through your solution it worked in Firefox as of now. But just curious to know what is the logic behind putting a string inside a string. Maybe date object manipulation in firefox and now it's validating string instead of date object?
