### ISSUE TITLE
Test do not pass

### ISSUE THREAD

**Issue by jjsino** [angular-ui/bootstrap#3630] opened 2015-05-06 15:07 UTC
I have just forked the repo.
On master, commit for version 0.13.0 when I run grunt I have the follozing test that fail:

```  
Chrome 41.0.2272 (Linux) datepicker directive as popup european format dd.MM.yyyy FAILED
	 TypeError: Cannot read property 'hasEvent' of undefined
	     at changeInputValueTo (/home/jji/Programmation/kpler-   github/bootstrap/src/datepicker/test/datepicker.spec.js:1174:26)
	    at Object.<anonymous> (/home/jji/Programmation/kpler-github/bootstrap/src/datepicker/test/datepicker.spec.js:1684:9)
```

**Comment by pkozlowski-opensource** [comment] 2015-05-07 08:54
Hmm, all tests are passing on TravisCI: https://travis-ci.org/angular-ui/bootstrap/branches

**Comment by rvanbaalen** [comment] 2015-05-07 10:15
Strange indeed @pkozlowski-opensource since I am actually able to reproduce this locally but as you said Travis haa no trouble at all.

**Comment by RobJacobs** [comment] 2015-05-07 11:41
I'm seeing this to, I had to delete my node_modules folder and run npm to reproduce.

**Comment by RobJacobs** [comment] 2015-05-13 15:27
Something is whacked with the build.  I tried checking in a fix for this issue but that surfaced another failing test:  Expected spy changeHandler to have been called. - datepicker.spec.js:1886:42.  So I reverted the change but the travis ci build is still failing???

The travis ci build is also set to use Firefox, which does not fail for the original issue, where Chrome does.

**Closed** 2015-05-13 16:20 UTC
Labels: PRs plz!, type: tests
