### ISSUE TITLE
$uibTooltipProvider seems not to inject proper object

### ISSUE THREAD

**Issue by Verdilac** [angular-ui/bootstrap#6271] opened 2016-09-30 09:06 UTC
According to [https://angular-ui.github.io/bootstrap/#/-uibtooltipprovider](documentation) $uibTooltipProvider should inject object with .`options()` function but it is injecting some kind of generic function.

Tested with:
`var $uibTooltip = <angular.ui.bootstrap.ITooltipProvider>$injector.get("$uibTooltip");`
`console.log($uibTooltip);`

Results in:
`function (e,k,m,n){function p(a){var b=(a||n.trigger||m).split(" "),d=b.map(function(a){return c[a]||a});return{show:b,hide:d}}n=angular.extend({},b,d,n);var q=a(e),r=j.startSymbol(),s=j.endSymbol(),t…`

I'm using 2.1.4 version.

**Comment by wesleycho** [comment] 2016-09-30 15:28
Please post a Plunker with a reproduction.

**Comment by wesleycho** [comment] 2016-10-11 05:30
Closing due to lack of actionable reproduction.

**Closed by wesleycho** 2016-10-11 05:30 UTC
Labels: component: tooltip, needs: plunkr
