### ISSUE TITLE
accordion: ng-form inputs within uib-accordion-transclude

### ISSUE THREAD

**Issue by mmoses98** [angular-ui/bootstrap#4624] opened 2015-10-14 21:01 UTC
There seems to be a problem with ng-form used with the directives. The form isn't binding properly within the accordion-directives' transcluded header input elements.

here's an example of it not working: http://plnkr.co/edit/sfB92B2cz6vaZ9kUF2dY?p=preview

If I move these input fields into the body (which is not where I want them), the forms will be set correctly.

(sorry for closing and opening, I pasted the wrong plnkr)

**Comment by icfantv** [comment] 2015-10-14 21:20
It's working for me.  See [this plunker](http://plnkr.co/edit/b2xZbXc92XHF8VcAAYhA).

**Comment by icfantv** [comment] 2015-10-14 21:22
Ahhhh, sorry.  You want the OUTER form's validity.  One sec.

**Comment by icfantv** [comment] 2015-10-14 21:27
This is a bug, but I'm not yet convinced it's in our code.  I need to check the scoping.  You can see from the updated plunker (after I post this) that the nested forms aren't getting reported to the parent form and thus the parent form is not aware of them.  This is why validation is not working.

**Comment by mmoses98** [comment] 2015-10-14 21:30
I can see it working if I place the required input fields in the body. Which is why I thought it could be related to the heading transclude directive.

**Comment by icfantv** [comment] 2015-10-14 21:52
Hey, just a heads up that we're looking at this, but we're not sure that this is something we want to support.  Having clickable elements in the header breaks the default show/hide toggling.

You may want to look at just using a Bootstrap panel for this and use ng-show/ng-hide on the panel-body.

Either way, we'll get back to you.

**Comment by wesleycho** [comment] 2015-10-15 04:56
Noting that this is a duplicate of #4285.

I am hesitant about supporting this UI - seems like poor design to me.

The problem point here is that the api for the `accordion-heading` destroys proper form handling due to the DOM manipulation happening here. Supporting this may require a major breaking change in how the API is used - any choice made here also has implications for the tab component, and we seem to have leaned against such change there.

I am inclined to reject this request, but am open to suggestions, as long as they can address these two key points in a consistent way.

**Comment by wesleycho** [comment] 2015-10-27 14:31
So I did further investigation - to support this, we would have to do `scope.$parent.$parent.$parent.$parent` in the `uib-accordion-header` directive, which is an antipattern. In addition, this change also requires a breaking change in breaking support for using the scope local to the accordion group, and introduces unexpected behavior in the API signature.

If you really must use this poor UI pattern, I would recommend just homebrewing a custom directive with the desired HTML as suggested by @icfantv and using the collapse directive directly.

**Closed by wesleycho** 2015-10-27 14:31 UTC
Labels: component: accordion, resolution: wontfix
