### ISSUE TITLE
Datepicker doesn't work with ng-model-options="{ allowInvalid: true }"

### ISSUE THREAD

**Issue by distinctdan** [angular-ui/bootstrap#4694] opened 2015-10-22 21:30 UTC
I'm trying to get the datepicker's input to set the model value even if the user entered invalid stuff, but it doesn't appear to respect ng-model-options' allowInvalid parameter.

**Comment by distinctdan** [comment] 2015-10-23 15:18
After some thought, I think what I'm really looking is for an option to make the datepicker's validation a bit looser, specifically, to allow leading 0's. The whole reason I was trying to disable validation is because the datepicker errors if the format isn't exactly right, so if the user enters "7/09/2015", it'll error if my format is "M/d/yyyy". Even though the datepicker should still output the desired format, it would be nice if there was an option to allow leading 0's in the input.

For now, I've modified the regexs in dateParser to accept leading 0's for days and months. I don't like modifying a library because it means extra effort when you upgrade, but I really don't see any other option since there's no way to extend/modify the date parsing.

I see that the date parser uses a big object of formats, with a regex for each format. What if we exposed this object, so that external code could override the formats?

**Comment by icfantv** [comment] 2015-10-23 15:20
I think this may be a duplicate of #2906.

**Comment by wesleycho** [comment] 2015-11-05 15:55
We added dateparser support for optional leading zeroes, but it would be nice to add support for all ngModelOptions config

**Comment by wesleycho** [comment] 2015-11-07 17:35
Closing in favor of #4837

**Closed by wesleycho** 2015-11-07 17:35 UTC
Labels: component: datepicker, needs: investigation

**Comment by dadoadk** [comment] 2016-02-10 14:33
I'm still having issues with this. I'm on version 1.1.2 angular-bootstrap, and have a uib-datepicker-popup="MM-dd-yyyy" with ng-model-options="{allowInvalid:true}". So my form requires users to enter dash "-" if they don't know the date. Everything is fine when they enter the dash, datepicker still opens on click if they want to change it to a date, form saves. Now, when form is loaded, ng-model takes the value of "-" dash and doesn't display it in input text box, also when user clicks on datepicker an error pops up with exception: "TypeError: this.activeDate.getFullYear is not a function at _refreshView"

Can you help me out with this issue? seems like on load the datepicker doesn't take "-" dash value.

**Comment by aschulz01** [comment] 2016-11-17 17:30
while using the uib-datepicker-popup it's possible to pass ng-model-options to the wrapped uib-datepicker component with the following attribute:

**`datepicker-options="{ ng-model-options :{ allowInvalid: true} }"`**

So the datepicker is no longer marked as invalid, if the bound data are not yet definded.
