### ISSUE TITLE
datepicker displays selected date in local time zone

### ISSUE THREAD

**Issue by veerasamyn** [angular-ui/bootstrap#1968] opened 2014-03-21 20:11 UTC
When you select the date from date picker it displays in local time zone when you set the date format as "yyyy-MM-ddTHH:mm.sssZ". I can change the timezone in javascript side and send to the server but I want to maintain consistency.

Please refer the plnkr
http://plnkr.co/edit/s63f7uzvokjNI4XgiyXI?p=preview

**Comment by rvanbaalen** [comment] 2015-05-08 15:50
Is this still an issue in UI Bootstrap 0.13.0? Can you reproduce this with the latest release?

**Comment by realityking** [comment] 2015-05-08 15:57
@rvanbaalen Yes it is. Since JS largely lacks time zone supports I don't think this is feasible to fix. Note that angular's date filter behaves the same way.

**Comment by karianna** [comment] 2015-05-10 11:02
I think this is one of the items that could get resolved if/when we move to using moment.

**Comment by wesleycho** [comment] 2015-10-21 14:33
I don't think this is something we should fix in the library itself - local time is by far the desired behavior. If we do come to the conclusion of allowing configurability, this is something that is also better encapsulated in other issues.

Closing as a result.

**Closed by wesleycho** 2015-10-21 14:33 UTC
Labels: component: datepicker, PRs plz!

**Comment by amodpandey** [comment] 2017-05-01 06:33
Timezone would not make sense while picking a Date. Any further thoughts?
