### ISSUE TITLE
[Modal] Strange blink when open modal

### ISSUE THREAD

**Issue by mazavr** [angular-ui/bootstrap#5220] opened 2016-01-12 06:51 UTC
Using pllunker with modal example and see the blink as well as on my site.

![modal_blink](https://cloud.githubusercontent.com/assets/988125/12256843/6984b6a0-b91a-11e5-8e16-dbeb4e4ee34c.gif)

It looks like a CSS class that contains a width of a modal are applied with some delay... And window should be shown (start showing) after the moment when the class already in place.

**Comment by grantfeldman** [comment] 2016-01-12 08:30
I have just upgrade to v1 and this is happening to me as well.

**Comment by hopest** [comment] 2016-01-12 08:57
You can add the ng-cloak

**Comment by mazavr** [comment] 2016-01-12 13:14
Thanks, it fixes the problem (applied that for now), but requires modifications of all my modals files =(

**Comment by yesman85** [comment] 2016-01-12 14:51
@hopest do you mean adding ng-cloak on the templates directly?

**Comment by deeg** [comment] 2016-01-12 15:13
Believe this is a duplicate of #5183, you can find a temp CSS fix there.

**Comment by icfantv** [comment] 2016-01-12 15:23
Guys, please extend us the courtesy of searching both open and closed issues before Bering new ones.  This is a duplicate and was fixed in last night's 1.0.3 release.

**Closed by icfantv** 2016-01-12 15:23 UTC

**Comment by deeg** [comment] 2016-01-12 15:25
@icfantv, was it really fixed?

**Comment by icfantv** [comment] 2016-01-12 16:12
I stand corrected, it was not.  My bad.  But it was still a dup, so I got that part right.  :-p
