### ISSUE TITLE
Latest angular-ui 1.0.3 shows a flicker when opening a modal

### ISSUE THREAD

**Issue by spiffy2man** [angular-ui/bootstrap#5256] opened 2016-01-14 21:45 UTC
This can be duplicated on the angular ui bootstrap examples page, by going to the modal directive and clicking on any one of the button. Notice that the text behind the modal shifts. In my application, it appears to be flashing other pages that are currently hidden by the angular ui router.

**Comment by icfantv** [comment] 2016-01-14 21:51
@spiffy2man, please extend us the courtesy of searching open and closed issues before opening a new one.  This is a duplicate of #5183.

**Closed by icfantv** 2016-01-14 21:51 UTC

**Comment by spiffy2man** [comment] 2016-01-14 21:52
I did search. I did not see any recent issues for this issue, only old ones for old versions. Thank you!
